### ISSUE TITLE
Unhandled exception on start

### ISSUE THREAD

**Issue by Artemis387** [EDDiscovery/EDDiscovery#1025]
For the past few months I haven't been able to launch EDDiscovery, even when updated to the latest version.

The log shows this about the issue:

[2017-04-26 17:54:16Z] Running logfile age check
[2017-04-26 17:54:16Z] Native library pre-loader is trying to load native SQLite library "C:\Program Files\EDDiscovery\EDDiscovery\x64\SQLite.Interop.dll"...
[2017-04-26 17:54:16Z] SQLite version 3.15.2
[2017-04-26 17:54:16Z] SQLite error (1): no such table: register
[2017-04-26 17:54:16Z] 
==== UNHANDLED EXCEPTION ====
System.Data.SQLite.SQLiteException (0x80004005): SQL logic error or missing database
no such table: register
   at System.Data.SQLite.SQLite3.Prepare(SQLiteConnection cnn, String strSql, SQLiteStatement previous, UInt32 timeoutMS, String& strRemain)
   at System.Data.SQLite.SQLiteCommand.BuildNextCommand()
   at System.Data.SQLite.SQLiteDataReader.NextResult()
   at System.Data.SQLite.SQLiteDataReader..ctor(SQLiteCommand cmd, CommandBehavior behave)
   at System.Data.SQLite.SQLiteCommand.ExecuteReader(CommandBehavior behavior)
   at EDDiscovery.DB.SQLiteDataReaderED`1..ctor(DbCommand cmd, CommandBehavior behaviour, SQLiteTransactionED`1 txn, SQLiteTxnLockED`1 txnlock)
   at EDDiscovery.DB.SQLiteCommandED`1.ExecuteDbDataReader(CommandBehavior behavior)
   at EDDiscovery.DB.SQLiteConnectionED`1.GetRegister(Dictionary`2 regs)
   at EDDiscovery.DB.SQLiteConnectionUser.EarlyGetRegister()
   at EDDiscovery.EDDiscoveryController.InitializeConfig(Boolean noreposition)
   at EDDiscovery.EDDiscoveryController.Initialize(Boolean noreposition)
   at EDDiscovery.Forms.SplashForm.Init()
   at EDDiscovery.Program.Run()
   at EDDiscovery.Program.Main()
==== cut ====

**Comment by klightspeed** [comment]
Please look in `%LOCALAPPDATA%\EDDiscovery`.  The error suggests that `EDDUser.sqlite` exists but has no data.

Please try renaming or deleting `EDDUser.sqlite`, and try launching EDDiscovery again.

**Comment by Artemis387** [comment]
That was it, the file existed but was 0KB. Deleted and it made a 3.6GB file in its place and opened after some time, thank you!
