### ISSUE TITLE
EDDiscovery would not load

### ISSUE THREAD

**Issue by kozality** [EDDiscovery/EDDiscovery#1045]
I'd spent an evening flying with EDDiscovery, then closed down everything as normal. Elite first, then EDD. Left system running. Next day, I go to fire everything up, but EDD will not launch. Can't find anything in Windows Application logs. Restarted. EDD launches then, but then I see this in the output window:

```
Check Systems exception: Unexpected character encountered while parsing number: <. Path '[3165].coords.x', line 1, position 450560.
Trace:    at Newtonsoft.Json.JsonTextReader.ReadNumberIntoBuffer()
   at Newtonsoft.Json.JsonTextReader.ParseNumber(ReadType readType)
   at Newtonsoft.Json.JsonTextReader.ParseValue()
   at Newtonsoft.Json.Linq.JContainer.ReadContentFrom(JsonReader r, JsonLoadSettings settings)
   at Newtonsoft.Json.Linq.JContainer.ReadTokenFrom(JsonReader reader, JsonLoadSettings options)
   at Newtonsoft.Json.Linq.JObject.Load(JsonReader reader, JsonLoadSettings settings)
   at EDDiscovery.DB.SystemClass.DoParseEDSMUpdateSystemsReader(JsonTextReader jr, String& date, Boolean& outoforder, Func`1 cancelRequested, Action`2 reportProgress, Boolean useCache, Boolean useTempSystems)
   at EDDiscovery.DB.SystemClass.ParseEDSMUpdateSystemsStream(TextReader sr, String& date, Boolean& outoforder, Boolean removenonedsmids, Func`1 cancelRequested, Action`2 reportProgress, Boolean useCache, Boolean useTempSystems)
   at EDDiscovery.DB.SystemClass.ParseEDSMUpdateSystemsString(String json, String& date, Boolean& outoforder, Boolean removenonedsmids, Func`1 cancelRequested, Action`2 reportProgress, Boolean useCache)
   at EDDiscovery.EDSM.EDSMClass.GetNewSystems(Func`1 cancelRequested, Action`2 reportProgress, Action`1 logLine)
   at EDDiscovery.DB.SystemClass.PerformSync(Func`1 cancelRequested, Action`2 reportProgress, Action`1 logLine, Action`1 logError, SystemsSyncState state)
   at EDDiscovery.EDDiscoveryController.DoPerformSync()
```

No response needed, just wanted to report the finding. Thanks!

**Comment by klightspeed** [comment]
Looks like PHP crapped in EDSM's JSON response.

**Comment by finwen** [comment]
We should catch that error so  rest of EDD will work atleast.

2017-05-09 5:33 GMT+02:00 Ben Peddell <notifications@github.com>:

**Comment by AnthorNet** [comment]
Something went wrong last night?

**Comment by robbyxp1** [comment]
Closed, no further details
