### ISSUE TITLE
New User and won't run.

### ISSUE THREAD

**Issue by CdnBass** [EDDiscovery/EDDiscovery#1052]
First timer user and trying to get the software running. 
Here is what my log is reading, as I can't load the log on this issue:

[2017-05-11 20:33:51Z] Running logfile age check
[2017-05-11 20:33:51Z] Native library pre-loader is trying to load native SQLite library "C:\Program Files\EDDiscovery\EDDiscovery\x64\SQLite.Interop.dll"...
[2017-05-11 20:33:51Z] SQLite version 3.15.2
[2017-05-11 20:33:51Z] SQLite error (1): no such table: register
[2017-05-11 20:33:51Z] 
==== UNHANDLED EXCEPTION ====
System.Data.SQLite.SQLiteException (0x80004005): SQL logic error or missing database
no such table: register
   at System.Data.SQLite.SQLite3.Prepare(SQLiteConnection cnn, String strSql, SQLiteStatement previous, UInt32 timeoutMS, String& strRemain)
   at System.Data.SQLite.SQLiteCommand.BuildNextCommand()
   at System.Data.SQLite.SQLiteDataReader.NextResult()
   at System.Data.SQLite.SQLiteDataReader..ctor(SQLiteCommand cmd, CommandBehavior behave)
   at System.Data.SQLite.SQLiteCommand.ExecuteReader(CommandBehavior behavior)
   at EDDiscovery.DB.SQLiteDataReaderED`1..ctor(DbCommand cmd, CommandBehavior behaviour, SQLiteTransactionED`1 txn, SQLiteTxnLockED`1 txnlock)
   at EDDiscovery.DB.SQLiteCommandED`1.ExecuteDbDataReader(CommandBehavior behavior)
   at EDDiscovery.DB.SQLiteConnectionED`1.GetRegister(Dictionary`2 regs)
   at EDDiscovery.DB.SQLiteConnectionUser.EarlyGetRegister()
   at EDDiscovery.EDDiscoveryController.InitializeConfig(Boolean noreposition)
   at EDDiscovery.EDDiscoveryController.Initialize(Boolean noreposition)
   at EDDiscovery.Forms.SplashForm.Init()
   at EDDiscovery.Program.Run()
   at EDDiscovery.Program.Main()
==== cut ====

**Comment by robbyxp1** [comment]
Did you just try re-running? Is it still broken?

**Comment by CdnBass** [comment]
Hello, I download the software for the first time, installed correctly and ran it. THe above message came up  and could only close the message and the program shut down. Tried rerunning and same issue. Tried uninstalling and reinstalling - same issue. No matter what I did I got the same message each time.

**Comment by robbyxp1** [comment]
Closing, 1025 closed
