### ISSUE TITLE
Crash on launch, engineering panel bug?

### ISSUE THREAD

**Issue by andybish** [EDDiscovery/EDDiscovery#1063]
v8.0.2.0:
EDD crashes on launch with this error (taken from the trace log file)
==== UNHANDLED UI EXCEPTION ====
System.ArgumentOutOfRangeException: Index was out of range. Must be non-negative and less than the size of the collection.
Parameter name: index
   at System.Collections.ArrayList.get_Item(Int32 index)
   at System.Windows.Forms.DataGridViewRowCollection.SharedRow(Int32 rowIndex)
   at System.Windows.Forms.DataGridViewRowCollection.get_Item(Int32 index)
   at EDDiscovery.UserControls.UserControlEngineering.Display()
   at EDDiscovery.TravelHistoryControl.ShowSystemInformation(DataGridViewRow rw)
   at EDDiscovery.TravelHistoryControl.UpdatedDisplay(HistoryList hl)
   at EDDiscovery.UserControls.UserControlTravelGrid.Display(HistoryList hl)
   at System.Action`1.Invoke(T obj)
   at EDDiscovery.EDDiscoveryController.RefreshHistoryWorkerCompleted(HistoryList hist)
==== cut ====

If I click ignore on it, the program will run, but won't display either of my right side panels (I think they were materials and engineering planner)

EDIT: another error during load, that didn't appear in the trace:
EDDiscoveryForm_Load exception: Object reference not set to an instance of an object.
Trace: at EDDiscovery.UserControls.UserControlEngineering.<>c.,Init>b__39_4(String sn)

at a load of other stuff I won't put here unless needed, because I'm having to type it manually

**Comment by finwen** [comment]
This should be solved in 8.0.3

2017-05-16 18:45 GMT+02:00 andybish <notifications@github.com>:
