### ISSUE TITLE
Unhandled UI Exception

### ISSUE THREAD

**Issue by elvee61** [EDDiscovery/EDDiscovery#1083]
This happens constantly when mousing over any window.  Speccy output attached.  

[BUTTONS.txt](https://github.com/EDDiscovery/EDDiscovery/files/1072199/BUTTONS.txt)

[2017-06-13 12:51:06Z] Running logfile age check
[2017-06-13 12:51:06Z] Native library pre-loader is trying to load native SQLite library "D:\Program Files\EDDiscovery\EDDiscovery\x64\SQLite.Interop.dll"...
[2017-06-13 12:51:06Z] SQLite version 3.15.2
[2017-06-13 12:51:06Z] *** Elite Dangerous Discovery Initializing - Version 8.0.7.0, Platform: Win32NT
[2017-06-13 12:51:06Z] Initializing database
[2017-06-13 12:51:06Z] Database initialization complete
[2017-06-13 12:51:07Z] Theme ID 10037
[2017-06-13 12:51:10Z] Unknown Gal Map object mysteryPOI
[2017-06-13 12:51:10Z] Unknown Gal Map object deepSpaceOutpost
[2017-06-13 12:51:10Z] Unknown Gal Map object restrictedSectors
[2017-06-13 12:51:10Z] Unknown Gal Map object neutronRoute
[2017-06-13 12:51:10Z] New watch on C:\Users\Elvee\Saved Games\Frontier Developments\Elite Dangerous
[2017-06-13 12:51:10Z] Scanned C:\Users\Elvee\Saved Games\Frontier Developments\Elite Dangerous
[2017-06-13 12:51:11Z] Unknown Gal Map object mysteryPOI
[2017-06-13 12:51:11Z] Last message repeated 23 times
[2017-06-13 12:51:11Z] Unknown Gal Map object deepSpaceOutpost
[2017-06-13 12:51:11Z] Last message repeated 34 times
[2017-06-13 12:51:11Z] Unknown Gal Map object restrictedSectors
[2017-06-13 12:51:11Z] Last message repeated 21 times
[2017-06-13 12:51:11Z] Unknown Gal Map object neutronRoute
[2017-06-13 12:51:11Z] Last message repeated 6 times
[2017-06-13 12:51:12Z] 
==== UNHANDLED UI EXCEPTION ====
System.OverflowException: Arithmetic operation resulted in an overflow.
   at EDDiscovery.EDDiscoveryForm.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)
==== cut ====
[2017-06-13 12:51:16Z] Start Monitor on C:\Users\Elvee\Saved Games\Frontier Developments\Elite Dangerous
[2017-06-13 12:51:17Z] Reading response

**Comment by klightspeed** [comment]
Given the lack of line numbers, it looks like the installer either doesn't include EDDiscovery.pdb, or that file doesn't get updated.

Also, the fact that you have an integer overflow exception suggests that you have arithmetic underflow/overflow checking enabled, which is not the default.

#1084 should prevent overflows from occurring when either msg.WParam or msg.Result have garbage values.
