### ISSUE TITLE
Last commitments (1180 to 1181) scramble System Information Panel

### ISSUE THREAD

**Issue by andreaspada** [EDDiscovery/EDDiscovery#1182]
Hi! I noticed that the last commitments had make my System Information panel scramble, both in History and Grid view. I cannot adjust anymore the position of the fields as it gives me Unhandled Exception...

Logs attached:
[Log.zip](https://github.com/EDDiscovery/EDDiscovery/files/1211376/Log.zip)

**Comment by phroggster** [comment]
Both exceptions are the same:
```
[2017-08-09 09:11:50Z] *** Elite Dangerous Discovery Initializing - Version 8.2.0.0, Platform: Win32NT
*** clip ***
[2017-08-09 09:13:58Z] 
==== UNHANDLED UI EXCEPTION ====
System.ArgumentOutOfRangeException: Index was out of range. Must be non-negative and less than the size of the collection.
Parameter name: index
   at System.ThrowHelper.ThrowArgumentOutOfRangeException(ExceptionArgument argument, ExceptionResource resource)
   at EDDiscovery.UserControls.UserControlSysInfo.CompressOrder() in C:\projects\eddiscovery\EDDiscovery\UserControls\UserControlSysInfo.cs:line 763
   at EDDiscovery.UserControls.UserControlSysInfo.controlMouseUp(Object sender, MouseEventArgs e) in C:\projects\eddiscovery\EDDiscovery\UserControls\UserControlSysInfo.cs:line 748
   at System.Windows.Forms.Control.OnMouseUp(MouseEventArgs e)
   at System.Windows.Forms.Control.WmMouseUp(Message& m, MouseButtons button, Int32 clicks)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)
==== cut ====
```

**Comment by phroggster** [comment]
It looks like an unusual for loop was left in from testing. I'm sure a fix will be coming soon enough.

```CS
for (int i = 0; i < Order.Count; i += HorzPositions)        // now clean out empty rows
{
    int empty = 0;
    for (; empty < HorzPositions && Order[i + empty] < 0; empty++) // *** Guaranteed exception. ***
        ;

    if (empty == HorzPositions)
    {
        Order.RemoveRange(i, HorzPositions);
        System.Diagnostics.Debug.WriteLine("Line " + i + " removed, now " + String.Join(",", Order));
    }
```

**Comment by robbyxp1** [comment]
its been reworked.
