### ISSUE TITLE
Screenshots returned to provoce some troubles

### ISSUE THREAD

**Issue by andreaspada** [EDDiscovery/EDDiscovery#1190]
By sometime, screenshots function returned to things. Very often, it refuse to convert the image and stop working. In the log, there's always something like this:

```
[2017-08-11 20:40:35Z] Unable to open screenshot 'd:\Users\Andrea\Pictures\Frontier Developments\Elite Dangerous\Screenshot_0000.bmp': Could not find file 'd:\Users\Andrea\Pictures\Frontier Developments\Elite Dangerous\Screenshot_0000.bmp'.
[2017-08-11 20:40:35Z] Exception watcher: Could not find file 'd:\Users\Andrea\Pictures\Frontier Developments\Elite Dangerous\Screenshot_0000.bmp'.
[2017-08-11 20:40:35Z] Trace:    at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)

[2017-08-11 20:40:35Z]    at System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)

[2017-08-11 20:40:35Z]    at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share)

[2017-08-11 20:40:35Z]    at EDDiscovery.ImageHandler.ImageConverter.GetScreenshot(String inputfile, String cur_sysname, Int32 cmdrid, JournalScreenshot& ss, String& store_name, Point& finalsize, FileInfo& fi) in C:\projects\eddiscovery\EDDiscovery\ImageHandler.cs:line 772

[2017-08-11 20:40:35Z]    at EDDiscovery.ImageHandler.ImageConverter.Convert() in C:\projects\eddiscovery\EDDiscovery\ImageHandler.cs:line 674

[2017-08-11 20:40:35Z]    at EDDiscovery.ImageHandler.ScreenshotDirectoryWatcher.ProcessScreenshot(String filename, String sysname, JournalScreenshot ss, Int32 cmdrid, ImageConverter cp) in C:\projects\eddiscovery\EDDiscovery\ImageHandler.cs:line 608
[2017-08-11 20:40:35Z] Error in executing image conversion, try another screenshot, check output path settings. (Exception Could not find file 'd:\Users\Andrea\Pictures\Frontier Developments\Elite Dangerous\Screenshot_0000.bmp'.
```

Curiously, the image is where it is supposed to be, and the folders are perfectly in place...

I have to close and restart EDDiscovery to have it working by a while, before the problem reappear.

**Comment by klightspeed** [comment]
That suggests that the file is removed between when the operating system tells the program it has been created and when the program attempts to access it.

Perhaps the program should retry opening the file a few times with a short delay between attempts.

Do you have anything else processing screenshots in that directory?

**Comment by andreaspada** [comment]
No, only EDDiscovery is responsible for my screenshots... I find curious that after it give this error, it refuse to work unless I close and restart it.

**Comment by klightspeed** [comment]
What are the screenshot log entries after it stops working?

**Comment by andreaspada** [comment]
Actually, it stops log anything related to screenshots... after the first error message, it display no more error messages at all.

**Comment by klightspeed** [comment]
Are there any journal entries related to screenshots?

**Comment by andreaspada** [comment]
Nope...

**Comment by klightspeed** [comment]
So using the event filter and selecting only `ScreenShot` gives you nothing?

**Comment by andreaspada** [comment]
Using the event filter, it display my attempts to take screenshots. The file appear in the frontier folder, under my pictures folder, but it's not converted, renamed nor moved.

Here are my last logs, if they can help in something...

[Log.zip](https://github.com/EDDiscovery/EDDiscovery/files/1219402/Log.zip)

**Comment by klightspeed** [comment]
Is `d:\Users\Andrea\Pictures\Frontier Developments\Elite Dangerous` in fact the directory in which screenshots are getting written?

If not, please switch to the `Screenshots` tab and set `ED/Steam Screenshot folder` to the correct directory.

**Comment by andreaspada** [comment]
Yes, the directory is correct. As I said, screenshots are working: they suddenly and unexpectedly stop working than, after a restart, they works again. I double checked absolutely everything...

**Comment by phroggster** [comment]
Re-uploading [Log.zip](https://github.com/EDDiscovery/EDDiscovery/files/1219458/Log.zip) with the EGO API key masqueraded.

I'm looking around for what might be the issue behind this, and am having troubles. Are you running Elite: Discovery as an administrator, or have any fancy NTFS permissions set for that folder? I'm assuming that you can actually browse and create files there; is that correct?

**Comment by klightspeed** [comment]
Please try the portable exe from https://ci.appveyor.com/project/EDDiscovery/eddiscovery/build/3.2.1.1482/artifacts and see if it fixes the issue.

**Comment by andreaspada** [comment]
Probably, I can do some test only on Monday, but as soon as I can I'll provide you a feedback. Thanks for your help, guys!

**Comment by andreaspada** [comment]
I'm playing by an hour or so, and I had no any trouble taking screenshots, yet. It seems that you got the problem solved...

**Comment by andreaspada** [comment]
I noticed that the log informed an error during a screenshot conversion, however the image was correctly converted and moved, and EDDiscovery did not refuse to work on subsequent images. So, it seems that the feature is much more solid now. KUDOS!

**Comment by phroggster** [comment]
The release of [8.2.3](https://github.com/EDDiscovery/EDDiscovery/releases/tag/Release_8.2.3) should see this resolved. Please re-open if issues occur again.
