### ISSUE TITLE
Unhandled Exception

### ISSUE THREAD

**Issue by Shazzsmifff** [EDDiscovery/EDDiscovery#1225]
---------------------------
Unhandled Exception
---------------------------
There was an unhandled UI exception.
Please report this at https://github.com/EDDiscovery/EDDiscovery/issues ⭐️⭐️⭐️and attach `C:\Users\james\AppData\Local\EDDiscovery\Log\Trace_20170824164024.0.log`⭐️⭐️⭐️
```
Exception: database is locked
   at System.Data.SQLite.SQLite3.Prepare(SQLiteConnection cnn, String strSql, SQLiteStatement previous, UInt32 timeoutMS, String& strRemain)
   at System.Data.SQLite.SQLiteCommand.BuildNextCommand()
   at System.Data.SQLite.SQLiteDataReader.NextResult()
   at System.Data.SQLite.SQLiteDataReader..ctor(SQLiteCommand cmd, CommandBehavior behave)
   at System.Data.SQLite.SQLiteCommand.ExecuteReader(CommandBehavior behavior)
   at EliteDangerousCore.DB.SQLiteDataReaderED`1..ctor(DbCommand cmd, CommandBehavior behaviour, SQLiteTransactionED`1 txn, SQLiteTxnLockED`1 txnlock)
   at EliteDangerousCore.DB.SQLiteCommandED`1.ExecuteDbDataReader(CommandBehavior behavior)
   at EliteDangerousCore.DB.SystemClassDB.GetEdsmIdsFromName(String name, SQLiteConnectionSystem cn)
   at EliteDangerousCore.DB.SystemClassDB.GetSystemsByName(String name, SQLiteConnectionSystem cn)
   at EliteDangerousCore.DB.SystemClassDB.FindEDSM(ISystem s, SQLiteConnectionSystem conn)
   at EliteDangerousCore.HistoryList.FindEDSM(HistoryEntry syspos, SQLiteConnectionSystem conn, Boolean reload)
   at EliteDangerousCore.HistoryList.FillEDSM(HistoryEntry syspos, SystemClassDB edsmsys, Boolean reload, SQLiteConnectionUser uconn)
   at EDDiscovery.UserControls.UserControlSysInfo.Display(HistoryEntry he, HistoryList hl)
   at EDDiscovery.UserControls.ChangedSelectionHE.Invoke(HistoryEntry he, HistoryList hl)
   at EDDiscovery.UserControls.UserControlTravelGrid.FireChangeSelection()
   at EDDiscovery.UserControls.UserControlTravelGrid.AddNewEntry(HistoryEntry he, HistoryList hl)
   at System.Action`2.Invoke(T1 arg1, T2 arg2)
   at EDDiscovery.EDDiscoveryController.NewEntry(JournalEntry je)
   at EliteDangerousCore.EDJournalClass.ScanTickDone(List`1 entries)
```

```
Do you wish to abort, or ignore the exception and try to continue?
---------------------------
Abort   Retry   Ignore   
---------------------------
```

**Comment by phroggster** [comment]
Can you reply and attach the file `C:\Users\james\AppData\Local\EDDiscovery\Log\Trace_20170824164024.0.log` to help determine what had locked the database?
