### ISSUE TITLE
Attempting to open journal history window threw error

### ISSUE THREAD

**Issue by tivec** [EDDiscovery/EDDiscovery#1284]
On version 8.2.7.0, trying to open the journal history window threw an error. Restarting EDDiscovery has worked out fine. Log attached.

[Trace_20170923181433.0.log](https://github.com/EDDiscovery/EDDiscovery/files/1326663/Trace_20170923181433.0.log)

**Comment by klightspeed** [comment]
Suggests that a row somehow didn't have a history entry attached to it.

It looks like there may be the potential for a race to occur between the row being added and the tag being set where the row is painted asynchronously.

**Comment by phroggster** [comment]
```
[2017-09-23 18:15:02Z]
==== UNHANDLED UI EXCEPTION ====
System.NullReferenceException: Object reference not set to an instance of an object.
   at EDDiscovery.UserControls.UserControlTravelGrid.PaintEventColumn(DataGridView grid, DataGridViewRowPostPaintEventArgs e, Int32 totalentries, HistoryEntry he, Int32 hpos, Int32 colwidth, Boolean showfsdmapcolour)
   at EDDiscovery.UserControls.UserControlJournalGrid.dataGridViewJournal_RowPostPaint(Object sender, DataGridViewRowPostPaintEventArgs e)
   at System.Windows.Forms.DataGridView.OnRowPostPaint(DataGridViewRowPostPaintEventArgs e)
   at System.Windows.Forms.DataGridViewRow.Paint(Graphics graphics, Rectangle clipBounds, Rectangle rowBounds, Int32 rowIndex, DataGridViewElementStates rowState, Boolean isFirstDisplayedRow, Boolean isLastVisibleRow)
   at System.Windows.Forms.DataGridView.PaintRows(Graphics g, Rectangle boundingRect, Rectangle clipRect, Boolean singleHorizontalBorderAdded)
   at System.Windows.Forms.DataGridView.PaintGrid(Graphics g, Rectangle gridBounds, Rectangle clipRect, Boolean singleVerticalBorderAdded, Boolean singleHorizontalBorderAdded)
   at System.Windows.Forms.DataGridView.OnPaint(PaintEventArgs e)
   at System.Windows.Forms.Control.PaintWithErrorHandling(PaintEventArgs e, Int16 layer)
   at System.Windows.Forms.Control.WmPaint(Message& m)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)
==== cut ====
```

**Comment by klightspeed** [comment]
Perhaps `UserControlTravelGrid.PaintEventColumn` should return without doing anything it `he` is null?

It looks like `Debug.Assert` doesn't actually do anything on a non-debug build.

**Comment by phroggster** [comment]
That's the correct answer, but it does bring up another problem: `Debug.Assert` is contained within our code 539 times (including commented lines). How many of these also need to be updated?

**Comment by robbyxp1** [comment]
Debug.Assert is supposed to be out in release code.. ;-)
