### ISSUE TITLE
Action File Editor open error UNHANDLED UI EXCEPTION

### ISSUE THREAD

**Issue by qubeGH** [EDDiscovery/EDDiscovery#1292]
This sentence is machine translated from Japanese to English. It may be unreadable.

An error occurs when trying to edit the Action File.
This log file is version 8.2.7, but this error also occurs in 8.3.0.
Is there a solution?
I use OS language in Japanese.
[Trace_20170917140925.0.log](https://github.com/EDDiscovery/EDDiscovery/files/1327922/Trace_20170917140925.0.log)

**Comment by phroggster** [comment]
> Version 8.2.7.0, Platform: Win32NT reported:
```
[2017-09-17 14:10:04Z] 
==== UNHANDLED UI EXCEPTION ====
System.NullReferenceException: Object reference not set to an instance of an object.
   at ActionLanguage.ActionPackEditorForm.PositionGroups(Boolean calcminsize)
   at System.Windows.Forms.Control.OnResize(EventArgs e)
   at System.Windows.Forms.Control.OnSizeChanged(EventArgs e)
   at System.Windows.Forms.Control.UpdateBounds(Int32 x, Int32 y, Int32 width, Int32 height, Int32 clientWidth, Int32 clientHeight)
   at System.Windows.Forms.Control.UpdateBounds(Int32 x, Int32 y, Int32 width, Int32 height)
   at System.Windows.Forms.Control.SetBoundsCore(Int32 x, Int32 y, Int32 width, Int32 height, BoundsSpecified specified)
   at System.Windows.Forms.Control.ScaleControl(SizeF factor, BoundsSpecified specified)
   at System.Windows.Forms.ScrollableControl.ScaleControl(SizeF factor, BoundsSpecified specified)
   at System.Windows.Forms.Control.ScaleControl(SizeF includedFactor, SizeF excludedFactor, Control requestingControl)
   at System.Windows.Forms.Control.Scale(SizeF includedFactor, SizeF excludedFactor, Control requestingControl)
   at System.Windows.Forms.Control.ScaleChildControls(SizeF includedFactor, SizeF excludedFactor, Control requestingControl)
   at System.Windows.Forms.Control.Scale(SizeF includedFactor, SizeF excludedFactor, Control requestingControl)
   at System.Windows.Forms.ContainerControl.OnChildLayoutResuming(Control child, Boolean performLayout)
   at System.Windows.Forms.Control.OnLayoutResuming(Boolean performLayout)
   at System.Windows.Forms.Control.ResumeLayout(Boolean performLayout)
   at ActionLanguage.ActionPackEditorForm.InitializeComponent()
   at EDDiscovery.Actions.ActionController.EditActionFile(String name)
   at EDDiscovery.Forms.AddOnManagerForm.ActionbuttonEdit_Click(Object sender, EventArgs e)
   at System.Windows.Forms.Control.OnClick(EventArgs e)
   at System.Windows.Forms.Button.OnClick(EventArgs e)
   at System.Windows.Forms.Button.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)
==== cut ====
```

**Comment by phroggster** [comment]
This appears to only impact certain non-Cyrillic script locales, but is caused by an artifact regarding how Windows deals with character font scaling. I'm not able to debug this issue effectively, so could you please try running [this build](https://ci.appveyor.com/api/buildjobs/y5ji9f9fajpablia/artifacts/EDDiscovery.Portable.zip) and let me know if the issue still occurs when you click the `Edit` button?

> 試す [https://ci.appveyor.com/api/buildjobs/y5ji9f9fajpablia/artifacts/EDDiscovery.Portable.zip](https://ci.appveyor.com/api/buildjobs/y5ji9f9fajpablia/artifacts/EDDiscovery.Portable.zip)
