### ISSUE TITLE
Constantly get error when syncing From EDSM

### ISSUE THREAD

**Issue by KrS14** [EDDiscovery/EDDiscovery#135]
Error:

GetEDSMDistances exception:Exception of type 'System.OutOfMemoryException' was thrown.
   at System.Collections.Generic.Dictionary`2.Initialize(Int32 capacity)
   at System.Collections.Generic.Dictionary`2.Insert(TKey key, TValue value, Boolean add)
   at Newtonsoft.Json.Linq.JPropertyKeyedCollection.InsertItem(Int32 index, JToken item)
   at System.Collections.ObjectModel.Collection`1.Insert(Int32 index, T item)
   at Newtonsoft.Json.Linq.JContainer.InsertItem(Int32 index, JToken item, Boolean skipParentCheck)
   at Newtonsoft.Json.Linq.JObject.InsertItem(Int32 index, JToken item, Boolean skipParentCheck)
   at Newtonsoft.Json.Linq.JContainer.AddInternal(Int32 index, Object content, Boolean skipParentCheck)
   at Newtonsoft.Json.Linq.JContainer.Add(Object content)
   at Newtonsoft.Json.Linq.JContainer.ReadContentFrom(JsonReader r)
   at Newtonsoft.Json.Linq.JContainer.ReadTokenFrom(JsonReader reader)
   at Newtonsoft.Json.Linq.JArray.Load(JsonReader reader)
   at Newtonsoft.Json.Linq.JArray.Parse(String json)
   at EDDiscovery.DB.DistanceClass.ParseEDSM(String json, String& date)
   at EDDiscovery.EDDiscoveryForm.GetEDSMDistances()

I get this error every time I sync FROM EDSM, Sync TO EDSM works fine.

**Comment by AnthorNet** [comment]
Which version of EDD do you use?

**Comment by KrS14** [comment]
UPDATE;  This error does not occur, when the get "Distances from EDSM" Checkbox in the settings tab is NOT checked.

**Comment by AnthorNet** [comment]
Again which version of EDD are you using?

**Comment by KrS14** [comment]
Using 2.7.5.0  Sorry I didn't see that question before the first reply :)

**Comment by AnthorNet** [comment]
There might be too much distances to handle now.
May be it would be better to only grab them when they are needed ?

**Comment by KrS14** [comment]
Oh it's absolutely ok to run it without that checkbox, just reporting what I saw for an error :)  You can close this is you're ok with it as is.

**Comment by AnthorNet** [comment]
Sorry the reply was not for you but for the developers ;)

**Comment by finwen** [comment]
You are using the 32 bit version of EDDiscovery? That one  reaches memory limit faster. 

Parsing of the big json distance files makes the 32 bit EDDiscovery breaking memory limit.
We need to a streaming parser instead of parsing all data at once. 

Until that happends the 64 bit client helps.  And having the "Distances from EDSM" checked is really not needed unless you enter distances between each system you are visiting.

**Comment by KrS14** [comment]
I was going to enter distances for each system I'm exploring yes.  I do run the 64-bit ED client.  Are you going to have a 64 bit version of EDDiscovery? I couldn't find an installer or anything for a 64 bit version.

**Comment by finwen** [comment]
http://eddiscovery.astronet.se/release/  The latest versions here is 64/32 bits. 

The clickonce installer from http://robert.astronet.se/Elite/EDDiscovery2/  is 32 bit only.

**Comment by KrS14** [comment]
Perfect! Thanks for clearing that up for me Fin!  Much appreciated!

**Comment by gregmalcolm** [comment]
Looks like we can close this one? Closing this one.
