### ISSUE TITLE
crashes all the time

### ISSUE THREAD

**Issue by braxhunter** [EDDiscovery/EDDiscovery#1411]
brand new install issue.. every is good when new computer start then 15 min program crashes.

error log
```
[2017-10-19 18:05:59Z] Running logfile age check
[2017-10-19 18:05:59Z] Native library pre-loader is trying to load native SQLite library "C:\Users\Rob\Desktop\EDDiscovery.Portable_8.3.3\x64\SQLite.Interop.dll"...
[2017-10-19 18:05:59Z] SQLite version 3.19.3
[2017-10-19 18:05:59Z] *** Elite Dangerous Discovery Initializing - Version 8.3.3.0, Platform: Win32NT
[2017-10-19 18:06:01Z] SQLite notice (27): delayed 1375ms for lock/sharing conflict at line 43027
[2017-10-19 18:06:01Z] SQLite error (3338): os_win.c:43031: (5) winAccess(D:\Google Drive\Personal\games\Elite Dangerous\EDDSystem.sqlite-journal) - Access is denied.
[2017-10-19 18:06:01Z] SQLite error (3338): disk I/O error
[2017-10-19 18:06:16Z] Theme ID 10037
[2017-10-19 18:06:19Z] SQLite notice (27): delayed 1375ms for lock/sharing conflict at line 43027
[2017-10-19 18:06:19Z] SQLite error (3338): os_win.c:43031: (5) winAccess(D:\Google Drive\Personal\games\Elite Dangerous\EDDSystem.sqlite-journal) - Access is denied.
[2017-10-19 18:06:19Z] SQLite error (3338): disk I/O error
[2017-10-19 18:06:22Z] SQLite notice (27): delayed 1375ms for lock/sharing conflict at line 43027
[2017-10-19 18:06:22Z] SQLite error (3338): os_win.c:43031: (5) winAccess(D:\Google Drive\Personal\games\Elite Dangerous\EDDSystem.sqlite-journal) - Access is denied.
[2017-10-19 18:06:22Z] SQLite error (3338): disk I/O error
[2017-10-19 18:06:24Z] SQLite notice (27): delayed 1375ms for lock/sharing conflict at line 43027
[2017-10-19 18:06:24Z] SQLite error (3338): os_win.c:43031: (5) winAccess(D:\Google Drive\Personal\games\Elite Dangerous\EDDSystem.sqlite-journal) - Access is denied.
[2017-10-19 18:06:24Z] SQLite error (3338): disk I/O error
[2017-10-19 18:06:24Z] Exception : disk I/O error
[2017-10-19 18:06:24Z] disk I/O error
[2017-10-19 18:06:24Z]    at System.Data.SQLite.SQLite3.Prepare(SQLiteConnection cnn, String strSql, SQLiteStatement previous, UInt32 timeoutMS, String& strRemain)
[2017-10-19 18:06:24Z]    at System.Data.SQLite.SQLiteCommand.BuildNextCommand()
[2017-10-19 18:06:24Z]    at System.Data.SQLite.SQLiteDataReader.NextResult()
[2017-10-19 18:06:24Z]    at System.Data.SQLite.SQLiteDataReader..ctor(SQLiteCommand cmd, CommandBehavior behave)
[2017-10-19 18:06:24Z]    at System.Data.SQLite.SQLiteCommand.ExecuteReader(CommandBehavior behavior)
[2017-10-19 18:06:24Z]    at EliteDangerousCore.DB.SQLiteDataReaderED`1..ctor(DbCommand cmd, CommandBehavior behaviour, SQLiteTransactionED`1 txn, SQLiteTxnLockED`1 txnlock) in V:\RobertW\EDDiscovery\EliteDangerous\DB\SQLiteCommandED.cs:line 339
[2017-10-19 18:06:24Z]    at EliteDangerousCore.DB.SQLiteCommandED`1.ExecuteDbDataReader(CommandBehavior behavior) in V:\RobertW\EDDiscovery\EliteDangerous\DB\SQLiteCommandED.cs:line 491
[2017-10-19 18:06:24Z]    at EliteDangerousCore.DB.SystemClassDB.GetLastSystemModifiedTime() in V:\RobertW\EDDiscovery\EliteDangerous\DB\SystemClassDB.cs:line 606
[2017-10-19 18:06:25Z] SQLite notice (27): delayed 1375ms for lock/sharing conflict at line 43027
[2017-10-19 18:06:25Z] SQLite error (3338): os_win.c:43031: (5) winAccess(D:\Google Drive\Personal\games\Elite Dangerous\EDDSystem.sqlite-journal) - Access is denied.
[2017-10-19 18:06:25Z] SQLite error (3338): disk I/O error
[2017-10-19 18:06:25Z] 
==== UNHANDLED EXCEPTION ====
System.Data.SQLite.SQLiteException (0x80004005): disk I/O error
disk I/O error
   at System.Data.SQLite.SQLite3.Prepare(SQLiteConnection cnn, String strSql, SQLiteStatement previous, UInt32 timeoutMS, String& strRemain)
   at System.Data.SQLite.SQLiteCommand.BuildNextCommand()
   at System.Data.SQLite.SQLiteDataReader.NextResult()
   at System.Data.SQLite.SQLiteDataReader..ctor(SQLiteCommand cmd, CommandBehavior behave)
   at System.Data.SQLite.SQLiteCommand.ExecuteReader(CommandBehavior behavior)
   at System.Data.SQLite.SQLiteCommand.ExecuteNonQuery(CommandBehavior behavior)
   at EliteDangerousCore.DB.SQLiteCommandED`1.ExecuteNonQuery() in V:\RobertW\EDDiscovery\EliteDangerous\DB\SQLiteCommandED.cs:line 529
   at EliteDangerousCore.DB.SQLiteConnectionSystem.CreateSystemsTableIndexesNoLock() in V:\RobertW\EDDiscovery\EliteDangerous\DB\SQLiteConnectionSystem.cs:line 342
   at EliteDangerousCore.DB.SQLiteConnectionSystem.CreateSystemsTableIndexes() in V:\RobertW\EDDiscovery\EliteDangerous\DB\SQLiteConnectionSystem.cs:line 319
   at EDDiscovery.EDDiscoveryController.CheckSystems(Func`1 cancelRequested, Action`2 reportProgress) in V:\RobertW\EDDiscovery\EDDiscovery\EDDiscoveryController.cs:line 420
   at EDDiscovery.EDDiscoveryController.BackgroundInit() in V:\RobertW\EDDiscovery\EDDiscovery\EDDiscoveryController.cs:line 710
   at EDDiscovery.EDDiscoveryController.BackgroundWorkerThread() in V:\RobertW\EDDiscovery\EDDiscovery\EDDiscoveryController.cs:line 653
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.ThreadHelper.ThreadStart()
==== cut ====
```

**Comment by phroggster** [comment]
Are you syncing your EDDiscovery data folder with Google Drive? Probably not a good idea.

You would be better off copying your data files to and fro when EDD is not running. Otherwise, Drive I going to interfere with things like temporary files.

**Comment by braxhunter** [comment]
Its the google file sync that saves everything on my desktop. I will see if i can move the folder to another location

Regards,
 
Rob Taylor 
Owner 
Taylor’d Photography and Graphics
613-983-0029
 
rtaylor@taylordphotography.com
www.taylordphotography.com
Add Me To Facebook
Add Me to Twitter

This e-mail message (including attachments) is intended only for the addressee and may contain information that is privileged, confidential and exempt from disclosure.  If you are not the intended recipient, distribution or copying of this communication is strictly prohibited.  If you have received this communication in error, please notify the sender and erase this message immediately.

**Comment by phroggster** [comment]
Yeah, another folder that's not mirrored by ~~Google Drive~~ Google Backup and Sync should be ok, or try the non-portable EDDiscovery version.

Here's a direct quote from your log showing the problem:
```
[2017-10-19 18:06:01Z] SQLite error (3338): os_win.c:43031: (5) winAccess(D:\Google Drive\Personal\games\Elite Dangerous\EDDSystem.sqlite-journal) - Access is denied.
```

**Comment by robbyxp1** [comment]
Closing, external prob to EDD
