### ISSUE TITLE
3D map crash System.AccessViolationException

### ISSUE THREAD

**Issue by gronkan** [EDDiscovery/EDDiscovery#1514]
Crash at open 3D map. Trace below
```
[2017-12-03 13:45:20Z] Running logfile age check
[2017-12-03 13:45:20Z] Native library pre-loader is trying to load native SQLite library "C:\Program Files\EDDiscovery\EDDiscovery\x64\SQLite.Interop.dll"...
[2017-12-03 13:45:20Z] SQLite version 3.19.3
[2017-12-03 13:45:20Z] *** Elite Dangerous Discovery Initializing - Version 8.4.2.0, Platform: Win32NT
[2017-12-03 13:45:21Z] Theme ID 10037
[2017-12-03 13:45:23Z] Unknown Gal Map object regional
[2017-12-03 13:45:23Z] Unknown Gal Map object organicPOI
[2017-12-03 13:45:23Z] Unknown Gal Map object geyserPOI
[2017-12-03 13:45:23Z] New watch on C:\Users\Daniel\Saved Games\Frontier Developments\Elite Dangerous
[2017-12-03 13:45:23Z] Scanned C:\Users\Daniel\Saved Games\Frontier Developments\Elite Dangerous
[2017-12-03 13:45:24Z] Unknown Gal Map object regional
[2017-12-03 13:45:24Z] Last message repeated 19 times
[2017-12-03 13:45:24Z] Unknown Gal Map object organicPOI
[2017-12-03 13:45:24Z] Last message repeated 9 times
[2017-12-03 13:45:24Z] Unknown Gal Map object geyserPOI
[2017-12-03 13:45:24Z] Last message repeated 45 times
[2017-12-03 13:45:24Z] Start Monitor on C:\Users\Daniel\Saved Games\Frontier Developments\Elite Dangerous
[2017-12-03 13:45:24Z] EDSM Fetch logs start with cmdr 1
[2017-12-03 13:45:24Z] EDSM Fetch logs restart time
[2017-12-03 13:45:25Z] Grids 522 Database Stars 10000000 mid 35 far 20
[2017-12-03 13:45:27Z] FormMap.OnShown
[2017-12-03 13:45:27Z] 
==== UNHANDLED EXCEPTION ====
System.AccessViolationException: Attempted to read or write protected memory. This is often an indication that other memory is corrupt.
   at OpenTK.Graphics.OpenGL.GL.GenBuffers(Int32 n, Int32& buffers)
   at EDDiscovery._3DMap.LineDataCollection.DrawAll(GLControl control) in C:\Code\EDDiscovery\EDDiscovery\3DMap\Data3DSetClass.cs:line 501
   at EDDiscovery.FormMap.DrawStars() in C:\Code\EDDiscovery\EDDiscovery\3DMap\FormMap.cs:line 811
   at EDDiscovery.FormMap.glControl_Paint(Object sender, PaintEventArgs e) in C:\Code\EDDiscovery\EDDiscovery\3DMap\FormMap.cs:line 788
   at System.Windows.Forms.Control.OnPaint(PaintEventArgs e)
   at OpenTK.GLControl.OnPaint(PaintEventArgs e)
   at System.Windows.Forms.Control.PaintWithErrorHandling(PaintEventArgs e, Int16 layer)
   at System.Windows.Forms.Control.WmPaint(Message& m)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)
==== cut ====
```

**Comment by phroggster** [comment]
It looks like all of seven seconds elapsed from when the application started initializing until the 3d map attempted to paint itself. This seems extremely quick, even if you're running some sort of super-computer. Did you manually launch the 3d map as soon as the button drew itself such that it could be clicked?

**Comment by gronkan** [comment]
No I waited until the GUI was stable. I have other examples of launching it much later with the same problem.

**Comment by phroggster** [comment]
Ok, just checking.

The next thing to do would be to update video card drivers. I'm assuming that you're running Windows 10? Probably the issues starting occurring after a major OS update? Win10 will usually automatically "install" minimally-functional drivers that can cause these kind of problems. Grab the most recent Nvidia/ATI/Intel/$other drivers directly from their website, and install those, then reboot to see if the problem persists. Also, when you report back, let us know what kind of video card you're running.

**Comment by klightspeed** [comment]
That `AccessViolationException` when calling [`GL.GenBuffers`](https://github.com/EDDiscovery/EDDiscovery/blob/master/EDDiscovery/3DMap/Data3DSetClass.cs#L500) suggests that the OpenGL implementation provided by the Video card driver doesn't implement [glGenBuffers](https://www.khronos.org/registry/OpenGL-Refpages/gl4/html/glGenBuffers.xhtml).

That function requires at least OpenGL 1.5

The default Windows OpenGL implementation (from Windows 98 all the way up to and including Windows 10) only provides OpenGL 1.1 compatibility when the video card driver doesn't provide its own OpenGL implementation.  This is often the case for older integrated Intel graphics (including in hybrid Intel/nVidia or Intel/AMD laptops where the program is run on the Intel adapter).

**Comment by gronkan** [comment]
Ok installing updated drivers and a reboot fixed the issue. Thank you!
