### ISSUE TITLE
Fatal Error

### ISSUE THREAD

**Issue by engineerjosh** [EDDiscovery/EDDiscovery#1547]
when i run EDDiscovery 9.0.0.0 this error message popup

A fatal exception was encountered while initializing EDDiscovery.

```
==== BEGIN ====
System.BadImageFormatException: Could not load file or assembly 'System.Core, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089' or one of its dependencies. The module was expected to contain an assembly manifest.
File name: 'System.Core, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089'
   at EDDiscovery.EDDOptions.ProcessCommandLineOptions(Func`3 getopt)
   at EDDiscovery.EDDOptions.Init() in C:\Code\EDDiscovery\EDDiscovery\EDDOptions.cs:line 247
   at EDDiscovery.EDDiscoveryController.InitializeConfig() in C:\Code\EDDiscovery\EDDiscovery\EDDiscoveryController.cs:line 348
   at EDDiscovery.EDDiscoveryController.Initialize(Action`1 msg) in C:\Code\EDDiscovery\EDDiscovery\EDDiscoveryController.cs:line 109
   at EDDiscovery.EDDApplicationContext.MainEngineStart(Object sender, EventArgs e) in C:\Code\EDDiscovery\EDDiscovery\EDDApplicationContext.cs:line 137

WRN: Assembly binding logging is turned OFF.
To enable assembly bind failure logging, set the registry value [HKLM\Software\Microsoft\Fusion!EnableLog] (DWORD) to 1.
Note: There is some performance penalty associated with assembly bind failure logging.
To turn this feature off, remove the registry value [HKLM\Software\Microsoft\Fusion!EnableLog].

===== END =====
```

can someone help me to fix this. i try downloading older versions but it will give me the some error

**Comment by klightspeed** [comment]
That sounds like your dotnet install is corrupt.

What OS are you using?

**Comment by phroggster** [comment]
Alternatively, is your config.ini file unmodified?

**Comment by engineerjosh** [comment]
the OS i using is a Window 8.1
