### ISSUE TITLE
Issue with EDDiscovery v9.0.3.0

### ISSUE THREAD

**Issue by majorsap** [EDDiscovery/EDDiscovery#1656]
I keep getting this error after installing and trying to start EDDiscovery:
```
An unhandled fatal exception has occurred
==== BEGIN ====
System.Data.SQLite.SQLiteException (0x80004005): database disk image is malformed
database disk image is malformed
   at System.Data.SQLite.SQLite3.Reset(SQLiteStatement stmt)
   at System.Data.SQLite.SQLite3.Step(SQLiteStatement stmt)
   at System.Data.SQLite.SQLiteDataReader.NextResult()
   at System.Data.SQLite.SQLiteDataReader..ctor(SQLiteCommand cmd, CommandBehavior behave)
   at System.Data.SQLite.SQLiteCommand.ExecuteReader(CommandBehavior behavior)
   at System.Data.SQLite.SQLiteCommand.ExecuteNonQuery(CommandBehavior behavior)
   at EliteDangerousCore.DB.SQLiteCommandED`1.ExecuteNonQuery() in C:\Code\EDDiscovery\EliteDangerous\DB\SQLiteCommandED.cs:line 529
   at EliteDangerousCore.DB.SQLiteConnectionSystem.CreateSystemsTableIndexesNoLock() in C:\Code\EDDiscovery\EliteDangerous\DB\SQLiteConnectionSystem.cs:line 342
   at EliteDangerousCore.DB.SQLiteConnectionSystem.CreateSystemsTableIndexes() in C:\Code\EDDiscovery\EliteDangerous\DB\SQLiteConnectionSystem.cs:line 319
   at EDDiscovery.EDDiscoveryController.CheckSystems(Func`1 cancelRequested, Action`2 reportProgress) in C:\Code\EDDiscovery\EDDiscovery\EDDiscoveryController.cs:line 421
   at EDDiscovery.EDDiscoveryController.BackgroundInit() in C:\Code\EDDiscovery\EDDiscovery\EDDiscoveryController.cs:line 720
   at EDDiscovery.EDDiscoveryController.BackgroundWorkerThread() in C:\Code\EDDiscovery\EDDiscovery\EDDiscoveryController.cs:line 663
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.ThreadHelper.ThreadStart()
===== END =====
```

**Comment by phroggster** [comment]
Your systems database is corrupt. Fortunately, this file will be downloaded automatically, so all you have to do is:
* Exit EDDiscovery.
* Delete `%LOCALAPPDATA%\EDDiscovery\EDDSystems.sqlite`.
  * If using the Portable version, this file will be in the `Data` folder alongside EDDiscovery.exe.
  * If you've moved your databases, the provided path will need to be updated to wherever you've moved them to.
* Start EDDiscovery again.
* Wait a little while for it to say that it's online with some 18 million systems.

**Comment by majorsap** [comment]
Thanks. All working now
