### ISSUE TITLE
9.0.4.0 Fatal Error

### ISSUE THREAD

**Issue by paulhoff** [EDDiscovery/EDDiscovery#1706]
An unhandled fatal exception has occurred.

==== BEGIN ====
System.InvalidOperationException: Invoke or BeginInvoke cannot be called on a control until the window handle has been created.
   at System.Windows.Forms.Control.MarshaledInvoke(Control caller, Delegate method, Object[] args, Boolean synchronous)
   at System.Windows.Forms.Control.BeginInvoke(Delegate method, Object[] args)
   at EDDiscovery.UserControls.UserControlMap.<KickComputation>b__13_0(ISystem s, SortedList`2 d) in C:\Code\EDDiscovery\EDDiscovery\UserControls\UserControlMap.cs:line 98
   at EDDiscovery.UserControls.UserControlStarDistance.StarDistanceComputer.BackgroundStardistWorkerThread() in C:\Code\EDDiscovery\EDDiscovery\UserControls\UserControlStarDistance.cs:line 323
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.ThreadHelper.ThreadStart()
===== END =====

**Comment by RipaMoram117** [comment]
I am getting this exact issue on startup of EDD as well, won't open a new ticket though, as this one is already here.

**Comment by klightspeed** [comment]
@RipaMoram117 does your exception mention `BackgroundStardistWorkerThread`?

If not, please open another issue with your exception details.

**Comment by robbyxp1** [comment]
Will fix in 9.1
