### ISSUE TITLE
"Unhandled UI exception" / " :database is locked"

### ISSUE THREAD

**Issue by ACEinONYX** [EDDiscovery/EDDiscovery#1723]
Last I opened EDD, it offered me a note to say I SHOULDN'T have both EDD and EDMC both sending to EDDN..  ( how can I get EDMC to "only" send the MARKET data, so EDD can continue to send SYSTEM data?  I use EDDB.io frequently...)

.. so I turned off EDDN in EDD, since the Market info is (presently) "more critical" for me than up-to-date Minor Faction %s..  ;)

Then, later, EDD "crashed".

Now, I forget (cuz I didn't immediately report!) it happened before or after I had put the PC into SLEEP mode for a short while, so I'm not sure if THAT would have anything to do with the EXCEPTION...

Here's the Unhandled Exception window contents, copy-pasted::
---------------------------
Unhandled Exception
---------------------------
There was an unhandled UI exception.
Please report this at https://github.com/EDDiscovery/EDDiscovery/issues and attach 
C:\Users\ (-me-) \AppData\Local\EDDiscovery\Log\Trace_20180213(mmhhss).0.log
Exception: database is locked

database is locked
   at System.Data.SQLite.SQLite3.Prepare(SQLiteConnection cnn, String strSql, SQLiteStatement previous, UInt32 timeoutMS, String& strRemain)

   at System.Data.SQLite.SQLiteCommand.BuildNextCommand()

   at System.Data.SQLite.SQLiteDataReader.NextResult()

   at System.Data.SQLite.SQLiteDataReader..ctor(SQLiteCommand cmd, CommandBehavior behave)

   at System.Data.SQLite.SQLiteCommand.ExecuteReader(CommandBehavior behavior)

   at EliteDangerousCore.DB.SQLiteDataReaderED`1..ctor(DbCommand cmd, CommandBehavior behaviour, SQLiteTransactionED`1 txn, SQLiteTxnLockED`1 txnlock)

   at EliteDangerousCore.DB.SQLiteCommandED`1.ExecuteDbDataReader(CommandBehavior behavior)

   at EliteDangerousCore.DB.SystemClassDB.GetEdsmIdsFromName(String name, SQLiteConnectionSystem cn, Boolean uselike)

   at EliteDangerousCore.DB.SystemClassDB.GetSystemsByName(String name, SQLiteConnectionSystem cn, Boolean uselike)

   at EliteDangerousCore.DB.SystemClassDB.FindEDSM(ISystem s, SQLiteConnectionSystem conn)

   at EliteDangerousCore.HistoryList.FindEDSM(HistoryEntry syspos, SQLiteConnectionSystem conn, Boolean reload)

   at EliteDangerousCore.HistoryList.FillEDSM(HistoryEntry syspos, SystemClassDB edsmsys, Boolean reload, SQLiteConnectionUser uconn)

   at EDDiscovery.UserControls.UserControlSysInfo.Display(HistoryEntry he, HistoryList hl)

   at EDDiscovery.UserControls.ChangedSelectionHE.Invoke(HistoryEntry he, HistoryList hl)

   at EDDiscovery.UserControls.UserControlTravelGrid.FireChangeSelection()

   at EDDiscovery.UserControls.UserControlTravelGrid.HistoryChanged(HistoryList hl)

   at System.Action`1.Invoke(T obj)

   at EDDiscovery.EDDiscoveryController.RefreshHistoryWorkerCompleted(HistoryList hist)

Do you wish to abort, or ignore the exception and try to continue?
---------------------------
Abort   Retry   Ignore   
---------------------------

**Comment by klightspeed** [comment]
Please attach the mentioned log - this "database is locked" is usually because either some external program has locked `EDDSystem.sqlite` or the SQLite library hasn't released the database lock after executing a command.  It would be helpful to know what was happening at the point this occurred.

**Comment by ACEinONYX** [comment]
Begging your pardon; I'd thought that was it...

Will go and fetch the relevant required . . . BRB

**Comment by ACEinONYX** [comment]
[2018-02-13 03:41:21Z] Running logfile age check
[2018-02-13 03:41:21Z] Native library pre-loader is trying to load native SQLite library "C:\Program Files (x86)\EDDiscovery\EDDiscovery\x64\SQLite.Interop.dll"...
[2018-02-13 03:41:21Z] SQLite version 3.19.3
[2018-02-13 03:41:22Z] *** Elite Dangerous Discovery Initializing - Version 8.3.3.0, Platform: Win32NT
[2018-02-13 03:41:24Z] Theme ID 10037
[2018-02-13 03:41:35Z] Unknown Gal Map object regional
[2018-02-13 03:41:35Z] Unknown Gal Map object organicPOI
[2018-02-13 03:41:35Z] Unknown Gal Map object geyserPOI
[2018-02-13 03:41:36Z] New EDDiscovery installer available: EDDiscovery Release 9.0.4 with Free Voice Control
[2018-02-13 03:41:37Z] EDDiscovery and EDMarketConnector should not both sync to EDDN. Stop EDMC or uncheck 'send to EDDN' in settings tab!
[2018-02-13 03:41:37Z] New watch on C:\Users\ <-me-> \Saved Games\Frontier Developments\Elite Dangerous
[2018-02-13 03:41:37Z] Scanned C:\Users\ <-me-> \Saved Games\Frontier Developments\Elite Dangerous

..... and then these "Unknown Gal Map object **" messages, I found curious.....
 
[2018-02-13 03:41:38Z] Unknown Gal Map object regional
[2018-02-13 03:41:38Z] Last message repeated 19 times
[2018-02-13 03:41:38Z] Unknown Gal Map object organicPOI
[2018-02-13 03:41:38Z] Last message repeated 10 times
[2018-02-13 03:41:38Z] Unknown Gal Map object geyserPOI
[2018-02-13 03:41:38Z] Last message repeated 50 times

..... then a rather LONG "catchup" section (I don't see the need to copy it all) full of:

[2018-02-13 03:41:48Z] Write Journal to db <dd>/02/2018 <hh:mm:ss> <eventName>

... with ONE of these _in the middle_:

[2018-02-13 03:41:46Z] TLU C:\Users\ <-me-> \Saved Games\Frontier Developments\Elite Dangerous updated with commander 0

... from when I'd run Elite withOUT EDDisco, followed by ...

[2018-02-13 03:42:31Z] Directory watcher picked up screenshot C:\Users\ <etc>..
[2018-02-13 03:42:41Z] Start Monitor on C:\Users\ <etc>..
[2018-02-13 03:42:41Z] EDSM Fetch logs start with cmdr 0
[2018-02-13 03:42:41Z] EDSM Fetch logs restart time
[2018-02-13 03:42:42Z] New entry 13/02/2018 03:42:31 Screenshot
[2018-02-13 03:42:42Z] Journal Screenshot logged \ED_Pictures\Screenshot_0607.bmp
[2018-02-13 03:42:52Z] Thread Background Worker Thread waiting for readers to finish
[2018-02-13 03:44:32Z] Stop Monitor on C:\Users\ <etc>..
[2018-02-13 03:44:32Z] Scanned C:\Users\ <etc>..
[2018-02-13 03:44:33Z] Thread Background Worker Thread waiting for readers to finish
[2018-02-13 03:44:33Z] Last message repeated 27 times
[2018-02-13 03:44:40Z] EDDB Count 10000 Delta 81125 info 10000 update 8200 new 0
[2018-02-13 03:44:52Z] SQLite error (5): database is locked
[2018-02-13 03:45:22Z] Exception : database is locked

[2018-02-13 03:45:22Z] database is locked
[2018-02-13 03:45:22Z]    at System.Data.SQLite.SQLite3.Prepare(SQLiteConnection cnn, String strSql, SQLiteStatement previous, UInt32 timeoutMS, String& strRemain)

[2018-02-13 03:45:22Z]    at System.Data.SQLite.SQLiteCommand.BuildNextCommand()

[2018-02-13 03:45:22Z]    at System.Data.SQLite.SQLiteDataReader.NextResult()

[2018-02-13 03:45:22Z]    at System.Data.SQLite.SQLiteDataReader..ctor(SQLiteCommand cmd, CommandBehavior behave)

[2018-02-13 03:45:22Z]    at System.Data.SQLite.SQLiteCommand.ExecuteReader(CommandBehavior behavior)

[2018-02-13 03:45:22Z]    at EliteDangerousCore.DB.SQLiteDataReaderED`1..ctor(DbCommand cmd, CommandBehavior behaviour, SQLiteTransactionED`1 txn, SQLiteTxnLockED`1 txnlock)

[2018-02-13 03:45:22Z]    at EliteDangerousCore.DB.SQLiteCommandED`1.ExecuteDbDataReader(CommandBehavior behavior)

[2018-02-13 03:45:22Z]    at EliteDangerousCore.DB.SystemClassDB.GetSystem(Int64 id, SQLiteConnectionSystem cn, SystemIDType idtype)
[2018-02-13 03:45:22Z]    at EliteDangerousCore.DB.SystemClassDB.GetSystemSqDistancesFrom(SortedList`2 distlist, Double x, Double y, Double z, Int32 maxitems, Boolean removezerodiststar, Double maxdist, SQLiteConnectionSystem cn)
[2018-02-13 03:45:53Z] 
==== UNHANDLED UI EXCEPTION ====
System.Data.SQLite.SQLiteException (0x80004005): database is locked
database is locked

///*** section as copied previously, up to last previously-quoted line as follows ***///

   at EDDiscovery.EDDiscoveryController.RefreshHistoryWorkerCompleted(HistoryList hist)
==== cut ====
[2018-02-13 03:45:54Z] SQLite error (5): database is locked
[2018-02-13 03:45:54Z] Last message repeated 1076 times
[2018-02-13 03:45:54Z] Exception : database is locked

[2018-02-13 03:45:54Z] database is locked
[2018-02-13 03:45:54Z]    at System.Data.SQLite.SQLite3.Prepare(SQLiteConnection cnn, String strSql, SQLiteStatement previous, UInt32 timeoutMS, String& strRemain)

[2018-02-13 03:45:54Z]    at System.Data.SQLite.SQLiteCommand.BuildNextCommand()

[2018-02-13 03:45:54Z]    at System.Data.SQLite.SQLiteDataReader.NextResult()

[2018-02-13 03:45:54Z]    at System.Data.SQLite.SQLiteDataReader..ctor(SQLiteCommand cmd, CommandBehavior behave)

[2018-02-13 03:45:54Z]    at System.Data.SQLite.SQLiteCommand.ExecuteReader(CommandBehavior behavior)

[2018-02-13 03:45:54Z]    at EliteDangerousCore.DB.SQLiteDataReaderED`1..ctor(DbCommand cmd, CommandBehavior behaviour, SQLiteTransactionED`1 txn, SQLiteTxnLockED`1 txnlock)

[2018-02-13 03:45:54Z]    at EliteDangerousCore.DB.SQLiteCommandED`1.ExecuteDbDataReader(CommandBehavior behavior)

[2018-02-13 03:45:55Z] EDDB Count 20000 Delta 74703 info 20000 update 16649 new 0
[2018-02-13 03:46:25Z] EDSM Check date: 2018-02-12 17:07:53
[2018-02-13 04:02:56Z] Directory watcher picked up screenshot C:\Users\ <-me-> \Pictures\Frontier Developments\Elite Dangerous\Screenshot_0608.bmp
[2018-02-13 04:04:57Z] Import took 1105707ms

..... and then follows a MASSIVE section of Import "Id"s...

Id <xxxx> count <nnn>

... which wouldn't be worth copying...
... along with a few more Screenshot pickups ...
... and regular "EDSM Check date" stamps, reflecting/updating the previous (approx hourly) ...
... until finally,

[2018-02-13 15:52:12Z] Closing down, please wait..
[2018-02-13 15:52:12Z] Close.. safe close launched

... erm... cuz that's how long I'd left EDD "hanging" with ..um .. the "Abort, Retry, Ignore" dialog box up..

Heh.  :]

**Comment by klightspeed** [comment]
```
[2018-02-13 03:44:40Z] EDDB Count 10000 Delta 81125 info 10000 update 8200 new 0
[2018-02-13 03:44:52Z] SQLite error (5): database is locked
...
[2018-02-13 03:45:22Z] at EliteDangerousCore.DB.SQLiteCommandED`1.ExecuteDbDataReader(CommandBehavior behavior)
[2018-02-13 03:45:22Z] at EliteDangerousCore.DB.SystemClassDB.GetSystem(Int64 id, SQLiteConnectionSystem cn, SystemIDType idtype)
[2018-02-13 03:45:22Z] at EliteDangerousCore.DB.SystemClassDB.GetSystemSqDistancesFrom(SortedList`2 distlist, Double x, Double y, Double z, Int32 maxitems, Boolean removezerodiststar, Double maxdist, SQLiteConnectionSystem cn)
...
[2018-02-13 03:45:54Z] SQLite error (5): database is locked
[2018-02-13 03:45:54Z] Last message repeated 1076 times
...
[2018-02-13 03:45:54Z] at System.Data.SQLite.SQLiteCommand.ExecuteReader(CommandBehavior behavior)
[2018-02-13 03:45:54Z] at EliteDangerousCore.DB.SQLiteDataReaderED1..ctor(DbCommand cmd, CommandBehavior behaviour, SQLiteTransactionED1 txn, SQLiteTxnLockED`1 txnlock)
[2018-02-13 03:45:54Z] at EliteDangerousCore.DB.SQLiteCommandED`1.ExecuteDbDataReader(CommandBehavior behavior)
[2018-02-13 03:45:55Z] EDDB Count 20000 Delta 74703 info 20000 update 16649 new 0
```

That looks like either the SQLite library is leaving a lock on the database after the connection is closed, or the fix in #1429 was negated.

**Comment by ACEinONYX** [comment]
I've yet to school myself on SQL(/Lite) .. :(

What I found most curious about the log here is that the "Last message repeated" over 1,000 times -- notwithstanding modern processing speeds probably implying it literally might not even have taken "half a second" ...  :p 

Thanks for the feedback; I'm not one for detailed readings of ChangeLogs, so ...  I hope my log info was useful to furthering the EDD project in general, and I hope it helps many more other users.

Oh, wait... I've not updated to the latest, cuz I'm not interested in the Voice control..

.. .but not being updated to the latest, could THAT be why I experienced that error?

Thanks, @klightspeed Ben.

Cheers,
Chris..

**Comment by klightspeed** [comment]
That commit is in 8.4.1

**Comment by robbyxp1** [comment]
We do tons of other fixes and add ons other than the major feature 9.0 was announced as having ;-)

**Comment by ACEinONYX** [comment]
Of course, do forgive me, Rob @robbyxp1 .. I did not mean to demean or diminish, in any way, the copious amounts of work that so many contributors bring to such a wonderful, popular, & useful project, by only having mentioned the much-lauded addition of voice control..  ;) 

As a quite-regular user of EDD, I'm immensely grateful for the existence & free availability of such a tool, and by extension grateful to all its contributors.  :D

**Happy Chinese / Lunar New Year (of the DOG), all, as it falls on today, Fri 16th., this year.
"Kung Hei Fat Choi" -- may (peace, happiness, health, &) wealth flow your way this year.
