### ISSUE TITLE
9.1.0 Crash on startup

### ISSUE THREAD

**Issue by lorrad** [EDDiscovery/EDDiscovery#1755]
### Exception Details:
>EDDiscovery v9.1.0.0 A fatal exception was encountered while initializing EDDiscovery.
>```
>==== BEGIN ====
>System.ArgumentException: Font 'Arial Narrow' does not support style 'Regular'.
>   at System.Drawing.Font.CreateNativeFont()
>   at System.Drawing.Font.Initialize(FontFamily family, Single emSize, FontStyle style, GraphicsUnit unit, Byte gdiCharSet, Boolean gdiVerticalFont)
>   at System.Drawing.Font..ctor(String familyName, Single emSize)
>   at ExtendedControls.ThemeStandard.IsFontAvailable(String fontwanted) in C:\Code\EDDiscovery\ExtendedControls\Themes\ThemeStandard.cs:line 1016
>   at ExtendedControls.ThemeStandard.LoadBaseThemes() in C:\Code\EDDiscovery\ExtendedControls\Themes\ThemeStandard.cs:line 284
>   at EDDiscovery.EDDTheme.LoadThemes() in C:\Code\EDDiscovery\EDDiscovery\Themeing\Theme.cs:line 123
>   at EDDiscovery.EDDiscoveryForm.Init(Action`1 msg) in C:\Code\EDDiscovery\EDDiscovery\EDDiscoveryForm.cs:line 168
>   at EDDiscovery.EDDApplicationContext.MainEngineStart(Object sender, EventArgs e) in C:\Code\EDDiscovery\EDDiscovery\EDDApplicationContext.cs:line 144
>===== END =====
>```

**Comment by robbyxp1** [comment]
Hold down shift when booting and select boot without theme

**Comment by robbyxp1** [comment]
Protected on master for exception

**Comment by lorrad** [comment]
Ok, did that with reset theme and reset window positions and still get,,
running portable version btw and when I revert to previous version 9.0.4 everything is fine 

Downloaded 9.1.1 and still getting

A fatal exception was encountered while initializing EDDiscovery.

==== BEGIN ====
System.ArgumentException: Font 'Arial Narrow' does not support style 'Regular'.
   at System.Drawing.Font.CreateNativeFont()
   at System.Drawing.Font.Initialize(FontFamily family, Single emSize, FontStyle style, GraphicsUnit unit, Byte gdiCharSet, Boolean gdiVerticalFont)
   at System.Drawing.Font..ctor(String familyName, Single emSize)
   at ExtendedControls.ThemeStandard.IsFontAvailable(String fontwanted) in C:\Code\EDDiscovery\ExtendedControls\Themes\ThemeStandard.cs:line 1030
   at ExtendedControls.ThemeStandard.LoadBaseThemes() in C:\Code\EDDiscovery\ExtendedControls\Themes\ThemeStandard.cs:line 284
   at EDDiscovery.EDDTheme.LoadThemes() in C:\Code\EDDiscovery\EDDiscovery\Themeing\Theme.cs:line 123
   at EDDiscovery.EDDiscoveryForm.Init(Action`1 msg) in C:\Code\EDDiscovery\EDDiscovery\EDDiscoveryForm.cs:line 169
   at EDDiscovery.EDDApplicationContext.MainEngineStart(Object sender, EventArgs e) in C:\Code\EDDiscovery\EDDiscovery\EDDApplicationContext.cs:line 144
===== END =====

**Comment by lorrad** [comment]
Tracked this down,,,Win 7 problem,,,Ariel Narrow not included in win 7,,,
I'll have to add it

https://www.google.ae/url?sa=t&rct=j&q=&esrc=s&source=web&cd=1&cad=rja&uact=8&ved=0ahUKEwif3vnazcbZAhVOzaQKHXbXBBwQFggvMAA&url=https%3A%2F%2Fanswers.microsoft.com%2Fen-us%2Fwindows%2Fforum%2Fwindows_7-desktop%2Farial-narrow-font-is-missing%2F98cfeeaa-dd34-4ba4-884a-2346744b5f05&usg=AOvVaw06IXYGnLV7p7kkUairEaqh

**Comment by robbyxp1** [comment]
It should not crash on 9.1.4..

**Comment by lorrad** [comment]
Thanks,,,it stopped crashing as soon as I installed the missing font.
