### ISSUE TITLE
Exception after first instance run

### ISSUE THREAD

**Issue by jgoode** [EDDiscovery/EDDiscovery#1756]
There was an unhandled UI exception.

==== BEGIN ====
System.NullReferenceException: Object reference not set to an instance of an object.
   at EDDiscovery.UserControls.UserControlTravelGrid.PaintEventColumn(DataGridView grid, DataGridViewRowPostPaintEventArgs e, Int32 totalentries, HistoryEntry he, Int32 hpos, Int32 colwidth, Boolean showfsdmapcolour) in C:\Code\EDDiscovery\EDDiscovery\UserControls\UserControlTravelGrid.cs:line 452
   at EDDiscovery.UserControls.UserControlTravelGrid.dataGridViewTravel_RowPostPaint(Object sender, DataGridViewRowPostPaintEventArgs e) in C:\Code\EDDiscovery\EDDiscovery\UserControls\UserControlTravelGrid.cs:line 422
   at System.Windows.Forms.DataGridView.OnRowPostPaint(DataGridViewRowPostPaintEventArgs e)
   at System.Windows.Forms.DataGridViewRow.Paint(Graphics graphics, Rectangle clipBounds, Rectangle rowBounds, Int32 rowIndex, DataGridViewElementStates rowState, Boolean isFirstDisplayedRow, Boolean isLastVisibleRow)
   at System.Windows.Forms.DataGridView.PaintRows(Graphics g, Rectangle boundingRect, Rectangle clipRect, Boolean singleHorizontalBorderAdded)
   at System.Windows.Forms.DataGridView.PaintGrid(Graphics g, Rectangle gridBounds, Rectangle clipRect, Boolean singleVerticalBorderAdded, Boolean singleHorizontalBorderAdded)
   at System.Windows.Forms.DataGridView.OnPaint(PaintEventArgs e)
   at System.Windows.Forms.Control.PaintWithErrorHandling(PaintEventArgs e, Int16 layer)
   at System.Windows.Forms.Control.WmPaint(Message& m)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)
===== END =====

**Comment by LethalByte** [comment]
Hi all,
I have the same issue. My exception is the same:-
>==== BEGIN ====
>System.NullReferenceException: Object reference not set to an instance of an object.
>   at EDDiscovery.UserControls.UserControlTravelGrid.PaintEventColumn(DataGridView grid, DataGridViewRowPostPaintEventArgs e, Int32 totalentries, HistoryEntry he, Int32 hpos, Int32 colwidth, Boolean showfsdmapcolour) in C:\Code\EDDiscovery\EDDiscovery\UserControls\UserControlTravelGrid.cs:line 452
>   at EDDiscovery.UserControls.UserControlTravelGrid.dataGridViewTravel_RowPostPaint(Object sender, DataGridViewRowPostPaintEventArgs e) in C:\Code\EDDiscovery\EDDiscovery\UserControls\UserControlTravelGrid.cs:line 422
>   at System.Windows.Forms.DataGridView.OnRowPostPaint(DataGridViewRowPostPaintEventArgs e)
>   at System.Windows.Forms.DataGridViewRow.Paint(Graphics graphics, Rectangle clipBounds, Rectangle rowBounds, Int32 rowIndex, DataGridViewElementStates rowState, Boolean isFirstDisplayedRow, Boolean isLastVisibleRow)
>   at System.Windows.Forms.DataGridView.PaintRows(Graphics g, Rectangle boundingRect, Rectangle clipRect, Boolean singleHorizontalBorderAdded)
>   at System.Windows.Forms.DataGridView.PaintGrid(Graphics g, Rectangle gridBounds, Rectangle clipRect, Boolean singleVerticalBorderAdded, Boolean singleHorizontalBorderAdded)
>   at System.Windows.Forms.DataGridView.OnPaint(PaintEventArgs e)
>   at System.Windows.Forms.Control.PaintWithErrorHandling(PaintEventArgs e, Int16 layer)
>   at System.Windows.Forms.Control.WmPaint(Message& m)
>   at System.Windows.Forms.Control.WndProc(Message& m)
>   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)
>===== END =====
>```

PS Thanks for all the great work on EDDiscovery o7

**Comment by 67MistakeNot** [comment]
I have the same problem. I have deleted the application and done a clean install, but it hasn't made a difference.

**Comment by robbyxp1** [comment]
Fixed,  try the latest.
