### ISSUE TITLE
9.1.3 error before fully loading

### ISSUE THREAD

**Issue by Disorganise** [EDDiscovery/EDDiscovery#1762]
I was on 9.1.0 when ED 3.0 downloaded - seemed to be ok until I scanned something and the overlay failed to update, then it the program went unresponsive though the jump overlay and voicepack were still updating.  When I quit game there was a windows error dialog unhandled exception but I didn't grab it, sorry.
Restarted and the log was giving lots of red...check for update - no release (seems it's not checking?).  Came here and got 9.1.3, but I still get lots of red and it doesn't finish the load (responsive but no history displayed and overlays are empty)

Reading travel history
Voice Pack installed, running on EDD Version 9.1.3.0
Scanning for bmp screenshots in Z:\Picture_Libraries\Win10\Frontier Developments\Elite Dangerous
History Refresh Error: System.ArgumentOutOfRangeException: Index was out of range. Must be non-negative and less than the size of the collection.
Parameter name: index
   at System.ThrowHelper.ThrowArgumentOutOfRangeException(ExceptionArgument argument, ExceptionResource resource)
   at EliteDangerousCore.StarScan.ProcessElements(JournalScan sc, ISystem sys, SystemNode sn, String customname, List`1 elements, ScanNodeType starscannodetype, Boolean isbeltcluster) in C:\Code\EDDiscovery\EliteDangerous\EliteDangerous\StarScan.cs:line 736
   at EliteDangerousCore.StarScan.Process(JournalScan sc, ISystem sys, Boolean reprocessPrimary) in C:\Code\EDDiscovery\EliteDangerous\EliteDangerous\StarScan.cs:line 323
   at EliteDangerousCore.HistoryList.ProcessUserHistoryListEntries(Func`2 hlfilter) in C:\Code\EDDiscovery\EliteDangerous\HistoryList\HistoryList.cs:line 946
   at EliteDangerousCore.HistoryList.LoadHistory(EDJournalClass journalmonitor, Func`1 cancelRequested, Action`2 reportProgress, String NetLogPath, Boolean ForceNetLogReload, Boolean ForceJournalReload, Int32 CurrentCommander, Boolean Keepuievents) in C:\Code\EDDiscovery\EliteDangerous\HistoryList\HistoryList.cs:line 915
   at EDDiscovery.EDDiscoveryController.DoRefreshHistory(RefreshWorkerArgs args) in C:\Code\EDDiscovery\EDDiscovery\EDDiscoveryController.cs:line 811
Error at VoicePackV6::onRefreshEnd Step 3: Line 656:
Ledger Cannot find entry in Ledger
Logged into Companion API
History refresh complete.
Loading completed, total of 19,698,967 systems stored

**Comment by robbyxp1** [comment]
Thanks. Known. 9.1.4 will fix
