### ISSUE TITLE
StarScan error

### ISSUE THREAD

**Issue by Zefod** [EDDiscovery/EDDiscovery#1763]
EDDiscovery crashed while jumping after that it wat unable to load history:

History Refresh Error: System.NullReferenceException: Object reference not set to an instance of an object.
   at EliteDangerousCore.StarScan.Process(IBodyNameAndID sc, ISystem sys, Boolean reprocessPrimary) in C:\Code\EDDiscovery\EliteDangerous\EliteDangerous\StarScan.cs:line 423
   at EliteDangerousCore.StarScan.AddBodyToBestSystem(IBodyNameAndID je, Int32 startindex, List`1 hl, HistoryEntry& he, JournalLocOrJump& jl) in C:\Code\EDDiscovery\EliteDangerous\EliteDangerous\StarScan.cs:line 273
   at EliteDangerousCore.HistoryList.ProcessUserHistoryListEntries(Func`2 hlfilter) in C:\Code\EDDiscovery\EliteDangerous\HistoryList\HistoryList.cs:line 953
   at EliteDangerousCore.HistoryList.LoadHistory(EDJournalClass journalmonitor, Func`1 cancelRequested, Action`2 reportProgress, String NetLogPath, Boolean ForceNetLogReload, Boolean ForceJournalReload, Int32 CurrentCommander, Boolean Keepuievents) in C:\Code\EDDiscovery\EliteDangerous\HistoryList\HistoryList.cs:line 913
   at EDDiscovery.EDDiscoveryController.DoRefreshHistory(RefreshWorkerArgs args) in C:\Code\EDDiscovery\EDDiscovery\EDDiscoveryController.cs:line 811

**Comment by JerkerPihl** [comment]
Same here :(

**Comment by robbyxp1** [comment]
Acknowledged, the expert will arrive shortly

**Comment by esevens** [comment]
Same with me: EDD v9.1.3

History Refresh Error: System.ArgumentOutOfRangeException: Index was out of range. Must be non-negative and less than the size of the collection.
Parameter name: index
   at System.ThrowHelper.ThrowArgumentOutOfRangeException(ExceptionArgument argument, ExceptionResource resource)
   at EliteDangerousCore.StarScan.ProcessElements(JournalScan sc, ISystem sys, SystemNode sn, String customname, List`1 elements, ScanNodeType starscannodetype, Boolean isbeltcluster) in C:\Code\EDDiscovery\EliteDangerous\EliteDangerous\StarScan.cs:line 736
   at EliteDangerousCore.StarScan.Process(JournalScan sc, ISystem sys, Boolean reprocessPrimary) in C:\Code\EDDiscovery\EliteDangerous\EliteDangerous\StarScan.cs:line 323
   at EliteDangerousCore.HistoryList.ProcessUserHistoryListEntries(Func`2 hlfilter) in C:\Code\EDDiscovery\EliteDangerous\HistoryList\HistoryList.cs:line 946
   at EliteDangerousCore.HistoryList.LoadHistory(EDJournalClass journalmonitor, Func`1 cancelRequested, Action`2 reportProgress, String NetLogPath, Boolean ForceNetLogReload, Boolean ForceJournalReload, Int32 CurrentCommander, Boolean Keepuievents) in C:\Code\EDDiscovery\EliteDangerous\HistoryList\HistoryList.cs:line 915
   at EDDiscovery.EDDiscoveryController.DoRefreshHistory(RefreshWorkerArgs args) in C:\Code\EDDiscovery\EDDiscovery\EDDiscoveryController.cs:line 811

**Comment by robbyxp1** [comment]
9.1.4 should fix, please report back if not

**Comment by Zefod** [comment]
jep EDDiscovery is loading history again 👍 I had to manually download 9.1.4 though...
AVG thinks the installer is bad and crashes on analysing it... time for a new virus scanner i guess 😃
