### ISSUE TITLE
9.1.3 ArgumentOutOfRangeException when scanning for bmp's at upstart

### ISSUE THREAD

**Issue by MacrosBlack** [EDDiscovery/EDDiscovery#1765]
Scanning for bmp screenshots in C:\Users\[UserName]\Pictures\Frontier Developments\Elite Dangerous
History Refresh Error: System.ArgumentOutOfRangeException: Index was out of range. Must be non-negative and less than the size of the collection.
Parameter name: index
   at System.ThrowHelper.ThrowArgumentOutOfRangeException(ExceptionArgument argument, ExceptionResource resource)
   at EliteDangerousCore.StarScan.ProcessElements(JournalScan sc, ISystem sys, SystemNode sn, String customname, List`1 elements, ScanNodeType starscannodetype, Boolean isbeltcluster) in C:\Code\EDDiscovery\EliteDangerous\EliteDangerous\StarScan.cs:line 736
   at EliteDangerousCore.StarScan.Process(JournalScan sc, ISystem sys, Boolean reprocessPrimary) in C:\Code\EDDiscovery\EliteDangerous\EliteDangerous\StarScan.cs:line 323
   at EliteDangerousCore.HistoryList.ProcessUserHistoryListEntries(Func`2 hlfilter) in C:\Code\EDDiscovery\EliteDangerous\HistoryList\HistoryList.cs:line 946
   at EliteDangerousCore.HistoryList.LoadHistory(EDJournalClass journalmonitor, Func`1 cancelRequested, Action`2 reportProgress, String NetLogPath, Boolean ForceNetLogReload, Boolean ForceJournalReload, Int32 CurrentCommander, Boolean Keepuievents) in C:\Code\EDDiscovery\EliteDangerous\HistoryList\HistoryList.cs:line 915
   at EDDiscovery.EDDiscoveryController.DoRefreshHistory(RefreshWorkerArgs args) in C:\Code\EDDiscovery\EDDiscovery\EDDiscoveryController.cs:line 811

**Comment by TheHunstman** [comment]
Exactly the same issue for me.  Only 130 historic jumps loaded.

**Comment by robbyxp1** [comment]
Thanks. Known. 9.1.4 will fix
