### ISSUE TITLE
An Unhandled Fatal Exception Occured- Loadout

### ISSUE THREAD

**Issue by badbud65** [EDDiscovery/EDDiscovery#1766]
Installed new version and when EDDiscovery loads I get this error:

An unhandled fatal exception has occurred.

==== BEGIN ====
System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation. ---> Newtonsoft.Json.JsonReaderException: Could not convert string to double: $Thermic;. Path 'Modules[3].Engineering.Modifiers[7].Value', line 223, position 32.
   at Newtonsoft.Json.JsonReader.ReadDoubleString(String s)
   at Newtonsoft.Json.JsonReader.ReadAsDouble()
   at Newtonsoft.Json.JsonReader.ReadForType(JsonContract contract, Boolean hasConverter)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.PopulateObject(Object newObject, JsonReader reader, JsonObjectContract contract, JsonProperty member, String id)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateObject(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.PopulateList(IList list, JsonReader reader, JsonArrayContract contract, JsonProperty containerProperty, String id)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateList(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, Object existingValue, String id)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.Deserialize(JsonReader reader, Type objectType, Boolean checkAdditionalContent)
   at Newtonsoft.Json.JsonSerializer.DeserializeInternal(JsonReader reader, Type objectType)
   at Newtonsoft.Json.Linq.JToken.ToObject(Type objectType, JsonSerializer jsonSerializer)
   at Newtonsoft.Json.Linq.JToken.ToObject(Type objectType)
   at Newtonsoft.Json.Linq.JToken.ToObject[T]()
   at EliteDangerousCore.JournalEvents.JournalEngineerCraftBase.EngineeringData..ctor(JObject evt) in C:\Code\EDDiscovery\EliteDangerous\JournalEvents\JournalEngineerCraft.cs:line 134
   at EliteDangerousCore.JournalEvents.JournalLoadout..ctor(JObject evt) in C:\Code\EDDiscovery\EliteDangerous\JournalEvents\JournalLoadout.cs:line 141
   --- End of inner exception stack trace ---
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor)
   at System.Reflection.RuntimeConstructorInfo.Invoke(BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at System.RuntimeType.CreateInstanceImpl(BindingFlags bindingAttr, Binder binder, Object[] args, CultureInfo culture, Object[] activationAttributes, StackCrawlMark& stackMark)
   at System.Activator.CreateInstance(Type type, BindingFlags bindingAttr, Binder binder, Object[] args, CultureInfo culture, Object[] activationAttributes)
   at System.Activator.CreateInstance(Type type, Object[] args)
   at EliteDangerousCore.JournalEntry.CreateJournalEntry(JObject jo) in C:\Code\EDDiscovery\EliteDangerous\EliteDangerous\JournalEntry.cs:line 1077
   at EliteDangerousCore.JournalEntry.CreateJournalEntry(DataRow dr) in C:\Code\EDDiscovery\EliteDangerous\EliteDangerous\JournalEntry.cs:line 338
   at EliteDangerousCore.JournalEntry.GetAll(Int32 commander, Nullable`1 after, Nullable`1 before) in C:\Code\EDDiscovery\EliteDangerous\EliteDangerous\JournalEntry.cs:line 764
   at EliteDangerousCore.EDSM.EDSMLogFetcher.FetcherThreadProc() in C:\Code\EDDiscovery\EliteDangerous\EDSM\EDSMLogFetcher.cs:line 147
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.ThreadHelper.ThreadStart()
===== END =====

**Comment by badbud65** [comment]
Details from EDDiscover Log Panel:

Checking for new EDDiscovery maps
Checking for new Expedition data
Loaded Notes, Bookmarks and Galactic mapping.
Reading travel history
Scanning for bmp screenshots in C:\Users\STEVE ARTHUR\Pictures\Frontier Developments\Elite Dangerous
History Refresh Error: System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation. ---> Newtonsoft.Json.JsonReaderException: Could not convert string to double: $Thermic;. Path 'Modules[3].Engineering.Modifiers[7].Value', line 223, position 32.
   at Newtonsoft.Json.JsonReader.ReadDoubleString(String s)
   at Newtonsoft.Json.JsonReader.ReadAsDouble()
   at Newtonsoft.Json.JsonReader.ReadForType(JsonContract contract, Boolean hasConverter)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.PopulateObject(Object newObject, JsonReader reader, JsonObjectContract contract, JsonProperty member, String id)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateObject(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.PopulateList(IList list, JsonReader reader, JsonArrayContract contract, JsonProperty containerProperty, String id)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateList(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, Object existingValue, String id)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.Deserialize(JsonReader reader, Type objectType, Boolean checkAdditionalContent)
   at Newtonsoft.Json.JsonSerializer.DeserializeInternal(JsonReader reader, Type objectType)
   at Newtonsoft.Json.Linq.JToken.ToObject(Type objectType, JsonSerializer jsonSerializer)
   at Newtonsoft.Json.Linq.JToken.ToObject(Type objectType)
   at Newtonsoft.Json.Linq.JToken.ToObject[T]()
   at EliteDangerousCore.JournalEvents.JournalEngineerCraftBase.EngineeringData..ctor(JObject evt) in C:\Code\EDDiscovery\EliteDangerous\JournalEvents\JournalEngineerCraft.cs:line 134
   at EliteDangerousCore.JournalEvents.JournalLoadout..ctor(JObject evt) in C:\Code\EDDiscovery\EliteDangerous\JournalEvents\JournalLoadout.cs:line 141
   --- End of inner exception stack trace ---
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor)
   at System.Reflection.RuntimeConstructorInfo.Invoke(BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at System.RuntimeType.CreateInstanceImpl(BindingFlags bindingAttr, Binder binder, Object[] args, CultureInfo culture, Object[] activationAttributes, StackCrawlMark& stackMark)
   at System.Activator.CreateInstance(Type type, BindingFlags bindingAttr, Binder binder, Object[] args, CultureInfo culture, Object[] activationAttributes)
   at System.Activator.CreateInstance(Type type, Object[] args)
   at EliteDangerousCore.JournalEntry.CreateJournalEntry(JObject jo) in C:\Code\EDDiscovery\EliteDangerous\EliteDangerous\JournalEntry.cs:line 1077
   at EliteDangerousCore.JournalEntry.CreateJournalEntry(DataRow dr) in C:\Code\EDDiscovery\EliteDangerous\EliteDangerous\JournalEntry.cs:line 338
   at EliteDangerousCore.JournalEntry.GetAll(Int32 commander, Nullable`1 after, Nullable`1 before) in C:\Code\EDDiscovery\EliteDangerous\EliteDangerous\JournalEntry.cs:line 764
   at EliteDangerousCore.HistoryList.LoadHistory(EDJournalClass journalmonitor, Func`1 cancelRequested, Action`2 reportProgress, String NetLogPath, Boolean ForceNetLogReload, Boolean ForceJournalReload, Int32 CurrentCommander, Boolean Keepuievents) in C:\Code\EDDiscovery\EliteDangerous\HistoryList\HistoryList.cs:line 845
   at EDDiscovery.EDDiscoveryController.DoRefreshHistory(RefreshWorkerArgs args) in C:\Code\EDDiscovery\EDDiscovery\EDDiscoveryController.cs:line 811
Logged into Companion API
History refresh complete.
Loading completed, total of 19,734,951 systems stored

**Comment by robbyxp1** [comment]
Will disable reading for 9.1.4 

Can you send me the Journal record for this event.  Frontier did not really define it well so we may be decoding it wrong.

**Comment by robbyxp1** [comment]
Thats the Loadout line which caused this.

**Comment by badbud65** [comment]
There you go:

[Journal.180227210200.01.log](https://github.com/EDDiscovery/EDDiscovery/files/1764848/Journal.180227210200.01.log)
