### ISSUE TITLE
EDDiscovery v9.1.4.0 Fatal Error

### ISSUE THREAD

**Issue by ChosenOne316** [EDDiscovery/EDDiscovery#1778]
An unhandled fatal exception has occurred.

==== BEGIN ====
System.Reflection.TargetInvocationException: Ein Aufrufziel hat einen Ausnahmefehler verursacht. ---> Newtonsoft.Json.JsonReaderException: Could not convert string to double: $Thermic;. Path 'Modules[1].Engineering.Modifiers[9].Value', line 149, position 32.
   bei Newtonsoft.Json.JsonReader.ReadDoubleString(String s)
   bei Newtonsoft.Json.JsonReader.ReadAsDouble()
   bei Newtonsoft.Json.JsonReader.ReadForType(JsonContract contract, Boolean hasConverter)
   bei Newtonsoft.Json.Serialization.JsonSerializerInternalReader.PopulateObject(Object newObject, JsonReader reader, JsonObjectContract contract, JsonProperty member, String id)
   bei Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateObject(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
   bei Newtonsoft.Json.Serialization.JsonSerializerInternalReader.PopulateList(IList list, JsonReader reader, JsonArrayContract contract, JsonProperty containerProperty, String id)
   bei Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateList(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, Object existingValue, String id)
   bei Newtonsoft.Json.Serialization.JsonSerializerInternalReader.Deserialize(JsonReader reader, Type objectType, Boolean checkAdditionalContent)
   bei Newtonsoft.Json.JsonSerializer.DeserializeInternal(JsonReader reader, Type objectType)
   bei Newtonsoft.Json.Linq.JToken.ToObject(Type objectType, JsonSerializer jsonSerializer)
   bei Newtonsoft.Json.Linq.JToken.ToObject(Type objectType)
   bei Newtonsoft.Json.Linq.JToken.ToObject[T]()
   bei EliteDangerousCore.JournalEvents.JournalEngineerCraftBase.EngineeringData..ctor(JObject evt) in C:\Code\EDDiscovery\EliteDangerous\JournalEvents\JournalEngineerCraft.cs:Zeile 124.
   bei EliteDangerousCore.JournalEvents.JournalLoadout..ctor(JObject evt) in C:\Code\EDDiscovery\EliteDangerous\JournalEvents\JournalLoadout.cs:Zeile 141.
   --- Ende der internen Ausnahmestapelüberwachung ---
   bei System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor)
   bei System.Reflection.RuntimeConstructorInfo.Invoke(BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   bei System.RuntimeType.CreateInstanceImpl(BindingFlags bindingAttr, Binder binder, Object[] args, CultureInfo culture, Object[] activationAttributes, StackCrawlMark& stackMark)
   bei System.Activator.CreateInstance(Type type, BindingFlags bindingAttr, Binder binder, Object[] args, CultureInfo culture, Object[] activationAttributes)
   bei System.Activator.CreateInstance(Type type, Object[] args)
   bei EliteDangerousCore.JournalEntry.CreateJournalEntry(JObject jo) in C:\Code\EDDiscovery\EliteDangerous\EliteDangerous\JournalEntry.cs:Zeile 1077.
   bei EliteDangerousCore.JournalEntry.CreateJournalEntry(DataRow dr) in C:\Code\EDDiscovery\EliteDangerous\EliteDangerous\JournalEntry.cs:Zeile 338.
   bei EliteDangerousCore.JournalEntry.GetAll(Int32 commander, Nullable`1 after, Nullable`1 before) in C:\Code\EDDiscovery\EliteDangerous\EliteDangerous\JournalEntry.cs:Zeile 764.
   bei EliteDangerousCore.EDSM.EDSMLogFetcher.FetcherThreadProc() in C:\Code\EDDiscovery\EliteDangerous\EDSM\EDSMLogFetcher.cs:Zeile 147.
   bei System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   bei System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   bei System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   bei System.Threading.ThreadHelper.ThreadStart()
===== END =====

   bei EliteDangerousCore.JournalEvents.JournalLoadout..ctor(JObject evt) in C:\Code\EDDiscovery\EliteDangerous\JournalEvents\JournalLoadout.cs:Zeile 141.
   --- Ende der internen Ausnahmestapelüberwachung ---
   bei System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor)
   bei System.Reflection.RuntimeConstructorInfo.Invoke(BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   bei System.RuntimeType.CreateInstanceImpl(BindingFlags bindingAttr, Binder binder, Object[] args, CultureInfo culture, Object[] activationAttributes, StackCrawlMark& stackMark)
   bei System.Activator.CreateInstance(Type type, BindingFlags bindingAttr, Binder binder, Object[] args, CultureInfo culture, Object[] activationAttributes)
   bei System.Activator.CreateInstance(Type type, Object[] args)
   bei EliteDangerousCore.JournalEntry.CreateJournalEntry(JObject jo) in C:\Code\EDDiscovery\EliteDangerous\EliteDangerous\JournalEntry.cs:Zeile 1077.
   bei EliteDangerousCore.JournalEntry.CreateJournalEntry(DataRow dr) in C:\Code\EDDiscovery\EliteDangerous\EliteDangerous\JournalEntry.cs:Zeile 338.
   bei EliteDangerousCore.JournalEntry.GetAll(Int32 commander, Nullable`1 after, Nullable`1 before) in C:\Code\EDDiscovery\EliteDangerous\EliteDangerous\JournalEntry.cs:Zeile 764.
   bei EliteDangerousCore.HistoryList.LoadHistory(EDJournalClass journalmonitor, Func`1 cancelRequested, Action`2 reportProgress, String NetLogPath, Boolean ForceNetLogReload, Boolean ForceJournalReload, Int32 CurrentCommander, Boolean Keepuievents) in C:\Code\EDDiscovery\EliteDangerous\HistoryList\HistoryList.cs:Zeile 845.
   bei EDDiscovery.EDDiscoveryController.DoRefreshHistory(RefreshWorkerArgs args) in C:\Code\EDDiscovery\EDDiscovery\EDDiscoveryController.cs:Zeile 811.
History refresh complete.
Loading completed, total of 19.756.068 systems stored

**Comment by Brantford** [comment]
An unhandled fatal exception has occurred.

==== BEGIN ====
System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation. ---> Newtonsoft.Json.JsonReaderException: Could not convert string to double: $Thermic;. Path 'Modules[2].Engineering.Modifiers[6].Value', line 173, position 32.
   at Newtonsoft.Json.JsonReader.ReadDoubleString(String s)
   at Newtonsoft.Json.JsonReader.ReadAsDouble()
   at Newtonsoft.Json.JsonReader.ReadForType(JsonContract contract, Boolean hasConverter)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.PopulateObject(Object newObject, JsonReader reader, JsonObjectContract contract, JsonProperty member, String id)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateObject(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.PopulateList(IList list, JsonReader reader, JsonArrayContract contract, JsonProperty containerProperty, String id)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateList(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, Object existingValue, String id)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.Deserialize(JsonReader reader, Type objectType, Boolean checkAdditionalContent)
   at Newtonsoft.Json.JsonSerializer.DeserializeInternal(JsonReader reader, Type objectType)
   at Newtonsoft.Json.Linq.JToken.ToObject(Type objectType, JsonSerializer jsonSerializer)
   at Newtonsoft.Json.Linq.JToken.ToObject(Type objectType)
   at Newtonsoft.Json.Linq.JToken.ToObject[T]()
   at EliteDangerousCore.JournalEvents.JournalEngineerCraftBase.EngineeringData..ctor(JObject evt) in C:\Code\EDDiscovery\EliteDangerous\JournalEvents\JournalEngineerCraft.cs:line 124
   at EliteDangerousCore.JournalEvents.JournalLoadout..ctor(JObject evt) in C:\Code\EDDiscovery\EliteDangerous\JournalEvents\JournalLoadout.cs:line 141
   --- End of inner exception stack trace ---
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor)
   at System.Reflection.RuntimeConstructorInfo.Invoke(BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at System.RuntimeType.CreateInstanceImpl(BindingFlags bindingAttr, Binder binder, Object[] args, CultureInfo culture, Object[] activationAttributes, StackCrawlMark& stackMark)
   at System.Activator.CreateInstance(Type type, BindingFlags bindingAttr, Binder binder, Object[] args, CultureInfo culture, Object[] activationAttributes)
   at System.Activator.CreateInstance(Type type, Object[] args)
   at EliteDangerousCore.JournalEntry.CreateJournalEntry(JObject jo) in C:\Code\EDDiscovery\EliteDangerous\EliteDangerous\JournalEntry.cs:line 1077
   at EliteDangerousCore.JournalEntry.CreateJournalEntry(DataRow dr) in C:\Code\EDDiscovery\EliteDangerous\EliteDangerous\JournalEntry.cs:line 338
   at EliteDangerousCore.JournalEntry.GetAll(Int32 commander, Nullable`1 after, Nullable`1 before) in C:\Code\EDDiscovery\EliteDangerous\EliteDangerous\JournalEntry.cs:line 764
   at EliteDangerousCore.EDSM.EDSMLogFetcher.FetcherThreadProc() in C:\Code\EDDiscovery\EliteDangerous\EDSM\EDSMLogFetcher.cs:line 147
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.ThreadHelper.ThreadStart()
===== END =====

**Comment by klightspeed** [comment]
Duplicate of #1766 - should be fixed in 9.1.5 by #1777
