### ISSUE TITLE
Unhandled fatal exception in 9.1.4

### ISSUE THREAD

**Issue by mhimmel** [EDDiscovery/EDDiscovery#1780]
1st run after install, can only exit

## Exception Traceback:

An unhandled fatal exception has occurred.

==== BEGIN ====
System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation. ---> Newtonsoft.Json.JsonReaderException: Could not convert string to double: $Thermic;. Path 'Modules[0].Engineering.Modifiers[7].Value', line 75, position 32.
   at Newtonsoft.Json.JsonReader.ReadDoubleString(String s)
   at Newtonsoft.Json.JsonReader.ReadAsDouble()
   at Newtonsoft.Json.JsonReader.ReadForType(JsonContract contract, Boolean hasConverter)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.PopulateObject(Object newObject, JsonReader reader, JsonObjectContract contract, JsonProperty member, String id)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateObject(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.PopulateList(IList list, JsonReader reader, JsonArrayContract contract, JsonProperty containerProperty, String id)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateList(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, Object existingValue, String id)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.Deserialize(JsonReader reader, Type objectType, Boolean checkAdditionalContent)
   at Newtonsoft.Json.JsonSerializer.DeserializeInternal(JsonReader reader, Type objectType)
   at Newtonsoft.Json.Linq.JToken.ToObject(Type objectType, JsonSerializer jsonSerializer)
   at Newtonsoft.Json.Linq.JToken.ToObject(Type objectType)
   at Newtonsoft.Json.Linq.JToken.ToObject[T]()
   at EliteDangerousCore.JournalEvents.JournalEngineerCraftBase.EngineeringData..ctor(JObject evt) in C:\Code\EDDiscovery\EliteDangerous\JournalEvents\JournalEngineerCraft.cs:line 124
   at EliteDangerousCore.JournalEvents.JournalLoadout..ctor(JObject evt) in C:\Code\EDDiscovery\EliteDangerous\JournalEvents\JournalLoadout.cs:line 141
   --- End of inner exception stack trace ---
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor)
   at System.Reflection.RuntimeConstructorInfo.Invoke(BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at System.RuntimeType.CreateInstanceImpl(BindingFlags bindingAttr, Binder binder, Object[] args, CultureInfo culture, Object[] activationAttributes, StackCrawlMark& stackMark)
   at System.Activator.CreateInstance(Type type, BindingFlags bindingAttr, Binder binder, Object[] args, CultureInfo culture, Object[] activationAttributes)
   at System.Activator.CreateInstance(Type type, Object[] args)
   at EliteDangerousCore.JournalEntry.CreateJournalEntry(JObject jo) in C:\Code\EDDiscovery\EliteDangerous\EliteDangerous\JournalEntry.cs:line 1077
   at EliteDangerousCore.JournalEntry.CreateJournalEntry(DataRow dr) in C:\Code\EDDiscovery\EliteDangerous\EliteDangerous\JournalEntry.cs:line 338
   at EliteDangerousCore.JournalEntry.GetAll(Int32 commander, Nullable`1 after, Nullable`1 before) in C:\Code\EDDiscovery\EliteDangerous\EliteDangerous\JournalEntry.cs:line 764
   at EliteDangerousCore.EDSM.EDSMLogFetcher.FetcherThreadProc() in C:\Code\EDDiscovery\EliteDangerous\EDSM\EDSMLogFetcher.cs:line 147
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.ThreadHelper.ThreadStart()
===== END =====

## Logfile:
Checking for new EDDiscovery maps
Checking for new Expedition data
Loaded Notes, Bookmarks and Galactic mapping.
Reading travel history
Scanning for bmp screenshots in D:\___ac___\_OPTICS\Frontier Developments\Elite Dangerous
History Refresh Error: System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation. ---> Newtonsoft.Json.JsonReaderException: Could not convert string to double: $Thermic;. Path 'Modules[0].Engineering.Modifiers[7].Value', line 75, position 32.
   at Newtonsoft.Json.JsonReader.ReadDoubleString(String s)
   at Newtonsoft.Json.JsonReader.ReadAsDouble()
   at Newtonsoft.Json.JsonReader.ReadForType(JsonContract contract, Boolean hasConverter)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.PopulateObject(Object newObject, JsonReader reader, JsonObjectContract contract, JsonProperty member, String id)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateObject(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.PopulateList(IList list, JsonReader reader, JsonArrayContract contract, JsonProperty containerProperty, String id)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateList(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, Object existingValue, String id)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.Deserialize(JsonReader reader, Type objectType, Boolean checkAdditionalContent)
   at Newtonsoft.Json.JsonSerializer.DeserializeInternal(JsonReader reader, Type objectType)
   at Newtonsoft.Json.Linq.JToken.ToObject(Type objectType, JsonSerializer jsonSerializer)
   at Newtonsoft.Json.Linq.JToken.ToObject(Type objectType)
   at Newtonsoft.Json.Linq.JToken.ToObject[T]()
   at EliteDangerousCore.JournalEvents.JournalEngineerCraftBase.EngineeringData..ctor(JObject evt) in C:\Code\EDDiscovery\EliteDangerous\JournalEvents\JournalEngineerCraft.cs:line 124
   at EliteDangerousCore.JournalEvents.JournalLoadout..ctor(JObject evt) in C:\Code\EDDiscovery\EliteDangerous\JournalEvents\JournalLoadout.cs:line 141
   --- End of inner exception stack trace ---
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor)
   at System.Reflection.RuntimeConstructorInfo.Invoke(BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at System.RuntimeType.CreateInstanceImpl(BindingFlags bindingAttr, Binder binder, Object[] args, CultureInfo culture, Object[] activationAttributes, StackCrawlMark& stackMark)
   at System.Activator.CreateInstance(Type type, BindingFlags bindingAttr, Binder binder, Object[] args, CultureInfo culture, Object[] activationAttributes)
   at System.Activator.CreateInstance(Type type, Object[] args)
   at EliteDangerousCore.JournalEntry.CreateJournalEntry(JObject jo) in C:\Code\EDDiscovery\EliteDangerous\EliteDangerous\JournalEntry.cs:line 1077
   at EliteDangerousCore.JournalEntry.CreateJournalEntry(DataRow dr) in C:\Code\EDDiscovery\EliteDangerous\EliteDangerous\JournalEntry.cs:line 338
   at EliteDangerousCore.JournalEntry.GetAll(Int32 commander, Nullable`1 after, Nullable`1 before) in C:\Code\EDDiscovery\EliteDangerous\EliteDangerous\JournalEntry.cs:line 764
   at EliteDangerousCore.HistoryList.LoadHistory(EDJournalClass journalmonitor, Func`1 cancelRequested, Action`2 reportProgress, String NetLogPath, Boolean ForceNetLogReload, Boolean ForceJournalReload, Int32 CurrentCommander, Boolean Keepuievents) in C:\Code\EDDiscovery\EliteDangerous\HistoryList\HistoryList.cs:line 845
   at EDDiscovery.EDDiscoveryController.DoRefreshHistory(RefreshWorkerArgs args) in C:\Code\EDDiscovery\EDDiscovery\EDDiscoveryController.cs:line 811
History refresh complete.
Loading completed, total of 19,758,526 systems stored
No new events to send to EDSM

## Screenshot:
https://i.imgur.com/xevmpEP.png

**Comment by robbyxp1** [comment]
Known, 9.1.5 coming today will fix. thanks
