### ISSUE TITLE
Journal Entries Missing in 9.1.4

### ISSUE THREAD

**Issue by codevolunt** [EDDiscovery/EDDiscovery#1781]
Just upgraded to 9.1.4 and apart from today's entries, the next most recent is September 2016.

EDSM has all the recent flight logs. These would have been created while using my laptop, not my PC which is what I am using now. Do I need to copy Journal logs from one to the other?

Cheers

**Comment by robbyxp1** [comment]
Is all your journal logs present in the folder.

Try Admin | Rescan all journal files

**Comment by codevolunt** [comment]
Hi Rob

There are quite a few with 2017 dates, for example, but I did try a rescan, then a refresh, but still didn’t load anything before 9 Sep 2016. 

Kind regards


Nigel

**Comment by klightspeed** [comment]
The journals do need to be accessible to the program for it to load them.  If they're in a directory other than `shell:SavedGames\Frontier Developments\Elite Dangerous`, then you can set the journal path of one of your commanders to the path of the directory containing the journal entries.

**Comment by Nordlaw** [comment]
I have the same issue, but my journals are in the correct file location, when I force EDDiscovery to re-read them nothing gets populated. I'm getting the following error script;

History Refresh Error: System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation. ---> Newtonsoft.Json.JsonReaderException: Could not convert string to double: $Kinetic;. Path 'Modules[0].Engineering.Modifiers[4].Value', line 55, position 32.
   at Newtonsoft.Json.JsonReader.ReadDoubleString(String s)
   at Newtonsoft.Json.JsonReader.ReadAsDouble()
   at Newtonsoft.Json.JsonReader.ReadForType(JsonContract contract, Boolean hasConverter)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.PopulateObject(Object newObject, JsonReader reader, JsonObjectContract contract, JsonProperty member, String id)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateObject(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.PopulateList(IList list, JsonReader reader, JsonArrayContract contract, JsonProperty containerProperty, String id)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateList(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, Object existingValue, String id)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.Deserialize(JsonReader reader, Type objectType, Boolean checkAdditionalContent)
   at Newtonsoft.Json.JsonSerializer.DeserializeInternal(JsonReader reader, Type objectType)
   at Newtonsoft.Json.Linq.JToken.ToObject(Type objectType, JsonSerializer jsonSerializer)
   at Newtonsoft.Json.Linq.JToken.ToObject(Type objectType)
   at Newtonsoft.Json.Linq.JToken.ToObject[T]()
   at EliteDangerousCore.JournalEvents.JournalEngineerCraftBase.EngineeringData..ctor(JObject evt) in C:\Code\EDDiscovery\EliteDangerous\JournalEvents\JournalEngineerCraft.cs:line 124
   at EliteDangerousCore.JournalEvents.JournalLoadout..ctor(JObject evt) in C:\Code\EDDiscovery\EliteDangerous\JournalEvents\JournalLoadout.cs:line 141
   --- End of inner exception stack trace ---
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor)
   at System.Reflection.RuntimeConstructorInfo.Invoke(BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at System.RuntimeType.CreateInstanceImpl(BindingFlags bindingAttr, Binder binder, Object[] args, CultureInfo culture, Object[] activationAttributes, StackCrawlMark& stackMark)
   at System.Activator.CreateInstance(Type type, BindingFlags bindingAttr, Binder binder, Object[] args, CultureInfo culture, Object[] activationAttributes)
   at System.Activator.CreateInstance(Type type, Object[] args)
   at EliteDangerousCore.JournalEntry.CreateJournalEntry(JObject jo) in C:\Code\EDDiscovery\EliteDangerous\EliteDangerous\JournalEntry.cs:line 1077
   at EliteDangerousCore.JournalEntry.CreateJournalEntry(DbDataReader dr) in C:\Code\EDDiscovery\EliteDangerous\EliteDangerous\JournalEntry.cs:line 356
   at EliteDangerousCore.JournalEntry.GetAllByTLU(Int64 tluid) in C:\Code\EDDiscovery\EliteDangerous\EliteDangerous\JournalEntry.cs:line 821
   at EliteDangerousCore.JournalMonitorWatcher.ParseJournalFiles(Func`1 cancelRequested, Action`2 updateProgress, Boolean forceReload) in C:\Code\EDDiscovery\EliteDangerous\EliteDangerous\EDJournalMonitorWatcher.cs:line 230
   at EliteDangerousCore.EDJournalClass.ParseJournalFiles(Func`1 cancelRequested, Action`2 updateProgress, Boolean forceReload) in C:\Code\EDDiscovery\EliteDangerous\EliteDangerous\EDJournalClass.cs:line 278
   at EliteDangerousCore.HistoryList.LoadHistory(EDJournalClass journalmonitor, Func`1 cancelRequested, Action`2 reportProgress, String NetLogPath, Boolean ForceNetLogReload, Boolean ForceJournalReload, Int32 CurrentCommander, Boolean Keepuievents) in C:\Code\EDDiscovery\EliteDangerous\HistoryList\HistoryList.cs:line 836
   at EDDiscovery.EDDiscoveryController.DoRefreshHistory(RefreshWorkerArgs args) in C:\Code\EDDiscovery\EDDiscovery\EDDiscoveryController.cs:line 811
Checking for updated EDSM systems (may take a few moments).

**Comment by iainross** [comment]
@Nordlaw that error is down to the journal format not being as described and should be fixed in 9.1.5, released earlier tonight.

@codevolunt if you've got the same underlying issue 9.1.5 should fix it.
