### ISSUE TITLE
SQLite failing on exFAT 

### ISSUE THREAD

**Issue by DaddaTheButt** [EDDiscovery/EDDiscovery#1783]
Portable installation on an exFAT partition (multi-o/s system so o/s partitions kept minimal size and majority formatted as 'cross-o/s' exFAT).

On (new) install, loads proceed until EDDSystem.sqlite reaches approx 4.7GB (may not be 'size' related but full load is approx. 4.9GB) at which point:
"Check Systems exception: database disk image is malformed"

Trace:

[2018-02-28 16:10:21Z] SQLite error (17): statement aborts at 68: [DROP TABLE IF EXISTS Systems] database schema has changed
[2018-02-28 16:24:12Z] DownloadFile: E:\opt\eddiscovery-9.1.4p\Data\eddb\systems_populated.jsonl up to date (etag).
[2018-02-28 16:25:22Z] Remove 24516Remove 28436 [...] Remove 18663EDDB Count 10000 Delta 69421 info 10000 update 0 new 10000
[2018-02-28 16:26:18Z] EDDB Count 20000 Delta 56532 info 20000 update 0 new 20000
[2018-02-28 16:27:00Z] SQLite error (11): database corruption at line 61461 of [1a584e4999]
[2018-02-28 16:27:00Z] SQLite error (11): database corruption at line 61502 of [1a584e4999]
[2018-02-28 16:27:00Z] SQLite error (11): statement aborts at 57: [INSERT INTO EdsmSystems (EdsmId, X, Y, Z, CreateTimestamp, UpdateTimestamp, VersionTimestamp, GridId, RandomId) VALUES (@EdsmId, @X, @Y, @Z, @CreateTimestamp, @UpdateTimestamp, @Versio
[2018-02-28 16:27:07Z] Check Systems exception: database disk image is malformed
database disk image is malformed
Trace:    at System.Data.SQLite.SQLite3.Reset(SQLiteStatement stmt)
   at System.Data.SQLite.SQLite3.Step(SQLiteStatement stmt)
   at System.Data.SQLite.SQLiteDataReader.NextResult()
   at System.Data.SQLite.SQLiteDataReader..ctor(SQLiteCommand cmd, CommandBehavior behave)
   at System.Data.SQLite.SQLiteCommand.ExecuteReader(CommandBehavior behavior)
   at System.Data.SQLite.SQLiteCommand.ExecuteNonQuery(CommandBehavior behavior)
   at EliteDangerousCore.DB.SQLiteCommandED'1.ExecuteNonQuery() in C:\Code\EDDiscovery\EliteDangerous\DB\SQLiteCommandED.cs:line 535
   at EliteDangerousCore.EDSM.SystemClassEDSM.DoParseEDSMUpdateSystemsReader(JsonTextReader jr, Boolean[] grididallowed, DateTime& maxdate, Func'1 cancelRequested, Action'2 reportProgress, Boolean useCache, Boolean useTempSystems) in C:\Code\EDDiscovery\EliteDangerous\EDSM\SystemClassEDSM.cs:line 523
   at EliteDangerousCore.EDSM.SystemClassEDSM.ParseEDSMUpdateSystemsStream(TextReader sr, Boolean[] grididallow, DateTime& date, Boolean removenonedsmids, Func'1 cancelRequested, Action'2 reportProgress, Boolean useCache, Boolean useTempSystems) in C:\Code\EDDiscovery\EliteDangerous\EDSM\SystemClassEDSM.cs:line 262
   at EliteDangerousCore.EDSM.SystemClassEDSM.ParseEDSMUpdateSystemsString(String json, Boolean[] grididallow, DateTime& date, Boolean removenonedsmids, Func'1 cancelRequested, Action'2 reportProgress, Boolean useCache) in C:\Code\EDDiscovery\EliteDangerous\EDSM\SystemClassEDSM.cs:line 251
   at EliteDangerousCore.EDSM.SystemClassEDSM.PerformEDSMUpdateSync(Boolean[] grididallow, Func'1 PendingClose, Action'2 ReportProgress, Action'1 LogLine, Action'1 LogLineHighlight) in C:\Code\EDDiscovery\EliteDangerous\EDSM\SystemClassEDSM.cs:line 734
   at EDDiscovery.EDDiscoveryController.DoPerformSync() in C:\Code\EDDiscovery\EDDiscovery\EDDiscoveryController.cs:line 701
[2018-02-28 16:27:12Z] SQLite error (11): database corruption at line 61461 of [1a584e4999]
[2018-02-28 16:27:12Z] SQLite error (11): database corruption at line 61502 of [1a584e4999]
[2018-02-28 16:27:12Z] SQLite error (11): statement aborts at 6: [select Count(EdsmId) from EdsmSystems] database disk image is malformed
[2018-02-28 16:27:12Z] Exception : database disk image is malformed
[2018-02-28 16:27:12Z] database disk image is malformed
[2018-02-28 16:27:12Z]    at System.Data.SQLite.SQLite3.Reset(SQLiteStatement stmt)
[2018-02-28 16:27:12Z]    at System.Data.SQLite.SQLite3.Step(SQLiteStatement stmt)
[2018-02-28 16:27:12Z]    at System.Data.SQLite.SQLiteDataReader.NextResult()
[2018-02-28 16:27:12Z]    at System.Data.SQLite.SQLiteDataReader..ctor(SQLiteCommand cmd, CommandBehavior behave)
[2018-02-28 16:27:12Z]    at System.Data.SQLite.SQLiteCommand.ExecuteReader(CommandBehavior behavior)
[2018-02-28 16:27:12Z]    at EliteDangerousCore.DB.SQLiteDataReaderED'1..ctor(DbCommand cmd, CommandBehavior behaviour, SQLiteTransactionED'1 txn, SQLiteTxnLockED'1 txnlock) in C:\Code\EDDiscovery\EliteDangerous\DB\SQLiteCommandED.cs:line 339
[2018-02-28 16:27:12Z]    at EliteDangerousCore.DB.SQLiteCommandED'1.ExecuteDbDataReader(CommandBehavior behavior) in C:\Code\EDDiscovery\EliteDangerous\DB\SQLiteCommandED.cs:line 509
[2018-02-28 16:27:12Z]    at EliteDangerousCore.DB.SystemClassDB.GetTotalSystems() in C:\Code\EDDiscovery\EliteDangerous\DB\SystemClassDB.cs:line 504

**Comment by robbyxp1** [comment]
This is external to our program.. We can't do anything about this.
