### ISSUE TITLE
include filename of corrupted DB file in message of SQLite exception 

### ISSUE THREAD

**Issue by Nishi** [EDDiscovery/EDDiscovery#1933]
It'd help troubleshooting / would be obvious which file should be deleted/restored from backup.

```
Check Systems exception: database disk image is malformed
database disk image is malformed
Trace:    at System.Data.SQLite.SQLite3.Reset(SQLiteStatement stmt)
   at System.Data.SQLite.SQLite3.Step(SQLiteStatement stmt)
   at System.Data.SQLite.SQLiteDataReader.NextResult()
   at System.Data.SQLite.SQLiteDataReader..ctor(SQLiteCommand cmd, CommandBehavior behave)
   at System.Data.SQLite.SQLiteCommand.ExecuteReader(CommandBehavior behavior)
   at System.Data.SQLite.SQLiteCommand.ExecuteNonQuery(CommandBehavior behavior)
   at EliteDangerousCore.DB.SQLiteCommandED`1.ExecuteNonQuery() in C:\Code\EDDiscovery\EliteDangerous\DB\SQLiteCommandED.cs:line 535
   at EliteDangerousCore.EDSM.SystemClassEDSM.DoParseEDSMUpdateSystemsReader(JsonTextReader jr, Boolean[] grididallowed, DateTime& maxdate, Func`1 cancelRequested, Action`2 reportProgress, Boolean useCache, Boolean useTempSystems) in C:\Code\EDDiscovery\EliteDangerous\EDSM\SystemClassEDSM.cs:line 526
   at EliteDangerousCore.EDSM.SystemClassEDSM.ParseEDSMUpdateSystemsStream(TextReader sr, Boolean[] grididallow, DateTime& date, Boolean removenonedsmids, Func`1 cancelRequested, Action`2 reportProgress, Boolean useCache, Boolean useTempSystems) in C:\Code\EDDiscovery\EliteDangerous\EDSM\SystemClassEDSM.cs:line 265
   at EliteDangerousCore.EDSM.SystemClassEDSM.ParseEDSMUpdateSystemsString(String json, Boolean[] grididallow, DateTime& date, Boolean removenonedsmids, Func`1 cancelRequested, Action`2 reportProgress, Boolean useCache) in C:\Code\EDDiscovery\EliteDangerous\EDSM\SystemClassEDSM.cs:line 254
   at EliteDangerousCore.EDSM.SystemClassEDSM.PerformEDSMUpdateSync(Boolean[] grididallow, Func`1 PendingClose, Action`2 ReportProgress, Action`1 LogLine, Action`1 LogLineHighlight) in C:\Code\EDDiscovery\EliteDangerous\EDSM\SystemClassEDSM.cs:line 744
   at EDDiscovery.EDDiscoveryController.DoPerformSync() in C:\Code\EDDiscovery\EDDiscovery\EDDiscoveryController.cs:line 701
```

**Comment by robbyxp1** [comment]
That comes from SQL code itself, which means its hard to do.  nice idea, will keep it in the back of my mind.

Here its the system DB (EDSM Update Systems)..
