### ISSUE TITLE
Version 10.0 - History Refresh Error: System.NullReferenceException: Object reference not set to an instance of an object.

### ISSUE THREAD

**Issue by trevornicholls** [EDDiscovery/EDDiscovery#1934]
This version crashes stack trace below, something in the new engineering side by the look of it, if you need my logs please let me know.

```
[2018-05-09 14:30:45Z] History Refresh Error: System.NullReferenceException: Object reference not set to an instance of an object.
   at EliteDangerousCore.ShipModule.EngineeringData.Same(EngineeringData other) in C:\Code\EDDiscovery\EliteDangerous\EliteDangerous\ShipModule.cs:line 258
   at EliteDangerousCore.ShipModule.Same(ShipModule other) in C:\Code\EDDiscovery\EliteDangerous\EliteDangerous\ShipModule.cs:line 117
   at EliteDangerousCore.ShipInformationList.Loadout(Int32 id, String ship, String shipfd, String name, String ident, List`1 modulelist, Int64 HullValue, Int64 ModulesValue, Int64 Rebuy) in C:\Code\EDDiscovery\EliteDangerous\EliteDangerous\ShipInformationList.cs:line 89
   at EliteDangerousCore.JournalEvents.JournalLoadout.ShipInformation(ShipInformationList shp, String whereami, ISystem system, SQLiteConnectionUser conn) in C:\Code\EDDiscovery\EliteDangerous\JournalEvents\JournalLoadout.cs:line 90
   at EliteDangerousCore.ShipInformationList.Process(JournalEntry je, SQLiteConnectionUser conn, String whereami, ISystem system) in C:\Code\EDDiscovery\EliteDangerous\EliteDangerous\ShipInformationList.cs:line 445
   at EliteDangerousCore.HistoryList.ProcessUserHistoryListEntries(Func`2 hlfilter) in C:\Code\EDDiscovery\EliteDangerous\HistoryList\HistoryList.cs:line 961
   at EliteDangerousCore.HistoryList.LoadHistory(EDJournalClass journalmonitor, Func`1 cancelRequested, Action`2 reportProgress, String NetLogPath, Boolean ForceNetLogReload, Boolean ForceJournalReload, Int32 CurrentCommander, Boolean Keepuievents) in C:\Code\EDDiscovery\EliteDangerous\HistoryList\HistoryList.cs:line 933
   at EDDiscovery.EDDiscoveryController.DoRefreshHistory(RefreshWorkerArgs args) in C:\Code\EDDiscovery\EDDiscovery\EDDiscoveryController.cs:line 806
```

**Comment by klightspeed** [comment]
Comparing a module with engineering to one without engineering?

**Comment by robbyxp1** [comment]
Already coped with that in line 117/238.. my guess is that another underlying object inside engineering is faulting

**Comment by robbyxp1** [comment]
Hi Trevor,

I can't see the path to find this.  If you would zip up all your journal logs, found in the Elite journal folder (c:\users\<name>\saved games\frontier developments\elite dangerous), and send them to me, that would be the quickest path to finding the problem.  You could email them me back using the email address that this comment will provide, or we could swap them on the EDD discord.

Thanks

**Comment by heltonhm** [comment]
I've got the same message, and the history won't load. Anything I can provide to assist with the fix, let me know.

**Comment by klightspeed** [comment]
I'm wondering if it's trying to compare two null modifiers

**Comment by heltonhm** [comment]
One thing I noticed is that the path it's referencing doesn't exist (C:\Code\EDDiscovery). I thought the program had set the folders as System, so I revealed all system folders/files but yet, it's not there.

**Comment by klightspeed** [comment]
That `C:\Code\EDDiscovery` is on the HDD of the person who created the installer.

**Comment by heltonhm** [comment]
That's what I thought :)

**Comment by robbyxp1** [comment]
Thanks for the logs, i ran them and saw the crash.  Mr. Klightspeed identified the point precisely.

10.0.1 will be out this afternoon with the fix.
