### ISSUE TITLE
error message

### ISSUE THREAD

**Issue by Ianchandler1990** [EDDiscovery/EDDiscovery#1946]
This error pops up after a few seconds of opening the program. fully uninstalled still have same problem.

> An unhandled fatal exception has occurred.

==== BEGIN ====
System.InvalidOperationException: Invoke or BeginInvoke cannot be called on a control until the window handle has been created.
   at System.Windows.Forms.Control.MarshaledInvoke(Control caller, Delegate method, Object[] args, Boolean synchronous)
   at System.Windows.Forms.Control.BeginInvoke(Delegate method, Object[] args)
   at EDDiscovery.UserControls.UserControlStarDistance.<KickComputation>b__16_0(ISystem s, SortedListDoubleDuplicate`1 d) in C:\Code\EDDiscovery\EDDiscovery\UserControls\UserControlStarDistance.cs:line 106
   at EDDiscovery.UserControls.StarDistanceComputer.BackgroundStardistWorkerThread() in C:\Code\EDDiscovery\EDDiscovery\UserControls\StarDistanceComputer.cs:line 106
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.ThreadHelper.ThreadStart()
===== END =====

**Comment by robbyxp1** [comment]
What version of the program is this?

**Comment by Ianchandler1990** [comment]
Just to add i removed all files in app data as well before i reinstalled EDD. still had same issue.

**Comment by klightspeed** [comment]
That suggests that either KickComputation is being called before the UI has been loaded, or the control is being disposed before the nearest stars have been retrieved.

**Comment by Ianchandler1990** [comment]
Ok, so leave it to load fully before trying to change settings/anything so help? going to reinstall 10.1 now to see if still giving me issues.

**Comment by Ianchandler1990** [comment]
Ok. so loaded worked ok about 20 seconds gave the same error again.

**Comment by klightspeed** [comment]
This kind of issue sometimes occurs when something in Windows causes events during the creation of a control, despite that control creation suspending the layout of the control which should prevent those events from being fired.

**Comment by Ianchandler1990** [comment]
Ok, I think I know what it could be then, I use EDD on second pc(laptop) so I have the files as a shared drive on the network. I did notice that not always EDD could see this folder even when I have it open in windows. Could be this making EDD think its lost the files?

**Comment by klightspeed** [comment]
The issue is due to a DotNET bug that causes events to fire on a control before its handle has been created.  A workaround for this bug should be in 10.0.2

**Comment by Ianchandler1990** [comment]
Running now for over 5 mins when I pointed it to local folder. Moved back to network folder and seems ok now again. This time EDD can see the folder when I go to pick where my files are, Last time It could still read the files but If I went to pick some where else only network folders I could see was on shared from local pc not the others.

**Comment by Ianchandler1990** [comment]
Ok sweet, will look forward to that patch if this happens again.
