### ISSUE TITLE
Unhandled UI Exception

### ISSUE THREAD

**Issue by CMDRLucienn** [EDDiscovery/EDDiscovery#1948]
### Description
I get an error message every time I sell exploration data, or otherwise incur an event that would add an entry to the history journal. The app does not crash; I can otherwise continue with operations and the software still works fine.

### Additional Information
![2018-05-14_02-13-37](https://user-images.githubusercontent.com/7802122/39985655-7dad1a80-571c-11e8-82d1-a6195a9684b2.png)

### Exception Details:
>EDDiscovery v10.0.1.0 There was an unhandled UI exception.
>```
>==== BEGIN ====
>System.NullReferenceException: Object reference not set to an instance of an object.
>   at EDDiscovery.UserControls.UserControlSpanel.DrawHistoryEntry(HistoryEntry he, Int32 rowpos, Int32 rowheight, Point3D tpos, Color textcolour, Color backcolour) in C:\Code\EDDiscovery\EDDiscovery\UserControls\UserControlSpanel.cs:line 335
>   at EDDiscovery.UserControls.UserControlSpanel.Display(HistoryList hl) in C:\Code\EDDiscovery\EDDiscovery\UserControls\UserControlSpanel.cs:line 309
>   at EDDiscovery.UserControls.UserControlSpanel.NewEntry(HistoryEntry he, HistoryList hl) in C:\Code\EDDiscovery\EDDiscovery\UserControls\UserControlSpanel.cs:line 532
>   at System.Action`2.Invoke(T1 arg1, T2 arg2)
>   at EDDiscovery.EDDiscoveryController.ActionEntry(JournalEntry je) in C:\Code\EDDiscovery\EDDiscovery\EDDiscoveryController.cs:line 460
>   at EDDiscovery.EDDiscoveryController.PlayJournalList() in C:\Code\EDDiscovery\EDDiscovery\EDDiscoveryController.cs:line 439
>   at EliteDangerousCore.EDJournalClass.ScanTickDone(List`1 entries) in C:\Code\EDDiscovery\EliteDangerous\EliteDangerous\EDJournalClass.cs:line 184
>===== END =====
>```

**Comment by robbyxp1** [comment]
Hi

Any chance you could send up the journal entry for SellExplorationData which caused this to happen?  Right click on the entry and use the copy write journal entry to copy buffer option thingy.

Thanks

**Comment by CMDRLucienn** [comment]
All of the entries that were written over the last two or so days have been throwing this message. I've dug into the EDDiscovery app logs (after the fresh reinstall) to try to grab some specific events.

```
[2018-05-14 05:12:43Z] New entry 14-May-18 5:12:41 AM FuelScoop
[2018-05-14 05:14:13Z] New entry 14-May-18 5:14:11 AM SupercruiseExit
[2018-05-14 05:14:13Z] SQLite error (5): database is locked
[2018-05-14 05:14:14Z] SQLite error (5): database is locked
[2018-05-14 05:14:14Z] Last message repeated 3 times
[2018-05-14 05:14:14Z] New entry 14-May-18 5:14:11 AM Music
[2018-05-14 05:14:14Z] New entry 14-May-18 5:14:12 AM ReceiveText
[2018-05-14 05:14:20Z] New entry 14-May-18 5:14:16 AM Music
[2018-05-14 05:14:25Z] New entry 14-May-18 5:14:23 AM DockingRequested
[2018-05-14 05:14:28Z] New entry 14-May-18 5:14:25 AM ReceiveText
[2018-05-14 05:14:30Z] New entry 14-May-18 5:14:25 AM DockingGranted
[2018-05-14 05:14:31Z] New entry 14-May-18 5:14:25 AM ReceiveText
[2018-05-14 05:14:32Z] New entry 14-May-18 5:14:27 AM Music
[2018-05-14 05:15:28Z] New entry 14-May-18 5:15:26 AM Docked
[2018-05-14 05:15:30Z] Reading response
[2018-05-14 05:15:32Z] Companion API get failed: Object reference not set to an instance of an object.
[2018-05-14 05:15:32Z] Adding Docked event to EDSM journal sync (At Fuglesang Hub)
[2018-05-14 05:15:32Z] New entry 14-May-18 5:15:26 AM Music
[2018-05-14 05:15:33Z] Update sync flag ID 95465 with 2
[2018-05-14 05:15:33Z] Update sync flag ID 95465 with 3
[2018-05-14 05:15:34Z] Reading response
[2018-05-14 05:21:23Z] New entry 14-May-18 5:21:21 AM RefuelAll
[2018-05-14 05:21:27Z] 
==== UNHANDLED UI EXCEPTION ====
System.NullReferenceException: Object reference not set to an instance of an object.
   at EDDiscovery.UserControls.UserControlSpanel.DrawHistoryEntry(HistoryEntry he, Int32 rowpos, Int32 rowheight, Point3D tpos, Color textcolour, Color backcolour) in C:\Code\EDDiscovery\EDDiscovery\UserControls\UserControlSpanel.cs:line 335
   at EDDiscovery.UserControls.UserControlSpanel.Display(HistoryList hl) in C:\Code\EDDiscovery\EDDiscovery\UserControls\UserControlSpanel.cs:line 309
   at EDDiscovery.UserControls.UserControlSpanel.NewEntry(HistoryEntry he, HistoryList hl) in C:\Code\EDDiscovery\EDDiscovery\UserControls\UserControlSpanel.cs:line 532
   at System.Action`2.Invoke(T1 arg1, T2 arg2)
   at EDDiscovery.EDDiscoveryController.ActionEntry(JournalEntry je) in C:\Code\EDDiscovery\EDDiscovery\EDDiscoveryController.cs:line 460
   at EDDiscovery.EDDiscoveryController.PlayJournalList() in C:\Code\EDDiscovery\EDDiscovery\EDDiscoveryController.cs:line 439
   at EliteDangerousCore.EDJournalClass.ScanTickDone(List`1 entries) in C:\Code\EDDiscovery\EliteDangerous\EliteDangerous\EDJournalClass.cs:line 184
==== cut ====
[2018-05-14 05:21:35Z] New entry 14-May-18 5:21:33 AM SellExplorationData
[2018-05-14 05:21:53Z] New entry 14-May-18 5:21:51 AM SellExplorationData
[2018-05-14 05:21:57Z] New entry 14-May-18 5:21:55 AM SellExplorationData
[2018-05-14 05:22:01Z] New entry 14-May-18 5:21:59 AM SellExplorationData
[2018-05-14 05:22:05Z] New entry 14-May-18 5:22:02 AM SellExplorationData
[2018-05-14 05:22:10Z] New entry 14-May-18 5:22:08 AM SellExplorationData
[2018-05-14 05:22:13Z] New entry 14-May-18 5:22:12 AM SellExplorationData
[2018-05-14 05:22:17Z] New entry 14-May-18 5:22:15 AM SellExplorationData
```
Note that leaving the error message window open stopped the error from occurring/writing to the log, though if I closed it at any point it'd get thrown again. 

The specific event referenced above, the RefuelAll, was:
{"timestamp":"2018-05-14T05:21:21Z","event":"RefuelAll","Cost":10,"Amount":0.056881}

**Comment by CMDRLucienn** [comment]
Here's an example of a point where I closed the error dialogue between the individual events:
```
[2018-05-14 08:00:45Z] Adding Docked event to EDSM journal sync (At Lozino-Lozinskiy Colony)
[2018-05-14 08:00:45Z] Update sync flag ID 95843 with 1
[2018-05-14 08:00:45Z] Update sync flag ID 95843 with 3
[2018-05-14 08:00:46Z] Reading response
[2018-05-14 08:03:32Z] New entry 14-May-18 8:03:27 AM RefuelAll
[2018-05-14 08:03:34Z] 
==== UNHANDLED UI EXCEPTION ====
System.NullReferenceException: Object reference not set to an instance of an object.
   at EDDiscovery.UserControls.UserControlSpanel.DrawHistoryEntry(HistoryEntry he, Int32 rowpos, Int32 rowheight, Point3D tpos, Color textcolour, Color backcolour) in C:\Code\EDDiscovery\EDDiscovery\UserControls\UserControlSpanel.cs:line 335
   at EDDiscovery.UserControls.UserControlSpanel.Display(HistoryList hl) in C:\Code\EDDiscovery\EDDiscovery\UserControls\UserControlSpanel.cs:line 309
   at EDDiscovery.UserControls.UserControlSpanel.NewEntry(HistoryEntry he, HistoryList hl) in C:\Code\EDDiscovery\EDDiscovery\UserControls\UserControlSpanel.cs:line 532
   at System.Action`2.Invoke(T1 arg1, T2 arg2)
   at EDDiscovery.EDDiscoveryController.ActionEntry(JournalEntry je) in C:\Code\EDDiscovery\EDDiscovery\EDDiscoveryController.cs:line 460
   at EDDiscovery.EDDiscoveryController.PlayJournalList() in C:\Code\EDDiscovery\EDDiscovery\EDDiscoveryController.cs:line 439
   at EliteDangerousCore.EDJournalClass.ScanTickDone(List`1 entries) in C:\Code\EDDiscovery\EliteDangerous\EliteDangerous\EDJournalClass.cs:line 184
==== cut ====
[2018-05-14 08:07:03Z] New entry 14-May-18 8:06:57 AM ReceiveText
[2018-05-14 08:07:04Z] 
==== UNHANDLED UI EXCEPTION ====
System.NullReferenceException: Object reference not set to an instance of an object.
   at EDDiscovery.UserControls.UserControlSpanel.DrawHistoryEntry(HistoryEntry he, Int32 rowpos, Int32 rowheight, Point3D tpos, Color textcolour, Color backcolour) in C:\Code\EDDiscovery\EDDiscovery\UserControls\UserControlSpanel.cs:line 335
   at EDDiscovery.UserControls.UserControlSpanel.Display(HistoryList hl) in C:\Code\EDDiscovery\EDDiscovery\UserControls\UserControlSpanel.cs:line 309
   at EDDiscovery.UserControls.UserControlSpanel.NewEntry(HistoryEntry he, HistoryList hl) in C:\Code\EDDiscovery\EDDiscovery\UserControls\UserControlSpanel.cs:line 532
   at System.Action`2.Invoke(T1 arg1, T2 arg2)
   at EDDiscovery.EDDiscoveryController.ActionEntry(JournalEntry je) in C:\Code\EDDiscovery\EDDiscovery\EDDiscoveryController.cs:line 460
   at EDDiscovery.EDDiscoveryController.PlayJournalList() in C:\Code\EDDiscovery\EDDiscovery\EDDiscoveryController.cs:line 439
   at EliteDangerousCore.EDJournalClass.ScanTickDone(List`1 entries) in C:\Code\EDDiscovery\EliteDangerous\EliteDangerous\EDJournalClass.cs:line 184
==== cut ====
[2018-05-14 08:11:00Z] New entry 14-May-18 8:10:54 AM SellExplorationData
[2018-05-14 08:11:02Z] 
==== UNHANDLED UI EXCEPTION ====
System.NullReferenceException: Object reference not set to an instance of an object.
   at EDDiscovery.UserControls.UserControlSpanel.DrawHistoryEntry(HistoryEntry he, Int32 rowpos, Int32 rowheight, Point3D tpos, Color textcolour, Color backcolour) in C:\Code\EDDiscovery\EDDiscovery\UserControls\UserControlSpanel.cs:line 335
   at EDDiscovery.UserControls.UserControlSpanel.Display(HistoryList hl) in C:\Code\EDDiscovery\EDDiscovery\UserControls\UserControlSpanel.cs:line 309
   at EDDiscovery.UserControls.UserControlSpanel.NewEntry(HistoryEntry he, HistoryList hl) in C:\Code\EDDiscovery\EDDiscovery\UserControls\UserControlSpanel.cs:line 532
   at System.Action`2.Invoke(T1 arg1, T2 arg2)
   at EDDiscovery.EDDiscoveryController.ActionEntry(JournalEntry je) in C:\Code\EDDiscovery\EDDiscovery\EDDiscoveryController.cs:line 460
   at EDDiscovery.EDDiscoveryController.PlayJournalList() in C:\Code\EDDiscovery\EDDiscovery\EDDiscoveryController.cs:line 439
   at EliteDangerousCore.EDJournalClass.ScanTickDone(List`1 entries) in C:\Code\EDDiscovery\EliteDangerous\EliteDangerous\EDJournalClass.cs:line 184
==== cut ====
[2018-05-14 08:15:48Z] New entry 14-May-18 8:15:42 AM Friends
[2018-05-14 08:15:52Z] 
==== UNHANDLED UI EXCEPTION ====
System.NullReferenceException: Object reference not set to an instance of an object.
   at EDDiscovery.UserControls.UserControlSpanel.DrawHistoryEntry(HistoryEntry he, Int32 rowpos, Int32 rowheight, Point3D tpos, Color textcolour, Color backcolour) in C:\Code\EDDiscovery\EDDiscovery\UserControls\UserControlSpanel.cs:line 335
   at EDDiscovery.UserControls.UserControlSpanel.Display(HistoryList hl) in C:\Code\EDDiscovery\EDDiscovery\UserControls\UserControlSpanel.cs:line 309
   at EDDiscovery.UserControls.UserControlSpanel.NewEntry(HistoryEntry he, HistoryList hl) in C:\Code\EDDiscovery\EDDiscovery\UserControls\UserControlSpanel.cs:line 532
   at System.Action`2.Invoke(T1 arg1, T2 arg2)
   at EDDiscovery.EDDiscoveryController.ActionEntry(JournalEntry je) in C:\Code\EDDiscovery\EDDiscovery\EDDiscoveryController.cs:line 460
   at EDDiscovery.EDDiscoveryController.PlayJournalList() in C:\Code\EDDiscovery\EDDiscovery\EDDiscoveryController.cs:line 439
==== cut ====
[2018-05-14 08:19:22Z] Thread Journal Monitor Thread waiting for thread  to finish writer
[2018-05-14 08:19:22Z] The following command is taking a long time to execute:
[2018-05-14 08:19:22Z] Update Register set ValueString = @ValueString Where ID=@ID
[2018-05-14 08:19:24Z] Thread Journal Monitor Thread waiting for thread  to finish writer
[2018-05-14 08:19:24Z] The following command is taking a long time to execute:
[2018-05-14 08:19:24Z] Update Register set ValueString = @ValueString Where ID=@ID
[2018-05-14 08:19:24Z] Thread Journal Monitor Thread waiting for thread  to finish writer
[2018-05-14 08:19:24Z] The following command is taking a long time to execute:
[2018-05-14 08:19:24Z] Update Register set ValueString = @ValueString Where ID=@ID
[2018-05-14 08:20:28Z] New entry 14-May-18 8:20:27 AM SellExplorationData
```

The entries for the four above are:
```
{"timestamp":"2018-05-14T08:03:27Z","event":"RefuelAll","Cost":10,"Amount":0.176917}
{"timestamp":"2018-05-14T08:06:57Z","event":"ReceiveText","From":"$npc_name_decorate:#name=Richard James;","From_Localised":"Richard James","Message":"$Commuter_AuthorityScan01;","Message_Localised":"Is there a problem here, officer?","Channel":"npc"}
{"timestamp":"2018-05-14T08:10:54Z","event":"SellExplorationData","Systems":["Syrivoae IO-Q b32-0"],"Discovered":[],"BaseValue":1604,"Bonus":0,"TotalEarnings":1604}
{"timestamp":"2018-05-14T08:15:42Z","event":"Friends","Status":"Online","Name":"FALAVA"}
```

**Comment by robbyxp1** [comment]
I still can't see the path to the error.. hmmm.  Care to zip up all your logs and discord them to me, or drop box them?  All in confidence.  It's the quickest way to find bugs like this which happen due to journal data.

rob

**Comment by robbyxp1** [comment]
Going to monitor this and see if we can reproduce. With Lucienn logs I could not reproduce quickly.
