### ISSUE TITLE
Unhandled Fatal Exception

### ISSUE THREAD

**Issue by andybish** [EDDiscovery/EDDiscovery#1953]
Just updated to 10.0.2, it was downloading systems from EDSM and reading events from an H4F2 run. It seemed to be putting events in the history that I have filtered out, such as faction kill bond events.

```
An unhandled fatal exception has occurred.

==== BEGIN ====
System.Data.SQLite.SQLiteException (0x80004005): disk I/O error
disk I/O error
   at System.Data.SQLite.SQLite3.Prepare(SQLiteConnection cnn, String strSql, SQLiteStatement previous, UInt32 timeoutMS, String& strRemain)
   at System.Data.SQLite.SQLiteCommand.BuildNextCommand()
   at System.Data.SQLite.SQLiteDataReader.NextResult()
   at System.Data.SQLite.SQLiteDataReader..ctor(SQLiteCommand cmd, CommandBehavior behave)
   at System.Data.SQLite.SQLiteCommand.ExecuteReader(CommandBehavior behavior)
   at EliteDangerousCore.DB.SQLiteDataReaderED`1..ctor(DbCommand cmd, CommandBehavior behaviour, SQLiteTransactionED`1 txn, SQLiteTxnLockED`1 txnlock) in C:\Code\EDDiscovery\EliteDangerous\DB\SQLiteCommandED.cs:line 339
   at EliteDangerousCore.DB.SQLiteCommandED`1.ExecuteDbDataReader(CommandBehavior behavior) in C:\Code\EDDiscovery\EliteDangerous\DB\SQLiteCommandED.cs:line 509
   at System.Data.Common.DbDataAdapter.FillInternal(DataSet dataset, DataTable[] datatables, Int32 startRecord, Int32 maxRecords, String srcTable, IDbCommand command, CommandBehavior behavior)
   at System.Data.Common.DbDataAdapter.Fill(DataSet dataSet, Int32 startRecord, Int32 maxRecords, String srcTable, IDbCommand command, CommandBehavior behavior)
   at System.Data.Common.DbDataAdapter.Fill(DataSet dataSet)
   at EliteDangerousCore.DB.SQLiteDBClass.SQLQueryText(SQLiteConnectionED cn, DbCommand cmd) in C:\Code\EDDiscovery\EliteDangerous\DB\SQLiteDBClass.cs:line 49
   at EliteDangerousCore.DB.TravelLogUnit.GetAll() in C:\Code\EDDiscovery\EliteDangerous\DB\TravelLogUnit.cs:line 147
   at EliteDangerousCore.JournalEntry.GetAll(Int32 commander, Nullable`1 after, Nullable`1 before) in C:\Code\EDDiscovery\EliteDangerous\EliteDangerous\JournalEntry.cs:line 735
   at EliteDangerousCore.EDSM.EDSMLogFetcher.FetcherThreadProc() in C:\Code\EDDiscovery\EliteDangerous\EDSM\EDSMLogFetcher.cs:line 151
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.ThreadHelper.ThreadStart()
===== END =====
```

**Comment by klightspeed** [comment]
Disk I/O error - is the disk full?

**Comment by robbyxp1** [comment]
No response. Closing
