### ISSUE TITLE
EDDiscovery v10.0.2.0 Fatal Error

### ISSUE THREAD

**Issue by KazutoEleros** [EDDiscovery/EDDiscovery#1957]
An unhandled fatal exception has occurred.

==== BEGIN ====
Newtonsoft.Json.JsonReaderException: Unexpected character encountered while parsing value: <. Path '', line 0, position 0.
   at Newtonsoft.Json.JsonTextReader.ParseValue()
   at Newtonsoft.Json.Linq.JObject.Load(JsonReader reader, JsonLoadSettings settings)
   at Newtonsoft.Json.Linq.JObject.Parse(String json, JsonLoadSettings settings)
   at EliteDangerousCore.EDSM.EDSMClass.GetComments(Action`1 logout) in C:\Code\EDDiscovery\EliteDangerous\EDSM\EDSMClass.cs:line 302
   at EliteDangerousCore.EDSM.EDSMLogFetcher.FetcherThreadProc() in C:\Code\EDDiscovery\EliteDangerous\EDSM\EDSMLogFetcher.cs:line 94
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.ThreadHelper.ThreadStart()
===== END =====

**Comment by Tromador** [comment]
At the risk of being repetitive..
<metoo>
[2018-05-17 08:55:09Z] Check Systems exception: Unexpected character encountered while parsing value: <. Path '', line 0, position 0.
Trace:    at Newtonsoft.Json.JsonTextReader.ParseValue()
   at EliteDangerousCore.EDSM.SystemClassEDSM.DoParseEDSMUpdateSystemsReader(JsonTextReader jr, Boolean[] grididallowed, DateTime& maxdate, Func`1 cancelRequested, Action`2 reportProgress, Boolean useCache, Boolean useTempSystems) in C:\Code\EDDiscovery\EliteDangerous\EDSM\SystemClassEDSM.cs:line 295
   at EliteDangerousCore.EDSM.SystemClassEDSM.ParseEDSMUpdateSystemsStream(TextReader sr, Boolean[] grididallow, DateTime& date, Boolean removenonedsmids, Func`1 cancelRequested, Action`2 reportProgress, Boolean useCache, Boolean useTempSystems) in C:\Code\EDDiscovery\EliteDangerous\EDSM\SystemClassEDSM.cs:line 265
   at EliteDangerousCore.EDSM.SystemClassEDSM.ParseEDSMUpdateSystemsString(String json, Boolean[] grididallow, DateTime& date, Boolean removenonedsmids, Func`1 cancelRequested, Action`2 reportProgress, Boolean useCache) in C:\Code\EDDiscovery\EliteDangerous\EDSM\SystemClassEDSM.cs:line 254
   at EliteDangerousCore.EDSM.SystemClassEDSM.PerformEDSMUpdateSync(Boolean[] grididallow, Func`1 PendingClose, Action`2 ReportProgress, Action`1 LogLine, Action`1 LogLineHighlight) in C:\Code\EDDiscovery\EliteDangerous\EDSM\SystemClassEDSM.cs:line 744
   at EDDiscovery.EDDiscoveryController.DoPerformSync() in C:\Code\EDDiscovery\EDDiscovery\EDDiscoveryController.cs:line 696
[2018-05-17 08:55:10Z] Start Monitor on C:\Users\Tromador\Saved Games\Frontier Developments\Elite Dangerous
[2018-05-17 08:55:10Z] Reading response
[2018-05-17 08:55:10Z] EDSM Fetch logs start with cmdr 2
[2018-05-17 08:55:10Z] EDSM Fetch logs restart time
[2018-05-17 08:55:10Z] EDSM Thread logs start
[2018-05-17 08:55:12Z] 
==== UNHANDLED EXCEPTION ====
Newtonsoft.Json.JsonReaderException: Unexpected character encountered while parsing value: <. Path '', line 0, position 0.
   at Newtonsoft.Json.JsonTextReader.ParseValue()
   at Newtonsoft.Json.Linq.JObject.Load(JsonReader reader, JsonLoadSettings settings)
   at Newtonsoft.Json.Linq.JObject.Parse(String json, JsonLoadSettings settings)
   at EliteDangerousCore.EDSM.EDSMClass.GetComments(Action`1 logout) in C:\Code\EDDiscovery\EliteDangerous\EDSM\EDSMClass.cs:line 302
   at EliteDangerousCore.EDSM.EDSMLogFetcher.FetcherThreadProc() in C:\Code\EDDiscovery\EliteDangerous\EDSM\EDSMLogFetcher.cs:line 94
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.ThreadHelper.ThreadStart()
==== cut ====
</metoo>

**Comment by AnthorNet** [comment]
Did I break something again?

**Comment by AnthorNet** [comment]
It was on me, forgot to remove a debug ;)

**Comment by robbyxp1** [comment]
It should be protected.. i'll check

**Comment by Tromador** [comment]
Whatever you did, it seems fine now.
