### ISSUE TITLE
Unhandled Fatal Exception

### ISSUE THREAD

**Issue by mstgil** [EDDiscovery/EDDiscovery#1958]
Context, I leave EDDiscovery up and running when I've closed out the ED client overnight.  Checked on PC this morning and this exception was waiting.

An unhandled fatal exception has occurred.

==== BEGIN ====
Newtonsoft.Json.JsonReaderException: Unexpected character encountered while parsing value: <. Path '', line 0, position 0.
   at Newtonsoft.Json.JsonTextReader.ParseValue()
   at Newtonsoft.Json.Linq.JObject.Load(JsonReader reader, JsonLoadSettings settings)
   at Newtonsoft.Json.Linq.JObject.Parse(String json, JsonLoadSettings settings)
   at EliteDangerousCore.EDSM.EDSMClass.GetComments(Action`1 logout) in C:\Code\EDDiscovery\EliteDangerous\EDSM\EDSMClass.cs:line 302
   at EliteDangerousCore.EDSM.EDSMLogFetcher.FetcherThreadProc() in C:\Code\EDDiscovery\EliteDangerous\EDSM\EDSMLogFetcher.cs:line 94
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.ThreadHelper.ThreadStart()
===== END =====

**Comment by klightspeed** [comment]
This was an error with EDSM.  10.0.3 should prevent this crash when EDSM errors out.

**Comment by robbyxp1** [comment]
Closed.
