### ISSUE TITLE
Unhandled UI exception

### ISSUE THREAD

**Issue by bernardd** [EDDiscovery/EDDiscovery#1976]
### Description
Nothing in particular, just exploring and scanning

### Exception Details:
>EDDiscovery v10.0.4.0 There was an unhandled UI exception.
>```
>==== BEGIN ====
>System.NullReferenceException: Object reference not set to an instance of an object.
>   at ExtendedControls.PictureBoxHotspot.AddTextFixedSizeC(Point topleft, Size size, String label, Font fnt, Color c, Color backcolour, Single backscale, Boolean centered, Object tag, String tiptext) in C:\Code\EDDiscovery\ExtendedControls\Controls\PictureBoxHotspot.cs:line 193
>   at EDDiscovery.UserControls.UserControlTrippanel.DisplayState(HistoryEntry he, HistoryEntry lastfsd) in C:\Code\EDDiscovery\EDDiscovery\UserControls\UserControlTrippanel.cs:line 154
>   at System.Action`2.Invoke(T1 arg1, T2 arg2)
>   at EDDiscovery.EDDiscoveryForm.<>c__DisplayClass96_0.<Init>b__6() in C:\Code\EDDiscovery\EDDiscovery\EDDiscoveryForm.cs:line 270
>   at System.Windows.Forms.Control.InvokeMarshaledCallbackHelper(Object obj)
>   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
>   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
>   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
>   at System.Windows.Forms.Control.InvokeMarshaledCallback(ThreadMethodEntry tme)
>   at System.Windows.Forms.Control.InvokeMarshaledCallbacks()
>===== END =====
>```

**Comment by robbyxp1** [comment]
Meaning elements was not initialised.. Only way that could happen if after it was disposed.. thats the only time elements=null in picturboxhotspot.

Was the program being shut down when this happened? Or closing one of the panels?

Rob

**Comment by bernardd** [comment]
At the time it happened I wasn't doing anything in particular on the UI, if I recall. However I think I'd previously been playing around with the tabs, adding and removing them. No biggie, anyway - it hasn't happened since. If I do see it I'll try to get a more detailed description.

**Comment by Disorganise** [comment]
Just got this too.  not sure when it popped up.... I alt tabbed out to scroll the scan panel and got the 'ding' of 'there's a dialog somewhere you need to deal with first'.  Assuming it popped before 'now' the main window has continued to update as I jumped (running on 2nd screen).   What I have done today is create a grid window and also gone to fullscreen mode since borderless doesn't seem to allow gsync.


### Description


### Additional Information


### Exception Details:
>EDDiscovery v10.0.4.0 There was an unhandled UI exception.
>```
>==== BEGIN ====
>System.NullReferenceException: Object reference not set to an instance of an object.
>   at ExtendedControls.PictureBoxHotspot.AddTextFixedSizeC(Point topleft, Size size, String label, Font fnt, Color c, Color backcolour, Single backscale, Boolean centered, Object tag, String tiptext) in C:\Code\EDDiscovery\ExtendedControls\Controls\PictureBoxHotspot.cs:line 193
>   at EDDiscovery.UserControls.UserControlTrippanel.DisplayState(HistoryEntry he, HistoryEntry lastfsd) in C:\Code\EDDiscovery\EDDiscovery\UserControls\UserControlTrippanel.cs:line 154
>   at System.Action`2.Invoke(T1 arg1, T2 arg2)
>   at EDDiscovery.EDDiscoveryForm.<>c__DisplayClass96_0.<Init>b__6() in C:\Code\EDDiscovery\EDDiscovery\EDDiscoveryForm.cs:line 270
>   at System.Windows.Forms.Control.InvokeMarshaledCallbackHelper(Object obj)
>   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
>   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
>   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
>   at System.Windows.Forms.Control.InvokeMarshaledCallback(ThreadMethodEntry tme)
>   at System.Windows.Forms.Control.InvokeMarshaledCallbacks()
>===== END =====
>```

**Comment by robbyxp1** [comment]
This smells of a win/.net issue.  At no point do we dispose of the picturebox..    elements should never be null as it seems to imply by the 193 statement line.

if it was on a close of the panel i could see it more.

have to try it

**Comment by robbyxp1** [comment]
Can't make it fail.. have put a timer in to cause it to cont update..

**Comment by robbyxp1** [comment]
Probably due to the EDSM hook bug.. try 10.1.1
