### ISSUE TITLE
Receive UI Error When Trying to Search for System Information

### ISSUE THREAD

**Issue by DasExorcist** [EDDiscovery/EDDiscovery#2041]
I receive this error message whenever I click any of the fields to search for System Information. This occurs on Windows 10 (latest version), multiple machines.

There was an unhandled UI exception.

==== BEGIN ====
System.ArgumentNullException: Value cannot be null.
Parameter name: text
   at System.Windows.Forms.Clipboard.SetText(String text, TextDataFormat format)
   at System.Windows.Forms.Control.OnClick(EventArgs e)
   at System.Windows.Forms.Control.OnClick(EventArgs e)
   at System.Windows.Forms.TextBoxBase.OnMouseUp(MouseEventArgs mevent)
   at System.Windows.Forms.Control.WmMouseUp(Message& m, MouseButtons button, Int32 clicks)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)
===== END =====

**Comment by robbyxp1** [comment]
What version are you using?  or are you using the portable version?

**Comment by klightspeed** [comment]
`UserControlSysInfo.clickTextBox` doesn't check that the control text is not null before setting the clipboard text.

**Comment by DasExorcist** [comment]
Using latest version, 10.1.3.0. Happens on both regular installation builds and portable.
