### ISSUE TITLE
Unhandled UI Exception

### ISSUE THREAD

**Issue by sarcophilus73** [EDDiscovery/EDDiscovery#2063]
### Description

Unhandled UI exception after trying to add the "Shopping List" as a Menu-Panel. Adding in a new window is working as intended. 

### Exception Details:
>EDDiscovery v10.1.5.0 There was an unhandled UI exception.
>```
>==== BEGIN ====
>System.ArgumentOutOfRangeException: Index was out of range. Must be non-negative and less than the size of the collection.
>Parameter name: index
>   at System.ThrowHelper.ThrowArgumentOutOfRangeException(ExceptionArgument argument, ExceptionResource resource)
>   at EDDiscovery.UserControls.UserControlEngineering.Init() in C:\Code\eddiscovery2\EDDiscovery\EDDiscovery\UserControls\UserControlEngineering.cs:line 105
>   at EDDiscovery.UserControls.UserControlShoppingList.Init() in C:\Code\eddiscovery2\EDDiscovery\EDDiscovery\UserControls\UserControlShoppingList.cs:line 64
>   at EDDiscovery.MajorTabControl.CreateTab(PanelIDs ptype, String name, Int32 dn, Int32 posindex, Boolean dotheme) in C:\Code\eddiscovery2\EDDiscovery\EDDiscovery\MajorTabControl.cs:line 248
>   at EDDiscovery.MajorTabControl.AddTab(PanelIDs id, Int32 tabindex) in C:\Code\eddiscovery2\EDDiscovery\EDDiscovery\MajorTabControl.cs:line 148
>   at System.Windows.Forms.Control.OnClick(EventArgs e)
>   at System.Windows.Forms.Button.OnClick(EventArgs e)
>   at System.Windows.Forms.Button.OnMouseUp(MouseEventArgs mevent)
>   at System.Windows.Forms.Control.WmMouseUp(Message& m, MouseButtons button, Int32 clicks)
>   at System.Windows.Forms.Control.WndProc(Message& m)
>   at System.Windows.Forms.ButtonBase.WndProc(Message& m)
>   at System.Windows.Forms.Button.WndProc(Message& m)
>   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)
>===== END =====
![eddiscovery_error](https://user-images.githubusercontent.com/8410275/42348256-0ebf299a-80a9-11e8-92aa-2f13a8e87b1c.jpg)
[Trace_2018-07-05-23-02-18.0.log](https://github.com/EDDiscovery/EDDiscovery/files/2168243/Trace_2018-07-05-23-02-18.0.log)

**Comment by robbyxp1** [comment]
This looks like a bug not taking into account recipes numbers can change.. oh dear.

**Comment by robbyxp1** [comment]
Fixed, will push to master/10.1.x tomorrow.  We will wait for a little bit before 10.1.6 is done with this fix

**Comment by datavizzard** [comment]
Got this Unhandled UI Exception when creating a new Bookmark

```
### Description
<!-- Please write a brief description about what you were doing when the exception was encountered. -->

### Additional Information
<!-- Please attach (drag and drop) any relevant trace logs, screenshots, and/or journal files here to provide information about the problem. -->

### Exception Details:
>EDDiscovery v10.1.5.0 There was an unhandled UI exception.
>```
>==== BEGIN ====
>System.NullReferenceException: Der Objektverweis wurde nicht auf eine Objektinstanz festgelegt.
>   bei EDDiscovery.UserControls.SurfaceBookmarksForm.dataGridViewMarks_CellEndEdit(Object sender, DataGridViewCellEventArgs e) in C:\Code\eddiscovery2\EDDiscovery\EDDiscovery\UserControls\Helpers\SurfaceBookmarksForm.cs:Zeile 175.
>   bei System.Windows.Forms.DataGridView.OnCellEndEdit(DataGridViewCellEventArgs e)
>   bei System.Windows.Forms.DataGridView.EndEdit(DataGridViewDataErrorContexts context, DataGridViewValidateCellInternal validateCell, Boolean fireCellLeave, Boolean fireCellEnter, Boolean fireRowLeave, Boolean fireRowEnter, Boolean fireLeave, Boolean keepFocus, Boolean resetCurrentCell, Boolean resetAnchorCell)
>   bei System.Windows.Forms.DataGridView.OnValidating(CancelEventArgs e)
>   bei System.Windows.Forms.Control.NotifyValidating()
>   bei System.Windows.Forms.Control.PerformControlValidation(Boolean bulkValidation)
>   bei System.Windows.Forms.ContainerControl.ValidateThroughAncestor(Control ancestorControl, Boolean preventFocusChangeOnError)
>   bei System.Windows.Forms.ContainerControl.UpdateFocusedControl()
>   bei System.Windows.Forms.ContainerControl.AssignActiveControlInternal(Control value)
>   bei System.Windows.Forms.ContainerControl.ActivateControlInternal(Control control, Boolean originator)
>   bei System.Windows.Forms.Control.WmSetFocus(Message& m)
>   bei System.Windows.Forms.Control.WndProc(Message& m)
>   bei System.Windows.Forms.RichTextBox.WndProc(Message& m)
>   bei System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)
>===== END =====
>```
```

**Comment by robbyxp1** [comment]
Thank for the report -  note that it may have been missed, it prob better to open a new one since the incident is not in the same place.

found and patched for 10.1.6
