### ISSUE TITLE
Unhandled UI Exception (EDDiscovery 10.1.6.0)

### ISSUE THREAD

**Issue by taggedcattle** [EDDiscovery/EDDiscovery#2089]
Error below. On opening EDDiscovery, Commander is not set. Go into settings, Edit the Commander (only one in list). Click OK. Error below occurs. After several tries, error doesn't occur. After restart, same phenomenon.

There was an unhandled UI exception.

==== BEGIN ====
System.NullReferenceException: Object reference not set to an instance of an object.
   at EliteDangerousCore.Inara.InaraSync.RefreshList(HistoryList history) in C:\Code\EDDiscovery\EliteDangerous\Inara\InaraSync.cs:line 87
   at EliteDangerousCore.Inara.InaraSync.Refresh(Action`1 logger, HistoryList history, EDCommander cmdr) in C:\Code\EDDiscovery\EliteDangerous\Inara\InaraSync.cs:line 49
   at EDDiscovery.EDDiscoveryForm.Controller_RefreshComplete() in C:\Code\EDDiscovery\EDDiscovery\EDDiscoveryForm.cs:line 633
   at EDDiscovery.EDDiscoveryController.ForegroundHistoryRefreshComplete(HistoryList hist) in C:\Code\EDDiscovery\EDDiscovery\EDDiscoveryController.cs:line 844
===== END =====

**Comment by robbyxp1** [comment]
On master
