### ISSUE TITLE
total lock out of pc

### ISSUE THREAD

**Issue by Alferret** [EDDiscovery/EDDiscovery#2146]
### Exception Details:
>EDDiscovery v10.1.5.0 There was an unhandled UI exception.
>```
>==== BEGIN ====
>System.ArgumentException: Parameter is not valid.
>   at System.Drawing.Bitmap..ctor(Int32 width, Int32 height, PixelFormat format)
>   at ExtendedControls.TabControlCustom.OnPaint(PaintEventArgs e) in C:\Code\eddiscovery2\EDDiscovery\ExtendedControls\Controls\TabControlCustom.cs:line 248
>   at System.Windows.Forms.Control.PaintWithErrorHandling(PaintEventArgs e, Int16 layer)
>   at System.Windows.Forms.Control.WmPaint(Message& m)
>   at System.Windows.Forms.Control.WndProc(Message& m)
>   at System.Windows.Forms.TabControl.WndProc(Message& m)
>   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)
>===== END =====
>```

**Comment by klightspeed** [comment]
This looks like it was saved with zero width.

Please try holding shift while starting, and clicking `Reset Window Positions` then clicking `Run`
