### ISSUE TITLE
EDDiscovery v10.2.3.0 fatal error

### ISSUE THREAD

**Issue by Pelzer24** [EDDiscovery/EDDiscovery#2221]
Installed and everything worked fine. Restarted my PC and ever since I keep getting this error. Uninstalled and reinstalled multiple times on different drives. Same issue. Help?

An unhandled fatal exception has occurred.

==== BEGIN ====
System.Data.SQLite.SQLiteException (0x80004005): database or disk is full
database or disk is full
   at System.Data.SQLite.SQLite3.Reset(SQLiteStatement stmt)
   at System.Data.SQLite.SQLite3.Step(SQLiteStatement stmt)
   at System.Data.SQLite.SQLiteDataReader.NextResult()
   at System.Data.SQLite.SQLiteDataReader..ctor(SQLiteCommand cmd, CommandBehavior behave)
   at System.Data.SQLite.SQLiteCommand.ExecuteReader(CommandBehavior behavior)
   at System.Data.SQLite.SQLiteCommand.ExecuteNonQuery(CommandBehavior behavior)
   at EliteDangerousCore.DB.SQLiteCommandED`1.ExecuteNonQuery() in C:\Code\EDDiscovery\EliteDangerous\DB\SQLiteCommandED.cs:line 559
   at EliteDangerousCore.DB.SQLiteConnectionSystem.CreateSystemsTableIndexesNoLock() in C:\Code\EDDiscovery\EliteDangerous\DB\SQLiteConnectionSystem.cs:line 341
   at EliteDangerousCore.DB.SQLiteConnectionSystem.CreateSystemsTableIndexes() in C:\Code\EDDiscovery\EliteDangerous\DB\SQLiteConnectionSystem.cs:line 318
   at EDDiscovery.EDDiscoveryController.BackgroundInit() in C:\Code\EDDiscovery\EDDiscovery\EDDiscoveryController.cs:line 552
   at EDDiscovery.EDDiscoveryController.BackgroundWorkerThread() in C:\Code\EDDiscovery\EDDiscovery\EDDiscoveryController.cs:line 495
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.ThreadHelper.ThreadStart()
===== END =====

**Comment by klightspeed** [comment]
> System.Data.SQLite.SQLiteException (0x80004005): database or disk is full

Is the disk full?

The stack trace suggests it is the EDDSystem.sqlite database. If the disk is not full, and it is not running on FAT32, then please try removing EDDSystem.sqlite from `%LOCALAPPDATA%\EDDiscovery`

**Comment by Pelzer24** [comment]
No. 392GB free. The other drive had 159GB free.

**Comment by Pelzer24** [comment]
Looks like that fixed it. Thank you.
