### ISSUE TITLE
UI Exception

### ISSUE THREAD

**Issue by spadino** [EDDiscovery/EDDiscovery#2249]
### Description
It happens when the history cursor enter in a system which has a FSS Full system scan entry:
{
  "timestamp": "2018-12-12T15:50:31Z",
  "event": "FSSAllBodiesFound",
  "SystemName": "Byeia Chrea HI-F c13-3",
  "SystemAddress": 909694909810,
  "Count": 26
}

### Additional Information
ED 3.3 - EDD 10.3.1.0

### Exception Details:
>EDDiscovery v10.3.1.0 There was an unhandled UI exception.
>```
>==== BEGIN ====
>System.NullReferenceException: Object reference not set to an instance of an object.
>   at EDDiscovery.UserControls.UserControlScanGrid.DrawSystem(HistoryEntry he, Boolean force) in C:\projects\eddiscovery\EDDiscovery\UserControls\UserControlScanGrid.cs:line 167
>   at EDDiscovery.UserControls.ChangedSelectionHEHandler.Invoke(HistoryEntry he, HistoryList hl)
>   at EDDiscovery.UserControls.UserControlTravelGrid.FireChangeSelection() in C:\projects\eddiscovery\EDDiscovery\UserControls\UserControlTravelGrid.cs:line 482
>   at System.Windows.Forms.DataGridView.OnCellClick(DataGridViewCellEventArgs e)
>   at System.Windows.Forms.DataGridView.OnMouseClick(MouseEventArgs e)
>   at System.Windows.Forms.Control.WmMouseUp(Message& m, MouseButtons button, Int32 clicks)
>   at System.Windows.Forms.Control.WndProc(Message& m)
>   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)
>===== END =====
>```

**Comment by spadino** [comment]
Fixed by #2250 and #2251
