### ISSUE TITLE
Keeps crashing on open. "An unhandled fatal exception has occurred."

### ISSUE THREAD

**Issue by Esenfur** [EDDiscovery/EDDiscovery#2279]
An unhandled fatal exception has occurred.

==== BEGIN ====
code = IoErr (10), message = System.Data.SQLite.SQLiteException (0x800007FF): disk I/O error
disk I/O error
   at System.Data.SQLite.SQLite3.Reset(SQLiteStatement stmt)
   at System.Data.SQLite.SQLite3.Step(SQLiteStatement stmt)
   at System.Data.SQLite.SQLiteDataReader.NextResult()
   at System.Data.SQLite.SQLiteDataReader..ctor(SQLiteCommand cmd, CommandBehavior behave)
   at System.Data.SQLite.SQLiteCommand.ExecuteReader(CommandBehavior behavior)
   at System.Data.SQLite.SQLiteCommand.ExecuteNonQuery(CommandBehavior behavior)
   at EliteDangerousCore.DB.SQLiteCommandED`1.ExecuteNonQuery() in C:\Code\EDDiscovery\EliteDangerous\DB\SQLiteCommandED.cs:line 559
   at EliteDangerousCore.DB.SQLiteConnectionSystem.CreateSystemsTableIndexesNoLock() in C:\Code\EDDiscovery\EliteDangerous\DB\SQLiteConnectionSystem.cs:line 341
   at EliteDangerousCore.DB.SQLiteConnectionSystem.CreateSystemsTableIndexes() in C:\Code\EDDiscovery\EliteDangerous\DB\SQLiteConnectionSystem.cs:line 318
   at EDDiscovery.EDDiscoveryController.BackgroundInit() in C:\Code\EDDiscovery\EDDiscovery\EDDiscoveryController.cs:line 552
   at EDDiscovery.EDDiscoveryController.BackgroundWorkerThread() in C:\Code\EDDiscovery\EDDiscovery\EDDiscoveryController.cs:line 495
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.ThreadHelper.ThreadStart()
===== END =====

**Comment by robbyxp1** [comment]
The SQL Database is corrupted in some way - using safe mode (hold down shift and run the program) delete the system db.  

The run normally.

**Comment by Inhumierer** [comment]
I think I got the same issue here, but description doesn't sound like corrupt database.

### Description

Adding a system name to trilateration page.
### Additional Information


### Exception Details:
>EDDiscovery v10.3.3.0 There was an unhandled UI exception.
>```
>==== BEGIN ====
>System.OverflowException: Die arithmetische Operation hat einen Überlauf verursacht.
>   bei ExtendedControls.DraggableForm.WndProc(Message& m) in C:\Code\EDDiscovery\ExtendedControls\ExtendedControls\Forms\DraggableForm.cs:Zeile 124.
>   bei System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)
>===== END =====
>```

**Comment by klightspeed** [comment]
@Inhumierer please create a new issue for this - it is completely unrelated to the original issue.

**Comment by Inhumierer** [comment]
I'll do, if it happens again.
