### ISSUE TITLE
DateTime problem?

### ISSUE THREAD

**Issue by anikaiful** [EDDiscovery/EDDiscovery#231]
SubmitToEDSM Exception:String was not recognized as a valid DateTime.   at System.Windows.Forms.Control.MarshaledInvoke(Control caller, Delegate method, Object[] args, Boolean synchronous)
   at System.Windows.Forms.Control.Invoke(Delegate method, Object[] args)
   at EDDiscovery.TrilaterationControl.SubmitToEDSM()

**Comment by anikaiful** [comment]
In addendum, after hitting 'refresh' button for the travel log (after trilaterating a system with above error), this pops up:

************** Exception Text **************
System.FormatException: String was not recognized as a valid DateTime.
   at System.DateTimeParse.ParseExact(String s, String format, DateTimeFormatInfo dtfi, DateTimeStyles style)
   at EDDiscovery2.EDSM.EDSMClass.RequestSystems(String date)
   at EDDiscovery2.EDSM.EDSMClass.GetNewSystems(SQLiteDBClass db)
   at EDDiscovery.TravelHistoryControl.TriggerEDSMRefresh()
   at EDDiscovery.TravelHistoryControl.button_RefreshHistory_Click(Object sender, EventArgs e)
   at System.Windows.Forms.Control.OnClick(EventArgs e)
   at System.Windows.Forms.Button.OnClick(EventArgs e)
   at System.Windows.Forms.Button.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)

**Comment by finwen** [comment]
This should be solved now i think

**Comment by anikaiful** [comment]
Seems to be fixed. At least I'm not getting that exception popping at my face anymore.
