### ISSUE TITLE
10.3.4 Fatal Error and Freezing when opening.

### ISSUE THREAD

**Issue by Iruse** [EDDiscovery/EDDiscovery#2326]
So I installed this earlier today opened up messed around with it and worked perfectly fine.  Left the computer came back and now the program will either just freeze once opened or through up a fatal error to report.  Like the program would like to continue using it.

An unhandled fatal exception has occurred.

==== BEGIN ====
code = Full (13), message = System.Data.SQLite.SQLiteException (0x800007FF): database or disk is full
database or disk is full
   at System.Data.SQLite.SQLite3.Reset(SQLiteStatement stmt)
   at System.Data.SQLite.SQLite3.Step(SQLiteStatement stmt)
   at System.Data.SQLite.SQLiteDataReader.NextResult()
   at System.Data.SQLite.SQLiteDataReader..ctor(SQLiteCommand cmd, CommandBehavior behave)
   at System.Data.SQLite.SQLiteCommand.ExecuteReader(CommandBehavior behavior)
   at System.Data.SQLite.SQLiteCommand.ExecuteNonQuery(CommandBehavior behavior)
   at EliteDangerousCore.DB.SQLiteCommandED`1.ExecuteNonQuery() in C:\Code\EDDiscovery\EliteDangerous\DB\SQLiteCommandED.cs:line 559
   at EliteDangerousCore.DB.SQLiteConnectionSystem.CreateSystemsTableIndexesNoLock() in C:\Code\EDDiscovery\EliteDangerous\DB\SQLiteConnectionSystem.cs:line 341
   at EliteDangerousCore.DB.SQLiteConnectionSystem.CreateSystemsTableIndexes() in C:\Code\EDDiscovery\EliteDangerous\DB\SQLiteConnectionSystem.cs:line 318
   at EDDiscovery.EDDiscoveryController.BackgroundInit() in C:\Code\EDDiscovery\EDDiscovery\EDDiscoveryController.cs:line 552
   at EDDiscovery.EDDiscoveryController.BackgroundWorkerThread() in C:\Code\EDDiscovery\EDDiscovery\EDDiscoveryController.cs:line 495
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.ThreadHelper.ThreadStart()
===== END =====

**Comment by klightspeed** [comment]
> database or disk is full

Is your disk full?

**Comment by Rynestone1** [comment]
My disk isn't full but I'm having a similar issue. There is no error for me, it stays stuck at "Repairing Canopy" I've tried fresh installs of EDD, and even trying a previous release.

**Comment by klightspeed** [comment]
@Rynestone1 your issue appears to be that you had exited or force-quit EDDiscovery while it was creating the index in EDDSystem.sqlite.  Please try removing that file and restarting EDDiscovery.

**Comment by Iruse** [comment]
No I have about 500gb left on that drive. And I also tried to uninstall and reinstall the program in a new folder.

**Comment by klightspeed** [comment]
Given that so many people are confused that the program doesn't store data in its install directory when that install directory is changed, it sounds like we need to:
* Detect if `%LOCALAPPDATA%\EDDiscovery` exists
  - if it exists, then use that as the default data directory
* Else detect if the program is installed in `%PROGRAMFILES%`, or if the install directory is not writable
  - if not, then use the `Data` directory in the install directory as the data directory

In the meantime, please create an `Options.txt` in your install directory with the following line:
```
AppFolder X:\Path\To\Data
```
replacing `X:\Path\To\Data` with where you want your data stored, then move everything from `%LOCALAPPDATA%\EDDiscovery` to that directory.  Also, since it appears your EDDSystem.sqlite is corrupt, please try deleting that.

**Comment by Iruse** [comment]
That would make sense as I just updated the star map and then closed the program and then it wouldn't work later on. 

I will do all of this tomorrow morning and let you know what happened. And thank you for your quick responses.

**Comment by Iruse** [comment]
All of this seemed to work, Yeah apparently when I set up my commander data I didn't notice the journal dir option. and I downloaded about 6gb of star data into my ssd.  I will keep playing around with it and see if the same issue happens but this seemed to fix the problem or at the very least let me run the program again. 

Thanks again for the help.
