### ISSUE TITLE
Unhandled UI exception

### ISSUE THREAD

**Issue by Evoflash** [EDDiscovery/EDDiscovery#2355]
Happened when moving over planets in the lower half of the screen.

### Exception Details:
>EDDiscovery v10.4.2.0 There was an unhandled UI exception.
>```
>==== BEGIN ====
>System.NullReferenceException: Object reference not set to an instance of an object.
>   at EDDiscovery.UserControls.UserControlScan.BuildScanValue(SystemNode system) in C:\Code\EDDiscovery\EDDiscovery\UserControls\ScansStars\UserControlScan.cs:line 194
>   at EDDiscovery.UserControls.UserControlScan.DrawSystem() in C:\Code\EDDiscovery\EDDiscovery\UserControls\ScansStars\UserControlScan.cs:line 181
>   at EDDiscovery.UserControls.UserControlScan.NewEntry(HistoryEntry he, HistoryList hl) in C:\Code\EDDiscovery\EDDiscovery\UserControls\ScansStars\UserControlScan.cs:line 135
>   at System.Action`2.Invoke(T1 arg1, T2 arg2)
>   at EDDiscovery.EDDiscoveryController.ActionEntry(JournalEntry je) in C:\Code\EDDiscovery\EDDiscovery\EDDiscoveryController.cs:line 453
>   at EDDiscovery.EDDiscoveryController.PlayJournalList() in C:\Code\EDDiscovery\EDDiscovery\EDDiscoveryController.cs:line 432
>   at EliteDangerousCore.EDJournalClass.ScanTickDone(List`1 entries) in C:\Code\EDDiscovery\EliteDangerous\EliteDangerous\EDJournalClass.cs:line 184
>===== END =====
>```

**Comment by klightspeed** [comment]
Looks like a duplcate of #2354
