### ISSUE TITLE
Further issue

### ISSUE THREAD

**Issue by blagstock** [EDDiscovery/EDDiscovery#2365]
An unhandled fatal exception has occurred.

==== BEGIN ====
System.InvalidOperationException: Invoke or BeginInvoke cannot be called on a control until the window handle has been created.
   at System.Windows.Forms.Control.MarshaledInvoke(Control caller, Delegate method, Object[] args, Boolean synchronous)
   at System.Windows.Forms.Control.BeginInvoke(Delegate method, Object[] args)
   at EDDiscovery.UserControls.UserControlStarDistance.<KickComputation>b__17_0(ISystem s, SortedListDoubleDuplicate`1 d) in C:\Code\EDDiscovery\EDDiscovery\UserControls\ScansStars\UserControlStarDistance.cs:line 117
   at EliteDangerousCore.StarDistanceComputer.BackgroundStardistWorkerThread() in C:\Code\EDDiscovery\EliteDangerous\EliteDangerous\StarDistanceComputer.cs:line 106
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.ThreadHelper.ThreadStart()
===== END

**Comment by blagstock** [comment]
It is persistent in that there have been multiple hangs / crashes.  Apologies for my lack of detail but I have not noted (or indeed perceived) what has precipitated each issue.  I should add that this is an install from the 10.4.3 exe (not the zip).

However, I can confirm that the star distance panel was in the 'standard' format upon opening (i.e. no user alteration to the default layout).

**Comment by robbyxp1** [comment]
Thanks.. have to have a think about what could be causing it.

**Comment by klightspeed** [comment]
Do you have a star distance panel in a popout?

**Comment by blagstock** [comment]
No - standard default layout.
