### ISSUE TITLE
unhandled UI exception

### ISSUE THREAD

**Issue by sutex** [EDDiscovery/EDDiscovery#2368]
Clicking on the Green planet looking "scan" icon (materials ? didn't open) on the main window right hand side may have added it myself , been configuring changing layouts. 
==== BEGIN ====
System.InvalidOperationException: SplitterDistance must be between Panel1MinSize and Width - Panel2MinSize.
   at System.Windows.Forms.SplitContainer.set_SplitterDistance(Int32 value)
   at ControlHelpersStaticFunc.SplitterDistance(SplitContainer sp, Double value) in C:\Code\EDDiscovery\BaseUtilities\BaseUtilities\WinForms\ControlHelpers.cs:line 292
   at EDDiscovery.UserControls.UserControlSearch.<Init>b__3_1(TabStrip tab, Control ctrl, Int32 si) in C:\Code\EDDiscovery\EDDiscovery\UserControls\Search\UserControlSearch.cs:line 62
   at ExtendedControls.TabStrip.PostCreate() in C:\Code\EDDiscovery\ExtendedControls\ExtendedControls\Controls\TabStrip.cs:line 179
   at ExtendedControls.TabStrip.ChangePanel(Int32 i) in C:\Code\EDDiscovery\ExtendedControls\ExtendedControls\Controls\TabStrip.cs:line 123
   at System.Windows.Forms.Control.OnClick(EventArgs e)
   at System.Windows.Forms.Control.WmMouseUp(Message& m, MouseButtons button, Int32 clicks)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)
===== END =====

**Comment by robbyxp1** [comment]
Fixed on tip. next version. 

In the meanwhile, if you can't clear it, hold down shift during launch and clear the tabs/popouts etc.
