### ISSUE TITLE
Splitter Error 

### ISSUE THREAD

**Issue by banger705** [EDDiscovery/EDDiscovery#2437]
There was an unhandled UI exception.

==== BEGIN ====
System.IndexOutOfRangeException: Index was outside the bounds of the array.
   at EDDiscovery.UserControls.UserControlContainerSplitter.<>c__DisplayClass16_1.<MakeNode>b__4(TabStrip tab, Int32 i) in C:\Code\EDDiscovery\EDDiscovery\UserControls\GridsSplitters\UserControlContainerSplitter.cs:line 265
   at ExtendedControls.TabStrip.panelPopOut_Click(Object sender, EventArgs e) in C:\Code\EDDiscovery\ExtendedControls\ExtendedControls\Controls\TabStrip.cs:line 242
   at System.Windows.Forms.Control.OnClick(EventArgs e)
   at ExtendedControls.DrawnPanel.OnMouseClick(MouseEventArgs e) in C:\Code\EDDiscovery\ExtendedControls\ExtendedControls\Controls\DrawnPanel.cs:line 502
   at ExtendedControls.DrawnPanel.OnMouseUp(MouseEventArgs mevent) in C:\Code\EDDiscovery\ExtendedControls\ExtendedControls\Controls\DrawnPanel.cs:line 556
   at System.Windows.Forms.Control.WmMouseUp(Message& m, MouseButtons button, Int32 clicks)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)
===== END =====

**Comment by klightspeed** [comment]
What were you doing at the time this occurred?

**Comment by klightspeed** [comment]
Duplicated the issue by clicking the popout button on a splitter panel where the panel hadn't been chosen yet.

**Comment by banger705** [comment]
thanks 

all I done was to click the X on the right hand corner...
