### ISSUE TITLE
Exception in Captain's Log

### ISSUE THREAD

**Issue by xenophonf** [EDDiscovery/EDDiscovery#2447]
### Description
I was in the calendar view of the Captain's Log and tried clicking on the 3/1 date, which had a log entry in it that I wanted to edit.

### Additional Information
The Captain's Log entry was dated 3/1/2019 7:00 PM, if I recall correctly.

### Exception Details:
EDDiscovery v10.5.0.0 There was an unhandled UI exception.
```
==== BEGIN ====
System.ArgumentOutOfRangeException: Year, Month, and Day parameters describe an un-representable DateTime.
   at System.DateTime.DateToTicks(Int32 year, Int32 month, Int32 day)
   at EDDiscovery.UserControls.CaptainsLogDiary.DayClick(Object sender, EventArgs e) in C:\Code\EDDiscovery\EDDiscovery\UserControls\LogsBookmarks\CaptainsLogDiary.cs:line 187
   at System.Windows.Forms.Control.OnClick(EventArgs e)
   at System.Windows.Forms.Button.OnClick(EventArgs e)
   at System.Windows.Forms.Button.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)
===== END =====
```

**Comment by klightspeed** [comment]
What date were you trying to select when this occurred?

**Comment by xenophonf** [comment]
I was trying to select 3/1.

-- 
"The lyf so short, the craft so longe to lerne."
