### ISSUE TITLE
"There was an unhandled UI exception."

### ISSUE THREAD

**Issue by BannorPhil** [EDDiscovery/EDDiscovery#2492]
This error occurred when opening the app after updating:

There was an unhandled UI exception.

==== BEGIN ====
code = Busy (5), message = System.Data.SQLite.SQLiteException (0x800007AF): database is locked
database is locked
   at System.Data.SQLite.SQLite3.Step(SQLiteStatement stmt)
   at System.Data.SQLite.SQLiteDataReader.NextResult()
   at System.Data.SQLite.SQLiteDataReader..ctor(SQLiteCommand cmd, CommandBehavior behave)
   at System.Data.SQLite.SQLiteCommand.ExecuteReader(CommandBehavior behavior)
   at System.Data.SQLite.SQLiteCommand.ExecuteNonQuery(CommandBehavior behavior)
   at SQLLiteExtensions.SQLExtCommand`1.ExecuteNonQuery() in C:\Code\EDDiscovery\BaseUtilities\SQLLite\SQLLite\SQLCommand.cs:line 131
   at EliteDangerousCore.DB.BookmarkClass.Update(SQLiteConnectionUser cn) in C:\Code\EDDiscovery\EliteDangerous\DB\BookmarkClass.cs:line 279
   at EliteDangerousCore.DB.BookmarkClass.Update() in C:\Code\EDDiscovery\EliteDangerous\DB\BookmarkClass.cs:line 259
   at EliteDangerousCore.DB.GlobalBookMarkList.AddOrUpdateBookmark(BookmarkClass bk, Boolean isstar, String name, Double x, Double y, Double z, DateTime tme, String notes, PlanetMarks planetMarks) in C:\Code\EDDiscovery\EliteDangerous\DB\BookmarkClass.cs:line 472
   at EDDiscovery.Actions.ActionBookmarks.ExecuteAction(ActionProgramRun ap) in C:\Code\EDDiscovery\EDDiscovery\Actions\ActionsEDDCmds\ActionBookmarks.cs:line 191
   at ActionLanguage.ActionRun.DoExecute() in C:\Code\EDDiscovery\ActionLanguage\ActionLanguage\ActionsCore\ActionRun.cs:line 217
   at ActionLanguage.ActionRun.Tick_Tick(Object sender, EventArgs e) in C:\Code\EDDiscovery\ActionLanguage\ActionLanguage\ActionsCore\ActionRun.cs:line 239
   at System.Windows.Forms.Timer.OnTick(EventArgs e)
   at System.Windows.Forms.Timer.TimerNativeWindow.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)
===== END =====

I was able to 'continue'.

**Comment by robbyxp1** [comment]
I think its a random transient but i'll investigate. thanks

**Comment by klightspeed** [comment]
Would it please be possible to attach the trace log?

**Comment by robbyxp1** [comment]
No user response. closed.
