### ISSUE TITLE
Disk Too Full SQLite error

### ISSUE THREAD

**Issue by Voyager47** [EDDiscovery/EDDiscovery#2495]
An unhandled fatal exception has occurred.

==== BEGIN ====
code = Full (13), message = System.Data.SQLite.SQLiteException (0x800007FF): database or disk is full
database or disk is full
   at System.Data.SQLite.SQLite3.Reset(SQLiteStatement stmt)
   at System.Data.SQLite.SQLite3.Step(SQLiteStatement stmt)
   at System.Data.SQLite.SQLiteDataReader.NextResult()
   at System.Data.SQLite.SQLiteDataReader..ctor(SQLiteCommand cmd, CommandBehavior behave)
   at System.Data.SQLite.SQLiteCommand.ExecuteReader(CommandBehavior behavior)
   at System.Data.SQLite.SQLiteCommand.ExecuteNonQuery(CommandBehavior behavior)
   at SQLLiteExtensions.SQLExtCommand`1.ExecuteNonQuery() in C:\Code\EDDiscovery\BaseUtilities\SQLLite\SQLLite\SQLCommand.cs:line 131
   at EliteDangerousCore.DB.SQLiteConnectionSystem.CreateSystemsTableIndexesNoLock() in C:\Code\EDDiscovery\EliteDangerous\DB\SQLiteConnectionSystem.cs:line 346
   at EliteDangerousCore.DB.SQLiteConnectionSystem.CreateSystemsTableIndexes() in C:\Code\EDDiscovery\EliteDangerous\DB\SQLiteConnectionSystem.cs:line 323
   at EDDiscovery.EDDiscoveryController.BackgroundInit() in C:\Code\EDDiscovery\EDDiscovery\EDDiscoveryController.cs:line 552
   at EDDiscovery.EDDiscoveryController.BackgroundWorkerThread() in C:\Code\EDDiscovery\EDDiscovery\EDDiscoveryController.cs:line 495
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.ThreadHelper.ThreadStart()
===== END =====

**Comment by klightspeed** [comment]
> database or disk is full

Is your disk full?

**Comment by robbyxp1** [comment]
No user response. Closed

**Comment by Voyager47** [comment]
no----- Original Message -----

**Comment by bymaximus** [comment]
I can confirm this, seems is related to SQLite database, its creating some temp files (recovery/optimize db?) at windows user temporary folder and not at EDDiscovery data folder.

The error happens if disk is full. I needed to create a windows link of this user/appdata/local/temp folder to some other disk to bypass this error.

![Anotação 2019-06-11 201540](https://user-images.githubusercontent.com/595991/59313654-47d39400-8c88-11e9-8338-2f05478dce73.jpg)

**Comment by klightspeed** [comment]
This suggests we need to override the `TMP` and/or `TEMP` environment variables to e.g. a `temp` directory in the data directory.
