### ISSUE TITLE
Moving/dragging main window with title bar UI exception

### ISSUE THREAD

**Issue by HockeyFan77** [EDDiscovery/EDDiscovery#2521]
### Description
Any time I move/drag/resize the main window, I get the UI exception below.
Windows 10 Pro - 64bit
nVidia GTX 1070 latest drivers
Primary Monitor: Alienware 34" Ultrawide - 3440x1440
Secondary Monitor: Asus 24" - 1920x1080

### Exception Details:
>EDDiscovery v10.6.0.0 There was an unhandled UI exception.
>```
>==== BEGIN ====
>System.OverflowException: Arithmetic operation resulted in an overflow.
>   at ExtendedControls.DraggableForm.WndProc(Message& m) in C:\Code\EDDiscovery\ExtendedControls\ExtendedControls\Forms\DraggableForm.cs:line 122
>   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)
>===== END =====
>```

**Comment by HockeyFan77** [comment]
Aha! On a hunch...
I'm also running WinDock. When I disable it, no UI exception. I can reproduce the exception easily by simply enabling WinDock. WinDock is definitely intercepting window movement/resizing so it must be interfering with EDDisc somehow. I have a workaround so no need to chase this down unless y'all want to. I'll leave this issue open for a bit and if no activity, I'll close it out.

**Comment by klightspeed** [comment]
The line number appears to be misleading - that line is an `==` line.

The arithmetic overflow suggests that either WinDock isn't passing LParam correctly for the `WM_NCHITTEST` or WM_NCLBUTTONDOWN messages, or the screen working area and screen bounds are more than 32k pixels apart.

**Comment by robbyxp1** [comment]
Closing, external program interaction, not much we can do.
