### ISSUE TITLE
Unhandled UI Exception - Custom Date Range in 3D Map

### ISSUE THREAD

**Issue by RadioActiveLobster** [EDDiscovery/EDDiscovery#2523]
I tried to set a custom date range in the 3D map and got this

```
### Description
<!-- Please write a brief description about what you were doing when the exception was encountered. -->

### Additional Information
<!-- Please attach (drag and drop) any relevant trace logs, screenshots, and/or journal files here to provide information about the problem. -->

### Exception Details:
>EDDiscovery v10.6.0.0 There was an unhandled UI exception.
>```
>==== BEGIN ====
>System.ArgumentOutOfRangeException: Value of '12/31/9999 11:59:59 PM' is not valid for 'Value'. 'Value' should be between 'MinDate' and 'MaxDate'.
>Parameter name: Value
>   at System.Windows.Forms.DateTimePicker.set_Value(DateTime value)
>   at EDDiscovery.FormMap.dropdownFilterHistory_Custom_Click(Object sender, EventArgs e, ToolStripButton sel) in C:\Code\EDDiscovery\EDDiscovery\3DMap\FormMap.cs:line 1132
>   at System.Windows.Forms.ToolStripItem.RaiseEvent(Object key, EventArgs e)
>   at System.Windows.Forms.ToolStripButton.OnClick(EventArgs e)
>   at System.Windows.Forms.ToolStripItem.HandleClick(EventArgs e)
>   at System.Windows.Forms.ToolStripItem.HandleMouseUp(MouseEventArgs e)
>   at System.Windows.Forms.ToolStrip.OnMouseUp(MouseEventArgs mea)
>   at System.Windows.Forms.ToolStripDropDown.OnMouseUp(MouseEventArgs mea)
>   at System.Windows.Forms.Control.WmMouseUp(Message& m, MouseButtons button, Int32 clicks)
>   at System.Windows.Forms.Control.WndProc(Message& m)
>   at System.Windows.Forms.ToolStrip.WndProc(Message& m)
>   at System.Windows.Forms.ToolStripDropDown.WndProc(Message& m)
>   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)
>===== END =====
>```
```

**Comment by klightspeed** [comment]
We probably need to convert that exception into a "your date is invalid" popup.

**Comment by klightspeed** [comment]
We will see if this is still the case in 11.0 - this part of the program was significantly re-written.

**Comment by robbyxp1** [comment]
I rewrote that bit since it was very old and iffy.  It should not happen.  

11.0 is due this month, if I can get away from work related stuff.
