### ISSUE TITLE
[UserControlStats] ArgumentNullException when counting discoveries

### ISSUE THREAD

**Issue by Garthy50** [EDDiscovery/EDDiscovery#2526]
I get this error every time i run ED Discovery.

```
There was an unhandled UI exception.

==== BEGIN ====
System.ArgumentNullException: Value cannot be null.
Parameter name: source
   at System.Linq.Enumerable.Count[TSource](IEnumerable`1 source)
   at System.Linq.Enumerable.WhereSelectEnumerableIterator`2.MoveNext()
   at System.Linq.Enumerable.Sum(IEnumerable`1 source)
   at EDDiscovery.UserControls.UserControlStats.StatsGeneral(HistoryEntry he, HistoryList hl) in C:\Code\EDDiscovery\EDDiscovery\UserControls\CurrentState\UserControlStats.cs:line 166
   at EDDiscovery.UserControls.UserControlStats.Stats(HistoryEntry he, HistoryList hl) in C:\Code\EDDiscovery\EDDiscovery\UserControls\CurrentState\UserControlStats.cs:line 123
   at EDDiscovery.UserControls.ChangedSelectionHEHandler.Invoke(HistoryEntry he, HistoryList hl, Boolean selectedEntry)
   at EDDiscovery.UserControls.UserControlTravelGrid.FireChangeSelection() in C:\Code\EDDiscovery\EDDiscovery\UserControls\History\UserControlTravelGrid.cs:line 546
   at System.Windows.Forms.DataGridView.OnCellClick(DataGridViewCellEventArgs e)
   at System.Windows.Forms.DataGridView.OnMouseClick(MouseEventArgs e)
   at System.Windows.Forms.Control.WmMouseUp(Message& m, MouseButtons button, Int32 clicks)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)
===== END =====
```

**Comment by klightspeed** [comment]
What version?

**Comment by klightspeed** [comment]
It looks like 3.3 changed `Discovered` in the `SellExplorationData` event from being a list of system names to a list of `{SystemName, NumBodies}`

**Comment by robbyxp1** [comment]
We will need to cope with both of course.  Journal manual is not pointing this out.

 196: { "timestamp":"2019-03-07T22:01:40Z", "event":"MultiSellExplorationData", "Discovered":[ { "SystemName":"Ossians", "NumBodies":2 }, { "SystemName":"Fu Hsi", "NumBodies":3 }, { "SystemName":"HIP 24912", "NumBodies":15 }, { "SystemName":"Hyades Sector UT-R c4-22", "NumBodies":1 }, { "SystemName":"Col 285 Sector EP-G b11-6", "NumBodies":1 } ], "BaseValue":1282965, "Bonus":0, "TotalEarnings":1282965 }

**Comment by robbyxp1** [comment]
Wrong - that was multisell. do not have evidence of SellExplorationData.

**Comment by robbyxp1** [comment]
Closing, bug patched, no more info
