### ISSUE TITLE
Crash Dialog

### ISSUE THREAD

**Issue by RalphVargr** [EDDiscovery/EDDiscovery#2538]
An unhandled fatal exception has occurred.

==== BEGIN ====
System.NullReferenceException: Object reference not set to an instance of an object.
   at EliteDangerousCore.EDJournalClass.StopMonitor() in C:\Code\EDDiscovery\EliteDangerous\Journal\EDJournalClass.cs:line 122
   at EDDiscovery.EDDiscoveryController.BackgroundHistoryRefreshWorkerThread() in C:\Code\EDDiscovery\EDDiscovery\EDDiscoveryController.cs:line 775
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.ThreadHelper.ThreadStart()
===== END =====

**Comment by robbyxp1** [comment]
Thanks for the report.

ToDo. Remove the StopRequested=null at line 123.. leave it alone.

**Comment by robbyxp1** [comment]
Speculative fix put in for 11.0, thanks
