### ISSUE TITLE
EDDiscovery Crash

### ISSUE THREAD

**Issue by hwru** [EDDiscovery/EDDiscovery#2561]
An unhandled fatal exception has occurred.

==== BEGIN ====
code = Busy (5), message = System.Data.SQLite.SQLiteException (0x800007AF): database is locked
database is locked
   at System.Data.SQLite.SQLite3.Step(SQLiteStatement stmt)
   at System.Data.SQLite.SQLiteDataReader.NextResult()
   at System.Data.SQLite.SQLiteDataReader..ctor(SQLiteCommand cmd, CommandBehavior behave)
   at System.Data.SQLite.SQLiteCommand.ExecuteReader(CommandBehavior behavior)
   at System.Data.SQLite.SQLiteCommand.ExecuteNonQuery(CommandBehavior behavior)
   at SQLLiteExtensions.SQLExtCommand`1.ExecuteNonQuery() in C:\Code\EDDiscovery\BaseUtilities\SQLLite\SQLLite\SQLCommand.cs:line 133
   at SQLLiteExtensions.SQLExtConnection.ExecuteNonQuery(String query) in C:\Code\EDDiscovery\BaseUtilities\SQLLite\SQLLite\SQLConnection.cs:line 237
   at SQLLiteExtensions.SQLExtConnection.ExecuteNonQueries(String[] queries) in C:\Code\EDDiscovery\BaseUtilities\SQLLite\SQLLite\SQLConnection.cs:line 230
   at EliteDangerousCore.DB.SQLiteConnectionSystem.UpgradeSystemTableFrom102TypeDB(Func`1 cancelRequested, Action`1 reportProgress, Boolean fullsyncrequested) in C:\Code\EDDiscovery\EliteDangerous\SystemDB\SQLiteConnectionSystem.cs:line 215
   at EDDiscovery.EDDiscoveryController.DoPerformSync() in C:\Code\EDDiscovery\EDDiscovery\EDDiscoveryControllerSync.cs:line 107
   at EDDiscovery.EDDiscoveryController.BackgroundWorkerThread() in C:\Code\EDDiscovery\EDDiscovery\EDDiscoveryControllerMain.cs:line 311
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.ThreadHelper.ThreadStart()
===== END =====

**Comment by robbyxp1** [comment]
This should clear on a restart..
