### ISSUE TITLE
EDDiscovery v11.0.1.0 There was an unhandled UI exception.

### ISSUE THREAD

**Issue by Slegnor** [EDDiscovery/EDDiscovery#2590]
### Description
Loaded up ED discovery, the GUI didnt appear and this appeared after about 30 seconds after the splash screen disappeared

### Exception Details:
>EDDiscovery v11.0.1.0 There was an unhandled UI exception.
>```
>==== BEGIN ====
>System.DivideByZeroException: Attempted to divide by zero.
>   at EDDiscovery.UserControls.UserControlPanelSelector.Reposition() in C:\Code\EDDiscovery\EDDiscovery\UserControls\GridsSplitters\UserControlPanelSelector.cs:line 164
>   at EDDiscovery.UserControls.UserControlPanelSelector.Redraw() in C:\Code\EDDiscovery\EDDiscovery\UserControls\GridsSplitters\UserControlPanelSelector.cs:line 130
>   at EDDiscovery.MajorTabControl.LoadTabs() in C:\Code\EDDiscovery\EDDiscovery\MajorTabControl.cs:line 117
>   at EDDiscovery.EDDiscoveryForm.EDDiscoveryForm_Load(Object sender, EventArgs e) in C:\Code\EDDiscovery\EDDiscovery\EDDiscoveryForm.cs:line 324
>   at System.Windows.Forms.Form.OnLoad(EventArgs e)
>   at System.Windows.Forms.Form.OnCreateControl()
>   at System.Windows.Forms.Control.CreateControl(Boolean fIgnoreVisible)
>   at System.Windows.Forms.Control.CreateControl()
>   at System.Windows.Forms.Control.WmShowWindow(Message& m)
>   at System.Windows.Forms.Control.WndProc(Message& m)
>   at System.Windows.Forms.Form.WmShowWindow(Message& m)
>   at ExtendedControls.SmartSysMenuForm.WndProc(Message& m) in C:\Code\EDDiscovery\ExtendedControls\ExtendedControls\Forms\SmartSysMenuForm.cs:line 224
>   at ExtendedControls.DraggableForm.WndProc(Message& m) in C:\Code\EDDiscovery\ExtendedControls\ExtendedControls\Forms\DraggableForm.cs:line 257
>   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)
>===== END =====
>```

**Comment by Slegnor** [comment]
I have just seen 11.0.3 is available so I'm going to close this and see if it occurs again after the update
