### ISSUE TITLE
Unhandled UI Exception

### ISSUE THREAD

**Issue by davidoakley** [EDDiscovery/EDDiscovery#2591]
Running EDDiscovery v11.0.3.0:

There was an unhandled UI exception.

==== BEGIN ====
System.NullReferenceException: Object reference not set to an instance of an object.
   at EliteDangerousCore.HistoryList.AddJournalEntry(JournalEntry je, Action`1 logerror) in C:\Code\EDDiscovery\EliteDangerous\HistoryList\HistoryList.cs:line 894
   at EDDiscovery.EDDiscoveryController.ActionEntry(JournalEntry je) in C:\Code\EDDiscovery\EDDiscovery\EDDiscoveryControllerNewEntry.cs:line 82
   at EDDiscovery.EDDiscoveryController.PlayJournalList() in C:\Code\EDDiscovery\EDDiscovery\EDDiscoveryControllerNewEntry.cs:line 72
   at EliteDangerousCore.EDJournalClass.ScanTickDone(Tuple`2 entries) in C:\Code\EDDiscovery\EliteDangerous\Journal\EDJournalClass.cs:line 185
===== END =====

**Comment by robbyxp1** [comment]
if (jl == null || (jl.StarSystem.Equals(jlhe.System.Name, StringComparison.InvariantCultureIgnoreCase) && !js.BodyDesignation.ToLowerInvariant().Contains(" belt cluster ")))

jl.starsystem or js.BodyDesignation is empty

BodyDesignation not set by JournalScan but by code in AddScanToBestSystem..

StarSystem is set in LocOrJump using .Str() so should never be null

js is taken from JournalScan and therefore is always null until passed into AddScan which may set it.

The logic looks wrong

Can you comment Ben?
