### ISSUE TITLE
Unhandled exception while updating from 10.6.0 

### ISSUE THREAD

**Issue by norberci** [EDDiscovery/EDDiscovery#2593]
An unhandled fatal exception has occurred.

==== BEGIN ====
code = Corrupt (11), message = System.Data.SQLite.SQLiteException (0x800007EF): database disk image is malformed
database disk image is malformed
   at System.Data.SQLite.SQLite3.Reset(SQLiteStatement stmt)
   at System.Data.SQLite.SQLite3.Step(SQLiteStatement stmt)
   at System.Data.SQLite.SQLiteDataReader.NextResult()
   at System.Data.SQLite.SQLiteDataReader..ctor(SQLiteCommand cmd, CommandBehavior behave)
   at System.Data.SQLite.SQLiteCommand.ExecuteReader(CommandBehavior behavior)
   at System.Data.SQLite.SQLiteCommand.ExecuteNonQuery(CommandBehavior behavior)
   at SQLLiteExtensions.SQLExtCommand`1.ExecuteNonQuery() in C:\Code\EDDiscovery\BaseUtilities\SQLLite\SQLLite\SQLCommand.cs:line 133
   at SQLLiteExtensions.SQLExtConnection.ExecuteNonQuery(String query) in C:\Code\EDDiscovery\BaseUtilities\SQLLite\SQLLite\SQLConnection.cs:line 237
   at SQLLiteExtensions.SQLExtConnection.ExecuteNonQueries(String[] queries) in C:\Code\EDDiscovery\BaseUtilities\SQLLite\SQLLite\SQLConnection.cs:line 230
   at EliteDangerousCore.DB.SQLiteConnectionSystem.UpgradeSystemTableFrom102TypeDB(Func`1 cancelRequested, Action`1 reportProgress, Boolean fullsyncrequested) in C:\Code\EDDiscovery\EliteDangerous\SystemDB\SQLiteConnectionSystem.cs:line 216
   at EDDiscovery.EDDiscoveryController.BackgroundWorkerThread() in C:\Code\EDDiscovery\EDDiscovery\EDDiscoveryControllerMain.cs:line 312
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.ThreadHelper.ThreadStart()
===== END =====

**Comment by norberci** [comment]
It happens during "removing old system database" step

**Comment by robbyxp1** [comment]
Hold down shift, run EDDiscovery. Delete the system DB using one of the options.  Then run

It will rebuild it.

Something went wrong during the process.

**Comment by norberci** [comment]
That worked, thanks.
