### ISSUE TITLE
Stand alone hung. Later fatal exception when syncronizing at start.

### ISSUE THREAD

**Issue by Eukaryoter** [EDDiscovery/EDDiscovery#2596]
Very new to EDDI. Using EDDI as a plugin to Voice Attack and as stand alone at times. Did use both at the same time. Fatal exception when starting as stand alone without VA.

An unhandled fatal exception has occurred.

==== BEGIN ====
code = IoErr (10), message = System.Data.SQLite.SQLiteException (0x800007FF): disk I/O error
disk I/O error
   at System.Data.SQLite.SQLite3.Reset(SQLiteStatement stmt)
   at System.Data.SQLite.SQLite3.Step(SQLiteStatement stmt)
   at System.Data.SQLite.SQLiteDataReader.NextResult()
   at System.Data.SQLite.SQLiteDataReader..ctor(SQLiteCommand cmd, CommandBehavior behave)
   at System.Data.SQLite.SQLiteCommand.ExecuteReader(CommandBehavior behavior)
   at SQLLiteExtensions.SQLExtDataReader`1..ctor(DbCommand cmd, CommandBehavior behaviour, SQLExtTransaction`1 txn, SQLExtTransactionLock`1 txnlock) in C:\Code\EDDiscovery\BaseUtilities\SQLLite\SQLLite\SQLReader.cs:line 38
   at SQLLiteExtensions.SQLExtCommand`1.ExecuteDbDataReader(CommandBehavior behavior) in C:\Code\EDDiscovery\BaseUtilities\SQLLite\SQLLite\SQLCommand.cs:line 94
   at EliteDangerousCore.DB.SystemsDB.GetSystemListBySqDistancesFrom(SortedListDoubleDuplicate`1 distlist, Double x, Double y, Double z, Int32 maxitems, Double mindist, Double maxdist, Boolean spherical, SQLiteConnectionSystem cn, Action`1 LookedUp) in C:\Code\EDDiscovery\EliteDangerous\SystemDB\SystemsDBGetByDistance.cs:line 91
   at EliteDangerousCore.DB.SystemCache.GetSystemListBySqDistancesFrom(SortedListDoubleDuplicate`1 distlist, Double x, Double y, Double z, Int32 maxitems, Double mindist, Double maxdist, Boolean spherical, SQLiteConnectionSystem cn) in C:\Code\EDDiscovery\EliteDangerous\SystemDB\SystemCache.cs:line 172
   at EliteDangerousCore.StarDistanceComputer.BackgroundStardistWorkerThread() in C:\Code\EDDiscovery\EliteDangerous\EliteDangerous\StarDistanceComputer.cs:line 101
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.ThreadHelper.ThreadStart()
===== END =====

**Comment by Eukaryoter** [comment]
Hi

Yes your right. Should have spotted that. But so far it's the only program that have shown this behaviour. 

I have the program program installed in the default location on the system disc C: a SSD disk not very old. 

Should/could I move the journal file to some other disk?

**Comment by Eukaryoter** [comment]
I get these messages a couple of times now:
History refresh complete.
Processing EDSM systems download failed, will try next time program is run

**Comment by klightspeed** [comment]
Please check the latest trace log in the `Log` directory in the EDDiscovery data directory (`%LOCALAPPDATA%\EDDiscovery\Log` for the installed version, or `Data\Log` for the portable version) - that should indicate what is causing the EDSM systems download to fail.

`History refresh complete` is normal, and is logged when your travel history has been fully read in.

**Comment by robbyxp1** [comment]
Closing
