### ISSUE TITLE
Unhandled Fatal Exception

### ISSUE THREAD

**Issue by Mr-Rhye** [EDDiscovery/EDDiscovery#2600]
Updated to v11.0.3.0 and this error now shows up and shuts the program down after I close the error box.
This is in the details.

An unhandled fatal exception has occurred.

```
==== BEGIN ====
code = Corrupt (11), message = System.Data.SQLite.SQLiteException (0x800007EF): database disk image is malformed
database disk image is malformed
   at System.Data.SQLite.SQLite3.Reset(SQLiteStatement stmt)
   at System.Data.SQLite.SQLite3.Step(SQLiteStatement stmt)
   at System.Data.SQLite.SQLiteDataReader.NextResult()
   at System.Data.SQLite.SQLiteDataReader..ctor(SQLiteCommand cmd, CommandBehavior behave)
   at System.Data.SQLite.SQLiteCommand.ExecuteReader(CommandBehavior behavior)
   at System.Data.SQLite.SQLiteCommand.ExecuteNonQuery(CommandBehavior behavior)
   at SQLLiteExtensions.SQLExtCommand`1.ExecuteNonQuery() in C:\Code\EDDiscovery\BaseUtilities\SQLLite\SQLLite\SQLCommand.cs:line 133
   at SQLLiteExtensions.SQLExtConnection.ExecuteNonQuery(String query) in C:\Code\EDDiscovery\BaseUtilities\SQLLite\SQLLite\SQLConnection.cs:line 237
   at SQLLiteExtensions.SQLExtConnection.ExecuteNonQueries(String[] queries) in C:\Code\EDDiscovery\BaseUtilities\SQLLite\SQLLite\SQLConnection.cs:line 230
   at EliteDangerousCore.DB.SQLiteConnectionSystem.UpgradeSystemTableFrom102TypeDB(Func`1 cancelRequested, Action`1 reportProgress, Boolean fullsyncrequested) in C:\Code\EDDiscovery\EliteDangerous\SystemDB\SQLiteConnectionSystem.cs:line 234
   at EDDiscovery.EDDiscoveryController.BackgroundWorkerThread() in C:\Code\EDDiscovery\EDDiscovery\EDDiscoveryControllerMain.cs:line 312
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.ThreadHelper.ThreadStart()
===== END =====
```

**Comment by robbyxp1** [comment]
Hold down shift, run EDD, delete the system database, and restart.  it will reload the star data but the problem will disappear.

**Comment by robbyxp1** [comment]
Presumed fixed.
