### ISSUE TITLE
Steam Client Freezes and EDD Freezez

### ISSUE THREAD

**Issue by Bwana-Jim** [EDDiscovery/EDDiscovery#2638]
Steam Client for ED froze and had to use Task Manager to kill it. That's when I noticed that EDD was frozen too. 
An unhandled fatal exception has occurred.

==== BEGIN ====
System.InvalidOperationException: Invoke or BeginInvoke cannot be called on a control until the window handle has been created.
   at System.Windows.Forms.Control.MarshaledInvoke(Control caller, Delegate method, Object[] args, Boolean synchronous)
   at System.Windows.Forms.Control.BeginInvoke(Delegate method, Object[] args)
   at DirectInputDevices.InputDeviceList.waitthread() in C:\Code\EDDiscovery\BaseUtilities\DirectInput\InputDeviceList.cs:line 122
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.ThreadHelper.ThreadStart()
===== END =====

**Comment by robbyxp1** [comment]
This call happens when an input device has events. The start() for this is called in actionsfrominputdevices.cs Start(). This is called from EliteInput enable in Action Perform.  And action packs only get to use that after EDDiscoveryForm::Shown::actioncontroller.OnStartup() triggers the action pack startup scripts

So its not due to the form not being there at the start.  Maybe during closedown.

I think its a very hard error to reproduce and may just be a windows forms querk.

**Comment by robbyxp1** [comment]
Tell us if it occurs again.
