### ISSUE TITLE
Database or disk is full?

### ISSUE THREAD

**Issue by treakifo** [EDDiscovery/EDDiscovery#2645]
Started getting this error after upgrading to 11.1.1.0. Not sure where the database is stored, but I have tons of free space.

An unhandled fatal exception has occurred.

==== BEGIN ====
code = Full (13), message = System.Data.SQLite.SQLiteException (0x800007FF): database or disk is full
database or disk is full
   at System.Data.SQLite.SQLite3.Reset(SQLiteStatement stmt)
   at System.Data.SQLite.SQLite3.Step(SQLiteStatement stmt)
   at System.Data.SQLite.SQLiteDataReader.NextResult()
   at System.Data.SQLite.SQLiteDataReader..ctor(SQLiteCommand cmd, CommandBehavior behave)
   at System.Data.SQLite.SQLiteCommand.ExecuteReader(CommandBehavior behavior)
   at System.Data.SQLite.SQLiteCommand.ExecuteNonQuery(CommandBehavior behavior)
   at SQLiteCommandExtensions.Vacuum(SQLExtConnection r) in C:\Code\EDDiscovery\BaseUtilities\SQLLite\SQLLite\SQLExtensions.cs:line 125
   at EliteDangerousCore.DB.SystemsDatabase.<>c__DisplayClass11_0.<UpgradeSystemTableFromFile>b__1(SystemsDatabaseConnection conn) in C:\Code\EDDiscovery\EliteDangerous\SystemDB\SystemsDatabase.cs:line 74
   at SQLLiteExtensions.SQLProcessingThread`1.Job.Exec() in C:\Code\EDDiscovery\BaseUtilities\SQLLite\SQLLite\SQLProcessingThread.cs:line 39
   at SQLLiteExtensions.SQLProcessingThread`1.SqlThreadProc() in C:\Code\EDDiscovery\BaseUtilities\SQLLite\SQLLite\SQLProcessingThread.cs:line 79
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.ThreadHelper.ThreadStart()
===== END =====

**Comment by klightspeed** [comment]
Please try deleting `EDDSystem.sqlite` from `%LOCALAPPDATA%\EDDiscovery` - it sounds like it is corrupt.

**Comment by treakifo** [comment]
That seemed to work for an hour or so, but it just crashed again. Here's
the latest error detail:

An unhandled fatal exception has occurred.

==== BEGIN ====
code = Full (13), message = System.Data.SQLite.SQLiteException
(0x800007FF): database or disk is full
database or disk is full
   at System.Data.SQLite.SQLite3.Reset(SQLiteStatement stmt)
   at System.Data.SQLite.SQLite3.Step(SQLiteStatement stmt)
   at System.Data.SQLite.SQLiteDataReader.NextResult()
   at System.Data.SQLite.SQLiteDataReader..ctor(SQLiteCommand cmd,
CommandBehavior behave)
   at System.Data.SQLite.SQLiteCommand.ExecuteReader(CommandBehavior
behavior)
   at System.Data.SQLite.SQLiteCommand.ExecuteNonQuery(CommandBehavior
behavior)
   at SQLiteCommandExtensions.Vacuum(SQLExtConnection r) in
C:\Code\EDDiscovery\BaseUtilities\SQLLite\SQLLite\SQLExtensions.cs:line 125
   at
EliteDangerousCore.DB.SystemsDatabase.<>c__DisplayClass11_0.<UpgradeSystemTableFromFile>b__1(SystemsDatabaseConnection
conn) in
C:\Code\EDDiscovery\EliteDangerous\SystemDB\SystemsDatabase.cs:line 74
   at SQLLiteExtensions.SQLProcessingThread`1.Job.Exec() in
C:\Code\EDDiscovery\BaseUtilities\SQLLite\SQLLite\SQLProcessingThread.cs:line
39
   at SQLLiteExtensions.SQLProcessingThread`1.SqlThreadProc() in
C:\Code\EDDiscovery\BaseUtilities\SQLLite\SQLLite\SQLProcessingThread.cs:line
79
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext
executionContext, ContextCallback callback, Object state, Boolean
preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext
executionContext, ContextCallback callback, Object state, Boolean
preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext
executionContext, ContextCallback callback, Object state)
   at System.Threading.ThreadHelper.ThreadStart()
===== END =====

**Comment by robbyxp1** [comment]
I read on t'internet
"The error message is from SQLite, which writes some transaction files in the temp folder.
SQLite does not honor the --tempdir advanced option, it always uses the system environment variable TMPDIR which is also used as the default for --tempdir (in other words, if you set the TMPDIR environment variable and nothing else, all temp files go there).

I am guessing that you have some really large volumes that are downloaded into the temporary folder, which causes SQLite to run out of temporary space. What is the volume size you are using?"

Where is your TEMP directory..
![image](https://user-images.githubusercontent.com/6573992/67622103-997f5400-f80e-11e9-9cb0-037d370f4198.png)

**Comment by treakifo** [comment]
That is definitely a possibility. I actually use a smallish (256MB) RAM
disk for temp storage to reduce wear-and-tear on my SSD drives. As an added
bonus, my temp files are destroyed at boot (since it's just RAM) so I don't
have to deal with the buildup of thousands of orphaned temp files like I
see on my coworker's disks at work.

I had been using EDDiscovery for several weeks before this issue started,
so maybe it will be enough to bump up my RAM disk to 512MB. I assume that
the transactions are eventually rolled up into the main database and not
live in Temp forever...

**Comment by klightspeed** [comment]
> ```
>    at SQLiteCommandExtensions.Vacuum(SQLExtConnection r) in C:\Code\EDDiscovery\BaseUtilities\SQLLite\SQLLite\SQLExtensions.cs:line 125
> ```

Vacuum basically rebuilds the database.  I wonder if the database connection does need to be closed between these large changes (the database connection is now long-lived where the connection lifetime was previously short but sometimes presumably extended by SQLite connection pooling).

**Comment by robbyxp1** [comment]
I think the user having a ram disk for TMP is a corner case. I would not code around it.

**Comment by robbyxp1** [comment]
Closing as solved.
