### ISSUE TITLE
Unhandled fatal exception

### ISSUE THREAD

**Issue by spec5sx** [EDDiscovery/EDDiscovery#2653]
EDDiscovery crashes on launch with a fatal exception. I can eventually get it running by restarting it two or three times. Don't remember the last version ever crashing like this. This is the latest version 11.1.2.0

An unhandled fatal exception has occurred.

==== BEGIN ====
System.AccessViolationException: Attempted to read or write protected memory. This is often an indication that other memory is corrupt.
   at System.Globalization.CompareInfo.InternalCompareString(IntPtr handle, IntPtr handleOrigin, String localeName, String string1, Int32 offset1, Int32 length1, String string2, Int32 offset2, Int32 length2, Int32 flags)
   at System.Globalization.CompareInfo.Compare(String string1, String string2, CompareOptions options)
   at System.Collections.Generic.ArraySortHelper`1.InternalBinarySearch(T[] array, Int32 index, Int32 length, T value, IComparer`1 comparer)
   at System.Collections.Generic.GenericArraySortHelper`1.BinarySearch(T[] array, Int32 index, Int32 length, T value, IComparer`1 comparer)
   at System.Collections.Generic.SortedList`2.Add(TKey key, TValue value)
   at EliteDangerousCore.StarScan.ProcessBelts(JournalScan sc, ScanNode node) in C:\Code\EDDiscovery\EliteDangerous\ScarScan\StarScanJournalScans.cs:line 400
   at EliteDangerousCore.StarScan.ProcessJournalScan(JournalScan sc, ISystem sys, Boolean reprocessPrimary) in C:\Code\EDDiscovery\EliteDangerous\ScarScan\StarScanJournalScans.cs:line 123
   at EliteDangerousCore.StarScan.AddScanToBestSystem(JournalScan je, Int32 startindex, List`1 hl, HistoryEntry& he, JournalLocOrJump& jl) in C:\Code\EDDiscovery\EliteDangerous\ScarScan\StarScanJournalScans.cs:line 56
   at EliteDangerousCore.HistoryList.ProcessUserHistoryListEntries() in C:\Code\EDDiscovery\EliteDangerous\HistoryList\HistoryList.cs:line 1118
   at EliteDangerousCore.HistoryList.LoadHistory(EDJournalClass journalmonitor, Func`1 cancelRequested, Action`2 reportProgress, String NetLogPath, Boolean ForceNetLogReload, Boolean ForceJournalReload, Int32 CurrentCommander, Int32 fullhistoryloaddaylimit, String essentialitems) in C:\Code\EDDiscovery\EliteDangerous\HistoryList\HistoryList.cs:line 1084
   at EDDiscovery.EDDiscoveryController.DoRefreshHistory(RefreshWorkerArgs args) in C:\Code\EDDiscovery\EDDiscovery\EDDiscoveryControllerHistory.cs:line 154
   at EDDiscovery.EDDiscoveryController.BackgroundWorkerThread() in C:\Code\EDDiscovery\EDDiscovery\EDDiscoveryControllerMain.cs:line 299
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.ThreadHelper.ThreadStart()
===== END =====

**Comment by klightspeed** [comment]
Crashes within DotNET internal calls would suggest that either:
* Your install is corrupt;
* DotNET is corrupt; or
* Some injected DLL is corrupting memory.

**Comment by spec5sx** [comment]
I think I may have solved the crashing issue. I used the 'Rebuild System DB Indexes' feature and that seems to have eliminated the problem.

**Comment by klightspeed** [comment]
That sounds almost as if a bug in SQLite resulted in memory corruption.

**Comment by robbyxp1** [comment]
Concluded then.
