### ISSUE TITLE
Unhandled UI Exception

### ISSUE THREAD

**Issue by mpfj** [EDDiscovery/EDDiscovery#2659]
Just started ED and I'm repeatedly getting this error.

I've rebooted the PC but it's still the same.

```
### Description
<!-- Please write a brief description about what you were doing when the exception was encountered. -->

### Additional Information
<!-- Please attach (drag and drop) any relevant trace logs, screenshots, and/or journal files here to provide information about the problem. -->

### Exception Details:
>EDDiscovery v11.1.2.0 There was an unhandled UI exception.
>```
>==== BEGIN ====
>System.NullReferenceException: Object reference not set to an instance of an object.
>   at EDDiscovery.UserControls.UserControlTrippanel.Display(HistoryList hl) in C:\Code\EDDiscovery\EDDiscovery\UserControls\Overlays\UserControlTrippanel.cs:line 118
>   at System.Action`1.Invoke(T obj)
>   at EDDiscovery.EDDiscoveryController.ForegroundHistoryRefreshCompleteonUI(HistoryList hist) in C:\Code\EDDiscovery\EDDiscovery\EDDiscoveryControllerHistory.cs:line 192
>===== END =====
>```
```

**Comment by klightspeed** [comment]
That sounds like there are no FSDJumps in your history - have you ever jumped anywhere?

**Comment by robbyxp1** [comment]
So, holdown Shift, run EDD

![image](https://user-images.githubusercontent.com/6573992/69378683-c9533780-0ca6-11ea-8d83-099b4ceba3b0.png)

Do reset tabs, remove popouts.

Run.

We will address the inherent problem. Thanks for the report.

**Comment by mpfj** [comment]
> So, holdown Shift, run EDD

This worked a treat ... thanks :)
