### ISSUE TITLE
Crashed

### ISSUE THREAD

**Issue by AliW-web** [EDDiscovery/EDDiscovery#2712]
An unhandled fatal exception has occurred.

```
==== BEGIN ====
SQLLiteExtensions.SQLProcessingThreadException: database is locked
database is locked ---> System.Data.SQLite.SQLiteException: database is locked
database is locked
   at System.Data.SQLite.SQLite3.Prepare(SQLiteConnection cnn, String strSql, SQLiteStatement previous, UInt32 timeoutMS, String& strRemain)
   at System.Data.SQLite.SQLiteCommand.BuildNextCommand()
   at System.Data.SQLite.SQLiteDataReader.NextResult()
   at System.Data.SQLite.SQLiteDataReader..ctor(SQLiteCommand cmd, CommandBehavior behave)
   at System.Data.SQLite.SQLiteCommand.ExecuteReader(CommandBehavior behavior)
   at SQLiteCommandExtensions.SQLMasterQuery(SQLExtConnection r, String type) in C:\Code\EDDiscovery\BaseUtilities\SQLLite\SQLLite\SQLExtensions.cs:line 127
   at SQLiteCommandExtensions.Tables(SQLExtConnection r) in C:\Code\EDDiscovery\BaseUtilities\SQLLite\SQLLite\SQLExtensions.cs:line 110
   at EliteDangerousCore.DB.SystemsDatabase.<>c__DisplayClass12_0.<UpgradeSystemTableFrom102TypeDB>b__0(SystemsDatabaseConnection conn) in C:\Code\EDDiscovery\EliteDangerous\SystemDB\SystemsDatabase.cs:line 107
   at SQLLiteExtensions.SQLProcessingThread`1.<>c__DisplayClass15_0.<ExecuteWithDatabase>b__0() in C:\Code\EDDiscovery\BaseUtilities\SQLLite\SQLLite\SQLProcessingThread.cs:line 172
   at SQLLiteExtensions.SQLProcessingThread`1.Job`1.Exec() in C:\Code\EDDiscovery\BaseUtilities\SQLLite\SQLLite\SQLProcessingThread.cs:line 66
   --- End of inner exception stack trace ---
   at SQLLiteExtensions.SQLProcessingThread`1.Job`1.Wait() in C:\Code\EDDiscovery\BaseUtilities\SQLLite\SQLLite\SQLProcessingThread.cs:line 89
   at SQLLiteExtensions.SQLProcessingThread`1.Execute[T](Func`1 func, Int32 skipframes, Int32 warnthreshold) in C:\Code\EDDiscovery\BaseUtilities\SQLLite\SQLLite\SQLProcessingThread.cs:line 158
   at SQLLiteExtensions.SQLProcessingThread`1.ExecuteWithDatabase(Action`1 action, Int32 warnthreshold) in C:\Code\EDDiscovery\BaseUtilities\SQLLite\SQLLite\SQLProcessingThread.cs:line 173
   at EliteDangerousCore.DB.SystemsDatabase.UpgradeSystemTableFrom102TypeDB(Func`1 cancelRequested, Action`1 reportProgress, Boolean fullsyncrequested) in C:\Code\EDDiscovery\EliteDangerous\SystemDB\SystemsDatabase.cs:line 119
   at EDDiscovery.EDDiscoveryController.DoPerformSync() in C:\Code\EDDiscovery\EDDiscovery\EDDiscoveryControllerSync.cs:line 107
   at EDDiscovery.EDDiscoveryController.BackgroundWorkerThread() in C:\Code\EDDiscovery\EDDiscovery\EDDiscoveryControllerMain.cs:line 310
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.ThreadHelper.ThreadStart()
===== END =====
```

**Comment by klightspeed** [comment]
This sounds like some external program is interfering with EDDiscovery accessing the system database.  Either that, or the system database is corrupt and needs to be re-created.

**Comment by robbyxp1** [comment]
Please check your drive status. You can rebuild the system database using safe mode to delete it.

I'm presuming your using 11.2.X

**Comment by AliW-web** [comment]
Hi Guys,

Yes, 11.2.1.0
It all seems to be OK now - as you said there must be something interfering with EDDiscovery.
It all seemed to start after a download from EDSM was getting stuck, that issue resolved itself after I left EDD running over a couple of nights.

Thanks for your replies
