### ISSUE TITLE
Can't open EDD - Unhandled UI exception

### ISSUE THREAD

**Issue by oberheim11** [EDDiscovery/EDDiscovery#2832]
### Exception Details:
>EDDiscovery v11.5.0.0 There was an unhandled UI exception.
>```
>==== BEGIN ====
>System.DivideByZeroException: Forsøkte å dele med null.
>   ved System.Windows.Forms.DataGridViewCell.MeasureTextPreferredSize(Graphics graphics, String text, Font font, Single maxRatio, TextFormatFlags flags)
>   ved System.Windows.Forms.DataGridViewColumnHeaderCell.GetPreferredSize(Graphics graphics, DataGridViewCellStyle cellStyle, Int32 rowIndex, Size constraintSize)
>   ved System.Windows.Forms.DataGridViewCell.GetPreferredSize(Int32 rowIndex)
>   ved System.Windows.Forms.DataGridView.AutoResizeColumnHeadersHeight(Boolean fixedRowHeadersWidth, Boolean fixedColumnsWidth)
>   ved System.Windows.Forms.DataGridView.OnGlobalAutoSize()
>   ved System.Windows.Forms.DataGridView.OnHandleCreated(EventArgs e)
>   ved System.Windows.Forms.Control.WmCreate(Message& m)
>   ved System.Windows.Forms.Control.WndProc(Message& m)
>   ved System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)
>===== END =====
>```

**Comment by klightspeed** [comment]
Please try resetting your theme and/or tabs by holding shift while starting, then clicking Reset Theme and Reset Tabs, and clicking Run.

A divide by zero error there suggests a bad font.

**Comment by oberheim11** [comment]
Thanks, it runs now. But crashes when i change font to Eurocaps.

**Comment by Fank** [comment]
I have like the same issue, and a friend as well.
We tried what @klightspeed wrote but didn't helped.
```
There was an unhandled UI exception.

==== BEGIN ====
System.NullReferenceException: Object reference not set to an instance of an object.
   at EDDiscovery.UserControls.UserControlTravelGrid.PaintEventColumn(DataGridView grid, DataGridViewRowPostPaintEventArgs e, Int32 totalentries, HistoryEntry he, Int32 hpos, Int32 colwidth, Boolean showfsdmapcolour) in C:\Code\EDDiscovery\EDDiscovery\UserControls\History\UserControlTravelGrid.cs:line 674
   at EDDiscovery.UserControls.UserControlTravelGrid.dataGridViewTravel_RowPostPaint(Object sender, DataGridViewRowPostPaintEventArgs e) in C:\Code\EDDiscovery\EDDiscovery\UserControls\History\UserControlTravelGrid.cs:line 619
   at System.Windows.Forms.DataGridView.OnRowPostPaint(DataGridViewRowPostPaintEventArgs e)
   at System.Windows.Forms.DataGridViewRow.Paint(Graphics graphics, Rectangle clipBounds, Rectangle rowBounds, Int32 rowIndex, DataGridViewElementStates rowState, Boolean isFirstDisplayedRow, Boolean isLastVisibleRow)
   at System.Windows.Forms.DataGridView.PaintRows(Graphics g, Rectangle boundingRect, Rectangle clipRect, Boolean singleHorizontalBorderAdded)
   at System.Windows.Forms.DataGridView.PaintGrid(Graphics g, Rectangle gridBounds, Rectangle clipRect, Boolean singleVerticalBorderAdded, Boolean singleHorizontalBorderAdded)
   at System.Windows.Forms.DataGridView.OnPaint(PaintEventArgs e)
   at System.Windows.Forms.Control.PaintWithErrorHandling(PaintEventArgs e, Int16 layer)
   at System.Windows.Forms.Control.WmPaint(Message& m)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)
===== END =====
```

**Comment by klightspeed** [comment]
@Fank your issue is related to #2833, and should be fixed by #2834

**Comment by klightspeed** [comment]
> Thanks, it runs now. But crashes when i change font to Eurocaps.

I'll have to see if I can reproduce this when I get home.

**Comment by robbyxp1** [comment]
Closing as no response.
