### ISSUE TITLE
EDDiscovery 11.6.1.0 crashing on startup

### ISSUE THREAD

**Issue by xenophonf** [EDDiscovery/EDDiscovery#2890]
The exception is:

```
An unhandled fatal exception has occurred.

==== BEGIN ====
SQLLiteExtensions.SQLProcessingThreadException: Exception has been thrown by the target of an invocation. ---> System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation. ---> System.TypeInitializationException: The type initializer for 'EliteDangerousCore.ShipModuleData' threw an exception. ---> System.InvalidProgramException: Common Language Runtime detected an invalid program.
   at EliteDangerousCore.ShipModuleData..cctor()
   --- End of inner exception stack trace ---
   at EliteDangerousCore.ShipModuleData.get_Instance() in C:\Code\EDDiscovery\EliteDangerousCore\EliteDangerous\Ships\ShipModuleData.cs:line 37
   at EliteDangerousCore.JournalFieldNaming.GetBetterItemName(String s) in C:\Code\EDDiscovery\EliteDangerousCore\EliteDangerous\EliteDangerous\JournalFieldNaming.cs:line 114
   at EliteDangerousCore.JournalEvents.JournalModuleInfo.Rescan(JObject evt) in C:\Code\EDDiscovery\EliteDangerousCore\EliteDangerous\JournalEvents\JournalModules.cs:line 535
   --- End of inner exception stack trace ---
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor)
   at System.Reflection.RuntimeConstructorInfo.Invoke(BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at System.RuntimeType.CreateInstanceImpl(BindingFlags bindingAttr, Binder binder, Object[] args, CultureInfo culture, Object[] activationAttributes, StackCrawlMark& stackMark)
   at System.Activator.CreateInstance(Type type, BindingFlags bindingAttr, Binder binder, Object[] args, CultureInfo culture, Object[] activationAttributes)
   at System.Activator.CreateInstance(Type type, Object[] args)
   at EliteDangerousCore.JournalEntry.CreateJournalEntry(JObject jo) in C:\Code\EDDiscovery\EliteDangerousCore\EliteDangerous\Journal\JournalEntry.cs:line 251
   at EliteDangerousCore.JournalEntry.CreateJournalEntry(DbDataReader dr) in C:\Code\EDDiscovery\EliteDangerousCore\EliteDangerous\Journal\JournalEntryDB.cs:line 53
   at EliteDangerousCore.JournalEntry.<>c__DisplayClass21_0.<GetAll>b__4(UserDatabaseConnection cn) in C:\Code\EDDiscovery\EliteDangerousCore\EliteDangerous\Journal\JournalEntryDB.cs:line 401
   at SQLLiteExtensions.SQLProcessingThread`1.Job`1.Exec() in C:\Code\EDDiscovery\BaseUtilities\SQLLite\SQLLite\SQLProcessingThread.cs:line 68
   --- End of inner exception stack trace ---
   at SQLLiteExtensions.SQLProcessingThread`1.Job`1.Wait() in C:\Code\EDDiscovery\BaseUtilities\SQLLite\SQLLite\SQLProcessingThread.cs:line 91
   at SQLLiteExtensions.SQLProcessingThread`1.Execute[T](Func`1 func, Int32 skipframes, Int32 warnthreshold) in C:\Code\EDDiscovery\BaseUtilities\SQLLite\SQLLite\SQLProcessingThread.cs:line 239
   at SQLLiteExtensions.SQLProcessingThread`1.ExecuteWithDatabase[T](Func`2 func, Int32 warnthreshold) in C:\Code\EDDiscovery\BaseUtilities\SQLLite\SQLLite\SQLProcessingThread.cs:line 260
   at EliteDangerousCore.JournalEntry.GetAll(Int32 commander, Nullable`1 afterutc, Nullable`1 beforeutc, JournalTypeEnum[] ids, Nullable`1 allidsafterutc) in C:\Code\EDDiscovery\EliteDangerousCore\EliteDangerous\Journal\JournalEntryDB.cs:line 350
   at EliteDangerousCore.EDSM.EDSMLogFetcher.Process(List`1 edsmlogs, DateTime logstarttime, DateTime logendtime) in C:\Code\EDDiscovery\EliteDangerousCore\EliteDangerous\EDSM\EDSMLogFetcher.cs:line 176
   at EliteDangerousCore.EDSM.EDSMLogFetcher.FetcherThreadProc() in C:\Code\EDDiscovery\EliteDangerousCore\EliteDangerous\EDSM\EDSMLogFetcher.cs:line 140
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.ThreadHelper.ThreadStart()
===== END =====
```

The latest player journal is attached below:
[Journal.200727073705.01.log](https://github.com/EDDiscovery/EDDiscovery/files/4984288/Journal.200727073705.01.log)

**Comment by klightspeed** [comment]
```
System.InvalidProgramException: Common Language Runtime detected an invalid program.
```

This suggests a corrupt install.

**Comment by xenophonf** [comment]
I re-installed EDDiscovery and EDD-EDMC, which resolved this problem.  Thanks for the suggestion, @klightspeed!
