### ISSUE TITLE
An unhandled fatal exception has occurred.

### ISSUE THREAD

**Issue by prusso** [EDDiscovery/EDDiscovery#2910]
An unhandled fatal exception has occurred.

==== BEGIN ====
CSCore.DirectSound.DirectSoundException (0x88780096): IDirectSoundBuffer::Stop caused an error: 0x88780096, "Unknown HRESULT".
   at CSCore.DirectSound.DirectSoundBuffer.Stop()
   at CSCore.SoundOut.DirectSoundOut.PlaybackProc(Object o)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.ThreadHelper.ThreadStart(Object obj)
===== END =====

**Comment by robbyxp1** [comment]
It happens, at very random intervals. We have seen this before, its a interaction between Windows and the Direct code.

Just ignore it, its unlikely to happen again

thanks
