### ISSUE TITLE
Version 11.7.0.0 issues

### ISSUE THREAD

**Issue by Mgzr51** [EDDiscovery/EDDiscovery#2914]
Just updated to the latest issue and was presented with this on running:

Scanning for bmp screenshots in C:\Users\*****\Pictures\Frontier Developments
Checking for new Expedition data
*** Web server is disabled ***
Checking for new Exploration data
Profile Default Loaded
Loaded Notes, Bookmarks and Galactic mapping.
Reading travel history
History Refresh Error: System.NullReferenceException: Object reference not set to an instance of an object.
   at EliteDangerousCore.HistoryList.MergeEntries(JournalEntry prev, JournalEntry je) in C:\Code\EDDiscovery\EliteDangerousCore\EliteDangerous\HistoryList\HistoryList.cs:line 1233
   at EliteDangerousCore.HistoryList.LoadHistory(EDJournalUIScanner journalmonitor, Func`1 cancelRequested, Action`2 reportProgress, String NetLogPath, Boolean ForceNetLogReload, Boolean ForceJournalReload, Int32 CurrentCommander, Int32 fullhistoryloaddaylimit, String essentialitems) in C:\Code\EDDiscovery\EliteDangerousCore\EliteDangerous\HistoryList\HistoryList.cs:line 1055
   at EDDiscovery.EDDiscoveryController.DoRefreshHistory(RefreshWorkerArgs args) in C:\Code\EDDiscovery\EDDiscovery\EDDiscoveryControllerHistory.cs:line 154
History refresh complete.

No issues with the previous one.

Help

**Comment by robbyxp1** [comment]
For now, try reinstalling the previous one.. We will investigate.

**Comment by Mgzr51** [comment]
Version 11.6.2.0 loaded and working fine.

**Comment by robbyxp1** [comment]
We can't see an obvious path to the error.  

11.7.1 will probably do the same.

It may be that your user DB is corrupted in some way. We do not have enough info to debug this as of now.

**Comment by Mgzr51** [comment]
I will try 11.7.1 but if its the same I will revert back to 11.6.2  I did notice that after I loaded 11.6.2 when I checked my history that there were double entries in the database up to the date that I installed 11.7. Not sure if this helps. Is there a way of flushing the database and reinatalling it?

Thanks

**Comment by robbyxp1** [comment]
To completely reset EDD, you can rename/delete the file %LOCALAPPDATA%\EDDiscovery\EDDUser.sqlite.  It will then rescan your journals.

What I would do,for an experiment, is to install 11.7.1, rename the above file to EDDUserBackup.sqlite , and run 11.7.1, and see if it goes wrong re-reading the journals.  Then restart and check it works again.

**Comment by Mgzr51** [comment]
I cleared the sql file, reloaded 11.7.1 and ran it. Journals were read ok . Everything seems to be back to normal. Thanks for your help.

Mgzr51

**Comment by robbyxp1** [comment]
Thats good. No idea what happened, but the DB was obv. not happy.
