### ISSUE TITLE
error, unhandled fatal exception

### ISSUE THREAD

**Issue by six-shooter** [EDDiscovery/EDDiscovery#2915]
An unhandled fatal exception has occurred.

it is installed on drive `S:\eddiscovery`

```
==== BEGIN ====
code = CantOpen (14), message = System.Data.SQLite.SQLiteException (0x800007FF): unable to open database file
   at System.Data.SQLite.SQLite3.Open(String strFilename, String vfsName, SQLiteConnectionFlags connectionFlags, SQLiteOpenFlagsEnum openFlags, Int32 maxPoolSize, Boolean usePool)
   at System.Data.SQLite.SQLiteConnection.Open()
   at SQLLiteExtensions.SQLExtConnectionRegister`1..ctor(String dbfile, Boolean utctimeindicator, AccessMode mode) in C:\Code\EDDiscovery\BaseUtilities\SQLLite\SQLLite\SQLConnectionRegister.cs:line 53
   at EliteDangerousCore.DB.UserDatabaseConnection..ctor() in C:\Code\EDDiscovery\EliteDangerousCore\EliteDangerous\DB\UserDatabase.cs:line 20
   at EliteDangerousCore.DB.UserDatabase.CreateConnection() in C:\Code\EDDiscovery\EliteDangerousCore\EliteDangerous\DB\UserDatabase.cs:line 48
   at SQLLiteExtensions.SQLProcessingThread`1.SqlThreadProc() in C:\Code\EDDiscovery\BaseUtilities\SQLLite\SQLLite\SQLProcessingThread.cs:line 141
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.ThreadHelper.ThreadStart()
===== END =====
```

**Comment by robbyxp1** [comment]
Some questions,

So, it can't open the DB file. 

Is there more than one instance running? 
Does it occur after a reboot? 
Is the file actually there? 
Is s: available? 
Did you use the portable version or the standard install?
Can you find the ED user database (EDUser.sqlite) anywhere?

**Comment by klightspeed** [comment]
Is anything logged immediately before this error in the trace log?

The most common cause of `SQLITE_CANTOPEN` is that the drive the database is on is not connected.

**Comment by robbyxp1** [comment]
Closing, no reply

**Comment by six-shooter** [comment]
I got it to work by deleting some files in appdata and the settings-files.

Sorry for the late response, got caught up in life.
