### ISSUE TITLE
EDDiscovery v11.6.2.0 Fatal Error - An unhandled fatal exception has occurred.

### ISSUE THREAD

**Issue by scottmasterton** [EDDiscovery/EDDiscovery#2916]
An unhandled fatal exception has occurred.

==== BEGIN ====
SQLLiteExtensions.SQLProcessingThreadException: database disk image is malformed
database disk image is malformed ---> System.Data.SQLite.SQLiteException: database disk image is malformed
database disk image is malformed
   at System.Data.SQLite.SQLite3.Reset(SQLiteStatement stmt)
   at System.Data.SQLite.SQLite3.Step(SQLiteStatement stmt)
   at System.Data.SQLite.SQLiteDataReader.Read()
   at EliteDangerousCore.DB.SystemsDB.GetSystemVector[V](Int32 gridid, V[]& vertices1, UInt32[]& colours1, V[]& vertices2, UInt32[]& colours2, Int32 percentage, Func`4 tovect, SQLiteConnectionSystem cn, SystemAskType ask) in C:\Code\EDDiscovery\EliteDangerousCore\EliteDangerous\SystemDB\SystemsDBGetByGrid.cs:line 110
   at EliteDangerousCore.DB.SystemsDB.<>c__DisplayClass37_0`1.<GetSystemVector>b__0(SystemsDatabaseConnection db) in C:\Code\EDDiscovery\EliteDangerousCore\EliteDangerous\SystemDB\SystemsDBGetByGrid.cs:line 54
   at SQLLiteExtensions.SQLProcessingThread`1.<>c__DisplayClass25_0.<ExecuteWithDatabase>b__0() in C:\Code\EDDiscovery\BaseUtilities\SQLLite\SQLLite\SQLProcessingThread.cs:line 255
   at SQLLiteExtensions.SQLProcessingThread`1.Job`1.Exec() in C:\Code\EDDiscovery\BaseUtilities\SQLLite\SQLLite\SQLProcessingThread.cs:line 68
   --- End of inner exception stack trace ---
   at SQLLiteExtensions.SQLProcessingThread`1.Job`1.Wait() in C:\Code\EDDiscovery\BaseUtilities\SQLLite\SQLLite\SQLProcessingThread.cs:line 91
   at SQLLiteExtensions.SQLProcessingThread`1.Execute[T](Func`1 func, Int32 skipframes, Int32 warnthreshold) in C:\Code\EDDiscovery\BaseUtilities\SQLLite\SQLLite\SQLProcessingThread.cs:line 239
   at SQLLiteExtensions.SQLProcessingThread`1.ExecuteWithDatabase(Action`1 action, Int32 warnthreshold) in C:\Code\EDDiscovery\BaseUtilities\SQLLite\SQLLite\SQLProcessingThread.cs:line 256
   at EliteDangerousCore.DB.SystemsDB.GetSystemVector[V](Int32 gridid, V[]& vertices1, UInt32[]& colours1, V[]& vertices2, UInt32[]& colours2, Int32 percentage, Func`4 tovect, SystemAskType ask) in C:\Code\EDDiscovery\EliteDangerousCore\EliteDangerous\SystemDB\SystemsDBGetByGrid.cs:line 56
   at EDDiscovery.StarGrid.FillFromDB() in C:\Code\EDDiscovery\EDDiscovery\3DMap\StarGrid.cs:line 86
   at EDDiscovery.StarGrids.ComputeThread() in C:\Code\EDDiscovery\EDDiscovery\3DMap\StarGrid.cs:line 590
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.ThreadHelper.ThreadStart()
===== END =====

**Comment by scottmasterton** [comment]
After I posted I realised there was a new version which I have now installed, still get the error message and crash.

An unhandled fatal exception has occurred.

==== BEGIN ====
SQLLiteExtensions.SQLProcessingThreadException: database disk image is malformed
database disk image is malformed ---> System.Data.SQLite.SQLiteException: database disk image is malformed
database disk image is malformed
   at System.Data.SQLite.SQLite3.Reset(SQLiteStatement stmt)
   at System.Data.SQLite.SQLite3.Step(SQLiteStatement stmt)
   at System.Data.SQLite.SQLiteDataReader.Read()
   at EliteDangerousCore.DB.SystemsDB.GetSystemVector[V](Int32 gridid, V[]& vertices1, UInt32[]& colours1, V[]& vertices2, UInt32[]& colours2, Int32 percentage, Func`4 tovect, SQLiteConnectionSystem cn, SystemAskType ask) in C:\Code\EDDiscovery\EliteDangerousCore\EliteDangerous\SystemDB\SystemsDBGetByGrid.cs:line 110
   at EliteDangerousCore.DB.SystemsDB.<>c__DisplayClass35_0`1.<GetSystemVector>b__0(SystemsDatabaseConnection db) in C:\Code\EDDiscovery\EliteDangerousCore\EliteDangerous\SystemDB\SystemsDBGetByGrid.cs:line 54
   at SQLLiteExtensions.SQLProcessingThread`1.<>c__DisplayClass25_0.<ExecuteWithDatabase>b__0() in C:\Code\EDDiscovery\BaseUtilities\SQLLite\SQLLite\SQLProcessingThread.cs:line 255
   at SQLLiteExtensions.SQLProcessingThread`1.Job`1.Exec() in C:\Code\EDDiscovery\BaseUtilities\SQLLite\SQLLite\SQLProcessingThread.cs:line 68
   --- End of inner exception stack trace ---
   at SQLLiteExtensions.SQLProcessingThread`1.Job`1.Wait() in C:\Code\EDDiscovery\BaseUtilities\SQLLite\SQLLite\SQLProcessingThread.cs:line 91
   at SQLLiteExtensions.SQLProcessingThread`1.Execute[T](Func`1 func, Int32 skipframes, Int32 warnthreshold) in C:\Code\EDDiscovery\BaseUtilities\SQLLite\SQLLite\SQLProcessingThread.cs:line 239
   at SQLLiteExtensions.SQLProcessingThread`1.ExecuteWithDatabase(Action`1 action, Int32 warnthreshold) in C:\Code\EDDiscovery\BaseUtilities\SQLLite\SQLLite\SQLProcessingThread.cs:line 256
   at EliteDangerousCore.DB.SystemsDB.GetSystemVector[V](Int32 gridid, V[]& vertices1, UInt32[]& colours1, V[]& vertices2, UInt32[]& colours2, Int32 percentage, Func`4 tovect, SystemAskType ask) in C:\Code\EDDiscovery\EliteDangerousCore\EliteDangerous\SystemDB\SystemsDBGetByGrid.cs:line 56
   at EDDiscovery.StarGrid.FillFromDB() in C:\Code\EDDiscovery\EDDiscovery\3DMap\StarGrid.cs:line 86
   at EDDiscovery.StarGrids.ComputeThread() in C:\Code\EDDiscovery\EDDiscovery\3DMap\StarGrid.cs:line 590
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.ThreadHelper.ThreadStart()
===== END =====

**Comment by robbyxp1** [comment]
The system DB has been borked for some reason. Sometimes that happens in the DB system.

The only thing to do is to delete it and let it rebuild.

**Comment by robbyxp1** [comment]
Closing, no more info
