### ISSUE TITLE
unhandled UI exception...?

### ISSUE THREAD

**Issue by englishlies** [EDDiscovery/EDDiscovery#2929]
got this while download 3d There was an unhandled UI exception.

==== BEGIN ====
SQLLiteExtensions.SQLProcessingThreadException: database is locked
database is locked ---> System.Data.SQLite.SQLiteException: database is locked
database is locked
   at System.Data.SQLite.SQLite3.Step(SQLiteStatement stmt)
   at System.Data.SQLite.SQLiteDataReader.NextResult()
   at System.Data.SQLite.SQLiteDataReader..ctor(SQLiteCommand cmd, CommandBehavior behave)
   at System.Data.SQLite.SQLiteCommand.ExecuteReader(CommandBehavior behavior)
   at System.Data.SQLite.SQLiteCommand.ExecuteScalar(CommandBehavior behavior)
   at SQLiteCommandExtensions.ExecuteScalar[T](DbCommand cmd, T def) in C:\Code\EDDiscovery\BaseUtilities\SQLLite\SQLLite\SQLExtensions.cs:line 93
   at EliteDangerousCore.DB.SystemsDB.FindAlias(Int64 edsmid, String name, SQLiteConnectionSystem cn) in C:\Code\EDDiscovery\EliteDangerousCore\EliteDangerous\SystemDB\SystemsDBEDSMSystemAliases.cs:line 153
   at EliteDangerousCore.DB.SystemCache.FindSystem(ISystem find, SystemsDatabaseConnection cn) in C:\Code\EDDiscovery\EliteDangerousCore\EliteDangerous\SystemDB\SystemCache.cs:line 93
   at SQLLiteExtensions.SQLProcessingThread`1.Job`1.Exec() in C:\Code\EDDiscovery\BaseUtilities\SQLLite\SQLLite\SQLProcessingThread.cs:line 68
   --- End of inner exception stack trace ---
   at SQLLiteExtensions.SQLProcessingThread`1.Job`1.Wait() in C:\Code\EDDiscovery\BaseUtilities\SQLLite\SQLLite\SQLProcessingThread.cs:line 91
   at SQLLiteExtensions.SQLProcessingThread`1.Execute[T](Func`1 func, Int32 skipframes, Int32 warnthreshold) in C:\Code\EDDiscovery\BaseUtilities\SQLLite\SQLLite\SQLProcessingThread.cs:line 239
   at SQLLiteExtensions.SQLProcessingThread`1.ExecuteWithDatabase[T](Func`2 func, Int32 warnthreshold) in C:\Code\EDDiscovery\BaseUtilities\SQLLite\SQLLite\SQLProcessingThread.cs:line 260
   at EliteDangerousCore.HistoryList.FindSystem(String name, GalacticMapping glist) in C:\Code\EDDiscovery\EliteDangerousCore\EliteDangerous\HistoryList\HistoryList.cs:line 773
   at EDDiscovery.UserControls.UserControlRoute.UpdateTo(Boolean updatename) in C:\Code\EDDiscovery\EDDiscovery\UserControls\RoutesExpeditions\UserControlRoute.cs:line 524
   at EDDiscovery.UserControls.UserControlRoute.HistoryChanged(HistoryList hl) in C:\Code\EDDiscovery\EDDiscovery\UserControls\RoutesExpeditions\UserControlRoute.cs:line 140
   at System.Action`1.Invoke(T obj)
   at ExtendedControls.ExtComboBox._cbsystem_SelectedIndexChanged(Object sender, EventArgs e) in C:\Code\EDDiscovery\ExtendedControls\ExtendedControls\Controls\ComboBox.cs:line 378
   at System.Windows.Forms.ComboBox.OnSelectedIndexChanged(EventArgs e)
   at System.Windows.Forms.ComboBox.set_SelectedIndex(Int32 value)
   at ExtendedControls.ExtComboBox.customdropdown_SelectedIndexChanged(Object sender, EventArgs e) in C:\Code\EDDiscovery\ExtendedControls\ExtendedControls\Controls\ComboBox.cs:line 350
   at ExtendedControls.ExtListBoxForm.listcontrol_SelectedIndexChanged(Object sender, EventArgs e) in C:\Code\EDDiscovery\ExtendedControls\ExtendedControls\Forms\ListBoxForm.cs:line 113
   at ExtendedControls.ExtListBox.OnMouseClick(MouseEventArgs e) in C:\Code\EDDiscovery\ExtendedControls\ExtendedControls\Controls\ListBox.cs:line 366
   at System.Windows.Forms.Control.WmMouseUp(Message& m, MouseButtons button, Int32 clicks)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)
===== END =====map of bubble and sole. not sure what it is or what it means.

**Comment by robbyxp1** [comment]
It happens sometimes, the DB being locked. If its not happening again, ignore it.
