### ISSUE TITLE
Unhandled fatal exception on startup

### ISSUE THREAD

**Issue by CommanderPuggle** [EDDiscovery/EDDiscovery#2946]
An unhandled fatal exception has occurred.

==== BEGIN ====
code = CantOpen (14), message = System.Data.SQLite.SQLiteException (0x800007FF): unable to open database file
   at System.Data.SQLite.SQLite3.Open(String strFilename, String vfsName, SQLiteConnectionFlags connectionFlags, SQLiteOpenFlagsEnum openFlags, Int32 maxPoolSize, Boolean usePool)
   at System.Data.SQLite.SQLiteConnection.Open()
   at SQLLiteExtensions.SQLExtConnectionRegister`1..ctor(String dbfile, Boolean utctimeindicator, AccessMode mode) in C:\Code\EDDiscovery\BaseUtilities\SQLLite\SQLLite\SQLConnectionRegister.cs:line 53
   at EliteDangerousCore.DB.SystemsDatabaseConnection..ctor(Boolean ro) in C:\Code\EDDiscovery\EliteDangerousCore\EliteDangerous\SystemDB\SystemsDatabase.cs:line 17
   at EliteDangerousCore.DB.SystemsDatabase.CreateConnection() in C:\Code\EDDiscovery\EliteDangerousCore\EliteDangerous\SystemDB\SystemsDatabase.cs:line 55
   at SQLLiteExtensions.SQLProcessingThread`1.SqlThreadProc() in C:\Code\EDDiscovery\BaseUtilities\SQLLite\SQLLite\SQLProcessingThread.cs:line 141
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.ThreadHelper.ThreadStart()
===== END =====

**Comment by robbyxp1** [comment]
This can happen for lots of reasons, most of them external to EDD. is it always occurring?

**Comment by klightspeed** [comment]
Perhaps we could add a couple of options to help diagnose this sort of thing:
* Before the database file is opened, log the database filename being opened
* When initialising the options, check whether the configured database path exists, and if it does not then warn the user (giving the option to either abort or reset the database path to the default).
* Wrap the open in the constructor, and (since there's not much we can do) wrap the exception with more information (including what the configured database path is).

**Comment by CommanderPuggle** [comment]
> This can happen for lots of reasons, most of them external to EDD. is it always occurring?

It cropped up in the last day (after about a solid two weeks since installing and running EDD without any issue. I haven't made any changes to hardware or software -- play Elite several hours a week. Prior to posting this, spent 30 minutes trying to figure out what had happened. Uninstalled and reinstalled the application to no avail, suggesting this database is in my local files (which, despite my best efforts, I couldn't locate on my hard drive -- I'm either looking in the wrong place and/or I can't decipher EDD's file naming scheme). I agree with @klightspeed's comment that it would help enormously if the bug reporter told me the filename of the database and or give some kind of reset/repair option.

**Comment by klightspeed** [comment]
The reset option is presented when you hold shift while starting EDDiscovery.

By default the databases are stored in `%LOCALAPPDATA%\EDDiscovery`.

Note that re-installing will not reset the database paths if configured (in `%LOCALAPPDATA%\EDDiscovery\dboptions.txt`), and will not delete any data in `%LOCALAPPDATA%\EDDiscovery`.

**Comment by CommanderPuggle** [comment]
> The reset option is presented when you hold shift while starting EDDiscovery.
> 
> By default the databases are stored in `%LOCALAPPDATA%\EDDiscovery`.
> 
> Note that re-installing will not reset the database paths if configured (in `%LOCALAPPDATA%\EDDiscovery\dboptions.txt`), and will not delete any data in `%LOCALAPPDATA%\EDDiscovery`.

What would a possible fix be to uninstall, locate and delete the database and start fresh? I have nothing saved in the app that I would lose sleep losing.

**Comment by klightspeed** [comment]
An uninstall is not necessary before nuking the DB.  If you really want to blow everything away, then just delete (or rename) the `EDDiscovery` directory in `%LOCALAPPDATA%`.  Make sure that you still have all of your journals if you don't want to lose that history.

**Comment by CommanderPuggle** [comment]
good to know! Thank you. Yes, my journals are safe (in my ED local files).

**Comment by robbyxp1** [comment]
We are going to add more warnings, thanks for the report.
