### ISSUE TITLE
Umhandled UI Exceptiom

### ISSUE THREAD

**Issue by Wombat1501** [EDDiscovery/EDDiscovery#2948]
here was an unhandled UI exception.

```
==== BEGIN ====
System.NullReferenceException: Object reference not set to an instance of an object.
   at EDDiscovery.UserControls.UserControlScan.Closing() in C:\Code\EDDiscovery\EDDiscovery\UserControls\ScansStars\UserControlScan.cs:line 112
   at EDDiscovery.UserControls.UserControlCommonBase.CloseDown() in C:\Code\EDDiscovery\EDDiscovery\UserControls\UserControlCommonBase.cs:line 88
   at EDDiscovery.Forms.UserControlForm.UserControlForm_FormClosing(Object sender, FormClosingEventArgs e) in C:\Code\EDDiscovery\EDDiscovery\Forms\UserControlForm.cs:line 307
   at System.Windows.Forms.Form.OnFormClosing(FormClosingEventArgs e)
   at EDDiscovery.Forms.UserControlForm.OnFormClosing(FormClosingEventArgs e) in C:\Code\EDDiscovery\EDDiscovery\Forms\UserControlForm.cs:line 299
   at System.Windows.Forms.Form.WmClose(Message& m)
   at ExtendedControls.SmartSysMenuForm.WndProc(Message& m) in C:\Code\EDDiscovery\ExtendedControls\ExtendedControls\Forms\SmartSysMenuForm.cs:line 224
   at ExtendedControls.DraggableForm.WndProc(Message& m) in C:\Code\EDDiscovery\ExtendedControls\ExtendedControls\Forms\DraggableForm.cs:line 318
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)
===== END =====
```

**Comment by klightspeed** [comment]
Could you please give more information on:
* What version of EDDiscovery you are running
* What OS are you running on
* What you were doing when this occurred

The only way I can see that this might have occurred is if the popout were closed before it was shown.

**Comment by Wombat1501** [comment]
Version 11.7.5.0
Windows 10
Supercruising between Planets
Popout was enabled and DID NOT close, even after error.

________________________________

**Comment by klightspeed** [comment]
The popout that threw the Null Reference Exception was a Scan panel.

Do you have any triggers set up to open the scan panel when you go into the System panel in-game, and close it when you exit the System panel?  I wonder if such a trigger could have caused this by creating the popout then before it was shown closing it?

**Comment by robbyxp1** [comment]
Closing, no more info. Likely just a random instance of it.
