### ISSUE TITLE
EDDiscovery Reporting no access to user db

### ISSUE THREAD

**Issue by HughBourbaki** [EDDiscovery/EDDiscovery#2951]
An unhandled fatal exception has occurred.

==== BEGIN ====
SQLLiteExtensions.SQLProcessingThreadException: database or disk is full
database or disk is full ---> System.Data.SQLite.SQLiteException: database or disk is full
database or disk is full
   at System.Data.SQLite.SQLite3.Reset(SQLiteStatement stmt)
   at System.Data.SQLite.SQLite3.Step(SQLiteStatement stmt)
   at System.Data.SQLite.SQLiteDataReader.NextResult()
   at System.Data.SQLite.SQLiteDataReader..ctor(SQLiteCommand cmd, CommandBehavior behave)
   at System.Data.SQLite.SQLiteCommand.ExecuteReader(CommandBehavior behavior)
   at System.Data.SQLite.SQLiteCommand.ExecuteNonQuery(CommandBehavior behavior)
   at EliteDangerousCore.JournalEntry.Add(JObject jo, SQLiteConnectionUser cn, DbTransaction tn) in C:\Code\EDDiscovery\EliteDangerousCore\EliteDangerous\Journal\JournalEntryDB.cs:line 72
   at EliteDangerousCore.JournalMonitorWatcher.<>c__DisplayClass16_0.<ScanReader>b__0(UserDatabaseConnection cn) in C:\Code\EDDiscovery\EliteDangerousCore\EliteDangerous\Journal\EDJournalMonitorWatcher.cs:line 191
   at SQLLiteExtensions.SQLProcessingThread`1.<>c__DisplayClass25_0.<ExecuteWithDatabase>b__0() in C:\Code\EDDiscovery\BaseUtilities\SQLLite\SQLLite\SQLProcessingThread.cs:line 255
   at SQLLiteExtensions.SQLProcessingThread`1.Job`1.Exec() in C:\Code\EDDiscovery\BaseUtilities\SQLLite\SQLLite\SQLProcessingThread.cs:line 68
   --- End of inner exception stack trace ---
   at SQLLiteExtensions.SQLProcessingThread`1.Job`1.Wait() in C:\Code\EDDiscovery\BaseUtilities\SQLLite\SQLLite\SQLProcessingThread.cs:line 91
   at SQLLiteExtensions.SQLProcessingThread`1.Execute[T](Func`1 func, Int32 skipframes, Int32 warnthreshold) in C:\Code\EDDiscovery\BaseUtilities\SQLLite\SQLLite\SQLProcessingThread.cs:line 239
   at SQLLiteExtensions.SQLProcessingThread`1.ExecuteWithDatabase(Action`1 action, Int32 warnthreshold) in C:\Code\EDDiscovery\BaseUtilities\SQLLite\SQLLite\SQLProcessingThread.cs:line 256
   at EliteDangerousCore.JournalMonitorWatcher.ScanForNewEntries() in C:\Code\EDDiscovery\EliteDangerousCore\EliteDangerous\Journal\EDJournalMonitorWatcher.cs:line 116
   at EliteDangerousCore.EDJournalUIScanner.ScanTickWorker(Func`1 stopRequested) in C:\Code\EDDiscovery\EliteDangerousCore\EliteDangerous\Journal\EDScanner.cs:line 151
   at EliteDangerousCore.EDJournalUIScanner.ScanThreadProc() in C:\Code\EDDiscovery\EliteDangerousCore\EliteDangerous\Journal\EDScanner.cs:line 0
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.ThreadHelper.ThreadStart()
===== END =====

**Comment by robbyxp1** [comment]
Check your disk location of EDDUser is still accessible, check your disk space, etc.

This is due to an external interaction with the windows system and not EDD directly.

**Comment by robbyxp1** [comment]
closing as no further response.
