### ISSUE TITLE
An unhandled fatal exception has occurred due to window handle

### ISSUE THREAD

**Issue by bob522t** [EDDiscovery/EDDiscovery#2953]
An unhandled fatal exception has occurred.

==== BEGIN ====
System.InvalidOperationException: Invoke or BeginInvoke cannot be called on a control until the window handle has been created.
   at System.Windows.Forms.Control.MarshaledInvoke(Control caller, Delegate method, Object[] args, Boolean synchronous)
   at System.Windows.Forms.Control.BeginInvoke(Delegate method, Object[] args)
   at DirectInputDevices.InputDeviceList.waitthread() in C:\Code\EDDiscovery\BaseUtilities\DirectInput\InputDeviceList.cs:line 122
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.ThreadHelper.ThreadStart()
===== END =====

**Comment by ruicabanita** [comment]
An unhandled fatal exception has occurred.

==== BEGIN ====
SQLLiteExtensions.SQLProcessingThreadException: disk I/O error
disk I/O error ---> System.Data.SQLite.SQLiteException: disk I/O error
disk I/O error
   at System.Data.SQLite.SQLite3.Reset(SQLiteStatement stmt)
   at System.Data.SQLite.SQLite3.Step(SQLiteStatement stmt)
   at System.Data.SQLite.SQLiteDataReader.NextResult()
   at System.Data.SQLite.SQLiteDataReader..ctor(SQLiteCommand cmd, CommandBehavior behave)
   at System.Data.SQLite.SQLiteCommand.ExecuteReader(CommandBehavior behavior)
   at System.Data.SQLite.SQLiteCommand.ExecuteNonQuery(CommandBehavior behavior)
   at EliteDangerousCore.JournalEntry.Add(JObject jo, SQLiteConnectionUser cn, DbTransaction tn) in C:\Code\EDDiscovery\EliteDangerousCore\EliteDangerous\Journal\JournalEntryDB.cs:line 72
   at EliteDangerousCore.JournalMonitorWatcher.<>c__DisplayClass16_0.<ScanReader>b__0(UserDatabaseConnection cn) in C:\Code\EDDiscovery\EliteDangerousCore\EliteDangerous\Journal\EDJournalMonitorWatcher.cs:line 191
   at SQLLiteExtensions.SQLProcessingThread`1.<>c__DisplayClass25_0.<ExecuteWithDatabase>b__0() in C:\Code\EDDiscovery\BaseUtilities\SQLLite\SQLLite\SQLProcessingThread.cs:line 255
   at SQLLiteExtensions.SQLProcessingThread`1.Job`1.Exec() in C:\Code\EDDiscovery\BaseUtilities\SQLLite\SQLLite\SQLProcessingThread.cs:line 68
   --- End of inner exception stack trace ---
   at SQLLiteExtensions.SQLProcessingThread`1.Job`1.Wait() in C:\Code\EDDiscovery\BaseUtilities\SQLLite\SQLLite\SQLProcessingThread.cs:line 91
   at SQLLiteExtensions.SQLProcessingThread`1.Execute[T](Func`1 func, Int32 skipframes, Int32 warnthreshold) in C:\Code\EDDiscovery\BaseUtilities\SQLLite\SQLLite\SQLProcessingThread.cs:line 239
   at SQLLiteExtensions.SQLProcessingThread`1.ExecuteWithDatabase(Action`1 action, Int32 warnthreshold) in C:\Code\EDDiscovery\BaseUtilities\SQLLite\SQLLite\SQLProcessingThread.cs:line 256
   at EliteDangerousCore.JournalMonitorWatcher.ScanForNewEntries() in C:\Code\EDDiscovery\EliteDangerousCore\EliteDangerous\Journal\EDJournalMonitorWatcher.cs:line 116
   at EliteDangerousCore.EDJournalUIScanner.ScanTickWorker(Func`1 stopRequested) in C:\Code\EDDiscovery\EliteDangerousCore\EliteDangerous\Journal\EDScanner.cs:line 151
   at EliteDangerousCore.EDJournalUIScanner.ScanThreadProc() in C:\Code\EDDiscovery\EliteDangerousCore\EliteDangerous\Journal\EDScanner.cs:line 0
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.ThreadHelper.ThreadStart()
===== END =====

**Comment by robbyxp1** [comment]
The above one is due to your SQLITE DB not being accessible by EDD - have you got it in a non standard place? is your disk full?

**Comment by robbyxp1** [comment]
The first one is probably just a random c# winforms issue, which should not repeat. It just sometimes happens that c# winforms does not shut down or start up in a good order.

**Comment by robbyxp1** [comment]
Closing, no more info, noted the first error.
