### ISSUE TITLE
System.InvalidOperationException: SplitterDistance must be between Panel1MinSize and Width - Panel2MinSize.

### ISSUE THREAD

**Issue by Catreina** [EDDiscovery/EDDiscovery#2954]
This is in v11.8.1.0 - fresh install.

There was an unhandled UI exception.

==== BEGIN ====
System.InvalidOperationException: SplitterDistance must be between Panel1MinSize and Width - Panel2MinSize.
   at System.Windows.Forms.SplitContainer.set_SplitterDistance(Int32 value)
   at System.Windows.Forms.SplitContainer.set_Orientation(Orientation value)
   at EDDiscovery.UserControls.UserControlShoppingList.InitialDisplay() in C:\Code\EDDiscovery\EDDiscovery\UserControls\EngineeringSynthesis\UserControlShoppingList.cs:line 148
   at EDDiscovery.Forms.UserControlForm.UserControlForm_Shown(Object sender, EventArgs e) in C:\Code\EDDiscovery\EDDiscovery\Forms\UserControlForm.cs:line 297
   at System.Windows.Forms.Form.OnShown(EventArgs e)
   at System.Windows.Forms.Control.InvokeMarshaledCallbackHelper(Object obj)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Windows.Forms.Control.InvokeMarshaledCallback(ThreadMethodEntry tme)
   at System.Windows.Forms.Control.InvokeMarshaledCallbacks()
===== END =====

**Comment by Catreina** [comment]
Windows 10 64
Upon opening EDD - with two popouts (Summary on right of primary monitor, purchase list on left)
Closing one or both popouts resolves issue

**Comment by robbyxp1** [comment]
Fixed on tip, thanks for the report. Next version will be soon.
