### ISSUE TITLE
error in log on startup

### ISSUE THREAD

**Issue by batkung** [EDDiscovery/EDDiscovery#2957]
just updated to 11.9.0.0 and now I get this on launch.

History Refresh Error: System.NullReferenceException: Object reference not set to an instance of an object.
   at EliteDangerousCore.MaterialCommoditiesList..ctor(MaterialCommoditiesList other) in C:\Code\EDDiscovery\EliteDangerousCore\EliteDangerous\MaterialsCommodities\MaterialCommoditiesList.cs:line 54
   at EliteDangerousCore.MaterialCommoditiesList.Process(JournalEntry je, MaterialCommoditiesList oldml) in C:\Code\EDDiscovery\EliteDangerousCore\EliteDangerous\MaterialsCommodities\MaterialCommoditiesList.cs:line 208
   at EliteDangerousCore.HistoryList.LoadHistory(EDJournalUIScanner journalmonitor, Func`1 cancelRequested, Action`2 reportProgress, String NetLogPath, Boolean ForceNetLogReload, Boolean ForceJournalReload, Int32 CurrentCommander, Int32 fullhistoryloaddaylimit, String essentialitems) in C:\Code\EDDiscovery\EliteDangerousCore\EliteDangerous\HistoryList\HistoryList.cs:line 1073
   at EDDiscovery.EDDiscoveryController.DoRefreshHistory(RefreshWorkerArgs args) in C:\Code\EDDiscovery\EDDiscovery\EDDiscoveryControllerHistory.cs:line 154

**Comment by rmiesen** [comment]
I also get this error.

**Comment by robbyxp1** [comment]
Will be fixed tomorrow. in the meanwhile, go back to 11.8.x
