### ISSUE TITLE
Null reference exception during history refresh after upgrading to 11.9.3.0

### ISSUE THREAD

**Issue by xenophonf** [EDDiscovery/EDDiscovery#2964]
When starting EDDiscovery, I get the following error even after deleting the EDSystems database:

```
History Refresh Error: System.NullReferenceException: Object reference not set to an instance of an object.
   at EliteDangerousCore.HistoryEntryStatus.Update(HistoryEntryStatus prev, JournalEntry je, String curStarSystem) in C:\Code\EDDiscovery\EliteDangerousCore\EliteDangerous\HistoryList\HistoryEntryStatus.cs:line 124
   at EliteDangerousCore.HistoryEntry.FromJournalEntry(JournalEntry je, HistoryEntry prev, Boolean checkdbforunknownsystem, Boolean& journalupdate) in C:\Code\EDDiscovery\EliteDangerousCore\EliteDangerous\HistoryList\HistoryEntry.cs:line 237
   at EliteDangerousCore.HistoryList.LoadHistory(EDJournalUIScanner journalmonitor, Func`1 cancelRequested, Action`2 reportProgress, String NetLogPath, Boolean ForceNetLogReload, Boolean ForceJournalReload, Int32 CurrentCommander, Int32 fullhistoryloaddaylimit, String essentialitems) in C:\Code\EDDiscovery\EliteDangerousCore\EliteDangerous\HistoryList\HistoryList.cs:line 1063
   at EDDiscovery.EDDiscoveryController.DoRefreshHistory(RefreshWorkerArgs args) in C:\Code\EDDiscovery\EDDiscovery\EDDiscoveryControllerHistory.cs:line 154
```

I tried safe mode, reset the UI, and deleted the systems database as a precaution.

Strangely, re-installing EDDiscovery seems to fix this problem.

**Comment by robbyxp1** [comment]
Probably the DB was borked.  Will keep it in mind, thanks.
