### ISSUE TITLE
History refresh error

### ISSUE THREAD

**Issue by Vana987** [EDDiscovery/EDDiscovery#3002]
Updated Eddiscovery  11.10.1  with the new version, but it looks like the new version is not loading all my journals. it gives me a fixed system location that is not possible to update. I don;t find the way to fix it.

I had Eddiscovery 11.9.3, and everything was working fine. I will reinstall the old version.

here is a paste of my Eddiscovery log:

History refresh complete.
History Refresh Error: SQLLiteExtensions.SQLProcessingThreadException: Index was outside the bounds of the array. ---> System.IndexOutOfRangeException: Index was outside the bounds of the array.
   at EliteDangerousCore.JournalEvents.JournalFSSSignalDiscovered.FSSSignal..ctor(JObject evt, DateTime EventTimeUTC) in C:\Code\EDDiscovery\EliteDangerousCore\EliteDangerous\JournalEvents\JournalDiscoveryScans.cs:line 92
   at EliteDangerousCore.JournalEvents.JournalFSSSignalDiscovered..ctor(JObject evt) in C:\Code\EDDiscovery\EliteDangerousCore\EliteDangerous\JournalEvents\JournalDiscoveryScans.cs:line 187
   at lambda_method(Closure , Object[] )
   at EliteDangerousCore.JournalEntry.CreateJournalEntry(String text, Boolean savejson, Boolean returnnullifbadjson) in C:\Code\EDDiscovery\EliteDangerousCore\EliteDangerous\Journal\JournalEntry.cs:line 237
   at EliteDangerousCore.JournalEntry.CreateJournalEntry(DbDataReader dr) in C:\Code\EDDiscovery\EliteDangerousCore\EliteDangerous\Journal\JournalEntryDB.cs:line 37
   at EliteDangerousCore.JournalEntry.GetAllByTLU(Int64 tluid, SQLiteConnectionUser cn) in C:\Code\EDDiscovery\EliteDangerousCore\EliteDangerous\Journal\JournalEntryDB.cs:line 564
   at EliteDangerousCore.JournalMonitorWatcher.<>c__DisplayClass18_0.<ProcessDetectedNewFiles>b__0(UserDatabaseConnection cn) in C:\Code\EDDiscovery\EliteDangerousCore\EliteDangerous\Journal\EDJournalMonitorWatcher.cs:line 318
   at SQLLiteExtensions.SQLProcessingThread`1.<>c__DisplayClass25_0.<ExecuteWithDatabase>b__0() in C:\Code\EDDiscovery\BaseUtilities\SQLLite\SQLLite\SQLProcessingThread.cs:line 255
   at SQLLiteExtensions.SQLProcessingThread`1.Job`1.Exec() in C:\Code\EDDiscovery\BaseUtilities\SQLLite\SQLLite\SQLProcessingThread.cs:line 68
   --- End of inner exception stack trace ---
   at SQLLiteExtensions.SQLProcessingThread`1.Job`1.Wait() in C:\Code\EDDiscovery\BaseUtilities\SQLLite\SQLLite\SQLProcessingThread.cs:line 91
   at SQLLiteExtensions.SQLProcessingThread`1.Execute[T](Func`1 func, Int32 skipframes, Int32 warnthreshold) in C:\Code\EDDiscovery\BaseUtilities\SQLLite\SQLLite\SQLProcessingThread.cs:line 239
   at SQLLiteExtensions.SQLProcessingThread`1.ExecuteWithDatabase(Action`1 action, Int32 warnthreshold) in C:\Code\EDDiscovery\BaseUtilities\SQLLite\SQLLite\SQLProcessingThread.cs:line 256
   at EliteDangerousCore.JournalMonitorWatcher.ProcessDetectedNewFiles(List`1 readersToUpdate, Action`2 updateProgress, Action`5 fireback, Int32 firebacklastn) in C:\Code\EDDiscovery\EliteDangerousCore\EliteDangerous\Journal\EDJournalMonitorWatcher.cs:line 315
   at EliteDangerousCore.EDJournalUIScanner.ParseJournalFilesOnWatchers(Action`2 updateProgress, Int32 reloadlastn, Action`5 firebacknostore, Int32 firebacklastn) in C:\Code\EDDiscovery\EliteDangerousCore\EliteDangerous\Journal\EDScanner.cs:line 311
   at EDDiscovery.EDDiscoveryController.DoRefreshHistory(RefreshWorkerArgs args) in C:\Code\EDDiscovery\EDDiscovery\EDDiscoveryControllerHistory.cs:line 163
History refresh complete.

**Comment by klightspeed** [comment]
https://github.com/EDDiscovery/EliteDangerousCore/blob/853c451a0b1efb34063af9e0a55f28d66733cde1/EliteDangerous/JournalEvents/JournalDiscoveryScans.cs#L117
```c#
                    int dash = SignalName.LastIndexOf('-');
                    if (dash == SignalName.Length - 4 && char.IsLetterOrDigit(SignalName[dash + 1]) && char.IsLetterOrDigit(SignalName[dash - 1]))
```

This will fail if the signal name is 3 characters long

**Comment by robbyxp1** [comment]
Darn,.

**Comment by robbyxp1** [comment]
A signal name starting with a dash with only one dash in it!

**Comment by robbyxp1** [comment]
or maybe other combos, anyway, it needs protecting

**Comment by robbyxp1** [comment]
I pushed a fix to this

Thanks for the report. New version tomorrow.

**Comment by klightspeed** [comment]
It would be SVP in the Andancan system
https://www.edsm.net/en/system/stations/id/8693/name/Andancan/details/idS/1495/nameS/SVP

**Comment by Vana987** [comment]
thank you guys
