### ISSUE TITLE
Fatal Error at launch

### ISSUE THREAD

**Issue by Stanissslav** [EDDiscovery/EDDiscovery#3019]
An unhandled fatal exception has occurred.

==== BEGIN ====
System.AccessViolationException: Attempted to read or write protected memory. This is often an indication that other memory is corrupt.
   at System.Speech.Internal.ObjectTokens.ObjectToken.ISpObjectWithToken.SetObjectToken(ISpObjectToken pToken)
   at System.Speech.Internal.ObjectTokens.ObjectToken.CreateObjectFromToken[T](String name)
   at System.Speech.Internal.Synthesis.VoiceSynthesis.GetComEngine(VoiceInfo voiceInfo)
   at System.Speech.Internal.Synthesis.VoiceSynthesis.GetProxyEngine(VoiceInfo voiceInfo)
   at System.Speech.Internal.Synthesis.VoiceSynthesis.ThreadProc()
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.ThreadHelper.ThreadStart()
===== END =====

**Comment by robbyxp1** [comment]
Does this occur all the time?  This may be just a think that just happens..  This bug is inside window system itself, not the program.

**Comment by klightspeed** [comment]
Broken speech system, or some speech occurring too early?

The only non-junk reference I can find is https://stackoverflow.com/questions/16057044/access-violation-exception-in-system-speech-synthesis, where it looks like speech would have been produced after the speech engine was disposed.

**Comment by Stanissslav** [comment]
> Does this occur all the time? This may be just a think that just happens.. This bug is inside window system itself, not the program.

Yes, all the time. and yes it's look like a bug inside windows.


> Broken speech system, or some speech occurring too early?
> 
> The only non-junk reference I can find is https://stackoverflow.com/questions/16057044/access-violation-exception-in-system-speech-synthesis, where it looks like speech would have been produced after the speech engine was disposed.

I will try to reinstall\repair speech engine

**Comment by robbyxp1** [comment]
Try another SAPI voice btw if your using a non microsoft one.  It may be the SAPI voice (a wild guess).

To do this, I'd go into %localappdata%\eddiscovery\actions and delete all action packs, or use safe mode (hold down shift and launch it) and delete the action packs. Then see if it starts up okay.  

Go into addon's - edit add ons - globals and delete the SpeechVoice variable that may be in there.

hit the windows key, type "text to speech" to go to the change speech settings dialog.  Check that voices work and select a default.

reinstall the voice pack and see what happens.

**Comment by Stanissslav** [comment]
Ok...issue was solved...in a strange way...
I just connect microphone and turn speech recognition "on"... (i can't turn it on without microphone connected - thats wierd...but it's Windows bug)

**Comment by klightspeed** [comment]
So speech _synthesis_ was crashing when speech _recognition_ was disabled?

**Comment by Stanissslav** [comment]
It looks like that...strange way, isn't it?

**Comment by robbyxp1** [comment]
okay, so its a windows thing. closing.
