### ISSUE TITLE
SQLite Based -  database disk image is malformed Error

### ISSUE THREAD

**Issue by tgaitskell** [EDDiscovery/EDDiscovery#3020]
Hi There,
This issue with EDDiscovery flagged up whilst playing last night. I haven't been able to get it running since, on any version of EDD, same error message. Please help! Message below:

An unhandled fatal exception has occurred.

==== BEGIN ====
SQLLiteExtensions.SQLProcessingThreadException: database disk image is malformed
database disk image is malformed ---> System.Data.SQLite.SQLiteException: database disk image is malformed
database disk image is malformed
   at System.Data.SQLite.SQLite3.Reset(SQLiteStatement stmt)
   at System.Data.SQLite.SQLite3.Step(SQLiteStatement stmt)
   at System.Data.SQLite.SQLiteDataReader.NextResult()
   at System.Data.SQLite.SQLiteDataReader..ctor(SQLiteCommand cmd, CommandBehavior behave)
   at System.Data.SQLite.SQLiteCommand.ExecuteReader(CommandBehavior behavior)
   at EliteDangerousCore.DB.SystemsDB.GetSystemListBySqDistancesFrom(SortedListDoubleDuplicate`1 distlist, Double x, Double y, Double z, Int32 maxitems, Double mindist, Double maxdist, Boolean spherical, SQLiteConnectionSystem cn, Action`1 LookedUp) in C:\Code\EDDiscovery\EliteDangerousCore\EliteDangerous\SystemDB\SystemsDBGetByDistance.cs:line 80
   at EliteDangerousCore.DB.SystemCache.GetSystemListBySqDistancesFrom(SortedListDoubleDuplicate`1 distlist, Double x, Double y, Double z, Int32 maxitems, Double mindist, Double maxdist, Boolean spherical, SystemsDatabaseConnection cn) in C:\Code\EDDiscovery\EliteDangerousCore\EliteDangerous\SystemDB\SystemCache.cs:line 252
   at EliteDangerousCore.DB.SystemCache.<>c__DisplayClass10_0.<GetSystemListBySqDistancesFrom>b__0(SystemsDatabaseConnection conn) in C:\Code\EDDiscovery\EliteDangerousCore\EliteDangerous\SystemDB\SystemCache.cs:line 243
   at SQLLiteExtensions.SQLProcessingThread`1.<>c__DisplayClass25_0.<ExecuteWithDatabase>b__0() in C:\Code\EDDiscovery\BaseUtilities\SQLLite\SQLLite\SQLProcessingThread.cs:line 255
   at SQLLiteExtensions.SQLProcessingThread`1.Job`1.Exec() in C:\Code\EDDiscovery\BaseUtilities\SQLLite\SQLLite\SQLProcessingThread.cs:line 68
   --- End of inner exception stack trace ---
   at SQLLiteExtensions.SQLProcessingThread`1.Job`1.Wait() in C:\Code\EDDiscovery\BaseUtilities\SQLLite\SQLLite\SQLProcessingThread.cs:line 91
   at SQLLiteExtensions.SQLProcessingThread`1.Execute[T](Func`1 func, Int32 skipframes, Int32 warnthreshold) in C:\Code\EDDiscovery\BaseUtilities\SQLLite\SQLLite\SQLProcessingThread.cs:line 239
   at SQLLiteExtensions.SQLProcessingThread`1.ExecuteWithDatabase(Action`1 action, Int32 warnthreshold) in C:\Code\EDDiscovery\BaseUtilities\SQLLite\SQLLite\SQLProcessingThread.cs:line 256
   at EliteDangerousCore.DB.SystemCache.GetSystemListBySqDistancesFrom(SortedListDoubleDuplicate`1 distlist, Double x, Double y, Double z, Int32 maxitems, Double mindist, Double maxdist, Boolean spherical) in C:\Code\EDDiscovery\EliteDangerousCore\EliteDangerous\SystemDB\SystemCache.cs:line 245
   at EliteDangerousCore.StarDistanceComputer.BackgroundStardistWorkerThread() in C:\Code\EDDiscovery\EliteDangerousCore\EliteDangerous\EliteDangerous\StarDistanceComputer.cs:line 101
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.ThreadHelper.ThreadStart()
===== END =====

**Comment by robbyxp1** [comment]
Delete the system DB and let it rebuild - hold down shift, run EDD, safe mode form, click delete/rebuild system db.

Your system DB is corrupted, did you have a power outage or another event which meant EDD did not shut down properly?

**Comment by tgaitskell** [comment]
Crikey, Rob! Ninja-like efficiency, good sir!

Many thanks, that appears to have fixed the issue. Databases updating now.

I'm playing ED & running EDD using a a phone Wifi hotspot in a remote location. I can only imagine that had something to do with it.

**Comment by robbyxp1** [comment]
No problem, just happened to be at my desk.

We get these reports frequently - I think SQLLite has a tendency to trash the DB I think if you don't tenderly shut it down.  

Closing.  thanks for the report.
