### ISSUE TITLE
Unhandled fatal exception when closing EDDiscovery v11.10.3.0

### ISSUE THREAD

**Issue by xenophonf** [EDDiscovery/EDDiscovery#3024]
When running it, EDDiscovery never showed my log entries.  After I closed it, I got the following error:

```
An unhandled fatal exception has occurred.

==== BEGIN ====
System.ObjectDisposedException: Cannot access a disposed object.
Object name: 'EDDiscoveryForm'.
   at System.Windows.Forms.Control.MarshaledInvoke(Control caller, Delegate method, Object[] args, Boolean synchronous)
   at System.Windows.Forms.Control.Invoke(Delegate method, Object[] args)
   at BaseUtils.Threads.TaskQueue.ProcessQueuedItems(Object ignored) in C:\Code\Examples\EDDiscovery\BaseUtilities\BaseUtilities\Threads\TaskQueue.cs:line 62
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.QueueUserWorkItemCallback.System.Threading.IThreadPoolWorkItem.ExecuteWorkItem()
   at System.Threading.ThreadPoolWorkQueue.Dispatch()
===== END =====
```

**Comment by xenophonf** [comment]
After restarting EDDiscovery, I got the following error:

```
There was an unhandled UI exception.

==== BEGIN ====
System.NullReferenceException: Object reference not set to an instance of an object.
   at EliteDangerousCore.DLL.EDDDLLCallerHE.CreateFromHistoryEntry(HistoryList hl, HistoryEntry he, Boolean storedflag) in C:\Code\Examples\EDDiscovery\EliteDangerousCore\EliteDangerous\DLL\EDDDLLHistoryEntry.cs:line 32
   at EDDiscovery.EDDiscoveryForm.Controller_RefreshComplete() in C:\Code\Examples\EDDiscovery\EDDiscovery\EDDiscoveryForm.cs:line 799
   at EDDiscovery.EDDiscoveryController.ForegroundHistoryRefreshCompleteonUI(HistoryList hist) in C:\Code\Examples\EDDiscovery\EDDiscovery\EDDiscoveryControllerHistory.cs:line 229
===== END =====
```

In the log window, I saw the following:

```
****
ChatConsole ready!
****
OBS Pack Installed, Files will be written to C:\Users\xenophonf\Documents\Frontier Developments\Elite Dangerous\On-screen Display for OBS Studio

Voice Pack installed, running on EDD Version 11.10.3.0
Scanning for bmp screenshots in C:\Users\xenophonf\Pictures\Frontier Developments\Elite Dangerous
*** Web server is disabled ***
Loaded Notes, Bookmarks and Galactic mapping.
Reading travel history
DLLs loaded: EDMCHarness
Profile Default Loaded
Loaded Bindings C:\Users\xenophonf\AppData\Local\Frontier Developments\Elite Dangerous\Options\Bindings\Angular Flight Standard Pro.3.0.binds
History Refresh Error: System.TypeInitializationException: The type initializer for 'EliteDangerousCore.ShipModuleData' threw an exception. ---> System.InvalidProgramException: Common Language Runtime detected an invalid program.
   at EliteDangerousCore.ShipModuleData..cctor()
   --- End of inner exception stack trace ---
   at EliteDangerousCore.ShipModuleData.get_Instance() in C:\Code\Examples\EDDiscovery\EliteDangerousCore\EliteDangerous\Ships\ShipModuleData.cs:line 37
   at EliteDangerousCore.JournalFieldNaming.GetBetterItemName(String s) in C:\Code\Examples\EDDiscovery\EliteDangerousCore\EliteDangerous\EliteDangerous\JournalFieldNaming.cs:line 114
   at EliteDangerousCore.JournalEvents.JournalModuleInfo.Rescan(JObject evt) in C:\Code\Examples\EDDiscovery\EliteDangerousCore\EliteDangerous\JournalEvents\JournalModules.cs:line 530
   at EliteDangerousCore.JournalEvents.JournalModuleInfo.ReadAdditionalFiles(String directory, Boolean historyrefreshparse) in C:\Code\Examples\EDDiscovery\EliteDangerousCore\EliteDangerous\JournalEvents\JournalModules.cs:line 567
   at EliteDangerousCore.EDJournalReader.ProcessLine(String line, Boolean inhistoryrefreshparse) in C:\Code\Examples\EDDiscovery\EliteDangerousCore\EliteDangerous\Journal\EDJournalReader.cs:line 168
   at EliteDangerousCore.EDJournalReader.ReadJournal(List`1 jent, List`1 uievents, Boolean historyrefreshparsing) in C:\Code\Examples\EDDiscovery\EliteDangerousCore\EliteDangerous\Journal\EDJournalReader.cs:line 273
   at EliteDangerousCore.JournalMonitorWatcher.ProcessDetectedNewFiles(List`1 readersToUpdate, Action`2 updateProgress, Action`5 fireback, Int32 firebacklastn) in C:\Code\Examples\EDDiscovery\EliteDangerousCore\EliteDangerous\Journal\EDJournalMonitorWatcher.cs:line 297
   at EliteDangerousCore.EDJournalUIScanner.ParseJournalFilesOnWatchers(Action`2 updateProgress, Int32 reloadlastn, Action`5 firebacknostore, Int32 firebacklastn) in C:\Code\Examples\EDDiscovery\EliteDangerousCore\EliteDangerous\Journal\EDScanner.cs:line 312
   at EDDiscovery.EDDiscoveryController.DoRefreshHistory(RefreshWorkerArgs args) in C:\Code\Examples\EDDiscovery\EDDiscovery\EDDiscoveryControllerHistory.cs:line 163
Checking for updated EDSM systems (may take a few moments).
Downloading systems from UTC 3/30/2021 11:45:10 PM to 3/31/2021 3:45:43 AM
Error: Cannot find entry in Ledger
At Step 3 in VoicePackV16::onRefreshEnd:904: Ledger
History refresh complete.
Retrieved 79 log entries from EDSM, from 3/23/2021 11:45:45 PM to 3/30/2021 11:45:45 PM
EDSM systems update complete with 5336 systems
```

However, EDDiscovery allowed me to continue running it after the above UI exception.

**Comment by xenophonf** [comment]
The log isn't being displayed correctly:

![image](https://user-images.githubusercontent.com/7139195/113087798-60d96c00-91b2-11eb-8fa1-476ef5b47142.png)

**Comment by xenophonf** [comment]
I uninstalled EDDiscovery and EDD-EDMC, rebooted, and re-installed both.  Everything appears to be working smoothly now.  I'm not sure why things broke.

**Comment by klightspeed** [comment]
The `InvalidProgramException` suggests that one or more DLLs did not get properly updated.  Uninstalling, rebooting, and re-installing would have fixed the broken DLLs.
