### ISSUE TITLE
UI Exception

### ISSUE THREAD

**Issue by TonyFlury** [EDDiscovery/EDDiscovery#3073]
This error ocurred :

here was an unhandled UI exception.

==== BEGIN ====
System.ArgumentException: InvalidArgument=Value of '81665' is not valid for 'rowIndex'.
   at System.Windows.Forms.DataGridViewRow.GetState(Int32 rowIndex)
   at System.Windows.Forms.DataGridViewRowCollection.GetFirstRow(DataGridViewElementStates includeFilter)
   at System.Windows.Forms.DataGridView.GetRowDisplayRectanglePrivate(Int32 rowIndex, Boolean cutOverflow)
   at System.Windows.Forms.DataGridView.GetCellDisplayRectangle(Int32 columnIndex, Int32 rowIndex, Boolean cutOverflow)
   at System.Windows.Forms.DataGridView.GetCellAdjustedDisplayRectangle(Int32 columnIndex, Int32 rowIndex, Boolean cutOverflow)
   at System.Windows.Forms.DataGridView.InvalidateCellPrivate(Int32 columnIndex, Int32 rowIndex)
   at System.Windows.Forms.DataGridView.OnCellStateChanged(DataGridViewCellStateChangedEventArgs e)
   at System.Windows.Forms.DataGridView.OnDataGridViewElementStateChanged(DataGridViewElement element, Int32 index, DataGridViewElementStates elementState)
   at System.Windows.Forms.DataGridViewCell.set_SelectedInternal(Boolean value)
   at System.Windows.Forms.DataGridView.SetSelectedCellCore(Int32 columnIndex, Int32 rowIndex, Boolean selected)
   at System.Windows.Forms.DataGridView.RemoveIndividuallySelectedCells()
   at System.Windows.Forms.DataGridView.ClearSelection()
   at EDDiscovery.UserControls.UserControlTravelGrid.AddEntry(HistoryEntry he) in C:\Code\Examples\EDDiscovery\EDDiscovery\UserControls\History\UserControlTravelGrid.cs:line 425
===== END =====

**Comment by robbyxp1** [comment]
This is deep within the windows subsystem. 

Is this repeatable? Is it still happening?

**Comment by robbyxp1** [comment]
What version of EDD is this?

**Comment by klightspeed** [comment]
It looks like <https://referencesource.microsoft.com/#System.Windows.Forms/winforms/Managed/System/WinForms/DataGridViewRow.cs,1482> is being hit, which would suggest that the row's `Index` was out of sync with the index of that row in the DataGrid.

**Comment by robbyxp1** [comment]
Hmm Not sure what we can do about this.

**Comment by GhostPLKR** [comment]
12.0.2.0
The error shows up from time to time. Closing the program, restarting (sometimes 2-3x) "fixes" the error.

I'll check something else and let you know.

**Comment by TonyFlury** [comment]
If it helps at all - this is version 12.0.2.0

**Comment by robbyxp1** [comment]
Its pretty undebuggable.  Sorry closing as its too deep into windows Forms.  it must have suffered a bad day.

**Comment by klightspeed** [comment]
> If it helps at all - this is version 12.0.2.0 - I have only seen this once, it seemed to coincide with a CTD of the game.

Memory error?  Unstable CPU overclock?
