### ISSUE TITLE
Fatal error

### ISSUE THREAD

**Issue by gthornhill** [EDDiscovery/EDDiscovery#3076]
An unhandled fatal exception has occurred.

==== BEGIN ====
System.InvalidOperationException: Invoke or BeginInvoke cannot be called on a control until the window handle has been created.
   at System.Windows.Forms.Control.MarshaledInvoke(Control caller, Delegate method, Object[] args, Boolean synchronous)
   at System.Windows.Forms.Control.Invoke(Delegate method, Object[] args)
   at EDDiscovery.EDDiscoveryForm.<EDDiscoveryForm_Shown>b__128_0(Action a) in C:\Code\Examples\EDDiscovery\EDDiscovery\EDDiscoveryForm.cs:line 370
   at System.IO.FileSystemWatcher.OnCreated(FileSystemEventArgs e)
   at System.IO.FileSystemWatcher.CompletionStatusChanged(UInt32 errorCode, UInt32 numBytes, NativeOverlapped* overlappedPointer)
   at System.Threading._IOCompletionCallback.PerformIOCompletionCallback(UInt32 errorCode, UInt32 numBytes, NativeOverlapped* pOVERLAP)
===== END =====

**Comment by robbyxp1** [comment]
No data. Closing

**Comment by klightspeed** [comment]
Original message before they deleted it was:

An unhandled fatal exception has occurred.

```
==== BEGIN ====
System.InvalidOperationException: Invoke or BeginInvoke cannot be called on a control until the window handle has been created.
at System.Windows.Forms.Control.MarshaledInvoke(Control caller, Delegate method, Object[] args, Boolean synchronous)
at System.Windows.Forms.Control.Invoke(Delegate method, Object[] args)
at EDDiscovery.EDDiscoveryForm.<EDDiscoveryForm_Shown>b__128_0(Action a) in C:\Code\Examples\EDDiscovery\EDDiscovery\EDDiscoveryForm.cs:line 370
at System.IO.FileSystemWatcher.OnCreated(FileSystemEventArgs e)
at System.IO.FileSystemWatcher.CompletionStatusChanged(UInt32 errorCode, UInt32 numBytes, NativeOverlapped* overlappedPointer)
at System.Threading._IOCompletionCallback.PerformIOCompletionCallback(UInt32 errorCode, UInt32 numBytes, NativeOverlapped* pOVERLAP)
===== END =====
```

This suggests that a file was created just before the window was shown.
