### ISSUE TITLE
EDD v.11.9.3.0 Installer error:  Unhandled UI Exception

### ISSUE THREAD

**Issue by Quillmonkey** [EDDiscovery/EDDiscovery#3089]
### Exception Details:
>EDDiscovery v11.9.3.0 There was an unhandled UI exception.
>```
>==== BEGIN ====
>System.ArgumentException: Height must be greater than 0px.
>   at System.Windows.Forms.DataVisualization.Charting.ChartPicture.InspectChartDimensions(Int32 width, Int32 height)
>   at System.Windows.Forms.DataVisualization.Charting.ChartPicture.set_Height(Int32 value)
>   at System.Windows.Forms.DataVisualization.Charting.Chart.OnResize(EventArgs e)
>   at System.Windows.Forms.Control.OnSizeChanged(EventArgs e)
>   at System.Windows.Forms.Control.UpdateBounds(Int32 x, Int32 y, Int32 width, Int32 height, Int32 clientWidth, Int32 clientHeight)
>   at System.Windows.Forms.Control.UpdateBounds(Int32 x, Int32 y, Int32 width, Int32 height)
>   at System.Windows.Forms.Control.SetBoundsCore(Int32 x, Int32 y, Int32 width, Int32 height, BoundsSpecified specified)
>   at System.Windows.Forms.Control.System.Windows.Forms.Layout.IArrangedElement.SetBounds(Rectangle bounds, BoundsSpecified specified)
>   at System.Windows.Forms.Layout.DefaultLayout.xLayoutDockedControl(IArrangedElement element, Rectangle newElementBounds, Boolean measureOnly, Size& preferredSize, Rectangle& remainingBounds)
>   at System.Windows.Forms.Layout.DefaultLayout.LayoutDockedControls(IArrangedElement container, Boolean measureOnly)
>   at System.Windows.Forms.Layout.DefaultLayout.xLayout(IArrangedElement container, Boolean measureOnly, Size& preferredSize)
>   at System.Windows.Forms.Layout.DefaultLayout.LayoutCore(IArrangedElement container, LayoutEventArgs args)
>   at System.Windows.Forms.Layout.LayoutEngine.Layout(Object container, LayoutEventArgs layoutEventArgs)
>   at System.Windows.Forms.Control.OnLayout(LayoutEventArgs levent)
>   at System.Windows.Forms.Control.PerformLayout(LayoutEventArgs args)
>   at System.Windows.Forms.Control.ControlCollection.SetChildIndexInternal(Control child, Int32 newIndex)
>   at EDDiscovery.UserControls.UserControlMiningOverlay.Display() in C:\Code\EDDiscovery\EDDiscovery\UserControls\Overlays\UserControlMiningOverlay.cs:line 512
>   at EDDiscovery.UserControls.UserControlMiningOverlay.Display(HistoryEntry he) in C:\Code\EDDiscovery\EDDiscovery\UserControls\Overlays\UserControlMiningOverlay.cs:line 165
>   at EDDiscovery.UserControls.ChangedSelectionHEHandler.Invoke(HistoryEntry he, HistoryList hl, Boolean selectedEntry)
>   at EDDiscovery.UserControls.UserControlTravelGrid.FireChangeSelection() in C:\Code\EDDiscovery\EDDiscovery\UserControls\History\UserControlTravelGrid.cs:line 540
>   at EDDiscovery.UserControls.UserControlTravelGrid.HistoryChanged(HistoryList hl, Boolean disablesorting) in C:\Code\EDDiscovery\EDDiscovery\UserControls\History\UserControlTravelGrid.cs:line 289
>   at System.Action`1.Invoke(T obj)
>   at EDDiscovery.EDDiscoveryController.ForegroundHistoryRefreshCompleteonUI(HistoryList hist) in C:\Code\EDDiscovery\EDDiscovery\EDDiscoveryControllerHistory.cs:line 192
>===== END =====
>```

**Comment by klightspeed** [comment]
This suggests that the window has a bad size.

You can reset the layout by holding shift while starting, and clicking Reset windows and positions.

Note however that the 11.9 branch will not be getting any updates, and will likely be blacklisted by some EDDN listeners.
