### ISSUE TITLE
EDDiscovery v12.0.2.0 Fatal Error, upon PC restart and opening application

### ISSUE THREAD

**Issue by Lyynk** [EDDiscovery/EDDiscovery#3091]
An unhandled fatal exception has occurred.

==== BEGIN ====
System.NullReferenceException: Object reference not set to an instance of an object.
   at EliteDangerousCore.JournalMonitorWatcher.ScanForNewEntries() in C:\Code\Examples\EDDiscovery\EliteDangerousCore\EliteDangerous\Journal\EDJournalMonitorWatcher.cs:line 168
   at EliteDangerousCore.EDJournalUIScanner.ScanTickWorker(Func`1 stopRequested) in C:\Code\Examples\EDDiscovery\EliteDangerousCore\EliteDangerous\Scanner\EDScanner.cs:line 105
   at EliteDangerousCore.EDJournalUIScanner.ScanThreadProc() in C:\Code\Examples\EDDiscovery\EliteDangerousCore\EliteDangerous\Scanner\EDScanner.cs:line 0
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.ThreadHelper.ThreadStart()
===== END =====

**Comment by Eahlstan** [comment]
Does this happen all the time or was it a one time crash?

**Comment by Lyynk** [comment]
It happened twice, I closed it out and reopened it happened again. Cleared it from task manager, retried and then restarted. It opened after that with no issue.

**Comment by klightspeed** [comment]
This should be fixed in EDDiscovery/EliteDangerousCore#42, which should be in the next release.

**Comment by robbyxp1** [comment]
Which will be out soon.
