### ISSUE TITLE
Euro Caps themes break the UI

### ISSUE THREAD

**Issue by GaryxGaming** [EDDiscovery/EDDiscovery#3192]
### Description
Changed UI theme

### Additional Information
Every default Euro Caps theme causes this

### Exception Details:
>EDDiscovery v12.1.5.0 There was an unhandled UI exception.
>```
>==== BEGIN ====
>System.DivideByZeroException: Attempted to divide by zero.
>   at System.Windows.Forms.DataGridViewCell.MeasureTextPreferredSize(Graphics graphics, String text, Font font, Single maxRatio, TextFormatFlags flags)
>   at System.Windows.Forms.DataGridViewColumnHeaderCell.GetPreferredSize(Graphics graphics, DataGridViewCellStyle cellStyle, Int32 rowIndex, Size constraintSize)
>   at System.Windows.Forms.DataGridViewCell.GetPreferredSize(Int32 rowIndex)
>   at System.Windows.Forms.DataGridView.AutoResizeColumnHeadersHeight(Boolean fixedRowHeadersWidth, Boolean fixedColumnsWidth)
>   at System.Windows.Forms.DataGridView.OnColumnHeadersGlobalAutoSize()
>   at System.Windows.Forms.DataGridView.OnColumnHeadersDefaultCellStyleChanged(EventArgs e)
>   at System.Windows.Forms.DataGridView.OnCellStyleContentChanged(DataGridViewCellStyleContentChangedEventArgs e)
>   at System.Windows.Forms.DataGridViewCellStyle.set_Font(Font value)
>   at System.Windows.Forms.DataGridView.OnFontChanged(EventArgs e)
>   at System.Windows.Forms.Control.OnParentFontChanged(EventArgs e)
>   at System.Windows.Forms.Control.OnFontChanged(EventArgs e)
>   at System.Windows.Forms.Control.OnParentFontChanged(EventArgs e)
>   at System.Windows.Forms.Control.OnFontChanged(EventArgs e)
>   at System.Windows.Forms.Control.OnParentFontChanged(EventArgs e)
>   at System.Windows.Forms.Control.OnFontChanged(EventArgs e)
>   at System.Windows.Forms.Control.OnParentFontChanged(EventArgs e)
>   at System.Windows.Forms.Control.OnFontChanged(EventArgs e)
>   at System.Windows.Forms.Control.OnParentFontChanged(EventArgs e)
>   at System.Windows.Forms.Control.OnFontChanged(EventArgs e)
>   at System.Windows.Forms.Control.OnParentFontChanged(EventArgs e)
>   at System.Windows.Forms.Control.OnFontChanged(EventArgs e)
>   at System.Windows.Forms.Control.OnParentFontChanged(EventArgs e)
>   at System.Windows.Forms.Control.OnFontChanged(EventArgs e)
>   at System.Windows.Forms.Control.OnParentFontChanged(EventArgs e)
>   at System.Windows.Forms.Control.OnFontChanged(EventArgs e)
>   at System.Windows.Forms.Control.OnParentFontChanged(EventArgs e)
>   at System.Windows.Forms.Control.OnFontChanged(EventArgs e)
>   at System.Windows.Forms.Control.OnParentFontChanged(EventArgs e)
>   at System.Windows.Forms.Control.OnFontChanged(EventArgs e)
>   at System.Windows.Forms.TabControl.OnFontChanged(EventArgs e)
>   at System.Windows.Forms.Control.OnParentFontChanged(EventArgs e)
>   at System.Windows.Forms.Control.OnFontChanged(EventArgs e)
>   at System.Windows.Forms.Control.set_Font(Font value)
>   at ExtendedControls.ThemeStandard.UpdateControls(Control parent, Control myControl, Font fnt, Int32 level, Boolean noborderoverride) in C:\Code\Examples\EDDiscovery\ExtendedControls\ExtendedControls\Themes\ThemeStandard.cs:line 595
>   at ExtendedControls.ThemeStandard.Apply(Control form, Font fnt, Boolean nowindowsborderoverride) in C:\Code\Examples\EDDiscovery\ExtendedControls\ExtendedControls\Themes\ThemeStandard.cs:line 568
>   at EDDiscovery.EDDiscoveryForm.ApplyTheme(Boolean panelrefreshaswell) in C:\Code\Examples\EDDiscovery\EDDiscovery\EDDiscoveryFormHelpers.cs:line 369
>   at EDDiscovery.UserControls.UserControlSettings.comboBoxTheme_SelectedIndexChanged(Object sender, EventArgs e) in C:\Code\Examples\EDDiscovery\EDDiscovery\UserControls\Settings\UserControlSettings.cs:line 397
>   at ExtendedControls.ExtComboBox._cbsystem_SelectedIndexChanged(Object sender, EventArgs e) in C:\Code\Examples\EDDiscovery\ExtendedControls\ExtendedControls\Controls\ComboBox.cs:line 377
>   at System.Windows.Forms.ComboBox.OnSelectedIndexChanged(EventArgs e)
>   at System.Windows.Forms.ComboBox.set_SelectedIndex(Int32 value)
>   at ExtendedControls.ExtComboBox.customdropdown_SelectedIndexChanged(Object sender, EventArgs e) in C:\Code\Examples\EDDiscovery\ExtendedControls\ExtendedControls\Controls\ComboBox.cs:line 352
>   at ExtendedControls.ExtListBoxForm.listcontrol_SelectedIndexChanged(Object sender, EventArgs e) in C:\Code\Examples\EDDiscovery\ExtendedControls\ExtendedControls\Forms\ListBoxForm.cs:line 111
>   at ExtendedControls.ExtListBox.OnMouseClick(MouseEventArgs e) in C:\Code\Examples\EDDiscovery\ExtendedControls\ExtendedControls\Controls\ListBox.cs:line 364
>   at System.Windows.Forms.Control.WmMouseUp(Message& m, MouseButtons button, Int32 clicks)
>   at System.Windows.Forms.Control.WndProc(Message& m)
>   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)
>===== END =====
>```

**Comment by Eahlstan** [comment]
If I read that error message correctly this happens immediately after you change the theme and while you are still on the settings panel?
Please screenshot that panel and upload it here.
