### ISSUE TITLE
EDDiscovery crash on exit

### ISSUE THREAD

**Issue by CmdrDeluvian** [EDDiscovery/EDDiscovery#3215]
An unhandled fatal exception has occurred.

==== BEGIN ====
System.InvalidOperationException: Invoke or BeginInvoke cannot be called on a control until the window handle has been created.
   at System.Windows.Forms.Control.MarshaledInvoke(Control caller, Delegate method, Object[] args, Boolean synchronous)
   at System.Windows.Forms.Control.BeginInvoke(Delegate method, Object[] args)
   at EDDiscovery.EDDiscoveryForm.<.ctor>b__125_3(Action a) in C:\Code\Examples\EDDiscovery\EDDiscovery\EDDiscoveryForm.cs:line 136
   at EDDiscovery.EDDiscoveryController.DoRefreshHistory(RefreshWorkerArgs args) in C:\Code\Examples\EDDiscovery\EDDiscovery\EDDiscoveryControllerHistory.cs:line 226
   at EDDiscovery.EDDiscoveryController.BackgroundHistoryRefreshWorkerThread() in C:\Code\Examples\EDDiscovery\EDDiscovery\EDDiscoveryControllerHistory.cs:line 136
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.ThreadHelper.ThreadStart()
===== END =====

**Comment by robbyxp1** [comment]
This is just one of those random windows forms crashes, due to a random out of order instance.

If it does not repeat, ignore it.

**Comment by CmdrDeluvian** [comment]
Ok. thanks! Merry Christmas
