### ISSUE TITLE
"An unhandled fatal exception has occurred."

### ISSUE THREAD

**Issue by SlashMatrix** [EDDiscovery/EDDiscovery#3227]
Re-installing didn't help. Here's the log:

An unhandled fatal exception has occurred.

==== BEGIN ====
SQLLiteExtensions.SQLProcessingThreadException: disk I/O error
disk I/O error ---> System.Data.SQLite.SQLiteException: disk I/O error
disk I/O error
   at System.Data.SQLite.SQLite3.Reset(SQLiteStatement stmt)
   at System.Data.SQLite.SQLite3.Step(SQLiteStatement stmt)
   at System.Data.SQLite.SQLiteDataReader.NextResult()
   at System.Data.SQLite.SQLiteDataReader..ctor(SQLiteCommand cmd, CommandBehavior behave)
   at System.Data.SQLite.SQLiteCommand.ExecuteReader(CommandBehavior behavior)
   at System.Data.SQLite.SQLiteCommand.ExecuteNonQuery(CommandBehavior behavior)
   at EliteDangerousCore.JournalEntry.Add(JObject jo, SQLiteConnectionUser cn, DbTransaction tn) in C:\Code\Examples\EDDiscovery\EliteDangerousCore\EliteDangerous\Journal\JournalEntryDB.cs:line 80
   at EliteDangerousCore.EDSM.EDSMLogFetcher.<>c__DisplayClass18_0.<Process>b__5(UserDatabaseConnection cn) in C:\Code\Examples\EDDiscovery\EliteDangerousCore\EliteDangerous\EDSM\EDSMLogFetcher.cs:line 247
   at SQLLiteExtensions.SQLProcessingThread`1.<>c__DisplayClass26_0.<ExecuteWithDatabase>b__0() in C:\Code\Examples\EDDiscovery\BaseUtilities\SQLLite\SQLLite\SQLProcessingThread.cs:line 263
   at SQLLiteExtensions.SQLProcessingThread`1.Job`1.Exec() in C:\Code\Examples\EDDiscovery\BaseUtilities\SQLLite\SQLLite\SQLProcessingThread.cs:line 66
   --- End of inner exception stack trace ---
   at SQLLiteExtensions.SQLProcessingThread`1.Job`1.Wait() in C:\Code\Examples\EDDiscovery\BaseUtilities\SQLLite\SQLLite\SQLProcessingThread.cs:line 89
   at SQLLiteExtensions.SQLProcessingThread`1.Execute[T](Func`1 func, Int32 skipframes, Int32 warnthreshold) in C:\Code\Examples\EDDiscovery\BaseUtilities\SQLLite\SQLLite\SQLProcessingThread.cs:line 247
   at SQLLiteExtensions.SQLProcessingThread`1.ExecuteWithDatabase(Action`1 action, Int32 warnthreshold) in C:\Code\Examples\EDDiscovery\BaseUtilities\SQLLite\SQLLite\SQLProcessingThread.cs:line 264
   at EliteDangerousCore.EDSM.EDSMLogFetcher.Process(List`1 edsmlogs, DateTime logstarttime, DateTime logendtime) in C:\Code\Examples\EDDiscovery\EliteDangerousCore\EliteDangerous\EDSM\EDSMLogFetcher.cs:line 255
   at EliteDangerousCore.EDSM.EDSMLogFetcher.FetcherThreadProc() in C:\Code\Examples\EDDiscovery\EliteDangerousCore\EliteDangerous\EDSM\EDSMLogFetcher.cs:line 155
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.ThreadHelper.ThreadStart()
===== END =====

**Comment by Eahlstan** [comment]
First: Are you sure your disk isn't dying?
Second: I told Robby countless times (so like 3 times), that not deleting files on uninstall is a bad idea :D So please go to %localappdata%\EDDiscovery (while EDD is closed and you made sure your disk is fine) and rename EDDUser.sqlite to something different, then start EDD to see if your DB was damaged by testing if a new DB doesn't error out.

**Comment by robbyxp1** [comment]
Hah. If i autodeleted it, people would moan all their settings is lost when they reinstalled..

What is really needed is some sort of detection of this.

**Comment by SlashMatrix** [comment]
I deleted all of it and repaired some bad disk sectors. Seems to be running now!  Thank you for the quick reply. Glad it was just something on my end!
