### ISSUE TITLE
EDDiscovery 15.0.0.0 still using IE11 even after installing the WebView2 Runtime

### ISSUE THREAD

**Issue by erasariel** [EDDiscovery/EDDiscovery#3239]
Hello! After installing 15.0.0.0 and the WebView2 runtime through the link you provided in the release page, EDDiscovery still prompts that it is using IE11 whenever I use a tab that loads a web page (such as EDDB):
![image](https://user-images.githubusercontent.com/60572143/158427716-e6a84dc6-388e-4372-bfb7-0d72cc2b34b1.png)

I also verified that the WebView2 Runtime is installed:
![image](https://user-images.githubusercontent.com/60572143/158427936-496708c4-8002-4228-a87d-2879d30fc277.png)

I'm running EDDiscovery on Win10 64-bit 21H1.

**Comment by robbyxp1** [comment]
Thanks for the report. I've just checked. I have that runtime installed, its showing the same, and yet I am getting it to run with webview2.

Without some debug in it, hard to know why its not running. I'll put some debug in for the next version.

**Comment by quinnell** [comment]
I just wanted to add that I'm seeing this behavior as well.  Shows on my EDSM and Spansh tabs.  Deleting the tabs and re-making them doesn't help.

15.0.0.4

**Comment by Eahlstan** [comment]
Did you try uninstalling and reinstalling the runtime?

**Comment by robbyxp1** [comment]
We will have a trace line in the log. 15.0.0.4 prob has it.

The trace file is in your appdata/logs folder. (%localappdata%/eddiscovery/logs normally)

See if there is lines saying "web browser" in there.

**Comment by quinnell** [comment]
> We will have a trace line in the log. 15.0.0.4 prob has it.
> 
> The trace file is in your appdata/logs folder. (%localappdata%/eddiscovery/logs normally)
> 
> See if there is lines saying "web browser" in there.

Just loaded up the tab and this is what got added to the trace file:
`[2022-03-23T16:31:15.445Z] Web browser initial display
[2022-03-23T16:31:15.546Z] Web browser view returned False
`

**Comment by quinnell** [comment]
> Your on windows 10, right?

Yup.

**Comment by Eahlstan** [comment]
As I asked before: Did you reinstall it?

There is (was) a bug in the installer that resulted in failed installations when not being executed as an admin.

https://github.com/MicrosoftEdge/WebView2Feedback/issues/2030

So please redownload the runtime installer and install it again.

**Comment by quinnell** [comment]
> As I asked before: Did you reinstall it?
> 
> There is (was) a bug in the installer that resulted in failed installations (without an visible error) when not being executed as an admin.
> 
> [MicrosoftEdge/WebView2Feedback#2030](https://github.com/MicrosoftEdge/WebView2Feedback/issues/2030)
> 
> So please redownload the runtime installer and install it again.

The installer was executed as admin because it failed when not.  Uninstalling and reinstalling had no effect.

**Comment by Eahlstan** [comment]
> The installer was executed as admin because it failed when not. Uninstalling and reinstalling had no effect.

Are you sure you used the latest version? There was a fix some time ago that makes the installer install the runtime on a "per user" basis when executed as user rather than on a "for all users" basis when executed as admin.

Just to be sure (yeah I'm annoying) can you please confirm you downloaded the latest release and installed that?

https://developer.microsoft.com/en-us/microsoft-edge/webview2/#download-section

**Comment by quinnell** [comment]
> > The installer was executed as admin because it failed when not. Uninstalling and reinstalling had no effect.
> 
> Are you sure you used the latest version? There was a fix some time ago that makes the installer install the runtime on a "per user" basis when executed as user rather than on a "for all users" basis when executed as admin (it failed as user before that fix).
> 
> Just to be sure (yeah I'm annoying) can you please confirm you downloaded the latest release and installed that?
> 
> https://developer.microsoft.com/en-us/microsoft-edge/webview2/#download-section

Yes, I installed it less than 3 days ago.

**Comment by quinnell** [comment]
> I compiled the WebView sample browser from Microsofts GitHub repository, could you download it and see if WebView works on your system? It should open bing.com when you start the app.
> 
> https://drive.google.com/file/d/1-xXxaHCZowiTeaT7qioJD5H4Oyy4jshH/view?usp=sharing
> 
> ![Screenshot 2022-03-24 163153](https://user-images.githubusercontent.com/59618179/159952667-d0bd4ac3-e4f2-4248-ad24-f8f1f5040b30.JPG)


It worked fine.
![image](https://user-images.githubusercontent.com/47070375/159980852-6b246e77-163d-4bec-b74d-4ab8b25e7db6.png)

**Comment by Eahlstan** [comment]
Great. At least we now know that Webview2 is indeed working on your system.

Have you tried starting EDD as an admin?

**Comment by quinnell** [comment]
> Great. At least we now know that Webview2 is indeed working on your system.
> 
> Have you tried starting EDD as an admin?

Just tried running as admin.  No change in behavior.  
![image](https://user-images.githubusercontent.com/47070375/159982361-a8ddac28-0138-450d-9e68-f856190eeae3.png)

**Comment by robbyxp1** [comment]
Today, I'll do another EDD version with more log output if webview2 fails

**Comment by robbyxp1** [comment]
https://github.com/EDDiscovery/EDDiscovery/releases/tag/Release_15.0.0

**Comment by robbyxp1** [comment]
Please look in the logs and report all lines, including the exception report lines you should be getting around webview2 exception.. we need all of the log really.

**Comment by quinnell** [comment]
Here's the error:

```
[2022-03-25T15:33:28.616Z] EDSM Comments downloaded/updated 0
[2022-03-25T15:33:29.067Z] Web browser initial display
[2022-03-25T15:33:29.187Z] Webview 2 exception System.DllNotFoundException: Unable to load DLL 'WebView2Loader.dll': The specified module could not be found. (Exception from HRESULT: 0x8007007E)

[2022-03-25T15:33:29.187Z]    at Microsoft.Web.WebView2.Core.CoreWebView2Environment.CreateCoreWebView2EnvironmentWithOptions(String browserExecutableFolder, String userDataFolder, ICoreWebView2EnvironmentOptions options, ICoreWebView2CreateCoreWebView2EnvironmentCompletedHandler environment_created_handler)

[2022-03-25T15:33:29.187Z]    at Microsoft.Web.WebView2.Core.CoreWebView2Environment.<CreateAsync>d__3.MoveNext()

[2022-03-25T15:33:29.187Z] --- End of stack trace from previous location where exception was thrown ---

[2022-03-25T15:33:29.187Z]    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()

[2022-03-25T15:33:29.187Z]    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)

[2022-03-25T15:33:29.187Z]    at Microsoft.Web.WebView2.WinForms.WebView2.<InitCoreWebView2Async>d__18.MoveNext()    at Microsoft.Web.WebView2.Core.CoreWebView2Environment.CreateCoreWebView2EnvironmentWithOptions(String browserExecutableFolder, String userDataFolder, ICoreWebView2EnvironmentOptions options, ICoreWebView2CreateCoreWebView2EnvironmentCompletedHandler environment_created_handler)

[2022-03-25T15:33:29.187Z]    at Microsoft.Web.WebView2.Core.CoreWebView2Environment.<CreateAsync>d__3.MoveNext()

[2022-03-25T15:33:29.187Z] --- End of stack trace from previous location where exception was thrown ---

[2022-03-25T15:33:29.187Z]    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()

[2022-03-25T15:33:29.187Z]    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)

[2022-03-25T15:33:29.187Z]    at Microsoft.Web.WebView2.WinForms.WebView2.<InitCoreWebView2Async>d__18.MoveNext()
[2022-03-25T15:33:29.188Z] Web browser view returned False
[2022-03-25T15:33:30.201Z] Web browser initial display
[2022-03-25T15:33:30.201Z] Webview 2 exception System.DllNotFoundException: Unable to load DLL 'WebView2Loader.dll': The specified module could not be found. (Exception from HRESULT: 0x8007007E)
   at Microsoft.Web.WebView2.Core.CoreWebView2Environment.CreateCoreWebView2EnvironmentWithOptions(String browserExecutableFolder, String userDataFolder, ICoreWebView2EnvironmentOptions options, ICoreWebView2CreateCoreWebView2EnvironmentCompletedHandler environment_created_handler)
   at Microsoft.Web.WebView2.Core.CoreWebView2Environment.<CreateAsync>d__3.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Web.WebView2.WinForms.WebView2.<InitCoreWebView2Async>d__18.MoveNext()    at Microsoft.Web.WebView2.Core.CoreWebView2Environment.CreateCoreWebView2EnvironmentWithOptions(String browserExecutableFolder, String userDataFolder, ICoreWebView2EnvironmentOptions options, ICoreWebView2CreateCoreWebView2EnvironmentCompletedHandler environment_created_handler)
   at Microsoft.Web.WebView2.Core.CoreWebView2Environment.<CreateAsync>d__3.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Web.WebView2.WinForms.WebView2.<InitCoreWebView2Async>d__18.MoveNext()
[2022-03-25T15:33:30.201Z] Web browser view returned False
[2022-03-25T15:33:35.284Z] 20204 TG TOTAL TIME 10845
[2022-03-25T15:33:35.830Z] HTTPPOST TO https://inara.cz/inapi/v1/ ThreadInara Journal Sync
[2022-03-25T15:33:36.008Z] ..HTTPPOST Response OK
```

**Comment by Eahlstan** [comment]
Could you please tell the full path of your EDD installation?

**Comment by quinnell** [comment]
C:\Program Files\EDDiscovery

**Comment by Eahlstan** [comment]
Please download the DLL and put it in that directory.

https://drive.google.com/file/d/1-zi4jYvJbpQdmkiRCKmBS3MaNE2K3DAP/view?usp=sharing

**Comment by klightspeed** [comment]
Both the installer and the portable zip are missing the `runtimes` directory.
Also, it looks like WebView2 needs to be configured to put its profile directory in a subdirectory of the EDDiscovery data directory - by default it will try to put it into `EDDiscovery.exe.WebView2` in its install directory, which will usually be denied.

**Comment by robbyxp1** [comment]
Thanks for your help. 15.0.0.6 should solve the issue with webview. This was due to a deployment issue (missing DLL) and misconfiguration of the user data folder for webview which meant it would not work if the program was stored in program files.

**Comment by quinnell** [comment]
Just tested with new version, works like a charm!  Good work guys.
