### ISSUE TITLE
Everytime I use 3d maps

### ISSUE THREAD

**Issue by Gopher-nz** [EDDiscovery/EDDiscovery#3266]
### Exception Details:
>EDDiscovery v15.0.2.0 There was an unhandled UI exception.
>```
>==== BEGIN ====
>System.ArgumentOutOfRangeException: Index was out of range. Must be non-negative and less than the size of the collection.
>Parameter name: index
>   at System.ThrowHelper.ThrowArgumentOutOfRangeException(ExceptionArgument argument, ExceptionResource resource)
>   at EDDiscovery.UserControls.Map3D.TravelPath.FindSystem(Point viewportloc, GLRenderState state, Size viewportsize, Single& z) in C:\Code\EDDiscovery\EDDiscovery\UserControls\3DMap\TravelPath.cs:line 273
>   at EDDiscovery.UserControls.Map3D.Map.FindObjectOnMap(Point loc) in C:\Code\EDDiscovery\EDDiscovery\UserControls\3DMap\Map.cs:line 1116
>   at EDDiscovery.UserControls.Map3D.Map.MouseClickOnMap(GLBaseControl s, GLMouseEventArgs e) in C:\Code\EDDiscovery\EDDiscovery\UserControls\3DMap\Map.cs:line 1297
>   at GLOFC.GL4.Controls.GLBaseControl.Gc_MouseClick(GLWindowControl sender, GLMouseEventArgs e)
>   at GLOFC.WinForm.GLWinFormControl.Gc_MouseClick(Object sender, MouseEventArgs e)
>   at System.Windows.Forms.Control.OnMouseClick(MouseEventArgs e)
>   at System.Windows.Forms.Control.WmMouseUp(Message& m, MouseButtons button, Int32 clicks)
>   at System.Windows.Forms.Control.WndProc(Message& m)
>   at System.Windows.Forms.UserControl.WndProc(Message& m)
>   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)
>===== END =====
>```

**Comment by robbyxp1** [comment]
Can you tell me what you were doing? Clicking on a star is my guess.  Is it a travel path (your history) star or is it a nav route star (your plotted route).  Did you have any time filtering selected in the menu for the travel path?

**Comment by Gopher-nz** [comment]
Clicking on any star - not on travel path, or nav route. Nothing filtered
either.

**Comment by ciberloky** [comment]
the same to me, when it sends data to inara it gives an exception but it is random since at another time it does not do it the same as in configuration it also randomly gives an exception.

**Comment by robbyxp1** [comment]
The one is fixed.

**Comment by ciberloky** [comment]
i use 15.0.3

**Comment by ciberloky** [comment]
when you send to inara  version  15.0.3.0
There was an unhandled UI exception.

==== BEGIN ====
System.InvalidOperationException: El objeto que acepta valores Null debe tener un valor.
   en System.ThrowHelper.ThrowInvalidOperationException(ExceptionResource resource)
   en EliteDangerousCore.Inara.InaraClass.setCommandersCommunityGoalProgress(CommunityGoal goals, DateTime dt) en C:\Code\EDDiscovery\EliteDangerousCore\EliteDangerous\Inara\Inara.cs:línea 661
   en EliteDangerousCore.Inara.InaraSync.NewEntryList(HistoryEntry he, Dictionary`2 mcmr) en C:\Code\EDDiscovery\EliteDangerousCore\EliteDangerous\Inara\InaraSync.cs:línea 561
   en EliteDangerousCore.Inara.InaraSync.NewEvent(Action`1 logger, HistoryEntry he, Dictionary`2 mcmr) en C:\Code\EDDiscovery\EliteDangerousCore\EliteDangerous\Inara\InaraSync.cs:línea 77
   en EDDiscovery.EDDiscoveryForm.Controller_NewHistoryEntryUnfiltered(HistoryEntry he) en C:\Code\EDDiscovery\EDDiscovery\EDDiscoveryFormJournalEvents.cs:línea 102
   en EDDiscovery.EDDiscoveryController.PlayJournalList() en C:\Code\EDDiscovery\EDDiscovery\EDDiscoveryControllerNewEntry.cs:línea 90
   en EliteDangerousCore.EDJournalUIScanner.IssueEventsInUIThread(List`1 entries) en C:\Code\EDDiscovery\EliteDangerousCore\EliteDangerous\Scanner\EDScanner.cs:línea 152
===== END =====

**Comment by Eahlstan** [comment]
Please upload the Elite journal file from that session.

**Comment by robbyxp1** [comment]
Or at least the JSON of the community goal event, you can get that by right clicking on the entry and doing 'copy journal entry to clipboard/log'

**Comment by robbyxp1** [comment]
Try 15.0.4

**Comment by Gopher-nz** [comment]
Hey Rob,
All good mate. Sorry I could not be more descriptive. Was juggling family
and other stuff at the time.

So I have  ED Discovery15.2.0 installed on a Win 10 Operating system - all
up to date with 21H2 OS Build 19044.1706.

Nothing seems out of the ordinary when I open EDD on its own.

HOWEVER - I use VR and I have five monitors on the go as well. One of the
monitors has EDD on it and I think when I ALT tab and start dicking around
with the 3d map, is when I get the error message.

SO I am not too sure if it really is a bug on EDDs part or maybe it is more
to do with the pain I put my GPUs through. If there is antyhign in the
error message that relates to display (beyond my skillset) then chances are
my quirky setup is to blame.

Feel free to come back to me if you have any questions or I can help you
out.

Cheers,

Karl

**Comment by robbyxp1** [comment]
Try 15.0.4
