### ISSUE TITLE
Show Expedtion in 3D Map Causes a Crash

### ISSUE THREAD

**Issue by Astronblue** [EDDiscovery/EDDiscovery#3270]
### Description
When trying to show an expedition in the 3D Map, an unhandled fatal exception occurs.  The window that pops up behind the fatal error notification titled shader log reads Pipeline shader compiler report for GLPLFragmentShaderBindlessTexture: ERROR: 0:11: " : array size too big

### Additional Information
<img width="412" alt="image" src="https://user-images.githubusercontent.com/106115611/169898986-f998eb90-28e0-4f40-9701-6de056c7cd43.png">

### Exception Details:
>EDDiscovery v15.0.4.0 An unhandled fatal exception has occurred.
>```
>==== BEGIN ====
>System.AccessViolationException: Attempted to read or write protected memory. This is often an indication that other memory is corrupt.
>   at OpenTK.Graphics.OpenGL4.GL.DrawElementsInstancedBaseVertexBaseInstance(PrimitiveType mode, Int32 count, DrawElementsType type, IntPtr indices, Int32 instancecount, Int32 basevertex, Int32 baseinstance) in C:\Users\juliu\Documents\GitHub\opentk\src\OpenTK\Graphics\OpenGL4\GL4.cs:line 17747
>   at GLOFC.GL4.GLRenderableItem.Render()
>   at GLOFC.GL4.Controls.GLControlDisplay.Render(GLRenderState currentstate, UInt64 ts)
>   at System.Action`1.Invoke(T obj)
>   at GLOFC.WinForm.GLWinFormControl.GlControl_Paint(Object sender, PaintEventArgs e)
>   at System.Windows.Forms.Control.OnPaint(PaintEventArgs e)
>   at OpenTK.GLControl.OnPaint(PaintEventArgs e) in I:\work\github\opentk\src\OpenTK.GLControl\GLControl.cs:line 287
>   at System.Windows.Forms.Control.PaintWithErrorHandling(PaintEventArgs e, Int16 layer)
>   at System.Windows.Forms.Control.WmPaint(Message& m)
>   at System.Windows.Forms.Control.WndProc(Message& m)
>   at System.Windows.Forms.UserControl.WndProc(Message& m)
>   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)
>===== END =====
>```

**Comment by Eahlstan** [comment]
Please state your hard- and software configuration.

**Comment by Astronblue** [comment]
Processor: 11th Gen Intel(R) Core(TM) i9-11900H @2.50GHz 
RAM: 16 GB
System Type: 64-bit

Windows Specifications
Windows 11 Version 21H2

**Comment by Eahlstan** [comment]
No graphic card?

**Comment by Astronblue** [comment]
Sorry slipped my mind,

NVIDIA GeForce RTX 3060 Laptop GPU

**Comment by Astronblue** [comment]
That appears to have fixed it, Thank you!
