### ISSUE TITLE
an unhandled fatal exception has occurred

### ISSUE THREAD

**Issue by Rev1008** [EDDiscovery/EDDiscovery#3277]
An unhandled fatal exception has occurred.

==== BEGIN ====
SQLLiteExtensions.SQLProcessingThreadException: SQL logic error
no such table: Systems ---> System.Data.SQLite.SQLiteException: SQL logic error
no such table: Systems
   at System.Data.SQLite.SQLite3.Prepare(SQLiteConnection cnn, String strSql, SQLiteStatement previous, UInt32 timeoutMS, String& strRemain)
   at System.Data.SQLite.SQLiteCommand.BuildNextCommand()
   at System.Data.SQLite.SQLiteDataReader.NextResult()
   at System.Data.SQLite.SQLiteDataReader..ctor(SQLiteCommand cmd, CommandBehavior behave)
   at System.Data.SQLite.SQLiteCommand.ExecuteReader(CommandBehavior behavior)
   at EliteDangerousCore.DB.SystemsDB.GetSystemListBySqDistancesFrom(SortedListDoubleDuplicate`1 distlist, Double x, Double y, Double z, Int32 maxitems, Double mindist, Double maxdist, Boolean spherical, SQLiteConnectionSystem cn, Action`1 LookedUp) in C:\Code\EDDiscovery\EliteDangerousCore\EliteDangerous\SystemDB\SystemsDBGetByDistance.cs:line 80
   at EliteDangerousCore.DB.SystemCache.<>c__DisplayClass9_0.<GetSystemListBySqDistancesFrom>b__0(SQLiteConnectionSystem cn) in C:\Code\EDDiscovery\EliteDangerousCore\EliteDangerous\SystemDB\SystemCache.cs:line 302
   at SQLLiteExtensions.SQLAdvProcessingThread`1.<>c__DisplayClass19_0.<DBRead>b__0() in C:\Code\EDDiscovery\BaseUtilities\SQLLite\SQLLite\SQLAdvProcessingThread.cs:line 47
   at SQLLiteExtensions.Job`1.Exec() in C:\Code\EDDiscovery\BaseUtilities\SQLLite\SQLLite\SQLAdvProcessingThread.cs:line 355
   --- End of inner exception stack trace ---
   at SQLLiteExtensions.Job`1.Wait() in C:\Code\EDDiscovery\BaseUtilities\SQLLite\SQLLite\SQLAdvProcessingThread.cs:line 374
   at SQLLiteExtensions.SQLAdvProcessingThread`1.Execute[T](Func`1 func, Boolean write, UInt32 warnthreshold, String jobname) in C:\Code\EDDiscovery\BaseUtilities\SQLLite\SQLLite\SQLAdvProcessingThread.cs:line 258
   at SQLLiteExtensions.SQLAdvProcessingThread`1.DBRead(Action`1 action, UInt32 warnthreshold, String jobname) in C:\Code\EDDiscovery\BaseUtilities\SQLLite\SQLLite\SQLAdvProcessingThread.cs:line 48
   at EliteDangerousCore.DB.SystemCache.GetSystemListBySqDistancesFrom(SortedListDoubleDuplicate`1 distlist, Double x, Double y, Double z, Int32 maxitems, Double mindist, Double maxdist, Boolean spherical) in C:\Code\EDDiscovery\EliteDangerousCore\EliteDangerous\SystemDB\SystemCache.cs:line 304
   at EliteDangerousCore.StarDistanceComputer.BackgroundStardistWorkerThread() in C:\Code\EDDiscovery\EliteDangerousCore\EliteDangerous\Computers\StarDistanceComputer.cs:line 101
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.ThreadHelper.ThreadStart()
===== END =====

**Comment by Rev1008** [comment]
Opened programOn Jun 13, 2022 14:09, Eahlstan ***@***.***> wrote:
What did you do before this?

**Comment by Rev1008** [comment]
It's like its freezing and then sometime starts workingOn Jun 13, 2022 15:04, Cody Chamberlain ***@***.***> wrote:Opened programOn Jun 13, 2022 14:09, Eahlstan ***@***.***> wrote:
What did you do before this?

**Comment by Eahlstan** [comment]
Your EDDSystem.sqlite might be damaged. Please navigate to the folder that contains it (default %localappdata%\EDDiscovery ) and rename EDDSystem.sqlite to something else (e.g. EDDSystemOriginal.sqlite) and then start EDDiscovery. This will trigger a rebuild of this DB. Don't close EDDiscovery while this DB is being built - it takes about 3 hours on a SSD and up to a few days on a HDD (so better don't use a HDD for this DB, select "None" in the popup after starting that asks you which systems to download). Closing EDDiscovery while this DB is being built can damage the DB.
