### ISSUE TITLE
unhandled fatal exception error

### ISSUE THREAD

**Issue by strapkass** [EDDiscovery/EDDiscovery#3305]
An unhandled fatal exception has occurred.

==== BEGIN ====
SQLLiteExtensions.SQLProcessingThreadException: SQL logic error
no such table: Systems ---> System.Data.SQLite.SQLiteException: SQL logic error
no such table: Systems
   at System.Data.SQLite.SQLite3.Prepare(SQLiteConnection cnn, String strSql, SQLiteStatement previous, UInt32 timeoutMS, String& strRemain)
   at System.Data.SQLite.SQLiteCommand.BuildNextCommand()
   at System.Data.SQLite.SQLiteDataReader.NextResult()
   at System.Data.SQLite.SQLiteDataReader..ctor(SQLiteCommand cmd, CommandBehavior behave)
   at System.Data.SQLite.SQLiteCommand.ExecuteReader(CommandBehavior behavior)
   at EliteDangerousCore.DB.SystemsDB.GetSystemListBySqDistancesFrom(SortedListDoubleDuplicate`1 distlist, Double x, Double y, Double z, Int32 maxitems, Double mindist, Double maxdist, Boolean spherical, SQLiteConnectionSystem cn, Action`1 LookedUp) in C:\Code\EDDiscovery\EliteDangerousCore\EliteDangerous\SystemDB\SystemsDBGetByDistance.cs:line 80
   at EliteDangerousCore.DB.SystemCache.<>c__DisplayClass9_0.<GetSystemListBySqDistancesFrom>b__0(SQLiteConnectionSystem cn) in C:\Code\EDDiscovery\EliteDangerousCore\EliteDangerous\SystemDB\SystemCache.cs:line 302
   at SQLLiteExtensions.SQLAdvProcessingThread`1.<>c__DisplayClass19_0.<DBRead>b__0() in C:\Code\EDDiscovery\BaseUtilities\SQLLite\SQLLite\SQLAdvProcessingThread.cs:line 47
   at SQLLiteExtensions.Job`1.Exec() in C:\Code\EDDiscovery\BaseUtilities\SQLLite\SQLLite\SQLAdvProcessingThread.cs:line 355
   --- End of inner exception stack trace ---
   at SQLLiteExtensions.Job`1.Wait() in C:\Code\EDDiscovery\BaseUtilities\SQLLite\SQLLite\SQLAdvProcessingThread.cs:line 374
   at SQLLiteExtensions.SQLAdvProcessingThread`1.Execute[T](Func`1 func, Boolean write, UInt32 warnthreshold, String jobname) in C:\Code\EDDiscovery\BaseUtilities\SQLLite\SQLLite\SQLAdvProcessingThread.cs:line 258
   at SQLLiteExtensions.SQLAdvProcessingThread`1.DBRead(Action`1 action, UInt32 warnthreshold, String jobname) in C:\Code\EDDiscovery\BaseUtilities\SQLLite\SQLLite\SQLAdvProcessingThread.cs:line 48
   at EliteDangerousCore.DB.SystemCache.GetSystemListBySqDistancesFrom(SortedListDoubleDuplicate`1 distlist, Double x, Double y, Double z, Int32 maxitems, Double mindist, Double maxdist, Boolean spherical) in C:\Code\EDDiscovery\EliteDangerousCore\EliteDangerous\SystemDB\SystemCache.cs:line 304
   at EliteDangerousCore.StarDistanceComputer.BackgroundStardistWorkerThread() in C:\Code\EDDiscovery\EliteDangerousCore\EliteDangerous\Computers\StarDistanceComputer.cs:line 101
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.ThreadHelper.ThreadStart()
===== END =====

**Comment by Eahlstan** [comment]
Your systems DB is broken, please close EDD go to %localappdata%\EDDiscovery locate EDDSystem.sqlite, move it to a backup location (just for the unlikely case it's not broken) and start EDD again to trigger the recreation process.

If you decided to download data from EDSM and fill the DB do not close EDD while the DB is being built (HDDs are too slow for it, even on SSDs a full build can take 2 hours or more) as closing EDD can damage the DB file (it shouldn't but the past revealed that closing EDD is a bad idea).

**Comment by robbyxp1** [comment]
Closed as answered
