### ISSUE TITLE
Unhandled fatal exception

### ISSUE THREAD

**Issue by Amaterasu-OwO** [EDDiscovery/EDDiscovery#3310]
When using the route finder for a long route 395 jumps or higher with the metric "nearest to waypoint" am met with this error the detail drop down of the error presents this

```
System.ArgumentNullException: Value cannot be null.
Parameter name: source
   at System.Linq.Enumerable.Where[TSource](IEnumerable`1 source, Func`2 predicate)
   at EliteDangerousCore.RoutePlotter.GetBestEDSMSystem(Point3D currentPosition, Point3D travelVectorPerLy, Single maxDistanceFromWanted, Single maxRange) in C:\Code\EDDiscovery\EliteDangerousCore\EliteDangerous\Computers\RoutePlotter.cs:line 158
   at EliteDangerousCore.RoutePlotter.RouteIterative(Action`1 info) in C:\Code\EDDiscovery\EliteDangerousCore\EliteDangerous\Computers\RoutePlotter.cs:line 86
   at EDDiscovery.UserControls.UserControlRoute.RoutingThread(Object _plotter) in C:\Code\EDDiscovery\EDDiscovery\UserControls\RoutesExpeditions\UserControlRoute.cs:line 494
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.ThreadHelper.ThreadStart(Object obj)
```

**Comment by Amaterasu-OwO** [comment]
![Screenshot (17)](https://user-images.githubusercontent.com/112890035/188483535-77a3822d-4227-4df7-a593-07056d46d763.png)
screenshot of error message

**Comment by robbyxp1** [comment]
I wonder if EDSM is returning a system with no co-ordinates.  Try turning off use EDSM button.

**Comment by Eahlstan** [comment]
> I wonder if EDSM is returning a system with no co-ordinates. Try turning off use EDSM button.

Do we have something that catches error returns when hitting the API limit?

**Comment by Eahlstan** [comment]
> > I wonder if EDSM is returning a system with no co-ordinates. Try turning off use EDSM button.
> 
> Can confirm this is the issue, did the same route without the EDSM button disabled and was able to fully generate the route

Could you please export your route and upload it here so we can have a look at the systems?

**Comment by Amaterasu-OwO** [comment]
> 

[ExpeditionGrid.csv](https://github.com/EDDiscovery/EDDiscovery/files/9491140/ExpeditionGrid.csv)
[Exploration trip.csv](https://github.com/EDDiscovery/EDDiscovery/files/9491141/Exploration.trip.csv)


this is the same route exported from the route finder and expedition grid since I couldn't figure out which one would be better for yall to look at

**Comment by Eahlstan** [comment]
First thing I notice is that we really should stop querying EDSM for WAYPOINT as this is an EDD hint and not a real system.

**Comment by Eahlstan** [comment]
```
System.ArgumentNullException
  HResult=0x80004003
  Message=Der Wert darf nicht NULL sein.
Parametername: source
  Source=System.Core
  StackTrace:
   at System.Linq.Enumerable.Where[TSource](IEnumerable`1 source, Func`2 predicate)
   at EliteDangerousCore.RoutePlotter.GetBestEDSMSystem(Point3D currentPosition, Point3D travelVectorPerLy, Single maxDistanceFromWanted, Single maxRange) in F:\Git\EDDiscovery\Original\EDDiscovery\EliteDangerousCore\EliteDangerous\Computers\RoutePlotter.cs:line 158
   at EliteDangerousCore.RoutePlotter.RouteIterative(Action`1 info) in F:\Git\EDDiscovery\Original\EDDiscovery\EliteDangerousCore\EliteDangerous\Computers\RoutePlotter.cs:line 86
   at EDDiscovery.UserControls.UserControlRoute.RoutingThread(Object _plotter) in F:\Git\EDDiscovery\Original\EDDiscovery\EDDiscovery\UserControls\RoutesExpeditions\UserControlRoute.cs:line 494
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.ThreadHelper.ThreadStart(Object obj)
```

Like I thought @robbyxp1 it's happening when reaching the EDSM limit.

```
2022-09-05T16:34:28.739Z: WebExceptionDer Remoteserver hat einen Fehler zurückgegeben: (429) Too Many Requests.: 
2022-09-05T16:34:28.740Z: HTTP Error code: 429: 
2022-09-05T16:34:28.740Z: HTTP Error body: {}: 
```

**Comment by robbyxp1** [comment]
Noted
