### ISSUE TITLE
VoicePack Crash

### ISSUE THREAD

**Issue by Tomcatt** [EDDiscovery/EDDiscovery#3337]
Hello,

Not sure what changed on my system, but the VoicePack crashes EDD.  If I go in and delete the two files, EDD works just fine.  Is there a setting somewhere I need to remove or modify?

I've downgraded EDD and downgraded the VP, and still no joy.  I've even cleaned everything out and reinstalled it, and it still doesn't work.  Is there another directory where files are stored?

**Comment by Eahlstan** [comment]
%localappdata%\EDDiscovery

But that's really strange, no action files should be able to crash EDD. Is there any error message? Please upload the *.log files made by EDD in its Log folder.

**Comment by Tomcatt** [comment]
### Description


### Additional Information


### Exception Details:
>EDDiscovery v15.1.4.0 There was an unhandled UI exception.
>```
>==== BEGIN ====
>code = Corrupt (11), message = System.Data.SQLite.SQLiteException (0x800007EF): database disk image is malformed
>database disk image is malformed
>   at System.Data.SQLite.SQLite3.Reset(SQLiteStatement stmt)
>   at System.Data.SQLite.SQLite3.Step(SQLiteStatement stmt)
>   at System.Data.SQLite.SQLiteDataReader.NextResult()
>   at System.Data.SQLite.SQLiteDataReader..ctor(SQLiteCommand cmd, CommandBehavior behave)
>   at System.Data.SQLite.SQLiteCommand.ExecuteReader(CommandBehavior behavior)
>   at EliteDangerousCore.DB.SystemsDB.FindStar(String name, SQLiteConnectionSystem cn) in C:\Code\EDDiscovery\EliteDangerousCore\EliteDangerous\SystemDB\SystemsDBGetStars.cs:line 47
>   at EliteDangerousCore.DB.SystemCache.FindSystemInCacheDB(ISystem find, SQLiteConnectionSystem cn) in C:\Code\EDDiscovery\EliteDangerousCore\EliteDangerous\SystemDB\SystemCache.cs:line 139
>   at SQLLiteExtensions.Job`1.Exec() in C:\Code\EDDiscovery\BaseUtilities\SQLLite\SQLLite\SQLAdvProcessingThread.cs:line 355
>===== END =====
>```

I just got this one after deleting a VP.  Where are the logs stored, please?

**Comment by Eahlstan** [comment]
Looks like your DB is dead. Please close EDD, move EDDUser.sqlite to another place and start EDD to make it create a new DB. If everything works with the new DB (you'll have to redo all your settings) delete the old DB.

**Comment by Eahlstan** [comment]
Looks like your system DB is dead, please move EDDSystem.sqlite to another place to trigger a rebuild. If this fixes it delete the moved DB.

**Comment by Tomcatt** [comment]
Did I have a bad shutdown?  I always close EDD before shutting down the computer.

**Comment by Eahlstan** [comment]
It's impossible to say what causes such corruption. Robby and I torture our DBs more than any user and never were able to corrupt them, so it seems like it's a random problem that's impossible to pin down. Might be bad hardware, might be bad software, might be cosmic rays flipping bits...

**Comment by Tomcatt** [comment]
[2022-11-04T11:33:24.174Z] Update Pack Scout Report
[2022-11-04T11:33:24.174Z] Update Pack KeyPressesV6
[2022-11-04T11:33:24.175Z] Update Pack chatconsole
[2022-11-04T11:33:24.175Z] Update Pack Canonn
[2022-11-04T11:33:24.175Z] Update Pack TGMS_Bookmarks
[2022-11-04T11:33:24.181Z] Add pack VoicePackV19
[2022-11-04T11:33:24.181Z] PRINT ****
[2022-11-04T11:33:24.193Z] PRINT ChatConsole ready!
[2022-11-04T11:33:24.194Z] PRINT Setting voice pack control to default values, use the Add-On menu Voice Pack Configuration to reconfigure


Just reinstalled the VP and it's doing it again.  Just hanging.  Can't click on anything.

**Comment by Eahlstan** [comment]
Log file of this latest thing, please.

**Comment by Tomcatt** [comment]
[Trace_2022-11-04-20-12-08.0.log](https://github.com/EDDiscovery/EDDiscovery/files/9937877/Trace_2022-11-04-20-12-08.0.log)

**Comment by robbyxp1** [comment]
The log is moaning about everything being very slow.  Updates to the panels is slow, and there is warnings about updating the DB being slow.

[2022-11-04T11:42:55.473Z] Warning access to DB to write new journal entries slow 239

Are you running anything else at the same time (excepting Elite?) What antivirus are you running? etc.

For some reason, EDD is running at a very slow pace.

**Comment by Tomcatt** [comment]
Running slow?  I don't geet that.  I've always had ED:Market, ED Engineer and some music going on.  Sounds like it's being throttled.

**Comment by robbyxp1** [comment]
Its unusual to see the db message especially.

**Comment by Tomcatt** [comment]
Where is the Configuration file for VP located?

**Comment by Tomcatt** [comment]
[Trace_2022-11-04-22-53-18.0.log](https://github.com/EDDiscovery/EDDiscovery/files/9939073/Trace_2022-11-04-22-53-18.0.log)

Normal shutdown without VP installed.

**Comment by Eahlstan** [comment]
So, no hanging?

**Comment by Tomcatt** [comment]
WIth no VP install, it runs like normal, no issues.

**Comment by Eahlstan** [comment]
Given your 

> I always have big, very odd issues when computers/apps don't work no more.

remark I guess that something is very wrong with your whole system. VP uses the Windows speech system, so if it hangs using VP and doesn't hang without it it might be that something conflicts there.

There's no sign of any error regarding this in any of your logs, so it's most likely not a problem of EDD.

**Comment by Tomcatt** [comment]
Why does CAPI want to log in so bad?

**Comment by Eahlstan** [comment]
Because you told it to.

**Comment by Tomcatt** [comment]
LOL
I wonder if it's this all anything to do with Windows?  Not sure how.

**Comment by Tomcatt** [comment]
PRINT Setting voice pack control to default values, use the Add-On menu Voice Pack Configuration to reconfigure

Where is this file located?  Maybe there are some settings in there the app doesn't like.

**Comment by Eahlstan** [comment]
There's no options file. All settings done in that menu are directly written to the .act file.

**Comment by Tomcatt** [comment]
Okay, how do I debug the .act file?  I'd soon start to REM outlines to see what happens.  

If it's having trouble using the Windows speech system, then I'd like to start there as well.

**Comment by klightspeed** [comment]
In your trace log, where there was nothing between 11:33 (when the voice pack was added) and 11:42 (when it started complaining about very slow database access), was EDDiscovery frozen for those 9 or 10 minutes?

The fact that it logged:
```
Setting voice pack control to default values, use the Add-On menu Voice Pack Configuration to reconfigure
```
but not
```
Voice Pack installed, running on EDD Version %version(1).%version(2).%version(3).%version(4)
```
suggests that it hung when either enumerating the installed voices or when trying to say welcome.

The fact that Free Voice Control also hung (did it get to saying `You have installed Free Voice Control`?) suggests that there is something screwy with the Text To Speech that isn't compatible with the dotnet `System.Speech` library (but presumably not a problem for whichever python TTS library EDCoPilot is using)

**Comment by Tomcatt** [comment]
Correct about it not giving me the welcome speech.  There was a .net update some time ago too.  (I hate dotnet, too many issues with it) and from the looks of it, that could be my problem.

**Comment by klightspeed** [comment]
Out of curiosity, what do you have set as your default voice in Settings -> Time & Language -> Speech -> Voices?

**Comment by Tomcatt** [comment]
![image](https://user-images.githubusercontent.com/6493668/200102508-a67daf87-de65-4ab3-b27c-2f446a44bf3a.png)

**Comment by robbyxp1** [comment]
I think we have determined its something up with your PC..  No one else is complaining about it.  Can't really see a pathway forwards..

Closing.
