### ISSUE TITLE
There was an unhandled UI exception.

### ISSUE THREAD

**Issue by amhaun01** [EDDiscovery/EDDiscovery#3342]
There was an unhandled UI exception.

==== BEGIN ====
OpenTK.Graphics.GraphicsContextException: Failed to make context 131072 current. Error: 0
   at OpenTK.Platform.Windows.WinGLContext.MakeCurrent(IWindowInfo window) in C:\Users\juliu\Documents\GitHub\opentk\src\OpenTK\Platform\Windows\WinGLContext.cs:line 279
   at EDDiscovery.UserControls.UserControl3DMap.SystemTick(Object sender, EventArgs e) in C:\Code\EDDiscovery\EDDiscovery\UserControls\3DMap\UserControl3DMap.cs:line 105
   at System.Windows.Forms.Timer.OnTick(EventArgs e)
   at System.Windows.Forms.Timer.TimerNativeWindow.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)
===== END =====

**Comment by robbyxp1** [comment]
See issue below this. Either the computer had been sleeping, or another issue had occurred. We are investigating but there is no obv answer.

Just restart the program.

Thanks for the report.
