### ISSUE TITLE
Unhandled Fatal Exception on Launch

### ISSUE THREAD

**Issue by Zakronia** [EDDiscovery/EDDiscovery#3350]
After updating EDDiscovery to v16.0.1.0, I now get this error whenever I try to launch the program.

```An unhandled fatal exception has occurred.

==== BEGIN ====
SQLLiteExtensions.SQLProcessingThreadException: Unable to cast object of type 'System.DBNull' to type 'System.String'. ---> System.InvalidCastException: Unable to cast object of type 'System.DBNull' to type 'System.String'.
   at EliteDangerousCore.DB.SystemNoteClass..ctor(DbDataReader dr) in C:\Code\EDDiscovery\EliteDangerousCore\EliteDangerous\DB\SystemNoteClass.cs:line 51
   at EliteDangerousCore.DB.SystemNoteClass.<>c.<GetAllSystemNotes>b__38_0(SQLiteConnectionUser cn) in C:\Code\EDDiscovery\EliteDangerousCore\EliteDangerous\DB\SystemNoteClass.cs:line 141
   at SQLLiteExtensions.Job`1.Exec() in C:\Code\EDDiscovery\BaseUtilities\SQLLite\SQLLite\SQLAdvProcessingThread.cs:line 355
   --- End of inner exception stack trace ---
   at SQLLiteExtensions.Job`1.Wait() in C:\Code\EDDiscovery\BaseUtilities\SQLLite\SQLLite\SQLAdvProcessingThread.cs:line 374
   at SQLLiteExtensions.SQLAdvProcessingThread`1.Execute[T](Func`1 func, Boolean write, UInt32 warnthreshold, String jobname) in C:\Code\EDDiscovery\BaseUtilities\SQLLite\SQLLite\SQLAdvProcessingThread.cs:line 258
   at SQLLiteExtensions.SQLAdvProcessingThread`1.DBRead[T](Func`2 func, UInt32 warnthreshold, String jobname) in C:\Code\EDDiscovery\BaseUtilities\SQLLite\SQLLite\SQLAdvProcessingThread.cs:line 42
   at EliteDangerousCore.DB.SystemNoteClass.GetAllSystemNotes() in C:\Code\EDDiscovery\EliteDangerousCore\EliteDangerous\DB\SystemNoteClass.cs:line 131
   at EDDiscovery.EDDiscoveryController.BackgroundWorkerThread() in C:\Code\EDDiscovery\EDDiscovery\EDDiscoveryControllerMain.cs:line 257
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.ThreadHelper.ThreadStart()
===== END =====```

**Comment by Zakronia** [comment]
I believe I had updated from 16.0.0

**Comment by klightspeed** [comment]
The stack trace suggests that there is a note in the database with a `null` `Note` column.

**Comment by robbyxp1** [comment]
Have you made a note since Tuesday at all?

**Comment by Zakronia** [comment]
I don’t recall having made any notes since Tuesday.

**Comment by robbyxp1** [comment]
Okay, we will release a fix by 10am UTC tomorrow, which will stop it going wrong.  We don't understand how it got a null field in the note.

**Comment by Zakronia** [comment]
Ok, thank you.

**Comment by robbyxp1** [comment]
16.0.2 should stop it happening. We have no idea why the DB had a null in that entry.
