### ISSUE TITLE
EDDiscovery v16.0.4.0 Fatal Error

### ISSUE THREAD

**Issue by eposone1979** [EDDiscovery/EDDiscovery#3367]
Hi there, happend today cant use the app now. When launching it it crashed after giving this error: 

An unhandled fatal exception has occurred.

```
==== BEGIN ====
SQLLiteExtensions.SQLProcessingThreadException: SQL logic error
no such table: Systems ---> System.Data.SQLite.SQLiteException: SQL logic error
no such table: Systems
   at System.Data.SQLite.SQLite3.Prepare(SQLiteConnection cnn, String strSql, SQLiteStatement previous, UInt32 timeoutMS, String& strRemain)
   at System.Data.SQLite.SQLiteCommand.BuildNextCommand()
   at System.Data.SQLite.SQLiteDataReader.NextResult()
   at System.Data.SQLite.SQLiteDataReader..ctor(SQLiteCommand cmd, CommandBehavior behave)
   at System.Data.SQLite.SQLiteCommand.ExecuteReader(CommandBehavior behavior)
   at EliteDangerousCore.DB.SystemsDB.GetSystemListBySqDistancesFrom(Double x, Double y, Double z, Int32 maxitems, Double mindist, Double maxdist, Boolean spherical, SQLiteConnectionSystem cn, Action`2 callback) in C:\Code\EDDiscovery\EliteDangerousCore\EliteDangerous\SystemDB\SystemsDBGetByDistance.cs:line 78
   at EliteDangerousCore.DB.SystemCache.<>c__DisplayClass9_0.<GetSystemListBySqDistancesFrom>b__0(SQLiteConnectionSystem cn) in C:\Code\EDDiscovery\EliteDangerousCore\EliteDangerous\SystemDB\SystemCache.cs:line 323
   at SQLLiteExtensions.SQLAdvProcessingThread`1.<>c__DisplayClass19_0.<DBRead>b__0() in C:\Code\EDDiscovery\BaseUtilities\SQLLite\SQLLite\SQLAdvProcessingThread.cs:line 47
   at SQLLiteExtensions.Job`1.Exec() in C:\Code\EDDiscovery\BaseUtilities\SQLLite\SQLLite\SQLAdvProcessingThread.cs:line 355
   --- End of inner exception stack trace ---
   at SQLLiteExtensions.Job`1.Wait() in C:\Code\EDDiscovery\BaseUtilities\SQLLite\SQLLite\SQLAdvProcessingThread.cs:line 374
   at SQLLiteExtensions.SQLAdvProcessingThread`1.Execute[T](Func`1 func, Boolean write, UInt32 warnthreshold, String jobname) in C:\Code\EDDiscovery\BaseUtilities\SQLLite\SQLLite\SQLAdvProcessingThread.cs:line 258
   at SQLLiteExtensions.SQLAdvProcessingThread`1.DBRead(Action`1 action, UInt32 warnthreshold, String jobname) in C:\Code\EDDiscovery\BaseUtilities\SQLLite\SQLLite\SQLAdvProcessingThread.cs:line 48
   at EliteDangerousCore.DB.SystemCache.GetSystemListBySqDistancesFrom(SortedListDoubleDuplicate`1 distlist, Double x, Double y, Double z, Int32 approxmaxitems, Double mindist, Double maxdist, Boolean spherical, HashSet`1 excludenames) in C:\Code\EDDiscovery\EliteDangerousCore\EliteDangerous\SystemDB\SystemCache.cs:line 325
   at EliteDangerousCore.StarDistanceComputer.BackgroundStardistWorkerThread() in C:\Code\EDDiscovery\EliteDangerousCore\EliteDangerous\Computers\StarDistanceComputer.cs:line 101
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.ThreadHelper.ThreadStart()
===== END =====
```

**Comment by Eahlstan** [comment]
See https://github.com/EDDiscovery/EDDiscovery/issues/3352 or https://github.com/EDDiscovery/EDDiscovery/issues/3277#issuecomment-1154352044

**Comment by eposone1979** [comment]
thanks fixed
