### ISSUE TITLE
System causing EDDiscovery to crash

### ISSUE THREAD

**Issue by EekaDroid** [EDDiscovery/EDDiscovery#3394]
Hello there!

After entering this undiscovered system ([Qiedea WX-F d12-5](https://www.edsm.net/en/system/id/50196435/name/Qiedea+WX-F+d12-5)) i was presented the following popup error:

![image](https://user-images.githubusercontent.com/74662657/225177289-c6711a90-6290-4584-b1d5-ccc206c2e0f3.png)

The details are as following:

An unhandled fatal exception has occurred.

==== BEGIN ====
SQLLiteExtensions.SQLProcessingThreadException: database disk image is malformed
database disk image is malformed ---> System.Data.SQLite.SQLiteException: database disk image is malformed
database disk image is malformed
   at System.Data.SQLite.SQLite3.Reset(SQLiteStatement stmt)
   at System.Data.SQLite.SQLite3.Step(SQLiteStatement stmt)
   at System.Data.SQLite.SQLiteDataReader.NextResult()
   at System.Data.SQLite.SQLiteDataReader..ctor(SQLiteCommand cmd, CommandBehavior behave)
   at System.Data.SQLite.SQLiteCommand.ExecuteReader(CommandBehavior behavior)
   at EliteDangerousCore.DB.SystemsDB.GetSystemListBySqDistancesFrom(Double x, Double y, Double z, Int32 maxitems, Double mindist, Double maxdist, Boolean spherical, SQLiteConnectionSystem cn, Action`2 callback) in C:\Code\EDDiscovery\EliteDangerousCore\EliteDangerous\SystemDB\SystemsDBGetByDistance.cs:line 78
   at EliteDangerousCore.DB.SystemCache.<>c__DisplayClass9_0.<GetSystemListBySqDistancesFrom>b__0(SQLiteConnectionSystem cn) in C:\Code\EDDiscovery\EliteDangerousCore\EliteDangerous\SystemDB\SystemCache.cs:line 323
   at SQLLiteExtensions.SQLAdvProcessingThread`1.<>c__DisplayClass19_0.<DBRead>b__0() in C:\Code\EDDiscovery\BaseUtilities\SQLLite\SQLLite\SQLAdvProcessingThread.cs:line 47
   at SQLLiteExtensions.Job`1.Exec() in C:\Code\EDDiscovery\BaseUtilities\SQLLite\SQLLite\SQLAdvProcessingThread.cs:line 355
   --- End of inner exception stack trace ---
   at SQLLiteExtensions.Job`1.Wait() in C:\Code\EDDiscovery\BaseUtilities\SQLLite\SQLLite\SQLAdvProcessingThread.cs:line 374
   at SQLLiteExtensions.SQLAdvProcessingThread`1.Execute[T](Func`1 func, Boolean write, UInt32 warnthreshold, String jobname) in C:\Code\EDDiscovery\BaseUtilities\SQLLite\SQLLite\SQLAdvProcessingThread.cs:line 258
   at SQLLiteExtensions.SQLAdvProcessingThread`1.DBRead(Action`1 action, UInt32 warnthreshold, String jobname) in C:\Code\EDDiscovery\BaseUtilities\SQLLite\SQLLite\SQLAdvProcessingThread.cs:line 48
   at EliteDangerousCore.DB.SystemCache.GetSystemListBySqDistancesFrom(SortedListDoubleDuplicate`1 distlist, Double x, Double y, Double z, Int32 approxmaxitems, Double mindist, Double maxdist, Boolean spherical, HashSet`1 excludenames) in C:\Code\EDDiscovery\EliteDangerousCore\EliteDangerous\SystemDB\SystemCache.cs:line 325
   at EliteDangerousCore.StarDistanceComputer.BackgroundStardistWorkerThread() in C:\Code\EDDiscovery\EliteDangerousCore\EliteDangerous\Computers\StarDistanceComputer.cs:line 101
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.ThreadHelper.ThreadStart()
===== END =====

Clicking exit will close EDD, but while i left the program opened in the background it worked normally registering the new system bodies.

Opening EDD while in this system leads to the same popup at the startup of the program.

This has happened to me another time back in august 2022, in the system [Eord Pri AS-B d13-2641](https://www.edsm.net/en/system/id/75794512/name/Eord+Pri+AS-B+d13-2641) but i cant confirm if the error details were the same, though the behavior was.

**Comment by EekaDroid** [comment]
Update in the issue. It is not related to a specific system, it happens every time i open EDDiscovery.

I renamed the EDDSystem.sqlite file to EDDSystem.sqlite.old and i'm redownloading the system data.

**Comment by robbyxp1** [comment]
Your system DB is borked.
Hold down shift when running EDD, and order it to delete the system DB. It will then rebuild it

Consider how this happened - what are you storing the system DB on?  How are you shutting down EDD? Are you letting it close properly?  Is it happening after sleeping the computer?

**Comment by robbyxp1** [comment]
Closing since you've fixed it

**Comment by EekaDroid** [comment]
hey robby, thanks for the quick response!

This database has all EDSM systems on it and i've been carrying it for a while now. It's stored in my second nvme SSD that is dedicated to games and so far all specs are healthy on it (i checked with CrystalDiskInfo before posting).

I also close the program correctly as habit (Tools -> Exit). 

The error popped as soon as i arrived in the mentioned system. Since it happened before, as i mentioned, i thought it was system-related as well (in the previous circumstance it only happened when jumping into that system). From this moment, it would appear after opening EDDiscovery, though the application would continue to work normally.

What i find strange about the EDDSystem.sqlite is that the old one has 5.57GBs and after i renamed it and let EDDiscovery download "All" star data again, the new EDDSystem.sqlite has only 46MBs.

I also use to rebuild index in both system and user databases, but this database never finished rebuilding it, despite waiting a lot of time. 

It is working perfectly now, i just wanted to add more info to the case.

Thanks for the development in this application, it is absolutely amazing!
