### ISSUE TITLE
Unhandled UI exception

### ISSUE THREAD

**Issue by SkeepyC** [EDDiscovery/EDDiscovery#3399]
### Description
I recently reinstalled EDD with the updated version. So I had to redownload everything like EDSM Star database (which takes a phenomenal time ^^' ) and during the process this appeared. (i'm not even sure if this is the reason for the error)

Thanks in advance ! 

### Additional Information
![image](https://user-images.githubusercontent.com/63789123/227809252-77d78cc4-618d-4cb4-9a6f-f9d1e7f5bb54.png)
I take this opportunity to ask you if it's normal that the number on the left doesn't move. Each million that is added to the right makes me despair even more...

### Exception Details:
>EDDiscovery v16.0.5.0 There was an unhandled UI exception.
>```
>==== BEGIN ====
>code = Busy (5), message = System.Data.SQLite.SQLiteException (0x800007AF): database is locked
>database is locked
>   à System.Data.SQLite.SQLite3.Step(SQLiteStatement stmt)
>   à System.Data.SQLite.SQLiteDataReader.NextResult()
>   à System.Data.SQLite.SQLiteDataReader..ctor(SQLiteCommand cmd, CommandBehavior behave)
>   à System.Data.SQLite.SQLiteCommand.ExecuteReader(CommandBehavior behavior)
>   à System.Data.SQLite.SQLiteCommand.ExecuteScalar(CommandBehavior behavior)
>   à SQLiteCommandExtensions.ExecuteScalar[T](DbCommand cmd, T def) dans C:\Code\EDDiscovery\BaseUtilities\SQLLite\SQLLite\SQLExtensions.cs:ligne 93
>   à EliteDangerousCore.DB.SystemsDB.FindAlias(Int64 edsmid, String name, SQLiteConnectionSystem cn) dans C:\Code\EDDiscovery\EliteDangerousCore\EliteDangerous\SystemDB\SystemsDBEDSMSystemAliases.cs:ligne 153
>   à EliteDangerousCore.DB.SystemCache.FindSystemInCacheDB(ISystem find, SQLiteConnectionSystem cn) dans C:\Code\EDDiscovery\EliteDangerousCore\EliteDangerous\SystemDB\SystemCache.cs:ligne 146
>   à SQLLiteExtensions.Job`1.Exec() dans C:\Code\EDDiscovery\BaseUtilities\SQLLite\SQLLite\SQLAdvProcessingThread.cs:ligne 355
>===== END =====
>```

**Comment by SkeepyC** [comment]
Update : 
I pressed continue on the error panel and now the database is downloaded, which confirm the fact that the error is not linked to the download.

**Comment by klightspeed** [comment]
This suggests that the Systems database job processor is allowing reads to go through while the database is being written to, or allowing writes to occur when the database should be in read-only mode.  Either that, or it's not properly closing the database when switching the database from single-threaded read-write to multi-threaded read-only mode.

**Comment by nemo1n** [comment]
> ### Description
> I recently reinstalled EDD with the updated version. So I had to redownload everything like EDSM Star database (which takes a phenomenal time ^^' ) and during the process this appeared. (i'm not even sure if this is the reason for the error)
> 
> Thanks in advance !
> 
> ### Additional Information
> ![image](https://user-images.githubusercontent.com/63789123/227809252-77d78cc4-618d-4cb4-9a6f-f9d1e7f5bb54.png) I take this opportunity to ask you if it's normal that the number on the left doesn't move. Each million that is added to the right makes me despair even more...
> 
> ### Exception Details:
> > EDDiscovery v16.0.5.0 There was an unhandled UI exception.
> > ```
> > ==== BEGIN ====
> > code = Busy (5), message = System.Data.SQLite.SQLiteException (0x800007AF): database is locked
> > database is locked
> >   à System.Data.SQLite.SQLite3.Step(SQLiteStatement stmt)
> >   à System.Data.SQLite.SQLiteDataReader.NextResult()
> >   à System.Data.SQLite.SQLiteDataReader..ctor(SQLiteCommand cmd, CommandBehavior behave)
> >   à System.Data.SQLite.SQLiteCommand.ExecuteReader(CommandBehavior behavior)
> >   à System.Data.SQLite.SQLiteCommand.ExecuteScalar(CommandBehavior behavior)
> >   à SQLiteCommandExtensions.ExecuteScalar[T](DbCommand cmd, T def) dans C:\Code\EDDiscovery\BaseUtilities\SQLLite\SQLLite\SQLExtensions.cs:ligne 93
> >   à EliteDangerousCore.DB.SystemsDB.FindAlias(Int64 edsmid, String name, SQLiteConnectionSystem cn) dans C:\Code\EDDiscovery\EliteDangerousCore\EliteDangerous\SystemDB\SystemsDBEDSMSystemAliases.cs:ligne 153
> >   à EliteDangerousCore.DB.SystemCache.FindSystemInCacheDB(ISystem find, SQLiteConnectionSystem cn) dans C:\Code\EDDiscovery\EliteDangerousCore\EliteDangerous\SystemDB\SystemCache.cs:ligne 146
> >   à SQLLiteExtensions.Job`1.Exec() dans C:\Code\EDDiscovery\BaseUtilities\SQLLite\SQLLite\SQLAdvProcessingThread.cs:ligne 355
> > ===== END =====
> > ```

### Description


### Additional Information


### Exception Details:
>EDDiscovery v16.0.5.0 There was an unhandled UI exception.
>```
>==== BEGIN ====
>code = Busy (5), message = System.Data.SQLite.SQLiteException (0x800007AF): database is locked
>database is locked
>   at System.Data.SQLite.SQLite3.Step(SQLiteStatement stmt)
>   at System.Data.SQLite.SQLiteDataReader.NextResult()
>   at System.Data.SQLite.SQLiteDataReader..ctor(SQLiteCommand cmd, CommandBehavior behave)
>   at System.Data.SQLite.SQLiteCommand.ExecuteReader(CommandBehavior behavior)
>   at System.Data.SQLite.SQLiteCommand.ExecuteScalar(CommandBehavior behavior)
>   at SQLiteCommandExtensions.ExecuteScalar[T](DbCommand cmd, T def) in C:\Code\EDDiscovery\BaseUtilities\SQLLite\SQLLite\SQLExtensions.cs:line 93
>   at EliteDangerousCore.DB.SystemsDB.FindAlias(Int64 edsmid, String name, SQLiteConnectionSystem cn) in C:\Code\EDDiscovery\EliteDangerousCore\EliteDangerous\SystemDB\SystemsDBEDSMSystemAliases.cs:line 153
>   at EliteDangerousCore.DB.SystemCache.FindSystemInCacheDB(ISystem find, SQLiteConnectionSystem cn) in C:\Code\EDDiscovery\EliteDangerousCore\EliteDangerous\SystemDB\SystemCache.cs:line 146
>   at SQLLiteExtensions.Job`1.Exec() in C:\Code\EDDiscovery\BaseUtilities\SQLLite\SQLLite\SQLAdvProcessingThread.cs:line 355
>===== END =====
>```

**Comment by robbyxp1** [comment]
The DBs do not work in the way described above any more, that was removed a few years ago.

I cannot reproduce this behaviour on my machine, and have never seen this, so it makes it hard to debug.

**Comment by klightspeed** [comment]
> The DBs do not work in the way described above any more, that was removed a few years ago.
> 
> I cannot reproduce this behaviour on my machine, and have never seen this, so it makes it hard to debug.

Try to do something that requires resolving a system while the systems database is being built / rebuilt?

**Comment by Eahlstan** [comment]
Do AV programs put a lock on files while scanning them?

**Comment by klightspeed** [comment]
> Do AV programs put a lock on files while scanning them?

`database is locked` means that another thread or process has the database opened using the SQLite library using a lock that is incompatible with the lock being requested - e.g. in this case where another thread or process is writing to the database using the SQLite library while the UI thread has requested a read from the database.

A sharing violation will result in `unable to open database file`
Trying to read a part of the database that has an OS-level range lock will result in `disk I/O error`

**Comment by robbyxp1** [comment]
So, I've tried to repo, but can't. In fact, it never goes wrong here. In fact, consider the number of people using the program, this issue is rare.

I'm afraid I can't debug this one. 

This ticket will be closed in a few days unless we can find a way of repo it.

**Comment by robbyxp1** [comment]
A change has been introduced to keep trying even if the disk is very slow. This may, or may not, fix something in some peoples systems.

Closing now, issue noted, will be monitored.
