### ISSUE TITLE
Exception message when wake up from sleep

### ISSUE THREAD

**Issue by dymm2000** [EDDiscovery/EDDiscovery#3447]
==== BEGIN ====
OpenTK.Graphics.GraphicsContextException: Failed to make context 65537 current. Error: 0
   at OpenTK.Platform.Windows.WinGLContext.MakeCurrent(IWindowInfo window) in C:\Users\juliu\Documents\GitHub\opentk\src\OpenTK\Platform\Windows\WinGLContext.cs:line 279
   at EDDiscovery.UserControls.UserControl3DMap.SystemTick(Object sender, EventArgs e) in C:\Code\EDDiscovery\EDDiscovery\UserControls\3DMap\UserControl3DMap.cs:line 109
   at System.Windows.Forms.Timer.OnTick(EventArgs e)
   at System.Windows.Forms.Timer.TimerNativeWindow.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)
===== END =====

**Comment by dymm2000** [comment]
Duplicated
