### ISSUE TITLE
unhandled UI exception

### ISSUE THREAD

**Issue by ZManak** [EDDiscovery/EDDiscovery#3466]
### Exception Details:
>EDDiscovery v17.0.1.0 There was an unhandled UI exception.
>```
>==== BEGIN ====
>System.NullReferenceException: Object reference not set to an instance of an object.
>   at EDDiscovery.EDDiscoveryForm.extButtonNewFeature_Click(Object sender, EventArgs e) in C:\Code\EDDiscovery\EDDiscovery\EDD\EDDiscoveryForm.cs:line 1172
>   at System.Windows.Forms.Control.OnClick(EventArgs e)
>   at System.Windows.Forms.Button.OnMouseUp(MouseEventArgs mevent)
>   at System.Windows.Forms.Control.WmMouseUp(Message& m, MouseButtons button, Int32 clicks)
>   at System.Windows.Forms.Control.WndProc(Message& m)
>   at System.Windows.Forms.ButtonBase.WndProc(Message& m)
>   at System.Windows.Forms.Button.WndProc(Message& m)
>   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)
>===== END =====
>```

**Comment by ZManak** [comment]
Glad you could fix it. I do not recall exactly what I was doing at the moment, just navigating trought the tabs when the "NEW" indicator appeared.

**Comment by robbyxp1** [comment]
Yep, you used a roll up bar, and when  you rolled it down, the button which should have been hidden appeared.  Thanks for the bug report
