### ISSUE TITLE
There was an unhandled UI exception

### ISSUE THREAD

**Issue by VonDugard** [EDDiscovery/EDDiscovery#3507]
OpenTK.Graphics.GraphicsContextException: Failed to make context 65537 current. Error: 0
   at OpenTK.Platform.Windows.WinGLContext.MakeCurrent(IWindowInfo window) in C:\Users\juliu\Documents\GitHub\opentk\src\OpenTK\Platform\Windows\WinGLContext.cs:line 279
   at EDDiscovery.UserControls.UserControl3DMap.SystemTick(Object sender, EventArgs e) in C:\Code\EDDiscovery\EDDiscovery\UserControls\3DMap\UserControl3DMap.cs:line 111
   at System.Windows.Forms.Timer.OnTick(EventArgs e)
   at System.Windows.Forms.Timer.TimerNativeWindow.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wpara

**Comment by robbyxp1** [comment]
Did you wake the computer from sleep?

**Comment by VonDugard** [comment]
No

**Comment by klightspeed** [comment]
What OS version and graphics card are you using?

**Comment by VonDugard** [comment]
Windows 10 Pro
22H2
19045'4355
NVIDIA Geforce RTX 2080 SUPER

**Comment by robbyxp1** [comment]
Normally this happens if you have the 3dmap open and the computer sleeps, as the GL context is not kept over a sleep

Is it still happening?  if not, then just treat it as a one off.

**Comment by VonDugard** [comment]
Ok, I'll check it out.

**Comment by robbyxp1** [comment]
Closing, no further info
