### ISSUE TITLE
CMDR no longer selectable and other bugs

### ISSUE THREAD

**Issue by genen** [EDDiscovery/EDDiscovery#3546]
I updated to 18.0.6.0 to get the new voice pack, and the entire App is no longer usable. 

The problem is the commander can not be selected like in previous version as it just shows a grayed out Cmdr. 

Also the log contains several lines in RED about null pointers.  I tried rebuilding the database and rereading logs, but errors do not go away. 

`****
Scanning for bmp screenshots in C:\Users\gene\OneDrive\Pictures\Frontier Developments\Elite Dangerous
*** Web server is disabled ***
DLLs loaded: EDDCanonn
Profile Default Loaded
Loaded Bindings C:\Users\gene\AppData\Local\Frontier Developments\Elite Dangerous\Options\Bindings\GameGlass.4.1.binds
CAPI Installed
Loaded Notes, Bookmarks and Galactic mapping.
Reading travel history
Get galactic mapping from EDSM.
ChatConsole ready!
****
Voice Pack installed, running on EDD Version 18.0.6.0
*** Unknown Module { "paintjob_diamondbackxl_operator_gold", new ShipModule(-1,ShipModule.ModuleTypes.VanityType,"Paint Job Diamondbackxl Operator Gold") }, - this is NOT an error, it will not affect operation, but it would be nice to report it to us so we can add it to known module lists
*** Unknown Module { "paintjob_vulture_operator_gold", new ShipModule(-1,ShipModule.ModuleTypes.VanityType,"Paint Job Vulture Operator Gold") }, - this is NOT an error, it will not affect operation, but it would be nice to report it to us so we can add it to known module lists
*** Unknown Module { "paintjob_empire_eagle_metallic2_gold", new ShipModule(-1,ShipModule.ModuleTypes.VanityType,"Paint Job Empire Eagle Metallic 2 Gold") }, - this is NOT an error, it will not affect operation, but it would be nice to report it to us so we can add it to known module lists
*** Unknown Module { "paintjob_vulture_salvage_03", new ShipModule(-1,ShipModule.ModuleTypes.VanityType,"Paint Job Vulture Salvage 3") }, - this is NOT an error, it will not affect operation, but it would be nice to report it to us so we can add it to known module lists
*** Unknown Module { "paintjob_asp_turbulence_06", new ShipModule(-1,ShipModule.ModuleTypes.VanityType,"Paint Job Asp Turbulence 6") }, - this is NOT an error, it will not affect operation, but it would be nice to report it to us so we can add it to known module lists
*** Unknown Module { "paintjob_mamba_racing_01", new ShipModule(-1,ShipModule.ModuleTypes.VanityType,"Paint Job Mamba Racing 1") }, - this is NOT an error, it will not affect operation, but it would be nice to report it to us so we can add it to known module lists
*** Unknown Module { "paintjob_empiretrader_metallic2_gold", new ShipModule(-1,ShipModule.ModuleTypes.VanityType,"Paint Job Empiretrader Metallic 2 Gold") }, - this is NOT an error, it will not affect operation, but it would be nice to report it to us so we can add it to known module lists
*** Unknown Module { "paintjob_mamba_operator_gold", new ShipModule(-1,ShipModule.ModuleTypes.VanityType,"Paint Job Mamba Operator Gold") }, - this is NOT an error, it will not affect operation, but it would be nice to report it to us so we can add it to known module lists
*** Unknown Module { "paintjob_type8_haulage_01", new ShipModule(-1,ShipModule.ModuleTypes.VanityType,"Paint Job Type 8 Haulage 1") }, - this is NOT an error, it will not affect operation, but it would be nice to report it to us so we can add it to known module lists
*** Unknown Module { "type8_shipkitc_wings1", new ShipModule(-1,ShipModule.ModuleTypes.VanityType,"Type 8 Shipkitc Wings 1") }, - this is NOT an error, it will not affect operation, but it would be nice to report it to us so we can add it to known module lists
Get galactic mapping from GEC.
History Refresh Error: System.NullReferenceException: Object reference not set to an instance of an object.
   at EliteDangerousCore.EngineerCrafting.Process(HistoryEntry he) in C:\Code\EDDiscovery\EliteDangerousCore\EliteDangerous\Stats\EngineerCrafting.cs:line 36
   at EliteDangerousCore.HistoryList.MakeHistoryEntry(JournalEntry je) in C:\Code\EDDiscovery\EliteDangerousCore\EliteDangerous\HistoryList\HistoryList.cs:line 75
   at EliteDangerousCore.HistoryList.LoadHistory(HistoryList hist, Action`2 reportProgress, CancellationToken cancelRequested, Int32 commanderid, String cmdname, Int32 fullhistoryloaddaylimit, JournalTypeEnum[] loadedbeforelimitids, Nullable`1 maxdateload) in C:\Code\EDDiscovery\EliteDangerousCore\EliteDangerous\HistoryList\HistoryList.cs:line 196
   at EDDiscovery.EDDiscoveryController.DoRefreshHistory(RefreshWorkerArgs args) in C:\Code\EDDiscovery\EDDiscovery\EDD\EDDiscoveryControllerHistory.cs:line 0
Error: Cannot find entry in Ledger
At Step 3 in VoicePackV22::onRefreshEnd:1047: Ledger
System data download from SPANSH required.
This will take a while, please be patient.
Please continue running ED Discovery until refresh is complete.
History refresh complete.
CAPI Refresh Succeeded
CAPI User Logged in to Live using ATLAS RAND
Web server enabled
*** Web server is disabled ***
History Refresh Error: System.NullReferenceException: Object reference not set to an instance of an object.
   at EliteDangerousCore.EngineerCrafting.Process(HistoryEntry he) in C:\Code\EDDiscovery\EliteDangerousCore\EliteDangerous\Stats\EngineerCrafting.cs:line 36
   at EliteDangerousCore.HistoryList.MakeHistoryEntry(JournalEntry je) in C:\Code\EDDiscovery\EliteDangerousCore\EliteDangerous\HistoryList\HistoryList.cs:line 75
   at EliteDangerousCore.HistoryList.LoadHistory(HistoryList hist, Action`2 reportProgress, CancellationToken cancelRequested, Int32 commanderid, String cmdname, Int32 fullhistoryloaddaylimit, JournalTypeEnum[] loadedbeforelimitids, Nullable`1 maxdateload) in C:\Code\EDDiscovery\EliteDangerousCore\EliteDangerous\HistoryList\HistoryList.cs:line 196
   at EDDiscovery.EDDiscoveryController.DoRefreshHistory(RefreshWorkerArgs args) in C:\Code\EDDiscovery\EDDiscovery\EDD\EDDiscoveryControllerHistory.cs:line 0
CAPI Logged Out
History refresh complete.
CAPI Refresh Succeeded
CAPI User Logged in to Live using ATLAS RAND
History Refresh Error: System.NullReferenceException: Object reference not set to an instance of an object.
   at EliteDangerousCore.EngineerCrafting.Process(HistoryEntry he) in C:\Code\EDDiscovery\EliteDangerousCore\EliteDangerous\Stats\EngineerCrafting.cs:line 36
   at EliteDangerousCore.HistoryList.MakeHistoryEntry(JournalEntry je) in C:\Code\EDDiscovery\EliteDangerousCore\EliteDangerous\HistoryList\HistoryList.cs:line 75
   at EliteDangerousCore.HistoryList.LoadHistory(HistoryList hist, Action`2 reportProgress, CancellationToken cancelRequested, Int32 commanderid, String cmdname, Int32 fullhistoryloaddaylimit, JournalTypeEnum[] loadedbeforelimitids, Nullable`1 maxdateload) in C:\Code\EDDiscovery\EliteDangerousCore\EliteDangerous\HistoryList\HistoryList.cs:line 196
   at EDDiscovery.EDDiscoveryController.DoRefreshHistory(RefreshWorkerArgs args) in C:\Code\EDDiscovery\EDDiscovery\EDD\EDDiscoveryControllerHistory.cs:line 0
CAPI Logged Out
History refresh complete.
CAPI Refresh Succeeded
CAPI User Logged in to Live using ATLAS RAND
`

**Comment by genen** [comment]
Additionally Inara tab is just blank. Does not load inara page.

**Comment by klightspeed** [comment]
Please try a full re-install of EDDiscovery - some of those line numbers don't make sense.

**Comment by robbyxp1** [comment]
History Refresh Error: System.NullReferenceException: Object reference not set to an instance of an object.
at EliteDangerousCore.EngineerCrafting.Process(HistoryEntry he) in C:\Code\EDDiscovery\EliteDangerousCore\EliteDangerous\Stats\EngineerCrafting.cs:line 36

at EliteDangerousCore.HistoryList.MakeHistoryEntry(JournalEntry je) in C:\Code\EDDiscovery\EliteDangerousCore\EliteDangerous\HistoryList\HistoryList.cs:line 75

he or he.journalentry is blank in Engineeringcrafting - this is very hard to see why at this point.

I

**Comment by robbyxp1** [comment]
The best way to debug this if you send me all your journal files (in c:\<user>\save games\frontier developments\elite dangerous 

And I mean all of them, because it may be triggering a problem from a journal way back.

thanks

**Comment by robbyxp1** [comment]
Send either via our discord or email me.

**Comment by Eahlstan** [comment]
Solved via Discord.
Code is fixed, user has temporary solution that enables him to use EDD.
