### ISSUE TITLE
Closing the Add-On Manager while its still loading will cause a crash

### ISSUE THREAD

**Issue by dinkley** [EDDiscovery/EDDiscovery#3548]
Hitting the X or ALT-F4'ing out of the Add-On Manager window while the addon list is loading, will cause a crash. This forces the program to stall and cannot be closed without killing it via Task Manager.

Stacktrace:

```An unhandled fatal exception has occurred.

==== BEGIN ====
System.NullReferenceException: Object reference not set to an instance of an object.
   at BaseUtils.GitHubClass.ReadFolder(CancellationToken cancel, String gitfolder, Int32 timeout) in C:\Code\EDDiscovery\BaseUtilities\BaseUtilities\HTTP\GitHubClass.cs:line 64
   at ActionLanguage.Manager.AddOnManagerForm.CheckState() in C:\Code\EDDiscovery\ActionLanguage\ActionLanguage\AddOnManager\AddOnManagerForm.cs:line 108
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.ThreadHelper.ThreadStart()
===== END =====```

**Comment by robbyxp1** [comment]
I've found it, thanks for the report. fixed in next issue.
