### ISSUE TITLE
UNHANDLED EXCEPTION 5.1.0 beta

### ISSUE THREAD

**Issue by Hawkertech** [EDDiscovery/EDDiscovery#575]
Native library pre-loader is trying to load native SQLite library "C:\Program Files (x86)\EDDiscovery\EDDiscoveryBeta\x64\SQLite.Interop.dll"...
SQLite version 3.14.2
SQLite notice (539): recovered 20571 pages from C:\Users\wb6anp\AppData\Local\EDDiscovery\EDDSystem.sqlite-journal
Theme ID 10037
Unknown Gal Map object deepSpaceOutpost
Unknown Gal Map object deepSpaceOutpost
Unknown Gal Map object deepSpaceOutpost
Unknown Gal Map object deepSpaceOutpost
Unknown Gal Map object deepSpaceOutpost
Unknown Gal Map object deepSpaceOutpost
Unknown Gal Map object deepSpaceOutpost
Unknown Gal Map object neutronRoute
Unknown Gal Map object neutronRoute
Unknown Gal Map object neutronRoute
Unknown Gal Map object neutronRoute
Unknown Gal Map object deepSpaceOutpost
Unknown Gal Map object neutronRoute
Unknown Gal Map object neutronRoute
Unknown Gal Map object neutronRoute
Running logfile age check
New watch on C:\Users\wb6anp\Saved Games\Frontier Developments\Elite Dangerous
First chance exception: Value cannot be null.
Parameter name: value
   at System.Enum.TryParseEnum(Type enumType, String value, Boolean ignoreCase, EnumResult& parseResult)
   at System.Enum.Parse(Type enumType, String value, Boolean ignoreCase)
   at System.Net.ServicePointManager.LoadDisableStrongCryptoConfiguration()
   at System.Net.ServicePointManager.EnsureConfigurationLoaded()
   at System.Net.ServicePointManager.get_SecurityProtocol()
   at System.Net.TlsStream.ProcessAuthentication(LazyAsyncResult result)
   at System.Net.TlsStream.Write(Byte[] buffer, Int32 offset, Int32 size)
   at System.Net.ConnectStream.WriteHeaders(Boolean async)
   at System.Net.HttpWebRequest.EndSubmitRequest()
   at System.Net.Connection.CompleteConnection(Boolean async, HttpWebRequest request)
   at System.Net.Connection.CompleteStartConnection(Boolean async, HttpWebRequest httpWebRequest)
   at System.Net.Connection.CompleteStartRequest(Boolean onSubmitThread, HttpWebRequest request, TriState needReConnect)
   at System.Net.Connection.SubmitRequest(HttpWebRequest request, Boolean forcedsubmit)
   at System.Net.ServicePoint.SubmitRequest(HttpWebRequest request, String connName)
   at System.Net.HttpWebRequest.SubmitRequest(ServicePoint servicePoint)
   at System.Net.HttpWebRequest.GetResponse()
   at EDDiscovery.GitHubClass.GetLatestRelease()
   at EDDiscovery.EDDiscoveryForm.CheckForNewinstaller()
   at System.Threading.Tasks.Task.Execute()
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot)
   at System.Threading.Tasks.Task.ExecuteEntry(Boolean bPreventDoubleExecution)
   at System.Threading.ThreadPoolWorkQueue.Dispatch()

DownloadFile: C:\Users\wb6anp\AppData\Local\EDDiscovery\Maps\SC-01.jpg up to date (etag).
DownloadFile: C:\Users\wb6anp\AppData\Local\EDDiscovery\Maps\SC-02.jpg up to date (etag).
DownloadFile: C:\Users\wb6anp\AppData\Local\EDDiscovery\Maps\SC-03.jpg up to date (etag).
DownloadFile: C:\Users\wb6anp\AppData\Local\EDDiscovery\Maps\SC-L4.jpg up to date (etag).
DownloadFile: C:\Users\wb6anp\AppData\Local\EDDiscovery\Maps\SC-04.jpg up to date (etag).
DownloadFile: C:\Users\wb6anp\AppData\Local\EDDiscovery\Maps\DW1.jpg up to date (etag).
DownloadFile: C:\Users\wb6anp\AppData\Local\EDDiscovery\Maps\Formidine.png up to date (etag).
DownloadFile: C:\Users\wb6anp\AppData\Local\EDDiscovery\Maps\Galaxy_L_Grid.jpg up to date (etag).
DownloadFile: C:\Users\wb6anp\AppData\Local\EDDiscovery\Maps\DW4.jpg up to date (etag).
DownloadFile: C:\Users\wb6anp\AppData\Local\EDDiscovery\Maps\Galaxy_L.jpg up to date (etag).
DownloadFile: C:\Users\wb6anp\AppData\Local\EDDiscovery\Maps\DW3.jpg up to date (etag).
DownloadFile: C:\Users\wb6anp\AppData\Local\EDDiscovery\Maps\SC-00.png up to date (etag).
DownloadFile: C:\Users\wb6anp\AppData\Local\EDDiscovery\Maps\DW2.jpg up to date (etag).
DownloadFile: C:\Users\wb6anp\AppData\Local\EDDiscovery\Maps\Galaxy_L_Grid.json up to date (etag).
DownloadFile: C:\Users\wb6anp\AppData\Local\EDDiscovery\Maps\Formidine.json up to date (etag).
DownloadFile: C:\Users\wb6anp\AppData\Local\EDDiscovery\Maps\Galaxy_L.json up to date (etag).
DownloadFile: C:\Users\wb6anp\AppData\Local\EDDiscovery\Maps\DW4.json up to date (etag).
DownloadFile: C:\Users\wb6anp\AppData\Local\EDDiscovery\Maps\SC-00.json up to date (etag).
DownloadFile: C:\Users\wb6anp\AppData\Local\EDDiscovery\Maps\DW3.json up to date (etag).
DownloadFile: C:\Users\wb6anp\AppData\Local\EDDiscovery\Maps\SC-U4.jpg up to date (etag).
DownloadFile: C:\Users\wb6anp\AppData\Local\EDDiscovery\Maps\DW2.json up to date (etag).
DownloadFile: C:\Users\wb6anp\AppData\Local\EDDiscovery\Maps\DW1.json up to date (etag).
DownloadFile: C:\Users\wb6anp\AppData\Local\EDDiscovery\Maps\Formidine trans.png up to date (etag).
DownloadFile: C:\Users\wb6anp\AppData\Local\EDDiscovery\Maps\Formidine trans.json up to date (etag).
New watch on \\DESKTOP-6KUJSI4\Saved Games\Frontier Developments\Elite Dangerous
Delete watch on C:\Users\wb6anp\Saved Games\Frontier Developments\Elite Dangerous
Scanned \\DESKTOP-6KUJSI4\Saved Games\Frontier Developments\Elite Dangerous
File Read \\DESKTOP-6KUJSI4\Saved Games\Frontier Developments\Elite Dangerous\Journal.161031104348.01.log
File Read \\DESKTOP-6KUJSI4\Saved Games\Frontier Developments\Elite Dangerous\Journal.161101100004.01.log
File Read \\DESKTOP-6KUJSI4\Saved Games\Frontier Developments\Elite Dangerous\Journal.161103100050.01.log
File Read \\DESKTOP-6KUJSI4\Saved Games\Frontier Developments\Elite Dangerous\Journal.161112071203.01.log
File Read \\DESKTOP-6KUJSI4\Saved Games\Frontier Developments\Elite Dangerous\Journal.161112073815.01.log
File Read \\DESKTOP-6KUJSI4\Saved Games\Frontier Developments\Elite Dangerous\Journal.161112074429.01.log
File Read \\DESKTOP-6KUJSI4\Saved Games\Frontier Developments\Elite Dangerous\Journal.161112130808.01.log
File Read \\DESKTOP-6KUJSI4\Saved Games\Frontier Developments\Elite Dangerous\Journal.161114125632.01.log
Start Monitor on \\DESKTOP-6KUJSI4\Saved Games\Frontier Developments\Elite Dangerous
EDSM Check date: 2016-11-23 15:35:14
First chance exception: Object reference not set to an instance of an object.
   at EDDiscovery.UserControls.UserControlScan.PositionInfo()
   at EDDiscovery.UserControls.UserControlScan.UserControlScan_Resize(Object sender, EventArgs e)
   at System.Windows.Forms.Control.OnResize(EventArgs e)
   at System.Windows.Forms.UserControl.OnResize(EventArgs e)
   at System.Windows.Forms.Control.OnSizeChanged(EventArgs e)
   at System.Windows.Forms.Control.UpdateBounds(Int32 x, Int32 y, Int32 width, Int32 height, Int32 clientWidth, Int32 clientHeight)
   at System.Windows.Forms.Control.UpdateBounds(Int32 x, Int32 y, Int32 width, Int32 height)
   at System.Windows.Forms.Control.SetBoundsCore(Int32 x, Int32 y, Int32 width, Int32 height, BoundsSpecified specified)
   at System.Windows.Forms.Control.ScaleControl(SizeF factor, BoundsSpecified specified)
   at System.Windows.Forms.ScrollableControl.ScaleControl(SizeF factor, BoundsSpecified specified)
   at System.Windows.Forms.Control.ScaleControl(SizeF includedFactor, SizeF excludedFactor, Control requestingControl)
   at System.Windows.Forms.ContainerControl.Scale(SizeF includedFactor, SizeF excludedFactor, Control requestingControl)
   at System.Windows.Forms.ContainerControl.PerformAutoScale(Boolean includedBounds, Boolean excludedBounds)
   at System.Windows.Forms.ContainerControl.PerformNeededAutoScaleOnLayout()
   at System.Windows.Forms.ContainerControl.OnLayoutResuming(Boolean performLayout)
   at System.Windows.Forms.Control.ResumeLayout(Boolean performLayout)
   at EDDiscovery.UserControls.UserControlScan.InitializeComponent()
   at EDDiscovery.UserControls.UserControlScan..ctor()
   at EDDiscovery.TravelHistoryControl.TabCreate(TabStrip t, Int32 si)
   at EDDiscovery.Controls.TabStrip.ChangePanel(Int32 i)
   at System.Windows.Forms.Control.OnClick(EventArgs e)
   at System.Windows.Forms.Control.WmMouseUp(Message& m, MouseButtons button, Int32 clicks)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)
   at System.Windows.Forms.UnsafeNativeMethods.DispatchMessageW(MSG& msg)
   at System.Windows.Forms.UnsafeNativeMethods.DispatchMessageW(MSG& msg)
   at System.Windows.Forms.Application.ComponentManager.System.Windows.Forms.UnsafeNativeMethods.IMsoComponentManager.FPushMessageLoop(IntPtr dwComponentID, Int32 reason, Int32 pvLoopData)
   at System.Windows.Forms.Application.ThreadContext.RunMessageLoopInner(Int32 reason, ApplicationContext context)
   at System.Windows.Forms.Application.ThreadContext.RunMessageLoop(Int32 reason, ApplicationContext context)
   at EDDiscovery.Program.Main()

====  ====
System.NullReferenceException: Object reference not set to an instance of an object.
   at EDDiscovery.UserControls.UserControlScan.PositionInfo()
   at EDDiscovery.UserControls.UserControlScan.UserControlScan_Resize(Object sender, EventArgs e)
   at System.Windows.Forms.Control.OnResize(EventArgs e)
   at System.Windows.Forms.UserControl.OnResize(EventArgs e)
   at System.Windows.Forms.Control.OnSizeChanged(EventArgs e)
   at System.Windows.Forms.Control.UpdateBounds(Int32 x, Int32 y, Int32 width, Int32 height, Int32 clientWidth, Int32 clientHeight)
   at System.Windows.Forms.Control.UpdateBounds(Int32 x, Int32 y, Int32 width, Int32 height)
   at System.Windows.Forms.Control.SetBoundsCore(Int32 x, Int32 y, Int32 width, Int32 height, BoundsSpecified specified)
   at System.Windows.Forms.Control.ScaleControl(SizeF factor, BoundsSpecified specified)
   at System.Windows.Forms.ScrollableControl.ScaleControl(SizeF factor, BoundsSpecified specified)
   at System.Windows.Forms.Control.ScaleControl(SizeF includedFactor, SizeF excludedFactor, Control requestingControl)
   at System.Windows.Forms.ContainerControl.Scale(SizeF includedFactor, SizeF excludedFactor, Control requestingControl)
   at System.Windows.Forms.ContainerControl.PerformAutoScale(Boolean includedBounds, Boolean excludedBounds)
   at System.Windows.Forms.ContainerControl.PerformNeededAutoScaleOnLayout()
   at System.Windows.Forms.ContainerControl.OnLayoutResuming(Boolean performLayout)
   at System.Windows.Forms.Control.ResumeLayout(Boolean performLayout)
   at EDDiscovery.UserControls.UserControlScan.InitializeComponent()
   at EDDiscovery.UserControls.UserControlScan..ctor()
   at EDDiscovery.TravelHistoryControl.TabCreate(TabStrip t, Int32 si)
   at EDDiscovery.Controls.TabStrip.ChangePanel(Int32 i)
   at System.Windows.Forms.Control.OnClick(EventArgs e)
   at System.Windows.Forms.Control.WmMouseUp(Message& m, MouseButtons button, Int32 clicks)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)
==== cut ====
No activity on \\DESKTOP-6KUJSI4\Saved Games\Frontier Developments\Elite Dangerous\Journal.161114125632.01.log for 60 seconds (1905 >= 1905 - scanning for new journals

**Comment by Hawkertech** [comment]
It could be that I am accessing my Journal via network?

**Comment by klightspeed** [comment]
It's possible that the issue has been fixed by one of the commits that @robbyxp1 has made since this beta was released.

**Comment by Hawkertech** [comment]
Get the exact same error with 5.1.0 portable, Logithech mouse driver issue?

**Comment by klightspeed** [comment]
Does the error still occur with the portable zip at https://ci.appveyor.com/project/klightspeed/eddiscovery/build/3.2.1.21/artifacts

**Comment by Hawkertech** [comment]
same thing happens, and only on my second computer on win 7, so far Haven't had a chance to really run it on my win 10 gaming machine much.

**Comment by Hawkertech** [comment]
Same error in 5.1.1

**Comment by finwen** [comment]
Is with with the .exe installer or standalone zip archive?

**Comment by Hawkertech** [comment]
Both do the same thing, thats why I am thinking it is on my end for some reason.

**Comment by klightspeed** [comment]
What is the stack trace with the 5.1.1 portable version?

**Comment by Hawkertech** [comment]
==== UNHANDLED EXCEPTION ON  THREAD ====
System.NullReferenceException: Object reference not set to an instance of an object.
   at EDDiscovery.UserControls.UserControlScan.PositionInfo() in C:\projects\eddiscovery\EDDiscovery\UserControls\UserControlScan.cs:line 562
   at EDDiscovery.UserControls.UserControlScan.UserControlScan_Resize(Object sender, EventArgs e) in C:\projects\eddiscovery\EDDiscovery\UserControls\UserControlScan.cs:line 68
   at System.Windows.Forms.Control.OnResize(EventArgs e)
   at System.Windows.Forms.UserControl.OnResize(EventArgs e)
   at System.Windows.Forms.Control.OnSizeChanged(EventArgs e)
   at System.Windows.Forms.Control.UpdateBounds(Int32 x, Int32 y, Int32 width, Int32 height, Int32 clientWidth, Int32 clientHeight)
   at System.Windows.Forms.Control.UpdateBounds(Int32 x, Int32 y, Int32 width, Int32 height)
   at System.Windows.Forms.Control.SetBoundsCore(Int32 x, Int32 y, Int32 width, Int32 height, BoundsSpecified specified)
   at System.Windows.Forms.Control.ScaleControl(SizeF factor, BoundsSpecified specified)
   at System.Windows.Forms.ScrollableControl.ScaleControl(SizeF factor, BoundsSpecified specified)
   at System.Windows.Forms.Control.ScaleControl(SizeF includedFactor, SizeF excludedFactor, Control requestingControl)
   at System.Windows.Forms.ContainerControl.Scale(SizeF includedFactor, SizeF excludedFactor, Control requestingControl)
   at System.Windows.Forms.ContainerControl.PerformAutoScale(Boolean includedBounds, Boolean excludedBounds)
   at System.Windows.Forms.ContainerControl.PerformNeededAutoScaleOnLayout()
   at System.Windows.Forms.ContainerControl.OnLayoutResuming(Boolean performLayout)
   at System.Windows.Forms.Control.ResumeLayout(Boolean performLayout)
   at EDDiscovery.UserControls.UserControlScan.InitializeComponent() in C:\projects\eddiscovery\EDDiscovery\UserControls\UserControlScan.Designer.cs:line 325
   at EDDiscovery.UserControls.UserControlScan..ctor() in C:\projects\eddiscovery\EDDiscovery\UserControls\UserControlScan.cs:line 36
   at EDDiscovery.TravelHistoryControl.TabCreate(TabStrip t, Int32 si) in C:\projects\eddiscovery\EDDiscovery\TravelHistoryControl.cs:line 179
   at EDDiscovery.Controls.TabStrip.ChangePanel(Int32 i) in C:\projects\eddiscovery\EDDiscovery\Controls\TabStrip.cs:line 70
   at System.Windows.Forms.Control.OnClick(EventArgs e)
   at System.Windows.Forms.Control.WmMouseUp(Message& m, MouseButtons button, Int32 clicks)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)
==== cut ====

**Comment by klightspeed** [comment]
That line number looks like it's from the appveyor build I pointed you to.

https://github.com/klightspeed/EDDiscovery/blob/1ec271bbbe85d9094b078e5f3c87268ce2efef58/EDDiscovery/UserControls/UserControlScan.cs#L562
```
                if (((bool)richTextBoxInfo.Tag) == true)
```

This suggests that the Tag on the textbox is null.
@robbyxp1 perhaps use `(richTextBoxInfo.Tag as bool?)` instead of `((bool)richTextBoxInfo.Tag)`?

**Comment by robbyxp1** [comment]
Can't see why the PositionInfo func would fail, but have defensively:

                if (richTextBoxInfo.Tag != null && ((bool)richTextBoxInfo.Tag) == true)

**Comment by robbyxp1** [comment]
As I said, i can't see a path to that being null, but it may solve the issue

**Comment by robbyxp1** [comment]
5.1 is in the past now. closing
