### ISSUE TITLE
Bug - EDD Crash on Dock

### ISSUE THREAD

**Issue by Norca** [EDDiscovery/EDDiscovery#904]
[2017-03-12 20:18:56Z] Running logfile age check
[2017-03-12 20:18:56Z] Native library pre-loader is trying to load native SQLite library "C:\Program Files\EDDiscovery\EDDiscovery\x64\SQLite.Interop.dll"...
[2017-03-12 20:18:56Z] SQLite version 3.15.2
[2017-03-12 20:18:56Z] Initializing database
[2017-03-12 20:18:56Z] Database initialization complete
[2017-03-12 20:18:57Z] Theme ID 10037
[2017-03-12 20:18:59Z] Unknown Gal Map object mysteryPOI
[2017-03-12 20:18:59Z] Unknown Gal Map object deepSpaceOutpost
[2017-03-12 20:18:59Z] Unknown Gal Map object restrictedSectors
[2017-03-12 20:18:59Z] Unknown Gal Map object neutronRoute
[2017-03-12 20:18:59Z] New watch on C:\Users\mobil\Saved Games\Frontier Developments\Elite Dangerous
[2017-03-12 20:18:59Z] Scanned C:\Users\mobil\Saved Games\Frontier Developments\Elite Dangerous
[2017-03-12 20:18:59Z] File Read C:\Users\mobil\Saved Games\Frontier Developments\Elite Dangerous\Journal.160923122042.01.log
[2017-03-12 20:18:59Z] File Read C:\Users\mobil\Saved Games\Frontier Developments\Elite Dangerous\Journal.160925130839.01.log
[2017-03-12 20:18:59Z] File Read C:\Users\mobil\Saved Games\Frontier Developments\Elite Dangerous\Journal.160925191035.01.log
[2017-03-12 20:18:59Z] File Read C:\Users\mobil\Saved Games\Frontier Developments\Elite Dangerous\Journal.160929184105.01.log
[2017-03-12 20:18:59Z] File Read C:\Users\mobil\Saved Games\Frontier Developments\Elite Dangerous\Journal.160929195255.01.log
[2017-03-12 20:18:59Z] File Read C:\Users\mobil\Saved Games\Frontier Developments\Elite Dangerous\Journal.161016154102.01.log
[2017-03-12 20:18:59Z] File Read C:\Users\mobil\Saved Games\Frontier Developments\Elite Dangerous\Journal.161025220501.01.log
[2017-03-12 20:18:59Z] File Read C:\Users\mobil\Saved Games\Frontier Developments\Elite Dangerous\Journal.161026085813.01.log
[2017-03-12 20:18:59Z] File Read C:\Users\mobil\Saved Games\Frontier Developments\Elite Dangerous\Journal.161026103322.01.log
[2017-03-12 20:18:59Z] File Read C:\Users\mobil\Saved Games\Frontier Developments\Elite Dangerous\Journal.161027161140.01.log
[2017-03-12 20:18:59Z] File Read C:\Users\mobil\Saved Games\Frontier Developments\Elite Dangerous\Journal.161027222833.01.log
[2017-03-12 20:18:59Z] File Read C:\Users\mobil\Saved Games\Frontier Developments\Elite Dangerous\Journal.161028100829.01.log
[2017-03-12 20:18:59Z] File Read C:\Users\mobil\Saved Games\Frontier Developments\Elite Dangerous\Journal.161028114436.01.log
[2017-03-12 20:18:59Z] File Read C:\Users\mobil\Saved Games\Frontier Developments\Elite Dangerous\Journal.161028190629.01.log
[2017-03-12 20:18:59Z] File Read C:\Users\mobil\Saved Games\Frontier Developments\Elite Dangerous\Journal.161030142239.01.log
[2017-03-12 20:18:59Z] File Read C:\Users\mobil\Saved Games\Frontier Developments\Elite Dangerous\Journal.161030181322.01.log
[2017-03-12 20:18:59Z] File Read C:\Users\mobil\Saved Games\Frontier Developments\Elite Dangerous\Journal.161031200726.01.log
[2017-03-12 20:18:59Z] File Read C:\Users\mobil\Saved Games\Frontier Developments\Elite Dangerous\Journal.161106140251.01.log
[2017-03-12 20:18:59Z] File Read C:\Users\mobil\Saved Games\Frontier Developments\Elite Dangerous\Journal.170107113858.01.log
[2017-03-12 20:18:59Z] File Read C:\Users\mobil\Saved Games\Frontier Developments\Elite Dangerous\Journal.170107170240.01.log
[2017-03-12 20:18:59Z] File Read C:\Users\mobil\Saved Games\Frontier Developments\Elite Dangerous\Journal.170108095611.01.log
[2017-03-12 20:18:59Z] File Read C:\Users\mobil\Saved Games\Frontier Developments\Elite Dangerous\Journal.170115130544.01.log
[2017-03-12 20:18:59Z] File Read C:\Users\mobil\Saved Games\Frontier Developments\Elite Dangerous\Journal.170228200903.01.log
[2017-03-12 20:18:59Z] File Read C:\Users\mobil\Saved Games\Frontier Developments\Elite Dangerous\Journal.170311091246.01.log
[2017-03-12 20:18:59Z] File Read C:\Users\mobil\Saved Games\Frontier Developments\Elite Dangerous\Journal.170311123212.01.log
[2017-03-12 20:18:59Z] File Read C:\Users\mobil\Saved Games\Frontier Developments\Elite Dangerous\Journal.170311123545.01.log
[2017-03-12 20:18:59Z] File Read C:\Users\mobil\Saved Games\Frontier Developments\Elite Dangerous\Journal.170311174147.01.log
[2017-03-12 20:18:59Z] File Read C:\Users\mobil\Saved Games\Frontier Developments\Elite Dangerous\Journal.170312191821.01.log
[2017-03-12 20:18:59Z] File Read C:\Users\mobil\Saved Games\Frontier Developments\Elite Dangerous\Journal.170312192007.01.log
[2017-03-12 20:18:59Z] Write Journal to db 12/03/2017 20:18:57 ReceiveText
[2017-03-12 20:19:00Z] EDSM Check date: 2017-03-12 19:16:12
[2017-03-12 20:19:00Z] Start Monitor on C:\Users\mobil\Saved Games\Frontier Developments\Elite Dangerous
[2017-03-12 20:19:01Z] Unknown Gal Map object mysteryPOI
[2017-03-12 20:19:01Z] Last message repeated 16 times
[2017-03-12 20:19:01Z] Unknown Gal Map object deepSpaceOutpost
[2017-03-12 20:19:01Z] Last message repeated 7 times
[2017-03-12 20:19:01Z] Unknown Gal Map object restrictedSectors
[2017-03-12 20:19:01Z] Last message repeated 10 times
[2017-03-12 20:19:01Z] Unknown Gal Map object neutronRoute
[2017-03-12 20:19:01Z] Last message repeated 6 times
[2017-03-12 20:19:03Z] Import took 1859ms
[2017-03-12 20:19:03Z] Id 2 count 17
[2017-03-12 20:19:03Z] Id 3 count 14
[2017-03-12 20:19:03Z] Id 11 count 3
[2017-03-12 20:19:03Z] Id 18 count 3
[2017-03-12 20:19:03Z] Id 102 count 6
[2017-03-12 20:19:03Z] Id 104 count 17
[2017-03-12 20:19:03Z] Id 211 count 10
[2017-03-12 20:19:03Z] Id 306 count 2
[2017-03-12 20:19:03Z] Id 310 count 1
[2017-03-12 20:19:03Z] Id 312 count 5
[2017-03-12 20:19:03Z] Id 406 count 16
[2017-03-12 20:19:03Z] Id 412 count 17
[2017-03-12 20:19:03Z] Id 507 count 8
[2017-03-12 20:19:03Z] Id 514 count 4
[2017-03-12 20:19:03Z] Id 515 count 1
[2017-03-12 20:19:03Z] Id 610 count 18
[2017-03-12 20:19:03Z] Id 613 count 3
[2017-03-12 20:19:03Z] Id 704 count 5
[2017-03-12 20:19:03Z] Id 706 count 1
[2017-03-12 20:19:03Z] Id 708 count 33
[2017-03-12 20:19:03Z] Id 709 count 27
[2017-03-12 20:19:03Z] Id 710 count 16
[2017-03-12 20:19:03Z] Id 712 count 15
[2017-03-12 20:19:03Z] Id 713 count 16
[2017-03-12 20:19:03Z] Id 807 count 2
[2017-03-12 20:19:03Z] Id 808 count 5
[2017-03-12 20:19:03Z] Id 809 count 39
[2017-03-12 20:19:03Z] Id 810 count 76
[2017-03-12 20:19:03Z] Id 811 count 12
[2017-03-12 20:19:03Z] Id 905 count 5
[2017-03-12 20:19:03Z] Id 908 count 20
[2017-03-12 20:19:03Z] Id 909 count 84
[2017-03-12 20:19:03Z] Id 910 count 76
[2017-03-12 20:19:03Z] Id 911 count 8
[2017-03-12 20:19:03Z] Id 914 count 4
[2017-03-12 20:19:03Z] Id 1009 count 94
[2017-03-12 20:19:03Z] Id 1010 count 45
[2017-03-12 20:19:03Z] Id 1011 count 8
[2017-03-12 20:19:03Z] Id 1012 count 6
[2017-03-12 20:19:03Z] Id 1014 count 13
[2017-03-12 20:19:03Z] Id 1108 count 29
[2017-03-12 20:19:03Z] Id 1109 count 11
[2017-03-12 20:19:03Z] Id 1110 count 85
[2017-03-12 20:19:03Z] Id 1202 count 5
[2017-03-12 20:19:03Z] Id 1204 count 2
[2017-03-12 20:19:03Z] Id 1207 count 34
[2017-03-12 20:19:03Z] Id 1208 count 80
[2017-03-12 20:19:03Z] Id 1209 count 18
[2017-03-12 20:19:03Z] Id 1210 count 71
[2017-03-12 20:19:03Z] Id 1214 count 11
[2017-03-12 20:19:03Z] Id 1302 count 24
[2017-03-12 20:19:03Z] Id 1303 count 6
[2017-03-12 20:19:03Z] Id 1306 count 43
[2017-03-12 20:19:03Z] Id 1307 count 86
[2017-03-12 20:19:03Z] Id 1308 count 134
[2017-03-12 20:19:03Z] Id 1309 count 24
[2017-03-12 20:19:03Z] Id 1311 count 4
[2017-03-12 20:19:03Z] Id 1316 count 8
[2017-03-12 20:19:03Z] Id 1402 count 14
[2017-03-12 20:19:03Z] Id 1405 count 53
[2017-03-12 20:19:03Z] Id 1406 count 61
[2017-03-12 20:19:03Z] Id 1407 count 78
[2017-03-12 20:19:03Z] Id 1408 count 3
[2017-03-12 20:19:03Z] Id 1409 count 3
[2017-03-12 20:19:03Z] Id 1418 count 22
[2017-03-12 20:19:03Z] Id 1504 count 59
[2017-03-12 20:19:03Z] Id 1505 count 309
[2017-03-12 20:19:03Z] Id 1506 count 57
[2017-03-12 20:19:03Z] Id 1509 count 4
[2017-03-12 20:19:03Z] Id 1510 count 10
[2017-03-12 20:19:03Z] Id 1511 count 17
[2017-03-12 20:19:03Z] Id 1600 count 33
[2017-03-12 20:19:03Z] Id 1601 count 73
[2017-03-12 20:19:03Z] Id 1602 count 12
[2017-03-12 20:19:03Z] Id 1603 count 225
[2017-03-12 20:19:03Z] Id 1604 count 236
[2017-03-12 20:19:03Z] Id 1605 count 81
[2017-03-12 20:19:03Z] Id 1702 count 26
[2017-03-12 20:19:03Z] Id 1703 count 136
[2017-03-12 20:19:03Z] Id 1704 count 55
[2017-03-12 20:19:03Z] Id 1705 count 18
[2017-03-12 20:19:03Z] Id 1706 count 18
[2017-03-12 20:19:03Z] Id 1709 count 7
[2017-03-12 20:19:03Z] Id 1710 count 38
[2017-03-12 20:19:03Z] Id 1711 count 16
[2017-03-12 20:19:03Z] Id 1713 count 3
[2017-03-12 20:19:03Z] Id 1714 count 25
[2017-03-12 20:19:03Z] Id 1800 count 1
[2017-03-12 20:19:03Z] Id 1812 count 5
[2017-03-12 20:19:03Z] Id 1813 count 11
[2017-03-12 20:19:03Z] Id 2001 count 11
[2017-03-12 20:19:03Z] Id 2102 count 4
[2017-03-12 20:19:03Z] Id 2217 count 24
[2017-03-12 20:19:03Z] Id 2307 count 17
[2017-03-12 20:19:03Z] Id 2309 count 9
[2017-03-12 20:19:03Z] Id 2318 count 1
[2017-03-12 20:19:03Z] Id 2415 count 16
[2017-03-12 20:19:03Z] Id 2418 count 14
[2017-03-12 20:19:03Z] Stop Monitor on C:\Users\mobil\Saved Games\Frontier Developments\Elite Dangerous
[2017-03-12 20:19:03Z] Scanned C:\Users\mobil\Saved Games\Frontier Developments\Elite Dangerous
[2017-03-12 20:19:03Z] File Read C:\Users\mobil\Saved Games\Frontier Developments\Elite Dangerous\Journal.160923122042.01.log
[2017-03-12 20:19:03Z] File Read C:\Users\mobil\Saved Games\Frontier Developments\Elite Dangerous\Journal.160925130839.01.log
[2017-03-12 20:19:03Z] File Read C:\Users\mobil\Saved Games\Frontier Developments\Elite Dangerous\Journal.160925191035.01.log
[2017-03-12 20:19:03Z] File Read C:\Users\mobil\Saved Games\Frontier Developments\Elite Dangerous\Journal.160929184105.01.log
[2017-03-12 20:19:03Z] File Read C:\Users\mobil\Saved Games\Frontier Developments\Elite Dangerous\Journal.160929195255.01.log
[2017-03-12 20:19:03Z] File Read C:\Users\mobil\Saved Games\Frontier Developments\Elite Dangerous\Journal.161016154102.01.log
[2017-03-12 20:19:03Z] File Read C:\Users\mobil\Saved Games\Frontier Developments\Elite Dangerous\Journal.161025220501.01.log
[2017-03-12 20:19:03Z] File Read C:\Users\mobil\Saved Games\Frontier Developments\Elite Dangerous\Journal.161026085813.01.log
[2017-03-12 20:19:03Z] File Read C:\Users\mobil\Saved Games\Frontier Developments\Elite Dangerous\Journal.161026103322.01.log
[2017-03-12 20:19:03Z] File Read C:\Users\mobil\Saved Games\Frontier Developments\Elite Dangerous\Journal.161027161140.01.log
[2017-03-12 20:19:03Z] File Read C:\Users\mobil\Saved Games\Frontier Developments\Elite Dangerous\Journal.161027222833.01.log
[2017-03-12 20:19:03Z] File Read C:\Users\mobil\Saved Games\Frontier Developments\Elite Dangerous\Journal.161028100829.01.log
[2017-03-12 20:19:03Z] File Read C:\Users\mobil\Saved Games\Frontier Developments\Elite Dangerous\Journal.161028114436.01.log
[2017-03-12 20:19:03Z] File Read C:\Users\mobil\Saved Games\Frontier Developments\Elite Dangerous\Journal.161028190629.01.log
[2017-03-12 20:19:03Z] File Read C:\Users\mobil\Saved Games\Frontier Developments\Elite Dangerous\Journal.161030142239.01.log
[2017-03-12 20:19:03Z] File Read C:\Users\mobil\Saved Games\Frontier Developments\Elite Dangerous\Journal.161030181322.01.log
[2017-03-12 20:19:03Z] File Read C:\Users\mobil\Saved Games\Frontier Developments\Elite Dangerous\Journal.161031200726.01.log
[2017-03-12 20:19:03Z] File Read C:\Users\mobil\Saved Games\Frontier Developments\Elite Dangerous\Journal.161106140251.01.log
[2017-03-12 20:19:03Z] File Read C:\Users\mobil\Saved Games\Frontier Developments\Elite Dangerous\Journal.170107113858.01.log
[2017-03-12 20:19:03Z] File Read C:\Users\mobil\Saved Games\Frontier Developments\Elite Dangerous\Journal.170107170240.01.log
[2017-03-12 20:19:03Z] File Read C:\Users\mobil\Saved Games\Frontier Developments\Elite Dangerous\Journal.170108095611.01.log
[2017-03-12 20:19:03Z] File Read C:\Users\mobil\Saved Games\Frontier Developments\Elite Dangerous\Journal.170115130544.01.log
[2017-03-12 20:19:03Z] File Read C:\Users\mobil\Saved Games\Frontier Developments\Elite Dangerous\Journal.170228200903.01.log
[2017-03-12 20:19:03Z] File Read C:\Users\mobil\Saved Games\Frontier Developments\Elite Dangerous\Journal.170311091246.01.log
[2017-03-12 20:19:03Z] File Read C:\Users\mobil\Saved Games\Frontier Developments\Elite Dangerous\Journal.170311123212.01.log
[2017-03-12 20:19:03Z] File Read C:\Users\mobil\Saved Games\Frontier Developments\Elite Dangerous\Journal.170311123545.01.log
[2017-03-12 20:19:03Z] File Read C:\Users\mobil\Saved Games\Frontier Developments\Elite Dangerous\Journal.170311174147.01.log
[2017-03-12 20:19:03Z] File Read C:\Users\mobil\Saved Games\Frontier Developments\Elite Dangerous\Journal.170312191821.01.log
[2017-03-12 20:19:03Z] File Read C:\Users\mobil\Saved Games\Frontier Developments\Elite Dangerous\Journal.170312192007.01.log
[2017-03-12 20:19:03Z] Start Monitor on C:\Users\mobil\Saved Games\Frontier Developments\Elite Dangerous
[2017-03-12 20:27:27Z] New entry 12/03/2017 20:27:26 ReceiveText
[2017-03-12 20:32:54Z] New entry 12/03/2017 20:32:53 Undocked
[2017-03-12 20:33:50Z] New entry 12/03/2017 20:33:48 ReceiveText
[2017-03-12 20:34:40Z] New entry 12/03/2017 20:34:38 FSDJump
[2017-03-12 20:34:40Z] Arrived at system: HR 5970 1:th visit.
[2017-03-12 20:34:40Z] Update sync flag ID 4442 with 1
[2017-03-12 20:34:41Z] Update sync flag ID 4442 with 3
[2017-03-12 20:35:16Z] New entry 12/03/2017 20:35:16 FuelScoop
[2017-03-12 20:38:03Z] New entry 12/03/2017 20:38:02 Scan
[2017-03-12 20:38:03Z] Update sync flag ID 4444 with 2
[2017-03-12 20:38:57Z] New entry 12/03/2017 20:38:55 SupercruiseExit
[2017-03-12 20:39:11Z] New entry 12/03/2017 20:39:10 DockingRequested
[2017-03-12 20:39:12Z] New entry 12/03/2017 20:39:10 ReceiveText
[2017-03-12 20:39:12Z] New entry 12/03/2017 20:39:11 ReceiveText
[2017-03-12 20:39:12Z] New entry 12/03/2017 20:39:11 DockingGranted
[2017-03-12 20:39:24Z] New entry 12/03/2017 20:39:23 ReceiveText
[2017-03-12 20:40:22Z] New entry 12/03/2017 20:40:21 Docked
[2017-03-12 20:40:22Z] 
==== UNHANDLED EXCEPTION ====
System.IndexOutOfRangeException: Index was outside the bounds of the array.
   at System.Windows.Forms.Control.MarshaledInvoke(Control caller, Delegate method, Object[] args, Boolean synchronous)
   at System.Windows.Forms.Control.Invoke(Delegate method, Object[] args)
   at EDDiscovery.EDDiscoveryForm.<.ctor>b__77_3(Action a)
   at EDDiscovery.EliteDangerous.EDJournalClass.ScanThreadProc()
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.ThreadHelper.ThreadStart()
==== cut ====

**Comment by klightspeed** [comment]
It looks like either the dotnet unhandled exception handler doesn't pass through the inner exception on the exception object, or `Form.Invoke` doesn't pass through the stack trace of any exceptions.

There are so many subscribers of OnNewEntry and OnNewJournalEntry that it could be almost anything - all we know is that one of the subscribers tried to access an element beyond the bounds of an array or list.

Please let us know if a UI exception is thrown when restarting EDDiscovery.

**Comment by Norca** [comment]
After clicking the OK button on the error window the program closes. When I restart the program it starts without error and will work as expected until I perform a dock event in the game.

The previous version worked without error on all events.

**Comment by klightspeed** [comment]
Please create an `Options.txt` file in the EDDiscovery program directory with the following line, then reproduce the conditions that cause the crash and submit the resulting trace log:
```
LogExceptions
```

**Comment by Norca** [comment]
As requested

[2017-03-14 19:51:40Z] Running logfile age check
[2017-03-14 19:51:40Z] Native library pre-loader is trying to load native SQLite library "C:\Program Files\EDDiscovery\EDDiscovery\x64\SQLite.Interop.dll"...
[2017-03-14 19:51:40Z] SQLite version 3.15.2
[2017-03-14 19:51:40Z] Initializing database
[2017-03-14 19:51:40Z] Database initialization complete
[2017-03-14 19:51:40Z] Theme ID 10037
[2017-03-14 19:51:42Z] Unknown Gal Map object mysteryPOI
[2017-03-14 19:51:42Z] Unknown Gal Map object deepSpaceOutpost
[2017-03-14 19:51:42Z] Unknown Gal Map object restrictedSectors
[2017-03-14 19:51:42Z] Unknown Gal Map object neutronRoute
[2017-03-14 19:51:42Z] New watch on C:\Users\mobil\Saved Games\Frontier Developments\Elite Dangerous
[2017-03-14 19:51:42Z] Scanned C:\Users\mobil\Saved Games\Frontier Developments\Elite Dangerous
[2017-03-14 19:51:42Z] File Read C:\Users\mobil\Saved Games\Frontier Developments\Elite Dangerous\Journal.160923122042.01.log
[2017-03-14 19:51:42Z] File Read C:\Users\mobil\Saved Games\Frontier Developments\Elite Dangerous\Journal.160925130839.01.log
[2017-03-14 19:51:42Z] File Read C:\Users\mobil\Saved Games\Frontier Developments\Elite Dangerous\Journal.160925191035.01.log
[2017-03-14 19:51:42Z] File Read C:\Users\mobil\Saved Games\Frontier Developments\Elite Dangerous\Journal.160929184105.01.log
[2017-03-14 19:51:42Z] File Read C:\Users\mobil\Saved Games\Frontier Developments\Elite Dangerous\Journal.160929195255.01.log
[2017-03-14 19:51:42Z] File Read C:\Users\mobil\Saved Games\Frontier Developments\Elite Dangerous\Journal.161016154102.01.log
[2017-03-14 19:51:42Z] File Read C:\Users\mobil\Saved Games\Frontier Developments\Elite Dangerous\Journal.161025220501.01.log
[2017-03-14 19:51:42Z] File Read C:\Users\mobil\Saved Games\Frontier Developments\Elite Dangerous\Journal.161026085813.01.log
[2017-03-14 19:51:42Z] File Read C:\Users\mobil\Saved Games\Frontier Developments\Elite Dangerous\Journal.161026103322.01.log
[2017-03-14 19:51:42Z] File Read C:\Users\mobil\Saved Games\Frontier Developments\Elite Dangerous\Journal.161027161140.01.log
[2017-03-14 19:51:42Z] File Read C:\Users\mobil\Saved Games\Frontier Developments\Elite Dangerous\Journal.161027222833.01.log
[2017-03-14 19:51:42Z] File Read C:\Users\mobil\Saved Games\Frontier Developments\Elite Dangerous\Journal.161028100829.01.log
[2017-03-14 19:51:42Z] File Read C:\Users\mobil\Saved Games\Frontier Developments\Elite Dangerous\Journal.161028114436.01.log
[2017-03-14 19:51:42Z] File Read C:\Users\mobil\Saved Games\Frontier Developments\Elite Dangerous\Journal.161028190629.01.log
[2017-03-14 19:51:42Z] File Read C:\Users\mobil\Saved Games\Frontier Developments\Elite Dangerous\Journal.161030142239.01.log
[2017-03-14 19:51:42Z] File Read C:\Users\mobil\Saved Games\Frontier Developments\Elite Dangerous\Journal.161030181322.01.log
[2017-03-14 19:51:42Z] File Read C:\Users\mobil\Saved Games\Frontier Developments\Elite Dangerous\Journal.161031200726.01.log
[2017-03-14 19:51:42Z] File Read C:\Users\mobil\Saved Games\Frontier Developments\Elite Dangerous\Journal.161106140251.01.log
[2017-03-14 19:51:42Z] File Read C:\Users\mobil\Saved Games\Frontier Developments\Elite Dangerous\Journal.170107113858.01.log
[2017-03-14 19:51:42Z] File Read C:\Users\mobil\Saved Games\Frontier Developments\Elite Dangerous\Journal.170107170240.01.log
[2017-03-14 19:51:42Z] File Read C:\Users\mobil\Saved Games\Frontier Developments\Elite Dangerous\Journal.170108095611.01.log
[2017-03-14 19:51:42Z] File Read C:\Users\mobil\Saved Games\Frontier Developments\Elite Dangerous\Journal.170115130544.01.log
[2017-03-14 19:51:42Z] File Read C:\Users\mobil\Saved Games\Frontier Developments\Elite Dangerous\Journal.170228200903.01.log
[2017-03-14 19:51:42Z] File Read C:\Users\mobil\Saved Games\Frontier Developments\Elite Dangerous\Journal.170311091246.01.log
[2017-03-14 19:51:42Z] File Read C:\Users\mobil\Saved Games\Frontier Developments\Elite Dangerous\Journal.170311123212.01.log
[2017-03-14 19:51:42Z] File Read C:\Users\mobil\Saved Games\Frontier Developments\Elite Dangerous\Journal.170311123545.01.log
[2017-03-14 19:51:42Z] File Read C:\Users\mobil\Saved Games\Frontier Developments\Elite Dangerous\Journal.170311174147.01.log
[2017-03-14 19:51:42Z] File Read C:\Users\mobil\Saved Games\Frontier Developments\Elite Dangerous\Journal.170312191821.01.log
[2017-03-14 19:51:42Z] File Read C:\Users\mobil\Saved Games\Frontier Developments\Elite Dangerous\Journal.170312192007.01.log
[2017-03-14 19:51:42Z] File Read C:\Users\mobil\Saved Games\Frontier Developments\Elite Dangerous\Journal.170314193401.01.log
[2017-03-14 19:51:42Z] Write Journal to db 14/03/2017 19:35:45 MarketBuy
[2017-03-14 19:51:42Z] Write Journal to db 14/03/2017 19:36:28 Undocked
[2017-03-14 19:51:42Z] Write Journal to db 14/03/2017 19:37:07 ReceiveText
[2017-03-14 19:51:42Z] Write Journal to db 14/03/2017 19:37:09 SupercruiseEntry
[2017-03-14 19:51:42Z] Write Journal to db 14/03/2017 19:46:49 SupercruiseExit
[2017-03-14 19:51:42Z] Write Journal to db 14/03/2017 19:47:03 DockingRequested
[2017-03-14 19:51:42Z] Write Journal to db 14/03/2017 19:47:03 ReceiveText
[2017-03-14 19:51:42Z] Write Journal to db 14/03/2017 19:47:05 ReceiveText
[2017-03-14 19:51:42Z] Write Journal to db 14/03/2017 19:47:05 DockingGranted
[2017-03-14 19:51:42Z] Write Journal to db 14/03/2017 19:47:16 ReceiveText
[2017-03-14 19:51:42Z] Write Journal to db 14/03/2017 19:48:09 Docked
[2017-03-14 19:51:42Z] Write Journal to db 14/03/2017 19:48:41 MarketBuy
[2017-03-14 19:51:43Z] Unknown Gal Map object mysteryPOI
[2017-03-14 19:51:43Z] Last message repeated 16 times
[2017-03-14 19:51:43Z] Unknown Gal Map object deepSpaceOutpost
[2017-03-14 19:51:43Z] Last message repeated 7 times
[2017-03-14 19:51:43Z] Unknown Gal Map object restrictedSectors
[2017-03-14 19:51:43Z] Last message repeated 10 times
[2017-03-14 19:51:43Z] Unknown Gal Map object neutronRoute
[2017-03-14 19:51:43Z] Last message repeated 6 times
[2017-03-14 19:51:43Z] Start Monitor on C:\Users\mobil\Saved Games\Frontier Developments\Elite Dangerous
[2017-03-14 19:52:25Z] File Read C:\Users\mobil\Saved Games\Frontier Developments\Elite Dangerous\Journal.170314195224.01.log
[2017-03-14 19:52:25Z] Change in file, scan C:\Users\mobil\Saved Games\Frontier Developments\Elite Dangerous\Journal.170314195224.01.log
[2017-03-14 19:52:25Z] New entry 14/03/2017 19:52:24 Fileheader
[2017-03-14 19:53:09Z] TLU C:\Users\mobil\Saved Games\Frontier Developments\Elite Dangerous updated with commander 1
[2017-03-14 19:53:09Z] New entry 14/03/2017 19:53:08 LoadGame
[2017-03-14 19:53:10Z] New entry 14/03/2017 19:53:08 Rank
[2017-03-14 19:53:10Z] New entry 14/03/2017 19:53:08 Progress
[2017-03-14 19:53:28Z] New entry 14/03/2017 19:53:27 Location
[2017-03-14 19:53:28Z] New entry 14/03/2017 19:53:28 Docked
[2017-03-14 19:53:28Z] 
==== UNHANDLED EXCEPTION ====
System.IndexOutOfRangeException: Index was outside the bounds of the array.
   at System.Windows.Forms.Control.MarshaledInvoke(Control caller, Delegate method, Object[] args, Boolean synchronous)
   at System.Windows.Forms.Control.Invoke(Delegate method, Object[] args)
   at EDDiscovery.EDDiscoveryForm.<.ctor>b__77_3(Action a)
   at EDDiscovery.EliteDangerous.EDJournalClass.ScanThreadProc()
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.ThreadHelper.ThreadStart()
==== cut ====

**Comment by Norca** [comment]
Hi,

Did a little bit more research and fault testing;

Firstly uninstalled 6.1.2
Installed 6.1.1 - ran ED and this version did NOT crash when the dock event was encountered
Installed 6.1.2 over the top of 6.1.1 - ran ED and this also did NOT crash

Started to think about the other possible changes I had made in the EDD program and then remembered that I had edited the speech file for the Global say_Docked

Orignal is this:
Global say_Docked $= "{Docked at %(EventClass_StationName), %ifnotempty(EventClass_StationType,\"%(EventClass_StationType) type\").}This is a %(EventClass_Economy_Localised) station;Station economy is %(EventClass_Economy_Localised)"

Modified the line to read:
Global say_Docked $= "Docked at %(EventClass_StationName), %ifnotempty(EventClass_StationType,\"%(EventClass_StationType) type\")."

Not sure why this would cause the crash but it does.

Hope this information helps.

**Comment by klightspeed** [comment]
> ```
> [2017-03-14 19:53:28Z] New entry 14/03/2017 19:53:28 Docked
> [2017-03-14 19:53:28Z]
> ==== UNHANDLED EXCEPTION ====
> ```

Strange that the first-chance exception wasn't logged despite using the LogExceptions option.  Did you create the `Options.txt` file in the directory that has the `EDDiscovery.exe` executable?

> ```
> Global say_Docked $= "Docked at %(EventClass_StationName), %ifnotempty(EventClass_StationType,"%(EventClass_StationType) type")."
> ```

Unable to reproduce crash with modified `say_Docked` variable, and act file will not load if missing backslashes as above.

Would you please try the latest v6.2 build at https://ci.appveyor.com/project/EDDiscovery/eddiscovery/build/3.2.1.839/artifacts

**Comment by Norca** [comment]
Problem appears to be resolved in version 6.1.3
