### ISSUE TITLE
6.2.0.0 Trace EDDN check box.

### ISSUE THREAD

**Issue by ZexMaxwell001** [EDDiscovery/EDDiscovery#951]
Repeatable. 
In settings tab, I put a check mark into "Sync to EDDN" then click to a different tab. dumps a trace.
I restart EDD and go back to settings tab. the "Sync to EDDN" checkmark is filled in. but if I then uncheck it then click to new tab it dumps a trace.

[2017-04-10 10:14:58Z] Running logfile age check
[2017-04-10 10:14:58Z] Native library pre-loader is trying to load native SQLite library "D:\Program Files\EDDiscovery\EDDiscovery\x64\SQLite.Interop.dll"...
[2017-04-10 10:14:58Z] SQLite version 3.15.2
[2017-04-10 10:14:58Z] *** Elite Dangerous Discovery Initializing - Version 6.2.0.0, Platform: Win32NT
[2017-04-10 10:14:58Z] Initializing database
[2017-04-10 10:14:58Z] Database initialization complete
[2017-04-10 10:14:59Z] Theme ID 10037
[2017-04-10 10:15:00Z] Unknown Gal Map object mysteryPOI
[2017-04-10 10:15:00Z] Unknown Gal Map object deepSpaceOutpost
[2017-04-10 10:15:00Z] Unknown Gal Map object restrictedSectors
[2017-04-10 10:15:00Z] Unknown Gal Map object neutronRoute
[2017-04-10 10:15:00Z] New watch on C:\Users\lsoli\Saved Games\Frontier Developments\Elite Dangerous
[2017-04-10 10:15:00Z] Scanned C:\Users\lsoli\Saved Games\Frontier Developments\Elite Dangerous
[2017-04-10 10:15:00Z] File Read C:\Users\lsoli\Saved Games\Frontier Developments\Elite Dangerous\Journal.161025174747.01.log
[2017-04-10 10:15:00Z] File Read C:\Users\lsoli\Saved Games\Frontier Developments\Elite Dangerous\Journal.161026125221.01.log
[2017-04-10 10:15:00Z] File Read C:\Users\lsoli\Saved Games\Frontier Developments\Elite Dangerous\Journal.161026152334.01.log
[2017-04-10 10:15:00Z] File Read C:\Users\lsoli\Saved Games\Frontier Developments\Elite Dangerous\Journal.161026210343.01.log
[2017-04-10 10:15:00Z] File Read C:\Users\lsoli\Saved Games\Frontier Developments\Elite Dangerous\Journal.161027173230.01.log
[2017-04-10 10:15:00Z] File Read C:\Users\lsoli\Saved Games\Frontier Developments\Elite Dangerous\Journal.161028161419.01.log
[2017-04-10 10:15:00Z] File Read C:\Users\lsoli\Saved Games\Frontier Developments\Elite Dangerous\Journal.161028192950.01.log
[2017-04-10 10:15:00Z] File Read C:\Users\lsoli\Saved Games\Frontier Developments\Elite Dangerous\Journal.161028223313.01.log
[2017-04-10 10:15:00Z] File Read C:\Users\lsoli\Saved Games\Frontier Developments\Elite Dangerous\Journal.161029072925.01.log
[2017-04-10 10:15:00Z] File Read C:\Users\lsoli\Saved Games\Frontier Developments\Elite Dangerous\Journal.161029091935.01.log
[2017-04-10 10:15:00Z] File Read C:\Users\lsoli\Saved Games\Frontier Developments\Elite Dangerous\Journal.161029153729.01.log
[2017-04-10 10:15:00Z] File Read C:\Users\lsoli\Saved Games\Frontier Developments\Elite Dangerous\Journal.161029181621.01.log
[2017-04-10 10:15:00Z] File Read C:\Users\lsoli\Saved Games\Frontier Developments\Elite Dangerous\Journal.161030095136.01.log
[2017-04-10 10:15:00Z] File Read C:\Users\lsoli\Saved Games\Frontier Developments\Elite Dangerous\Journal.161030190427.01.log
[2017-04-10 10:15:00Z] File Read C:\Users\lsoli\Saved Games\Frontier Developments\Elite Dangerous\Journal.161030195305.01.log
[2017-04-10 10:15:00Z] File Read C:\Users\lsoli\Saved Games\Frontier Developments\Elite Dangerous\Journal.161030204814.01.log
[2017-04-10 10:15:00Z] File Read C:\Users\lsoli\Saved Games\Frontier Developments\Elite Dangerous\Journal.161030213106.01.log
[2017-04-10 10:15:00Z] File Read C:\Users\lsoli\Saved Games\Frontier Developments\Elite Dangerous\Journal.161031175047.01.log
[2017-04-10 10:15:00Z] File Read C:\Users\lsoli\Saved Games\Frontier Developments\Elite Dangerous\Journal.161101180439.01.log
[2017-04-10 10:15:00Z] File Read C:\Users\lsoli\Saved Games\Frontier Developments\Elite Dangerous\Journal.161102174042.01.log
[2017-04-10 10:15:00Z] File Read C:\Users\lsoli\Saved Games\Frontier Developments\Elite Dangerous\Journal.161103175253.01.log
[2017-04-10 10:15:00Z] File Read C:\Users\lsoli\Saved Games\Frontier Developments\Elite Dangerous\Journal.161103204542.01.log
[2017-04-10 10:15:00Z] File Read C:\Users\lsoli\Saved Games\Frontier Developments\Elite Dangerous\Journal.161104103407.01.log
[2017-04-10 10:15:00Z] File Read C:\Users\lsoli\Saved Games\Frontier Developments\Elite Dangerous\Journal.161104150249.01.log
[2017-04-10 10:15:00Z] File Read C:\Users\lsoli\Saved Games\Frontier Developments\Elite Dangerous\Journal.161104204925.01.log
[2017-04-10 10:15:00Z] File Read C:\Users\lsoli\Saved Games\Frontier Developments\Elite Dangerous\Journal.161105101853.01.log
[2017-04-10 10:15:00Z] File Read C:\Users\lsoli\Saved Games\Frontier Developments\Elite Dangerous\Journal.161105153524.01.log
[2017-04-10 10:15:00Z] File Read C:\Users\lsoli\Saved Games\Frontier Developments\Elite Dangerous\Journal.161106105726.01.log
[2017-04-10 10:15:00Z] File Read C:\Users\lsoli\Saved Games\Frontier Developments\Elite Dangerous\Journal.161106140357.01.log
[2017-04-10 10:15:00Z] File Read C:\Users\lsoli\Saved Games\Frontier Developments\Elite Dangerous\Journal.161107175523.01.log
[2017-04-10 10:15:00Z] File Read C:\Users\lsoli\Saved Games\Frontier Developments\Elite Dangerous\Journal.161108180005.01.log
[2017-04-10 10:15:00Z] File Read C:\Users\lsoli\Saved Games\Frontier Developments\Elite Dangerous\Journal.161108193709.01.log
[2017-04-10 10:15:00Z] File Read C:\Users\lsoli\Saved Games\Frontier Developments\Elite Dangerous\Journal.161109175013.01.log
[2017-04-10 10:15:00Z] File Read C:\Users\lsoli\Saved Games\Frontier Developments\Elite Dangerous\Journal.161110180633.01.log
[2017-04-10 10:15:00Z] File Read C:\Users\lsoli\Saved Games\Frontier Developments\Elite Dangerous\Journal.161111171207.01.log
[2017-04-10 10:15:00Z] File Read C:\Users\lsoli\Saved Games\Frontier Developments\Elite Dangerous\Journal.161112101324.01.log
[2017-04-10 10:15:00Z] File Read C:\Users\lsoli\Saved Games\Frontier Developments\Elite Dangerous\Journal.161112101644.01.log
[2017-04-10 10:15:00Z] File Read C:\Users\lsoli\Saved Games\Frontier Developments\Elite Dangerous\Journal.161112101905.01.log
[2017-04-10 10:15:00Z] File Read C:\Users\lsoli\Saved Games\Frontier Developments\Elite Dangerous\Journal.161113084122.01.log
[2017-04-10 10:15:00Z] File Read C:\Users\lsoli\Saved Games\Frontier Developments\Elite Dangerous\Journal.161113095216.01.log
[2017-04-10 10:15:00Z] File Read C:\Users\lsoli\Saved Games\Frontier Developments\Elite Dangerous\Journal.161113140934.01.log
[2017-04-10 10:15:00Z] File Read C:\Users\lsoli\Saved Games\Frontier Developments\Elite Dangerous\Journal.161114175555.01.log
[2017-04-10 10:15:00Z] File Read C:\Users\lsoli\Saved Games\Frontier Developments\Elite Dangerous\Journal.161115123446.01.log
[2017-04-10 10:15:00Z] File Read C:\Users\lsoli\Saved Games\Frontier Developments\Elite Dangerous\Journal.161115134624.01.log
[2017-04-10 10:15:00Z] File Read C:\Users\lsoli\Saved Games\Frontier Developments\Elite Dangerous\Journal.161116150509.01.log
[2017-04-10 10:15:00Z] File Read C:\Users\lsoli\Saved Games\Frontier Developments\Elite Dangerous\Journal.161117184716.01.log
[2017-04-10 10:15:00Z] File Read C:\Users\lsoli\Saved Games\Frontier Developments\Elite Dangerous\Journal.161118173615.01.log
[2017-04-10 10:15:00Z] File Read C:\Users\lsoli\Saved Games\Frontier Developments\Elite Dangerous\Journal.161118173854.01.log
[2017-04-10 10:15:00Z] File Read C:\Users\lsoli\Saved Games\Frontier Developments\Elite Dangerous\Journal.161119103613.01.log
[2017-04-10 10:15:00Z] File Read C:\Users\lsoli\Saved Games\Frontier Developments\Elite Dangerous\Journal.161119204359.01.log
[2017-04-10 10:15:00Z] File Read C:\Users\lsoli\Saved Games\Frontier Developments\Elite Dangerous\Journal.161120084634.01.log
[2017-04-10 10:15:00Z] File Read C:\Users\lsoli\Saved Games\Frontier Developments\Elite Dangerous\Journal.161121203904.01.log
[2017-04-10 10:15:00Z] File Read C:\Users\lsoli\Saved Games\Frontier Developments\Elite Dangerous\Journal.161122183916.01.log
[2017-04-10 10:15:00Z] File Read C:\Users\lsoli\Saved Games\Frontier Developments\Elite Dangerous\Journal.161123164320.01.log
[2017-04-10 10:15:00Z] File Read C:\Users\lsoli\Saved Games\Frontier Developments\Elite Dangerous\Journal.161123193448.01.log
[2017-04-10 10:15:00Z] File Read C:\Users\lsoli\Saved Games\Frontier Developments\Elite Dangerous\Journal.161124184035.01.log
[2017-04-10 10:15:00Z] File Read C:\Users\lsoli\Saved Games\Frontier Developments\Elite Dangerous\Journal.161125100432.01.log
[2017-04-10 10:15:00Z] File Read C:\Users\lsoli\Saved Games\Frontier Developments\Elite Dangerous\Journal.161126104343.01.log
[2017-04-10 10:15:00Z] File Read C:\Users\lsoli\Saved Games\Frontier Developments\Elite Dangerous\Journal.161126163758.01.log
[2017-04-10 10:15:00Z] File Read C:\Users\lsoli\Saved Games\Frontier Developments\Elite Dangerous\Journal.161127105301.01.log
[2017-04-10 10:15:00Z] File Read C:\Users\lsoli\Saved Games\Frontier Developments\Elite Dangerous\Journal.161127132548.01.log
[2017-04-10 10:15:00Z] File Read C:\Users\lsoli\Saved Games\Frontier Developments\Elite Dangerous\Journal.161128181152.01.log
[2017-04-10 10:15:00Z] File Read C:\Users\lsoli\Saved Games\Frontier Developments\Elite Dangerous\Journal.161129175027.01.log
[2017-04-10 10:15:00Z] File Read C:\Users\lsoli\Saved Games\Frontier Developments\Elite Dangerous\Journal.161130175945.01.log
[2017-04-10 10:15:00Z] File Read C:\Users\lsoli\Saved Games\Frontier Developments\Elite Dangerous\Journal.161201175627.01.log
[2017-04-10 10:15:00Z] File Read C:\Users\lsoli\Saved Games\Frontier Developments\Elite Dangerous\Journal.161202180637.01.log
[2017-04-10 10:15:00Z] File Read C:\Users\lsoli\Saved Games\Frontier Developments\Elite Dangerous\Journal.161202193912.01.log
[2017-04-10 10:15:00Z] File Read C:\Users\lsoli\Saved Games\Frontier Developments\Elite Dangerous\Journal.161203173744.01.log
[2017-04-10 10:15:00Z] File Read C:\Users\lsoli\Saved Games\Frontier Developments\Elite Dangerous\Journal.161203225006.01.log
[2017-04-10 10:15:00Z] File Read C:\Users\lsoli\Saved Games\Frontier Developments\Elite Dangerous\Journal.161204084042.01.log
[2017-04-10 10:15:00Z] File Read C:\Users\lsoli\Saved Games\Frontier Developments\Elite Dangerous\Journal.161204124831.01.log
[2017-04-10 10:15:00Z] File Read C:\Users\lsoli\Saved Games\Frontier Developments\Elite Dangerous\Journal.161205124807.01.log
[2017-04-10 10:15:00Z] File Read C:\Users\lsoli\Saved Games\Frontier Developments\Elite Dangerous\Journal.161205175002.01.log
[2017-04-10 10:15:00Z] File Read C:\Users\lsoli\Saved Games\Frontier Developments\Elite Dangerous\Journal.161205180016.01.log
[2017-04-10 10:15:00Z] File Read C:\Users\lsoli\Saved Games\Frontier Developments\Elite Dangerous\Journal.161206143906.01.log
[2017-04-10 10:15:00Z] File Read C:\Users\lsoli\Saved Games\Frontier Developments\Elite Dangerous\Journal.161206144204.01.log
[2017-04-10 10:15:00Z] File Read C:\Users\lsoli\Saved Games\Frontier Developments\Elite Dangerous\Journal.161206173317.01.log
[2017-04-10 10:15:00Z] File Read C:\Users\lsoli\Saved Games\Frontier Developments\Elite Dangerous\Journal.161207175429.01.log
[2017-04-10 10:15:00Z] File Read C:\Users\lsoli\Saved Games\Frontier Developments\Elite Dangerous\Journal.161208175032.01.log
[2017-04-10 10:15:00Z] File Read C:\Users\lsoli\Saved Games\Frontier Developments\Elite Dangerous\Journal.161209175126.01.log
[2017-04-10 10:15:00Z] File Read C:\Users\lsoli\Saved Games\Frontier Developments\Elite Dangerous\Journal.161209205333.01.log
[2017-04-10 10:15:00Z] File Read C:\Users\lsoli\Saved Games\Frontier Developments\Elite Dangerous\Journal.161210111420.01.log
[2017-04-10 10:15:00Z] File Read C:\Users\lsoli\Saved Games\Frontier Developments\Elite Dangerous\Journal.161210163150.01.log
[2017-04-10 10:15:00Z] File Read C:\Users\lsoli\Saved Games\Frontier Developments\Elite Dangerous\Journal.161210185626.01.log
[2017-04-10 10:15:00Z] File Read C:\Users\lsoli\Saved Games\Frontier Developments\Elite Dangerous\Journal.161211093149.01.log
[2017-04-10 10:15:00Z] File Read C:\Users\lsoli\Saved Games\Frontier Developments\Elite Dangerous\Journal.161211183009.01.log
[2017-04-10 10:15:00Z] File Read C:\Users\lsoli\Saved Games\Frontier Developments\Elite Dangerous\Journal.161212175553.01.log
[2017-04-10 10:15:00Z] File Read C:\Users\lsoli\Saved Games\Frontier Developments\Elite Dangerous\Journal.161213174756.01.log
[2017-04-10 10:15:00Z] File Read C:\Users\lsoli\Saved Games\Frontier Developments\Elite Dangerous\Journal.161213210020.01.log
[2017-04-10 10:15:00Z] File Read C:\Users\lsoli\Saved Games\Frontier Developments\Elite Dangerous\Journal.161214175611.01.log
[2017-04-10 10:15:00Z] File Read C:\Users\lsoli\Saved Games\Frontier Developments\Elite Dangerous\Journal.161215190457.01.log
[2017-04-10 10:15:00Z] File Read C:\Users\lsoli\Saved Games\Frontier Developments\Elite Dangerous\Journal.161216171928.01.log
[2017-04-10 10:15:00Z] File Read C:\Users\lsoli\Saved Games\Frontier Developments\Elite Dangerous\Journal.161223200521.01.log
[2017-04-10 10:15:00Z] File Read C:\Users\lsoli\Saved Games\Frontier Developments\Elite Dangerous\Journal.170105183931.01.log
[2017-04-10 10:15:00Z] Unknown Gal Map object mysteryPOI
[2017-04-10 10:15:00Z] Last message repeated 21 times
[2017-04-10 10:15:00Z] Unknown Gal Map object deepSpaceOutpost
[2017-04-10 10:15:00Z] Last message repeated 7 times
[2017-04-10 10:15:00Z] Unknown Gal Map object restrictedSectors
[2017-04-10 10:15:00Z] Last message repeated 21 times
[2017-04-10 10:15:00Z] Unknown Gal Map object neutronRoute
[2017-04-10 10:15:00Z] Last message repeated 6 times
[2017-04-10 10:15:00Z] File Read C:\Users\lsoli\Saved Games\Frontier Developments\Elite Dangerous\Journal.170110140745.01.log
[2017-04-10 10:15:00Z] File Read C:\Users\lsoli\Saved Games\Frontier Developments\Elite Dangerous\Journal.170124175806.01.log
[2017-04-10 10:15:00Z] File Read C:\Users\lsoli\Saved Games\Frontier Developments\Elite Dangerous\Journal.170124211637.01.log
[2017-04-10 10:15:00Z] File Read C:\Users\lsoli\Saved Games\Frontier Developments\Elite Dangerous\Journal.170125151227.01.log
[2017-04-10 10:15:00Z] File Read C:\Users\lsoli\Saved Games\Frontier Developments\Elite Dangerous\Journal.170126010305.01.log
[2017-04-10 10:15:00Z] File Read C:\Users\lsoli\Saved Games\Frontier Developments\Elite Dangerous\Journal.170126011456.01.log
[2017-04-10 10:15:00Z] File Read C:\Users\lsoli\Saved Games\Frontier Developments\Elite Dangerous\Journal.170126163057.01.log
[2017-04-10 10:15:00Z] File Read C:\Users\lsoli\Saved Games\Frontier Developments\Elite Dangerous\Journal.170127013306.01.log
[2017-04-10 10:15:00Z] File Read C:\Users\lsoli\Saved Games\Frontier Developments\Elite Dangerous\Journal.170127153311.01.log
[2017-04-10 10:15:00Z] File Read C:\Users\lsoli\Saved Games\Frontier Developments\Elite Dangerous\Journal.170127194925.01.log
[2017-04-10 10:15:00Z] File Read C:\Users\lsoli\Saved Games\Frontier Developments\Elite Dangerous\Journal.170128010640.01.log
[2017-04-10 10:15:00Z] File Read C:\Users\lsoli\Saved Games\Frontier Developments\Elite Dangerous\Journal.170128144858.01.log
[2017-04-10 10:15:00Z] File Read C:\Users\lsoli\Saved Games\Frontier Developments\Elite Dangerous\Journal.170129054713.01.log
[2017-04-10 10:15:00Z] File Read C:\Users\lsoli\Saved Games\Frontier Developments\Elite Dangerous\Journal.170129153434.01.log
[2017-04-10 10:15:00Z] File Read C:\Users\lsoli\Saved Games\Frontier Developments\Elite Dangerous\Journal.170129153622.01.log
[2017-04-10 10:15:00Z] File Read C:\Users\lsoli\Saved Games\Frontier Developments\Elite Dangerous\Journal.170130085412.01.log
[2017-04-10 10:15:00Z] File Read C:\Users\lsoli\Saved Games\Frontier Developments\Elite Dangerous\Journal.170130180707.01.log
[2017-04-10 10:15:00Z] File Read C:\Users\lsoli\Saved Games\Frontier Developments\Elite Dangerous\Journal.170131170226.01.log
[2017-04-10 10:15:00Z] File Read C:\Users\lsoli\Saved Games\Frontier Developments\Elite Dangerous\Journal.170201014745.01.log
[2017-04-10 10:15:00Z] File Read C:\Users\lsoli\Saved Games\Frontier Developments\Elite Dangerous\Journal.170201161458.01.log
[2017-04-10 10:15:00Z] File Read C:\Users\lsoli\Saved Games\Frontier Developments\Elite Dangerous\Journal.170201165633.01.log
[2017-04-10 10:15:00Z] File Read C:\Users\lsoli\Saved Games\Frontier Developments\Elite Dangerous\Journal.170203182044.01.log
[2017-04-10 10:15:00Z] File Read C:\Users\lsoli\Saved Games\Frontier Developments\Elite Dangerous\Journal.170203183042.01.log
[2017-04-10 10:15:00Z] File Read C:\Users\lsoli\Saved Games\Frontier Developments\Elite Dangerous\Journal.170214073105.01.log
[2017-04-10 10:15:00Z] File Read C:\Users\lsoli\Saved Games\Frontier Developments\Elite Dangerous\Journal.170215024736.01.log
[2017-04-10 10:15:00Z] File Read C:\Users\lsoli\Saved Games\Frontier Developments\Elite Dangerous\Journal.170309182841.01.log
[2017-04-10 10:15:00Z] File Read C:\Users\lsoli\Saved Games\Frontier Developments\Elite Dangerous\Journal.170310005219.01.log
[2017-04-10 10:15:00Z] File Read C:\Users\lsoli\Saved Games\Frontier Developments\Elite Dangerous\Journal.170310152307.01.log
[2017-04-10 10:15:00Z] File Read C:\Users\lsoli\Saved Games\Frontier Developments\Elite Dangerous\Journal.170310172233.01.log
[2017-04-10 10:15:00Z] File Read C:\Users\lsoli\Saved Games\Frontier Developments\Elite Dangerous\Journal.170310232120.01.log
[2017-04-10 10:15:00Z] File Read C:\Users\lsoli\Saved Games\Frontier Developments\Elite Dangerous\Journal.170311113719.01.log
[2017-04-10 10:15:00Z] File Read C:\Users\lsoli\Saved Games\Frontier Developments\Elite Dangerous\Journal.170311174412.01.log
[2017-04-10 10:15:00Z] File Read C:\Users\lsoli\Saved Games\Frontier Developments\Elite Dangerous\Journal.170312015343.01.log
[2017-04-10 10:15:00Z] File Read C:\Users\lsoli\Saved Games\Frontier Developments\Elite Dangerous\Journal.170313234315.01.log
[2017-04-10 10:15:00Z] File Read C:\Users\lsoli\Saved Games\Frontier Developments\Elite Dangerous\Journal.170314063049.01.log
[2017-04-10 10:15:00Z] File Read C:\Users\lsoli\Saved Games\Frontier Developments\Elite Dangerous\Journal.170314093528.01.log
[2017-04-10 10:15:00Z] File Read C:\Users\lsoli\Saved Games\Frontier Developments\Elite Dangerous\Journal.170314175821.01.log
[2017-04-10 10:15:00Z] File Read C:\Users\lsoli\Saved Games\Frontier Developments\Elite Dangerous\Journal.170315105433.01.log
[2017-04-10 10:15:00Z] File Read C:\Users\lsoli\Saved Games\Frontier Developments\Elite Dangerous\Journal.170315151947.01.log
[2017-04-10 10:15:00Z] File Read C:\Users\lsoli\Saved Games\Frontier Developments\Elite Dangerous\Journal.170316041629.01.log
[2017-04-10 10:15:00Z] File Read C:\Users\lsoli\Saved Games\Frontier Developments\Elite Dangerous\Journal.170316133927.01.log
[2017-04-10 10:15:00Z] File Read C:\Users\lsoli\Saved Games\Frontier Developments\Elite Dangerous\Journal.170316233849.01.log
[2017-04-10 10:15:00Z] File Read C:\Users\lsoli\Saved Games\Frontier Developments\Elite Dangerous\Journal.170317152043.01.log
[2017-04-10 10:15:00Z] File Read C:\Users\lsoli\Saved Games\Frontier Developments\Elite Dangerous\Journal.170318175357.01.log
[2017-04-10 10:15:00Z] File Read C:\Users\lsoli\Saved Games\Frontier Developments\Elite Dangerous\Journal.170319201844.01.log
[2017-04-10 10:15:00Z] File Read C:\Users\lsoli\Saved Games\Frontier Developments\Elite Dangerous\Journal.170321160924.01.log
[2017-04-10 10:15:00Z] File Read C:\Users\lsoli\Saved Games\Frontier Developments\Elite Dangerous\Journal.170322010428.01.log
[2017-04-10 10:15:00Z] File Read C:\Users\lsoli\Saved Games\Frontier Developments\Elite Dangerous\Journal.170322193513.01.log
[2017-04-10 10:15:00Z] File Read C:\Users\lsoli\Saved Games\Frontier Developments\Elite Dangerous\Journal.170323174943.01.log
[2017-04-10 10:15:00Z] File Read C:\Users\lsoli\Saved Games\Frontier Developments\Elite Dangerous\Journal.170323230104.01.log
[2017-04-10 10:15:00Z] File Read C:\Users\lsoli\Saved Games\Frontier Developments\Elite Dangerous\Journal.170324154948.01.log
[2017-04-10 10:15:00Z] File Read C:\Users\lsoli\Saved Games\Frontier Developments\Elite Dangerous\Journal.170324224216.01.log
[2017-04-10 10:15:00Z] File Read C:\Users\lsoli\Saved Games\Frontier Developments\Elite Dangerous\Journal.170325131259.01.log
[2017-04-10 10:15:00Z] File Read C:\Users\lsoli\Saved Games\Frontier Developments\Elite Dangerous\Journal.170325154614.01.log
[2017-04-10 10:15:00Z] File Read C:\Users\lsoli\Saved Games\Frontier Developments\Elite Dangerous\Journal.170325184536.01.log
[2017-04-10 10:15:00Z] File Read C:\Users\lsoli\Saved Games\Frontier Developments\Elite Dangerous\Journal.170326125810.01.log
[2017-04-10 10:15:00Z] File Read C:\Users\lsoli\Saved Games\Frontier Developments\Elite Dangerous\Journal.170328103540.01.log
[2017-04-10 10:15:00Z] File Read C:\Users\lsoli\Saved Games\Frontier Developments\Elite Dangerous\Journal.170328151643.01.log
[2017-04-10 10:15:00Z] File Read C:\Users\lsoli\Saved Games\Frontier Developments\Elite Dangerous\Journal.170328211523.01.log
[2017-04-10 10:15:00Z] File Read C:\Users\lsoli\Saved Games\Frontier Developments\Elite Dangerous\Journal.170329145639.01.log
[2017-04-10 10:15:00Z] File Read C:\Users\lsoli\Saved Games\Frontier Developments\Elite Dangerous\Journal.170330141324.01.log
[2017-04-10 10:15:00Z] File Read C:\Users\lsoli\Saved Games\Frontier Developments\Elite Dangerous\Journal.170331001942.01.log
[2017-04-10 10:15:00Z] File Read C:\Users\lsoli\Saved Games\Frontier Developments\Elite Dangerous\Journal.170331034547.01.log
[2017-04-10 10:15:00Z] File Read C:\Users\lsoli\Saved Games\Frontier Developments\Elite Dangerous\Journal.170402160621.01.log
[2017-04-10 10:15:00Z] File Read C:\Users\lsoli\Saved Games\Frontier Developments\Elite Dangerous\Journal.170402180413.01.log
[2017-04-10 10:15:00Z] File Read C:\Users\lsoli\Saved Games\Frontier Developments\Elite Dangerous\Journal.170402212313.01.log
[2017-04-10 10:15:00Z] File Read C:\Users\lsoli\Saved Games\Frontier Developments\Elite Dangerous\Journal.170403050753.01.log
[2017-04-10 10:15:00Z] File Read C:\Users\lsoli\Saved Games\Frontier Developments\Elite Dangerous\Journal.170404033314.01.log
[2017-04-10 10:15:00Z] File Read C:\Users\lsoli\Saved Games\Frontier Developments\Elite Dangerous\Journal.170405025604.01.log
[2017-04-10 10:15:00Z] File Read C:\Users\lsoli\Saved Games\Frontier Developments\Elite Dangerous\Journal.170405143114.01.log
[2017-04-10 10:15:00Z] File Read C:\Users\lsoli\Saved Games\Frontier Developments\Elite Dangerous\Journal.170406080255.01.log
[2017-04-10 10:15:00Z] File Read C:\Users\lsoli\Saved Games\Frontier Developments\Elite Dangerous\Journal.170406160453.01.log
[2017-04-10 10:15:00Z] File Read C:\Users\lsoli\Saved Games\Frontier Developments\Elite Dangerous\Journal.170406193135.01.log
[2017-04-10 10:15:00Z] File Read C:\Users\lsoli\Saved Games\Frontier Developments\Elite Dangerous\Journal.170409064441.01.log
[2017-04-10 10:15:00Z] File Read C:\Users\lsoli\Saved Games\Frontier Developments\Elite Dangerous\Journal.170410003830.01.log
[2017-04-10 10:15:00Z] File Read C:\Users\lsoli\Saved Games\Frontier Developments\Elite Dangerous\Journal.170410095426.01.log
[2017-04-10 10:15:07Z] Start Monitor on C:\Users\lsoli\Saved Games\Frontier Developments\Elite Dangerous
[2017-04-10 10:15:11Z] 
==== UNHANDLED UI EXCEPTION ====
System.ArgumentException: Could not determine JSON object type for type <>f__AnonymousType29`2[System.String,System.String].
   at Newtonsoft.Json.Linq.JValue.GetValueType(Nullable`1 current, Object value)
   at Newtonsoft.Json.Linq.JContainer.CreateFromContent(Object content)
   at Newtonsoft.Json.Linq.JContainer.AddInternal(Int32 index, Object content, Boolean skipParentCheck)
   at EDDiscovery.EDCommander.Update(List`1 cmdrlist, Boolean reload)
   at EDDiscovery.Settings.dataGridViewCommanders_CellEndEdit(Object sender, DataGridViewCellEventArgs e)
   at System.Windows.Forms.DataGridView.OnCellEndEdit(DataGridViewCellEventArgs e)
   at System.Windows.Forms.DataGridView.EndEdit(DataGridViewDataErrorContexts context, DataGridViewValidateCellInternal validateCell, Boolean fireCellLeave, Boolean fireCellEnter, Boolean fireRowLeave, Boolean fireRowEnter, Boolean fireLeave, Boolean keepFocus, Boolean resetCurrentCell, Boolean resetAnchorCell)
   at System.Windows.Forms.DataGridView.OnValidating(CancelEventArgs e)
   at System.Windows.Forms.Control.NotifyValidating()
   at System.Windows.Forms.Control.PerformControlValidation(Boolean bulkValidation)
   at System.Windows.Forms.ContainerControl.ValidateThroughAncestor(Control ancestorControl, Boolean preventFocusChangeOnError)
   at System.Windows.Forms.ContainerControl.UpdateFocusedControl()
   at System.Windows.Forms.ContainerControl.AssignActiveControlInternal(Control value)
   at System.Windows.Forms.ContainerControl.ActivateControlInternal(Control control, Boolean originator)
   at System.Windows.Forms.ContainerControl.SetActiveControlInternal(Control value)
   at System.Windows.Forms.TabControl.WmSelChanging()
   at System.Windows.Forms.TabControl.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)
==== cut ====
[2017-04-10 10:15:45Z] 
==== UNHANDLED UI EXCEPTION ====
System.ArgumentException: Could not determine JSON object type for type <>f__AnonymousType29`2[System.String,System.String].
   at Newtonsoft.Json.Linq.JValue.GetValueType(Nullable`1 current, Object value)
   at Newtonsoft.Json.Linq.JContainer.CreateFromContent(Object content)
   at Newtonsoft.Json.Linq.JContainer.AddInternal(Int32 index, Object content, Boolean skipParentCheck)
   at EDDiscovery.EDCommander.Update(List`1 cmdrlist, Boolean reload)
   at EDDiscovery.Settings.dataGridViewCommanders_CellEndEdit(Object sender, DataGridViewCellEventArgs e)
   at System.Windows.Forms.DataGridView.OnCellEndEdit(DataGridViewCellEventArgs e)
   at System.Windows.Forms.DataGridView.EndEdit(DataGridViewDataErrorContexts context, DataGridViewValidateCellInternal validateCell, Boolean fireCellLeave, Boolean fireCellEnter, Boolean fireRowLeave, Boolean fireRowEnter, Boolean fireLeave, Boolean keepFocus, Boolean resetCurrentCell, Boolean resetAnchorCell)
   at System.Windows.Forms.DataGridView.OnValidating(CancelEventArgs e)
   at System.Windows.Forms.Control.NotifyValidating()
   at System.Windows.Forms.Control.PerformControlValidation(Boolean bulkValidation)
   at System.Windows.Forms.ContainerControl.ValidateThroughAncestor(Control ancestorControl, Boolean preventFocusChangeOnError)
   at System.Windows.Forms.ContainerControl.UpdateFocusedControl()
   at System.Windows.Forms.ContainerControl.AssignActiveControlInternal(Control value)
   at System.Windows.Forms.ContainerControl.ActivateControlInternal(Control control, Boolean originator)
   at System.Windows.Forms.ContainerControl.SetActiveControlInternal(Control value)
   at System.Windows.Forms.ContainerControl.set_ActiveControl(Control value)
   at System.Windows.Forms.ContainerControl.Select(Boolean directed, Boolean forward)
   at System.Windows.Forms.Control.SelectNextControl(Control ctl, Boolean forward, Boolean tabStopOnly, Boolean nested, Boolean wrap)
   at System.Windows.Forms.TabControl.UpdateTabSelection(Boolean updateFocus)
   at System.Windows.Forms.TabControl.OnSelectedIndexChanged(EventArgs e)
   at System.Windows.Forms.TabControl.WmSelChange()
   at System.Windows.Forms.TabControl.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)
==== cut ====

**Comment by ZexMaxwell001** [comment]
Looks like this also happens with EDSM check box
