### ISSUE TITLE
Unhandled exception report

### ISSUE THREAD

**Issue by CMDR-Cometborne** [EDDiscovery/EDDiscovery#971]
Just managed to create an unhandled exception by attempting to re-use a route name.  Traceback:

```
[2017-04-16 23:57:06Z] SQLite error (2067): abort at 15 in [Insert into routes_expeditions (name, start, end) values (@name, @start, @end)]: UNIQUE constraint failed: routes_expeditions.name
[2017-04-16 23:57:07Z] 
==== UNHANDLED UI EXCEPTION ====
System.Data.SQLite.SQLiteException (0x80004005): constraint failed
UNIQUE constraint failed: routes_expeditions.name
   at System.Data.SQLite.SQLite3.Reset(SQLiteStatement stmt)
   at System.Data.SQLite.SQLite3.Step(SQLiteStatement stmt)
   at System.Data.SQLite.SQLiteDataReader.NextResult()
   at System.Data.SQLite.SQLiteDataReader..ctor(SQLiteCommand cmd, CommandBehavior behave)
   at System.Data.SQLite.SQLiteCommand.ExecuteReader(CommandBehavior behavior)
   at System.Data.SQLite.SQLiteCommand.ExecuteNonQuery(CommandBehavior behavior)
   at EDDiscovery.DB.SQLiteCommandED`1.ExecuteNonQuery()
   at EDDiscovery.DB.SQLiteDBClass.SQLNonQueryText(SQLiteConnectionED cn, DbCommand cmd)
   at EDDiscovery.DB.SavedRouteClass.Add(SQLiteConnectionUser cn)
   at EDDiscovery.DB.SavedRouteClass.Add()
   at EDDiscovery.SavedRouteExpeditionControl.toolStripButtonSave_Click(Object sender, EventArgs e)
   at System.Windows.Forms.ToolStripItem.RaiseEvent(Object key, EventArgs e)
   at System.Windows.Forms.ToolStripButton.OnClick(EventArgs e)
   at System.Windows.Forms.ToolStripItem.HandleClick(EventArgs e)
   at System.Windows.Forms.ToolStripItem.HandleMouseUp(MouseEventArgs e)
   at System.Windows.Forms.ToolStrip.OnMouseUp(MouseEventArgs mea)
   at System.Windows.Forms.Control.WmMouseUp(Message& m, MouseButtons button, Int32 clicks)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.ToolStrip.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)
==== cut ====
```

**Comment by klightspeed** [comment]
We need to check if a route name exists, and tell the user to give it a different name if it does.  Probably also need a proper primary key on the routes table.
