### ISSUE TITLE
Failing to connect to db 

### ISSUE THREAD

**Issue by badbud65** [EDDiscovery/EDDiscovery#979]
I'm getting this error 2 or 3 times an hour.

```
Check Systems exception: database disk image is malformed
database disk image is malformed
Trace:    at System.Data.SQLite.SQLite3.Reset(SQLiteStatement stmt)
   at System.Data.SQLite.SQLite3.Step(SQLiteStatement stmt)
   at System.Data.SQLite.SQLiteDataReader.NextResult()
   at System.Data.SQLite.SQLiteDataReader..ctor(SQLiteCommand cmd, CommandBehavior behave)
   at System.Data.SQLite.SQLiteCommand.ExecuteReader(CommandBehavior behavior)
   at System.Data.SQLite.SQLiteCommand.ExecuteNonQuery(CommandBehavior behavior)
   at EDDiscovery.DB.SQLiteCommandED`1.ExecuteNonQuery()
   at EDDiscovery.DB.SystemClass.DoParseEDSMUpdateSystemsReader(JsonTextReader jr, String& date, Boolean& outoforder, Func`1 cancelRequested, Action`2 reportProgress, Boolean useCache, Boolean useTempSystems)
   at EDDiscovery.DB.SystemClass.ParseEDSMUpdateSystemsStream(TextReader sr, String& date, Boolean& outoforder, Boolean removenonedsmids, Func`1 cancelRequested, Action`2 reportProgress, Boolean useCache, Boolean useTempSystems)
   at EDDiscovery.DB.SystemClass.ParseEDSMUpdateSystemsString(String json, String& date, Boolean& outoforder, Boolean removenonedsmids, Func`1 cancelRequested, Action`2 reportProgress, Boolean useCache)
   at EDDiscovery.EDSM.EDSMClass.GetNewSystems(Func`1 cancelRequested, Action`2 reportProgress, Action`1 logLine)
   at EDDiscovery.DB.SystemClass.PerformSync(Func`1 cancelRequested, Action`2 reportProgress, Action`1 logLine, Action`1 logError, SystemsSyncState state)
   at EDDiscovery.EDDiscoveryController.DoPerformSync()
```

And as a result of this when I check EDSM the system bodies data hasn't been synced. when the error occurred as a consequence after I've jumped to a new system and check the body data at EDSM I find some o the bodies haven't been saved.

**Comment by finwen** [comment]
Go to %localappdata%\EDDiscovery

Delete or rename EDDSystem.sqlite  file  (this will not cointain your personal travels so its safe to delete). 

Start EDDiscovery and wait for it to rebuild EDDSystem.sqlite

**Comment by badbud65** [comment]
Cheers, that appears to have resolved the issue. 

Question: Where do I find the new Engineers stuff, and Ship loadout?

I've searched the wiki and I can find loadout there, but can't find it in the app. https://github.com/EDDiscovery/EDDiscovery/wiki/Using-the-Load-Out-Panel

With regards to Engineers I can't find anything in the wiki about it.

I fully uninstalled the APP including all files but I still can't find anything with reatgrdsto Loadout or Engineers.

**Comment by iainross** [comment]
The new Engineering panel is in the S-Panel drop down on the front screen.  Don't set a target number of lvl 5 FSD rolls or you'll get an error (just fixing that now).  I've not added it to the wiki yet.

**Comment by badbud65** [comment]
Cheers, found it.
