### ISSUE TITLE
Unhandled exception

### ISSUE THREAD

**Issue by mpfj** [EDDiscovery/EDDiscovery#993]
Just tried running 7.0.2.0 and have the following exception:-

![unhandled exception](https://cloud.githubusercontent.com/assets/1272389/25178374/7c33bb52-24fd-11e7-97d4-effa7e4ffd80.png)

**Comment by mpfj** [comment]
And here's the log file:-

[2017-04-19 11:36:31Z] Running logfile age check
[2017-04-19 11:36:31Z] Native library pre-loader is trying to load native SQLite library "C:\Program Files\EDDiscovery\EDDiscovery\x64\SQLite.Interop.dll"...
[2017-04-19 11:36:31Z] SQLite version 3.15.2
[2017-04-19 11:36:31Z] *** Elite Dangerous Discovery Initializing - Version 7.0.2.0, Platform: Win32NT
[2017-04-19 11:36:31Z] Initializing database
[2017-04-19 11:36:31Z] Database initialization complete
[2017-04-19 11:36:31Z] Theme ID 10037
[2017-04-19 11:36:33Z] Unknown Gal Map object mysteryPOI
[2017-04-19 11:36:33Z] Unknown Gal Map object deepSpaceOutpost
[2017-04-19 11:36:33Z] Unknown Gal Map object restrictedSectors
[2017-04-19 11:36:33Z] Unknown Gal Map object neutronRoute
[2017-04-19 11:36:33Z] SQLite error (2067): abort at 38 in [Update MaterialsCommodities set Category=@category, Name=@name, FDName=@fdname, Type=@type, ShortName=@shortname, Colour=@colour, Flags=@flags where ID=@id]: UNIQUE constraint failed: Materials
[2017-04-19 11:36:33Z] 
==== UNHANDLED EXCEPTION ====
System.Data.SQLite.SQLiteException (0x80004005): constraint failed
UNIQUE constraint failed: MaterialsCommodities.Category, MaterialsCommodities.Name
   at System.Data.SQLite.SQLite3.Reset(SQLiteStatement stmt)
   at System.Data.SQLite.SQLite3.Step(SQLiteStatement stmt)
   at System.Data.SQLite.SQLiteDataReader.NextResult()
   at System.Data.SQLite.SQLiteDataReader..ctor(SQLiteCommand cmd, CommandBehavior behave)
   at System.Data.SQLite.SQLiteCommand.ExecuteReader(CommandBehavior behavior)
   at System.Data.SQLite.SQLiteCommand.ExecuteNonQuery(CommandBehavior behavior)
   at EDDiscovery.DB.SQLiteCommandED`1.ExecuteNonQuery()
   at EDDiscovery.DB.SQLiteDBClass.SQLNonQueryText(SQLiteConnectionED cn, DbCommand cmd)
   at EDDiscovery.DB.MaterialCommodityDB.Update(SQLiteConnectionUser cn)
   at EDDiscovery.DB.MaterialCommodityDB.AddNewTypeC(SQLiteConnectionUser cn, String c, Color cl, String namelist, String t, String sn)
   at EDDiscovery.DB.MaterialCommodityDB.SetUpInitialTable()
   at EDDiscovery.EDDiscoveryController.CheckSystems(Func`1 cancelRequested, Action`2 reportProgress)
   at EDDiscovery.EDDiscoveryController.BackgroundInit()
   at EDDiscovery.EDDiscoveryController.BackgroundWorkerThread()
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.ThreadHelper.ThreadStart()
==== cut ====

**Comment by finwen** [comment]
I know why and will try  to fix  tihs tonight.

I you can sql you can remove content in MaterialCommodity table in EDDSystem.sqlite to get it to work for now.

**Comment by mpfj** [comment]
Fixed in 7.0.3 ... thx
